### ISSUE TITLE
Minor graphical layout bug. Notification overlaps check for new version

### ISSUE THREAD

**Issue by AtariBaby** [mylar3/mylar3#1001]
**Describe the bug**
On my iPad Pro 12.9, Safari browser, this icon overlaps the link to check for new version. As a result, it’s difficult to check for new version, even if one clicks some distance to the left or the right of the bell icon. Most of the time the notification window opens. This happens in landscape or portrait. Not terrible, but FYI.

**CarePackage**
[carepackage 10.zip](https://github.com/mylar3/mylar3/files/7876233/carepackage.10.zip)
If you're uncomfortable with pasting your CarePackage, include a DEBUG log containing the error from disk. 

Do not paste from the GUI log.
Do not just paste a traceback/error.

**Environment (please complete the following information):**
 Windows 10

Version: fce4771c5b627f8de6868dd4ab6bc53f7b22d303 (master)

**Additional information**
![F2F7F7D5-3710-444C-BE42-E200C744B370](https://user-images.githubusercontent.com/97095/149644511-64eafdbb-b894-4b43-a724-02e4f7be513b.jpeg)
Add any other information about the problem here.

**Comment by evilhero** [comment]
Try changing the interface to carbon as opposed to the default. It might correctthe positioning if the css isn't being cached.

**Comment by AtariBaby** [comment]
Doesn’t change much. You cant’s see my cursor but if I go past the “e” in “check”, the link text stops highlighting and only the notification action happens. But I’m glad for being shown 
![8FD20E19-229C-4CB0-9C6F-512B556677CA](https://user-images.githubusercontent.com/97095/149644861-341a3337-087a-4706-805f-75b2c2556575.jpeg)
![E1DA06AA-AD58-4D6E-89C4-13E328456DDD](https://user-images.githubusercontent.com/97095/149644862-76656527-a7a2-413e-953e-d8cd8aa08846.jpeg)
carbon! Easier on the eyes!

**Comment by jaytay79** [comment]
It's the same problem in Edge on Windows too

**Comment by evilhero** [comment]
Should be fixed in python3-dev now (awaiting merge up to master in a few days probably)

**Comment by AtariBaby** [comment]
I think this is now fixed!
