### ISSUE TITLE
Discord notification cards display incorrect date and time.

### ISSUE THREAD

**Issue by Nymarra** [mylar3/mylar3#1007]
**Describe the bug**
The new Discord notification cards added in [1003](https://github.com/mylar3/mylar3/pull/1003) do not display the proper system time.

**CarePackage**

Logs do not appear to yield anything useful, the lines related to the postprocessing are below: 

```
23-Jan-2022 02:50:59 - INFO    :: mylar.foundsearch.1017 : ThreadPoolExecutor-0_0 : [POST-PROCESSING][UPDATER] Updating Status (Post-Processed) now completed for Daredevil/Punisher: Seventh Circle Infinite Comic issue: 1
23-Jan-2022 02:50:59 - INFO    :: mylar.search_results.354 : SEARCH-QUEUE : There are 0 results
23-Jan-2022 02:50:59 - DEBUG   :: mylar.Process_next.3010 : ThreadPoolExecutor-0_0 : [annchk:no] issue to update: #1
23-Jan-2022 02:50:59 - INFO    :: mylar.search.250 : SEARCH-QUEUE : resultset: []
23-Jan-2022 02:50:59 - DEBUG   :: mylar.search.258 : SEARCH-QUEUE : sleep...15s
23-Jan-2022 02:50:59 - DEBUG   :: mylar.Process_next.3017 : ThreadPoolExecutor-0_0 : writing: {'Status': 'Downloaded', 'Location': 'Daredevil-Punisher Seventh Circle Infinite Comic 01 (2016).cbz'} -- {'IssueID': '517966'}
23-Jan-2022 02:50:59 - INFO    :: mylar.notify.592 : ThreadPoolExecutor-0_0 : [POST-PROCESSING][NOTIFIER]Discord notifications sent.
23-Jan-2022 02:50:59 - INFO    :: mylar.Process_next.3150 : ThreadPoolExecutor-0_0 : [POST-PROCESSING] Post-Processing completed for: Daredevil/Punisher: Seventh Circle Infinite Comic #1
23-Jan-2022 02:50:59 - INFO    :: mylar.Process.1972 : ThreadPoolExecutor-0_0 : [POST-PROCESSING] Manual post-processing completed for 1 issues.
```

This screenshot of the notification for the same issue should show the issue more clearly:

![Screen Shot 2022-01-23 at 2 57 44 AM](https://user-images.githubusercontent.com/98235487/150675944-c0dc0f91-5437-4dd9-87b6-d3fab401565e.png)

Here you can see both the actual time the message was received (2:50 am), and the timestamp on the new notification card (yesterday at 6:50 pm).

**Environment (please complete the following information):**
 - OS: [e.g. Windows10] MacOS
 - Branch / commit: [e.g. Dev/38aksi1] Dev/07180d18e98e9c6160a1603798168b595b95b25e

**Additional information**
Add any other information about the problem here.

It is worth noting that my timezone is UTC-8. The likeliest culprit is that the notification is assuming my system time *is* UTC, and then adding my timezone conversion to generate a timestamp for the card, as that would lead to it thinking it happened 8 hours in the past.

**Comment by barbequesauce** [comment]
Similar to #1006 - @misleadingrhino given that was your PR, can you take a crack at addressing it please?

**Comment by barbequesauce** [comment]
Change merged to dev, should be fixed now thanks @misleadingrhino

**Comment by Nymarra** [comment]
Confirmed fixed in [1008](https://github.com/mylar3/mylar3/pull/1008). Closing.
