### ISSUE TITLE
Mylar will not start ... dies to command line

### ISSUE THREAD

**Issue by holdeni** [mylar3/mylar3#1015]
It seems there is something in the commit d088eb27f5e264d45cb3477fdfac6420c6fa8939 
in the python3-dev branch that causes my Mylar start up to die at the point where it indicates in the output

24-Jan-2022 16:30:52 - INFO :: mylar.main.266 : MainThread : [AUTO-BACKUP] Backing up mylar.db & config.ini files for safety.

I'm starting Mylar3 using the command line
python3 ./Mylar.py --nolaunch --pidfile mylar.pid --verbose

If I drop the d088eb2 commit and try to start Mylar with a branch head of commit bb4a86731e5c8ad603fc3b7fed2418773c48eee4
Mylar starts fine.

**Comment by holdeni** [comment]
I'm running on MacOS 10.15.7, using Python version 2.7.16. Everything before updating to the latest few commits was working fine.

**Comment by evilhero** [comment]
This has been fixed as of a few moments ago.

Update your mylar and you're good to go.

(Also, I'm sure this is just a typo - but you can't run Mylar3 with python2.x)

**Comment by holdeni** [comment]
Updated and things run well. Thanks.

Ay, I checked the version of the wrong python executable I use for Mylar last time - I'm actually running 3.8.12.
