### ISSUE TITLE
Minor issue: "You are running an unknown version of mylar

### ISSUE THREAD

**Issue by thewindupboy** [mylar3/mylar3#1025]
**Describe the bug**
My host just updated my Mylar install to Mylar3.  Everything is working fine BUT I constantly have the 'You are running an unknown version of mylar' message.  Choosing 'Update' does not resolve it.
The version section in settings also shows [None]

**CarePack
[carepackage.zip](https://github.com/mylar3/mylar3/files/7960011/carepackage.zip)
age**
On the config page, there is a button labelled "CarePackage". Pressing this button will download a zip file containing a redacted copy of your config, your database, a summary of your operating environment, and your logs. Upload that file here.

If you're uncomfortable with pasting your CarePackage, include a DEBUG log containing the error from disk. 

Do not paste from the GUI log.
Do not just paste a traceback/error.

**Environment (please complete the following information):**
 - OS: [e.g. Windows10]
 - Branch / commit: [e.g. Dev/38aksi1]

**Additional information**
Add any other information about the problem here.

**Comment by evilhero** [comment]
Should be fixed in latest builds since we put in all the new checks for version checking.

If not, please open a new issue with the relevant information attached.
