### ISSUE TITLE
NZBGet Forced Priority Option for downloads

### ISSUE THREAD

**Issue by j-remy11** [mylar3/mylar3#1028]
Can you please add "forced" priority option to the nzbget downloader in mylar3? I can only select Default, low, normal, high, and paused priority for my comics and would like to have the "forced" priority option added so comics can automatically download even if nzbget is in paused mode.

I did not see this request on github.

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04 
 - Branch / commit: Latest Docker image from Linuxserverio 

**Additional information**

Everything works for me as it should but mylar3 doesnt have all the priority options for nzbget and would like the "forced" priority to be added cause that lets nzbs download automatically regardless of nzbget being in paused mode.

**Comment by evilhero** [comment]
Added in python3-dev as of today

**Comment by j-remy11** [comment]
Appreciate the quick response! Thanks again for all your hard work!
