### ISSUE TITLE
ModuleNotFoundError: No module named 'apscheduler'

### ISSUE THREAD

**Issue by mediumwalter** [mylar3/mylar3#1043]
I have seen other people with this issue, but i haven't been able to find a solution. I got this to work fine on another raspberry pi, but not this one.

 - OS: debian buster, raspberry pi
 - Branch / commit: master

$ sudo python3 "/opt/mylar3/Mylar.py" -v
Traceback (most recent call last):
  File "/opt/mylar3/Mylar.py", line 26, in <module>
    import mylar
  File "/opt/mylar3/mylar/__init__.py", line 37, in <module>
    from apscheduler.schedulers.background import BackgroundScheduler
ModuleNotFoundError: No module named 'apscheduler'

**Comment by evilhero** [comment]
There are installation instructions / requirements you should probably read before installing:

https://github.com/mylar3/mylar3/wiki/Installation-Instructions

**Comment by mediumwalter** [comment]
I have already run that. Ran it again just to be sure:

pip3 install -r "/opt/mylar3/requirements.txt"
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: APScheduler>=3.6.3 in ./.local/lib/python3.7/site-packages (from -r /opt/mylar3/requirements.txt (line 7)) (3.8.1)
Requirement already satisfied: beautifulsoup4>=4.8.2 in ./.local/lib/python3.7/site-packages (from -r /opt/mylar3/requirements.txt (line 8)) (4.10.0)
Requirement already satisfied: cfscrape>=2.0.8 in ./.local/lib/python3.7/site-packages (from -r /opt/mylar3/requirements.txt (line 9)) (2.1.1)
Requirement already satisfied: cheroot==8.2.1 in ./.local/lib/python3.7/site-packages (from -r /opt/mylar3/requirements.txt (line 10)) (8.2.1)
Requirement already satisfied: CherryPy>=18.5.0 in ./.local/lib/python3.7/site-packages (from -r /opt/mylar3/requirements.txt (line 11)) (18.6.1)
Requirement already satisfied: configparser>=4.0.2 in ./.local/lib/python3.7/site-packages (from -r /opt/mylar3/requirements.txt (line 12)) (5.2.0)
Requirement already satisfied: feedparser>=5.2.1 in ./.local/lib/python3.7/site-packages (from -r /opt/mylar3/requirements.txt (line 13)) (6.0.8)
Requirement already satisfied: Mako>=1.1.0 in ./.local/lib/python3.7/site-packages (from -r /opt/mylar3/requirements.txt (line 14)) (1.1.6)
Requirement already satisfied: natsort>=3.5.2 in ./.local/lib/python3.7/site-packages (from -r /opt/mylar3/requirements.txt (line 15)) (8.1.0)
Requirement already satisfied: Pillow>=8 in ./.local/lib/python3.7/site-packages (from -r /opt/mylar3/requirements.txt (line 16)) (9.0.1)
Requirement already satisfied: portend>=2.6 in ./.local/lib/python3.7/site-packages (from -r /opt/mylar3/requirements.txt (line 17)) (3.1.0)
Requirement already satisfied: pystun>=0.1.0 in ./.local/lib/python3.7/site-packages (from -r /opt/mylar3/requirements.txt (line 18)) (0.1.0)
Requirement already satisfied: pytz>=2019.3 in ./.local/lib/python3.7/site-packages (from -r /opt/mylar3/requirements.txt (line 19)) (2021.3)
Requirement already satisfied: rarfile>=4.0 in ./.local/lib/python3.7/site-packages (from -r /opt/mylar3/requirements.txt (line 20)) (4.0)
Requirement already satisfied: requests>=2.22.0 in ./.local/lib/python3.7/site-packages (from -r /opt/mylar3/requirements.txt (line 21)) (2.27.1)
Requirement already satisfied: simplejson>=3.17.0 in ./.local/lib/python3.7/site-packages (from -r /opt/mylar3/requirements.txt (line 22)) (3.17.6)
Requirement already satisfied: six>=1.13.0 in ./.local/lib/python3.7/site-packages (from -r /opt/mylar3/requirements.txt (line 23)) (1.16.0)
Requirement already satisfied: tzlocal>=2.0.0 in ./.local/lib/python3.7/site-packages (from -r /opt/mylar3/requirements.txt (line 24)) (4.1)
Requirement already satisfied: urllib3>=1.25.7 in ./.local/lib/python3.7/site-packages (from -r /opt/mylar3/requirements.txt (line 25)) (1.26.8)
Requirement already satisfied: setuptools>=0.7 in /usr/lib/python3/dist-packages (from APScheduler>=3.6.3->-r /opt/mylar3/requirements.txt (line 7)) (40.8.0)
Requirement already satisfied: soupsieve>1.2 in /usr/lib/python3/dist-packages (from beautifulsoup4>=4.8.2->-r /opt/mylar3/requirements.txt (line 8)) (1.8)
Requirement already satisfied: jaraco.functools in ./.local/lib/python3.7/site-packages (from cheroot==8.2.1->-r /opt/mylar3/requirements.txt (line 10)) (3.5.0)
Requirement already satisfied: more-itertools>=2.6 in ./.local/lib/python3.7/site-packages (from cheroot==8.2.1->-r /opt/mylar3/requirements.txt (line 10)) (8.12.0)
Requirement already satisfied: jaraco.collections in ./.local/lib/python3.7/site-packages (from CherryPy>=18.5.0->-r /opt/mylar3/requirements.txt (line 11)) (3.5.1)
Requirement already satisfied: zc.lockfile in ./.local/lib/python3.7/site-packages (from CherryPy>=18.5.0->-r /opt/mylar3/requirements.txt (line 11)) (2.0)
Requirement already satisfied: sgmllib3k in ./.local/lib/python3.7/site-packages (from feedparser>=5.2.1->-r /opt/mylar3/requirements.txt (line 13)) (1.0.0)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/lib/python3/dist-packages (from Mako>=1.1.0->-r /opt/mylar3/requirements.txt (line 14)) (1.1.0)
Requirement already satisfied: tempora>=1.8 in ./.local/lib/python3.7/site-packages (from portend>=2.6->-r /opt/mylar3/requirements.txt (line 17)) (5.0.1)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests>=2.22.0->-r /opt/mylar3/requirements.txt (line 21)) (2018.8.24)
Requirement already satisfied: charset-normalizer~=2.0.0; python_version >= "3" in ./.local/lib/python3.7/site-packages (from requests>=2.22.0->-r /opt/mylar3/requirements.txt (line 21)) (2.0.11)
Requirement already satisfied: idna<4,>=2.5; python_version >= "3" in /usr/lib/python3/dist-packages (from requests>=2.22.0->-r /opt/mylar3/requirements.txt (line 21)) (2.6)
Requirement already satisfied: pytz-deprecation-shim in ./.local/lib/python3.7/site-packages (from tzlocal>=2.0.0->-r /opt/mylar3/requirements.txt (line 24)) (0.1.0.post0)
Requirement already satisfied: backports.zoneinfo; python_version < "3.9" in ./.local/lib/python3.7/site-packages (from tzlocal>=2.0.0->-r /opt/mylar3/requirements.txt (line 24)) (0.2.1)
Requirement already satisfied: jaraco.text in ./.local/lib/python3.7/site-packages (from jaraco.collections->CherryPy>=18.5.0->-r /opt/mylar3/requirements.txt (line 11)) (3.7.0)
Requirement already satisfied: jaraco.classes in ./.local/lib/python3.7/site-packages (from jaraco.collections->CherryPy>=18.5.0->-r /opt/mylar3/requirements.txt (line 11)) (3.2.1)
Requirement already satisfied: tzdata; python_version >= "3.6" in ./.local/lib/python3.7/site-packages (from pytz-deprecation-shim->tzlocal>=2.0.0->-r /opt/mylar3/requirements.txt (line 24)) (2021.5)
Requirement already satisfied: importlib-resources; python_version < "3.9" in ./.local/lib/python3.7/site-packages (from jaraco.text->jaraco.collections->CherryPy>=18.5.0->-r /opt/mylar3/requirements.txt (line 11)) (5.4.0)
Requirement already satisfied: jaraco.context>=4.1 in ./.local/lib/python3.7/site-packages (from jaraco.text->jaraco.collections->CherryPy>=18.5.0->-r /opt/mylar3/requirements.txt (line 11)) (4.1.1)
Requirement already satisfied: zipp>=3.1.0; python_version < "3.10" in ./.local/lib/python3.7/site-packages (from importlib-resources; python_version < "3.9"->jaraco.text->jaraco.collections->CherryPy>=18.5.0->-r /opt/mylar3/requirements.txt (line 11)) (3.7.0)

Still no luck.

**Comment by evilhero** [comment]
If it says module not found, it's not installed for the version of python you're running it against. 

Either you have more than one version of python installed and you pip installed to the wrong one and are running the other python with Mylar or your version of python isn't at least 3.7.5 (which really should probably be 3.8+ since 3.7.x is outdated)

**Comment by mediumwalter** [comment]
Ah, you're right. I have 3.7.3. Been fooling with this for a day and didn't realize that. Thanks for your help.

**Comment by barbequesauce** [comment]
One other point - don't run mylar sudo'ing to root... you're asking for trouble.

**Comment by mediumwalter** [comment]
noted - thank you
