### ISSUE TITLE
StoryArc Refresh doesn't work on story arcs with ' in the name

### ISSUE THREAD

**Issue by foinse** [mylar3/mylar3#1057]
**Describe the bug**
I've got 7 Story Arcs added to Mylar at the moment including "Devil's Reign" and "Rise and Fall of the Shi'ar Empire". The refresh icon in the story arc page and the Refresh StoryArc button inside the Arc's work for the 5 Arcs without the single quote character in the name of the StoryArc however neither button does anything for the two Arcs with a single quote in the name

**CarePackage**

**Environment (please complete the following information):**
 - OS: Fedora
 - Branch / commit: Python3-dev/[5e4e44e85be9e47942601823ee1d8ea12665b5fb]

**Comment by barbequesauce** [comment]
@foinse  can you confirm these commits fixed your issue?

**Comment by foinse** [comment]
Yes it did fix the issue! Thanks.
