### ISSUE TITLE
Search not working for DDL

### ISSUE THREAD

**Issue by Roshri** [mylar3/mylar3#1063]
**Describe the bug**
First time Installation, I'm not using usenet and I'm trying to use DDL for the time being , while I research how to use torrents.
When I'm trying to search for a specific series using the Search option, it freezes on processing and doesn't search anything.

**Environment (please complete the following information):**
 - OS: W10
 - Branch / commit: [v0.6.4](https://github.com/mylar3/mylar3/releases/tag/v0.6.4)

**Additional information**
Add any other information about the problem here.
[carepackage.zip](https://github.com/mylar3/mylar3/files/8065303/carepackage.zip)

**Comment by evilhero** [comment]
It's hard to tell without the verbose/debug logging enabled - but if it's failing to add series, the usual culprits are :
- no CV API Key specified, or having trailing / leading spaces in the apikey
- not specifying a Comic Location path
- having Enforce Permissions on when the user running Mylar does not have proper permissions (or it's an external mount point).

Verify those settings, and if that doesn't work - look at the wiki entry for [debug logging](https://github.com/mylar3/mylar3/wiki/Debug-logging) to see how to enable it and then try to add a series again and once it fails, generate a new carepackage and throw that up and we can take a look.

**Comment by Roshri** [comment]
Trailing spaces in apikey was it!
Thanks for the quick reply!!
