### ISSUE TITLE
Mylar cant download from DDL

### ISSUE THREAD

**Issue by Roshri** [mylar3/mylar3#1064]
**Describe the bug**
I'm trying out the program and while I can search and set a series as Wanted, I've left the machine for 20 hours working an none of the issues were snatched.
When I tried to force search for an issue, it shows that it wasn't able to parse the posting date. Probably has to do with my machine locale being Japanese?
Then it says it cant finde the issue on GetComics when it does exist on the site.

Only thing I could do so far was import existing downloads from Jdwonloader to the Mylar directory but I couldn't download any new issues at all

`

> 15-2-2022 22:03:36 - INFO    :: SEARCH-QUEUE : getcomics.py:search_results:364 : There are 1 results
> 15-2-2022 22:03:36 - INFO    :: SEARCH-QUEUE : getcomics.py:search:260 : resultset: [{'title': 'Nyx #2 (2021)', 'pubdate': ', 08 12 2021 00:00:00', 'filename': 'Nyx #2 (2021)', 'size': '45M', 'pack': False, 'issues': None, 'link': 'https://getcomics.info/other-comics/nyx-2-2021/', 'year': '2021', 'id': '261502', 'site': 'DDL(GetComics)', 'page': 1, 'total_pages': 1}]
> 15-2-2022 22:03:36 - WARNING :: SEARCH-QUEUE : search_filer.py:checker:239 : Unable to convert timestamp from : (None,) ['NoneType' object is not subscriptable]
> 15-2-2022 22:03:36 - WARNING :: SEARCH-QUEUE : search_filer.py:checker:256 : Unable to parse posting date from provider result set for : Nyx #2 (2021). Error returned: 'NoneType' object is not subscriptable
> 15-2-2022 22:03:52 - INFO    :: SEARCH-QUEUE : getcomics.py:search_results:364 : There are 1 results
> 15-2-2022 22:03:52 - INFO    :: SEARCH-QUEUE : getcomics.py:search:260 : resultset: [{'title': 'Nyx #2 (2021)', 'pubdate': ', 08 12 2021 00:00:00', 'filename': 'Nyx #2 (2021)', 'size': '45M', 'pack': False, 'issues': None, 'link': 'https://getcomics.info/other-comics/nyx-2-2021/', 'year': '2021', 'id': '261502', 'site': 'DDL(GetComics)', 'page': 1, 'total_pages': 1}]
> 15-2-2022 22:03:52 - WARNING :: SEARCH-QUEUE : search_filer.py:checker:239 : Unable to convert timestamp from : (None,) ['NoneType' object is not subscriptable]
> 15-2-2022 22:03:52 - WARNING :: SEARCH-QUEUE : search_filer.py:checker:256 : Unable to parse posting date from provider result set for : Nyx #2 (2021). Error returned: 'NoneType' object is not subscriptable
> 15-2-2022 22:04:07 - INFO    :: SEARCH-QUEUE : search.py:NZB_SEARCH:1069 : bb returned from DDL(GetComics): []
> 15-2-2022 22:04:07 - INFO    :: SEARCH-QUEUE : search.py:search_init:538 : findit: {'status': False, 'provider': 'DDL(GetComics)', 'lastrun': 1644894022.4511309}
> 15-2-2022 22:04:07 - INFO    :: SEARCH-QUEUE : search.py:search_init:558 : check_once check.
> 15-2-2022 22:04:07 - INFO    :: SEARCH-QUEUE : search.py:search_init:586 : Could not find Issue 2 of Nyx (2021) using DDL(GetComics) [api]
> 15-2-2022 22:04:07 - INFO    :: SEARCH-QUEUE : search.py:search_init:597 : attempting to set DDL(GetComics) to not being the active provider.
> 15-2-2022 22:04:07 - INFO    :: SEARCH-QUEUE : search.py:search_init:599 : setting last run to: 1644894022.4511309
> 15-2-2022 22:04:07 - INFO    :: SEARCH-QUEUE : search.py:search_init:603 : setting took. Current provider is: {'DDL(GetComics)': {'type': 'DDL', 'lastrun': 1644973432.3626149, 'active': False}}
> 15-2-2022 22:04:07 - INFO    :: SEARCH-QUEUE : search.py:search_init:350 : checked_once: ['DDL(GetComics)']
> 15-2-2022 22:04:07 - INFO    :: SEARCH-QUEUE : search.py:search_init:350 : checked_once: ['DDL(GetComics)']
> 15-2-2022 22:04:07 - INFO    :: SEARCH-QUEUE : search.py:search_init:640 : Finished searching via : api. Issue not found - status kept as Wanted.`

**Environment (please complete the following information):**
 - OS: W10
 - Branch / commit: [v0.6.4]

[carepackage (1).zip](https://github.com/mylar3/mylar3/files/8075856/carepackage.1.zip)

**Comment by evilhero** [comment]
Get a carepackage and upload that. There's info in the package that is more helpful than just a log snippet.

Also turn on verbose logging and them do a search. Once it fails to find it generate a carepackage and put that someplace where we can grab it.

It has something to do with your locale on your machine not being set to a utf-8 format, or something similar.  You can tell because the log is written out in utf8, but the date has diamond icons in lieu of being able to properly display them, which means usually that your system can't display the required format.

No guarantees if we can fix this or not, cause everything is utf-8 within mylar.

**Comment by Roshri** [comment]
New carepackage and log file here
Should I try to run mylar on a VM?

[mylar.log](https://github.com/mylar3/mylar3/files/8076111/mylar.log)


> 15-2-2022 22:57:53 - DEBUG   :: SEARCH-QUEUE : getcomics.py:search:210 : [DDL-QUERY] Query set to: Nyx #1
> 15-2-2022 22:57:53 - DEBUG   :: SEARCH-QUEUE : getcomics.py:search:217 : [PROVIDER-SEARCH-DELAY][DDL] Last search took place 15 seconds ago. We're clear...
> 15-2-2022 22:57:54 - INFO    :: SEARCH-QUEUE : getcomics.py:search_results:364 : There are 3 results
> 15-2-2022 22:57:54 - DEBUG   :: SEARCH-QUEUE : getcomics.py:search_results:521 : Nyx #1 (2021) [48 M]
> 15-2-2022 22:57:54 - DEBUG   :: SEARCH-QUEUE : getcomics.py:search_results:521 : NYX - No Way Home # [235M]
> 15-2-2022 22:57:54 - DEBUG   :: SEARCH-QUEUE : getcomics.py:search_results:521 : NYX # [82 M]
> 15-2-2022 22:57:54 - INFO    :: SEARCH-QUEUE : getcomics.py:search:260 : resultset: [{'title': 'Nyx #1 (2021)', 'pubdate': ', 10 11 2021 00:00:00', 'filename': 'Nyx #1 (2021)', 'size': '48M', 'pack': False, 'issues': None, 'link': 'https://getcomics.info/other-comics/nyx-1-2021/', 'year': '2021', 'id': '220883', 'site': 'DDL(GetComics)', 'page': 1, 'total_pages': 1}, {'title': 'NYX - No Way Home #', 'pubdate': ', 08 11 2021 00:00:00', 'filename': 'NYX - No Way Home #1 - 6 (2008-2009)', 'size': '235M', 'pack': True, 'issues': '1 - 6', 'link': 'https://getcomics.info/marvel/nyx-no-way-home-1-6/', 'year': '2008-2009', 'id': '8024', 'site': 'DDL(GetComics)', 'page': 1, 'total_pages': 1}, {'title': 'NYX #', 'pubdate': ', 08 6 2015 00:00:00', 'filename': 'NYX #1 - 7 (2003-2005)', 'size': '82M', 'pack': True, 'issues': '1 - 7', 'link': 'https://getcomics.info/marvel/nyx-wannabe-1-7/', 'year': '2003-2005', 'id': '8020', 'site': 'DDL(GetComics)', 'page': 1, 'total_pages': 1}]
> 15-2-2022 22:57:54 - DEBUG   :: SEARCH-QUEUE : search_filer.py:checker:57 : checking search result: Nyx #1 (2021)
> 15-2-2022 22:57:54 - DEBUG   :: SEARCH-QUEUE : search_filer.py:checker:75 : sub: Nyx #1 (2021)
> 15-2-2022 22:57:54 - DEBUG   :: SEARCH-QUEUE : search_filer.py:checker:127 : comsize_b: 50331648
> 15-2-2022 22:57:54 - DEBUG   :: SEARCH-QUEUE : search_filer.py:checker:140 : size given as: 48.0 MB
> 15-2-2022 22:57:54 - DEBUG   :: SEARCH-QUEUE : search_filer.py:checker:220 : store date used is : 2021-11-10
> 15-2-2022 22:57:54 - DEBUG   :: SEARCH-QUEUE : search_filer.py:checker:221 : date used is : 2021-11-10
> 15-2-2022 22:57:54 - WARNING :: SEARCH-QUEUE : search_filer.py:checker:239 : Unable to convert timestamp from : (None,) ['NoneType' object is not subscriptable]
> 15-2-2022 22:57:54 - WARNING :: SEARCH-QUEUE : search_filer.py:checker:256 : Unable to parse posting date from provider result set for : Nyx #1 (2021). Error returned: 'NoneType' object is not subscriptable
> 15-2-2022 22:57:54 - DEBUG   :: SEARCH-QUEUE : search_filer.py:checker:57 : checking search result: NYX - No Way Home #
> 15-2-2022 22:57:54 - DEBUG   :: SEARCH-QUEUE : search_filer.py:checker:75 : sub: NYX - No Way Home #
> 15-2-2022 22:57:54 - DEBUG   :: SEARCH-QUEUE : search_filer.py:checker:127 : comsize_b: 246415360
> 15-2-2022 22:57:54 - DEBUG   :: SEARCH-QUEUE : search_filer.py:checker:140 : size given as: 235.0 MB
> 15-2-2022 22:57:54 - DEBUG   :: SEARCH-QUEUE : search_filer.py:checker:220 : store date used is : 2021-11-10
> 15-2-2022 22:57:54 - DEBUG   :: SEARCH-QUEUE : search_filer.py:checker:221 : date used is : 2021-11-10
> 15-2-2022 22:57:54 - WARNING :: SEARCH-QUEUE : search_filer.py:checker:239 : Unable to convert timestamp from : (None,) ['NoneType' object is not subscriptable]
> 15-2-2022 22:57:54 - WARNING :: SEARCH-QUEUE : search_filer.py:checker:256 : Unable to parse posting date from provider result set for : NYX - No Way Home #. Error returned: 'NoneType' object is not subscriptable
> 15-2-2022 22:57:54 - DEBUG   :: SEARCH-QUEUE : search_filer.py:checker:57 : checking search result: NYX #
> 15-2-2022 22:57:54 - DEBUG   :: SEARCH-QUEUE : search_filer.py:checker:75 : sub: NYX #
> 15-2-2022 22:57:54 - DEBUG   :: SEARCH-QUEUE : search_filer.py:checker:127 : comsize_b: 85983232
> 15-2-2022 22:57:54 - DEBUG   :: SEARCH-QUEUE : search_filer.py:checker:140 : size given as: 82.0 MB
> 15-2-2022 22:57:54 - DEBUG   :: SEARCH-QUEUE : search_filer.py:checker:220 : store date used is : 2021-11-10
> 15-2-2022 22:57:54 - DEBUG   :: SEARCH-QUEUE : search_filer.py:checker:221 : date used is : 2021-11-10
> 15-2-2022 22:57:54 - WARNING :: SEARCH-QUEUE : search_filer.py:checker:239 : Unable to convert timestamp from : (None,) ['NoneType' object is not subscriptable]
> 15-2-2022 22:57:54 - WARNING :: SEARCH-QUEUE : search_filer.py:checker:256 : Unable to parse posting date from provider result set for : NYX #. Error returned: 'NoneType' object is not subscriptable
> 15-2-2022 22:57:54 - DEBUG   :: SEARCH-QUEUE : getcomics.py:search:268 : sleep...15s


[carepackage (2).zip](https://github.com/mylar3/mylar3/files/8076098/carepackage.2.zip)

**Comment by Roshri** [comment]
Changed the Date Format from Windows Control Panel while mantaining the Japanese region overall for the machine and for non-Unicode programs and that seems to have fixed the issue.
When forcing a download it snatches it and then downloads it through DDL as intended.

**Comment by evilhero** [comment]
Forcing a download vs auto-search uses the same modules and date timestamp checks so there's probably no reason why it wouldn't work unless a Snatched item was coming from the RSS feed which might have a different date structure (mylar adjusts it, but it might trip on the locale thing still).

Can you maybe say what you changed the date format to within your WCP? In case this happens to someone else, it might help with future problems (knowing that Mylar can't enforce locale changes at an OS level, nor would it want to, as that should be done at the choice of the user).

Also thanks for reporting back, as well as the possible solution. I got stuck with the in-laws so I haven't been able to get to the carepackage, but it sounds like you may have figured it out by yourself without my assistance.

**Comment by Roshri** [comment]
Sure, I'll share the config I set. I'm just glad I didn't need to change the whole locale since that would mess up with most of my games that need the japanese one
![image](https://user-images.githubusercontent.com/29184137/154191038-d3dedaf3-bd92-49e5-b307-fd0fa6db42a2.png)

**Comment by Roshri** [comment]
The date issue was fixed and works as intended.
I'm having other kind of problems while downloading but unrelated to this issue so I'm closing this one
