### ISSUE TITLE
DDL files are stuck as snatched

### ISSUE THREAD

**Issue by arqcan** [mylar3/mylar3#1075]
**Describe the bug**
Downloads are getting snatched from DDL, however the post processing never happens. I can manually post process the comics from the Mylar cache folder and everything works. This has only happened within last month or so up until then everything has been fine.

**CarePackage**
[carepackage.zip](https://github.com/mylar3/mylar3/files/8146842/carepackage.zip)

**Environment (please complete the following information):**
 - OS: Windows 11
 - Branch / commit:  6e3a12bb699e1f6dd757ca8a56e57f82a8ce71cb (python3-dev)

**Comment by throwawat** [comment]
Same issue but on Ubuntu 20.04.4 LTS VM running on proxmox.

I have the Comic Location Path pointing to a mounted Samba share if that matters. I can read files just fine but DDL snatched files wind up sitting in the mylar cache forever.

**Comment by evilhero** [comment]
@throwawat would need to see a carepackage to see what's happening. I haven't been able to isolate the problems with ddl happening atm in the latest dev build, and additional logs may help isolate things.

**Comment by evilhero** [comment]
Most recent commit to python3-dev added a bunch of extra logging around the post-processing directory check aspect. If you both can update, turn on verbose/debug logging and then try to grab a DDL issue again and see if that works (there was a fix as well, but don't think it applies to you guys). 

If it doesn't work still, carepackage it up again and please attach and I can try to figure things out.

**Comment by arqcan** [comment]
Thanks for looking into it so quick. I've updated and still have the same issue. I've uploaded the care package.

[carepackage (1).zip](https://github.com/mylar3/mylar3/files/8156063/carepackage.1.zip)

there is an odd entry in the log;

2022-02-28 19:14:57	INFO	mismatched: [{'comicname': 'Ghost Rider', 'issuenumber': '1', 'comicid': '121736', 'status': 'Mismatched', 'releasedate': '2022-02-23', 'mismatch_type': 'Incorrect Dates (2019-12-01 - 2022-02-23)', 'pullyear': '2022', 'pullweek': '8'}, {'comicname': 'Angel', 'issuenumber': '2', 'comicid': '118417', 'status': 'Mismatched', 'releasedate': '2022-02-16', 'mismatch_type': 'Incorrect Dates (2019-06-25 - 2022-02-16)', 'pullyear': '2022', 'pullweek': '7'}]

the comic I was grabbing was Iron Man 17 (2022). No idea where Ghost Rider has come in.

**Comment by evilhero** [comment]
Ok, one last time - update to the latest commit of the python3-dev (just went in moments ago).  I'm hoping it will fix the problem you're having- I ran both previously on Windows and linux machines and didn't get any errors, so I'm running out of ideas (haha).

If it doesn't work after the update, please do the same thing as before - enable verbose logging, snatch a ddl issue and let the post-processing fail, then generate a new carepackage.

(We'll get this figured out hopefully soon....)

PS. The mismatched line is just when you load up the Wanted page - it lists all the issues that are in a ``mismatched`` status on the weeklypull, which basically means they're not matching up to the correct series for some reason (the Wanted page, Upcoming section has a tab that says Mismatched and tries to indicate what the problem might be).

**Comment by arqcan** [comment]
I've given it a shot this morning and still no luck, here is the care package.
[carepackage (2).zip](https://github.com/mylar3/mylar3/files/8160670/carepackage.2.zip)

**Comment by evilhero** [comment]
@arqcan  can you update and try it again please? Made an additional fix in an attempt to fix things, again.

**Comment by arqcan** [comment]
I updated and let it snatch this weeks books and still the same. Here is the care package;
[carepackage (3).zip](https://github.com/mylar3/mylar3/files/8181565/carepackage.3.zip)

**Comment by evilhero** [comment]
Ok, so what I'm seeing is:
``FileNotFoundError: [WinError 2] The system cannot find the file specified: 'D:\\Programs\\Mylar\\cache\\Spider-Woman 020 (2022) (Digital) (Zone-Empire)[__909672__].cbr' -> 'D:\\Programs\\Mylar\\cache\\Spider-Woman 020 (2022) (Digital) (Zone-Empire).cbr'`` which means it can't locate the 1st filename in the location specified.

So in looking at this for the past few days, and not being able to figure it out - these are the questions I have complied that hopefully you answer for me:

- Did your mylar cache directory (in D it looks like) have it's permissions changed or something recently that would prevent Mylar from renaming files within it? (ie. does the user running Mylar have full & complete access to the cache folder on the D drive) 

- I see you have your ct_settings ini value set to a location on your ``E:\Mylar\.ComicTagger`` - was this a previous installation? Why is it pointing there if the program doesn't reside there ? 

- You downloaded python  from the python.org website ?

- I'm assuming there is no symlinking, junctions or anything like that being done on the cache directory ? 

- If you go to the 1st tab of the configuration, what version of python does it say it's running and are the locations correct for everything ? 

- Fom a command line try doing ``where.exe python`` and see what it spits back? 

- Also from a command line type in just ``python`` (assuming you start it with python, if not whatever the executable for the python is that you're running) and paste what it returns.


If none of those pan out the only other thing I can think of is to upgrade your version of python to something in the 3.9.x range and see if that does it.

**Comment by arqcan** [comment]
Thanks for all the help in looking into this hopefully these answers are useful.

- Did your mylar cache directory (in D it looks like) have it's permissions changed or something recently that would prevent Mylar from renaming files within it? (ie. does the user running Mylar have full & complete access to the cache folder on the D drive) **The user runnig mylar has full permissions, i've given the folder an everyone (read and write permission for ease of use.**
- 
- I see you have your ct_settings ini value set to a location on your E:\Mylar\.ComicTagger - was this a previous installation? Why is it pointing there if the program doesn't reside there ? **I can't see anything within mylar but this is where my downloads are handled by SABNZB, there is a .comictagger folder in the path. I manually chancged the entry in the ini file the the path in the mylar program folder and the whole process errored out. I set it back to E:\Mylar\.ComicTagger and no more errors when the post processing runs, however the item still doesnt get post processed.....I hope that makes sense .**
- 
- You downloaded python from the python.org website? **Yes**
- 
- I'm assuming there is no symlinking, junctions or anything like that being done on the cache directory ? **Correct ,no symlinking**
- 
- If you go to the 1st tab of the configuration, what version of python does it say it's running and are the locations correct for everything ? **Python Version : 3.8.1**
- 
- Fom a command line try doing where.exe python and see what it spits back? **C:\Users\****\AppData\Local\Programs\Python\Python38\python.exe**
- 
- Also from a command line type in just python (assuming you start it with python, if not whatever the executable for the python is that you're running) and paste what it returns. **Python 3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 23:11:46) [MSC v.1916 64 bit (AMD64)] on win32**
- 
- If none of those pan out the only other thing I can think of is to upgrade your version of python to something in the 3.9.x range and see if that does it. **i've upgraded to 3.9.10**

**Comment by evilhero** [comment]
Does giving everyone access for you mean that it's open to everyone - fully ? I know sometimes that that's just read & write, and leaves out the execute, and some other aspects. Also if they're inheritable or not from the parent folder. Giving Mylar Full Control of the mylar folder and subfolders is normally required, as it needs to write/delete/rename/move etc from therein.

When you say you upgraded python - did you remove 3.8.1 prior to installing 3.9.10 ? I'm pretty sure with Windows you have to remove each version independently (update doesn't update, it just creates another instance kinda thing). Someone in the discord mentioned that it looks like you're running the VS Studio version of python that was from VS Studio 2017.  Not sure if that's the case, but maybe you can confirm or not ? 

I don't see any version of python listed in your environment path at all - how are exactly are you starting Mylar ?

You have an ``*`` multiple times in the python response path - is that what it is replying with or did github just go github on the text and remove something ?

You didn't provide a new carepackage for the 3.9.10 install - maybe that might help abit more too now that you're running an updated version.

**Comment by arqcan** [comment]
Thanks for all the suggestions, I removed all version of python and mylar and just started again. everything seems to be fine now, must have been something janky with my setup.
