### ISSUE TITLE
Adding QBittorrent / Deluge results in error

### ISSUE THREAD

**Issue by WorldTeacher** [mylar3/mylar3#1076]
**Describe the bug**
When trying to add qbittorrent / Deluge to mylar3 gives an error about not being able to add the downloader.
Tried using all available qbit & deluge Ports

**CarePackage**
[mylar.log](https://github.com/mylar3/mylar3/files/8148898/mylar.log)

**Environment (please complete the following information):**
 - OS: UnRaid (Docker)
 - Branch / commit: linuxserver/mylar3:latest

**Comment by evilhero** [comment]
Your log only shows an import. Nothing about your config or any downloaders. Can't help at all with that amount of info.

Check the wiki on how to enable verbose/debug logging, try to add your downloader and then generate a carepackage and attach that.

You may also want to read the basic usage portion of the wiki just to make sure you have the basics setup.
