### ISSUE TITLE
Error 500 due to missing directory which keeps being added to.

### ISSUE THREAD

**Issue by pjones112000** [mylar3/mylar3#1077]
When opening the comic Tarot Witch of the Black Rose (2000) from Broadsword Comics, I'm getting an error 500.  It's trying to access a folder that doesn't exist.  Originally it said that Extras was missing, the next time it said that CoversExtras was missing, the following time was CoversCoversExtrasExtras and then CoversCoversCoversExtrasCoversExtrasExtras....and so on.

Do not paste from the GUI log.
Do not just paste a traceback/error.

**Environment (please complete the following information):**
 - OS: Debian Buster
 
I'm also having a problem with DDL downloaded files not importing.  So far, none are importing at all.  I'm not clear whether this is connected or not.  I wasn't having any issues prior to this latest update.

**Comment by evilhero** [comment]
Need a carepackage with debug logging for any kind of assistance.

**Comment by pjones112000** [comment]
Ah....I thought I had.  It looks like the carepackage.zip is way to big.  Here's the error as it appears on the screen:

500 Internal Server Error
The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/cherrypy/_cprequest.py", line 638, in respond
    self._do_respond(path_info)
  File "/usr/local/lib/python3.7/dist-packages/cherrypy/_cprequest.py", line 697, in _do_respond
    response.body = self.handler()
  File "/usr/local/lib/python3.7/dist-packages/cherrypy/lib/encoding.py", line 223, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/media/storage/mylar3/mylar/webserve.py", line 346, in comicDetails
    if os.stat(os.path.join(root, direc))[stat.ST_MTIME] > filesupdated.timestamp():
FileNotFoundError: [Errno 2] No such file or directory: '/media/cbooks/mylar/Broadsword Comics/Tarot Witch of the Black Rose (2000)/CoversCoversCoversCoversExtrasCoversExtrasExtrasCoversCoversExtrasExtrasCoversExtrasExtras'

**Comment by pjones112000** [comment]
[mylar.log](https://github.com/mylar3/mylar3/files/8149488/mylar.log)
I deleted the logs to start with a short one before reproducing the problem.  See attached log file.

**Comment by pjones112000** [comment]
As stated, the carepackage is way too big to attach....I'm not sure how I accidentally closed the comment.  Regardless, I deleted the logs and re-created the error and attached the log file from that.  The database is too big to attach as well.
[MylarRunningEnvironment.txt](https://github.com/mylar3/mylar3/files/8149503/MylarRunningEnvironment.txt)

**Comment by evilhero** [comment]
If I'm reading just the error properly, you're running python3.7.x which is a problem.

Mylar only runs with python3.8.1+ now due to some post-processing conflicts with bundled libraries.

**Comment by pjones112000** [comment]
I just upgraded to 3.8.2....same error

**Comment by pjones112000** [comment]
Latest carepackage...(ish)
[mylar.log](https://github.com/mylar3/mylar3/files/8149781/mylar.log)
[MylarRunningEnvironment.txt](https://github.com/mylar3/mylar3/files/8149782/MylarRunningEnvironment.txt)

**Comment by evilhero** [comment]
I'm guessing that the particular series folder has both an Extras and a Covers folder? Removing those folders would allow the page to load, but it would only be a temporary measure as I'm assuming they're there for some reason. 

You also don't mention which branch / commit of mylar you're running, which also may impact things (possibly).

**Comment by pjones112000** [comment]
Version: [4d2666d781629771e9170f2f41f9520e22eba8f3]
Branch: Master

**Comment by pjones112000** [comment]
To be honest, I'm assuming that Mylar created the covers folder.  I deleted and it does indeed come up...so far it hasn't been re-created.

**Comment by evilhero** [comment]
Mylar doesn't create a Covers folder or any subfolder.  Something outside of Mylar did that or was manually done at some point in guessing. But you yeah, wouldn't have been mylar (it sometimes creates files in the series folders, not subfolders)

**Comment by pjones112000** [comment]
Well, at least it solves this problem....it probably should handle this better, but, at least I know what the problem is and can move on.

**Comment by evilhero** [comment]
It should be fixed in python3-dev already, but it hasn't merged up into master - which is why I was also asking the branch you were on as I figured you were probably on the master branch.
