### ISSUE TITLE
'Unknown version of mylar' error permanently displayed

### ISSUE THREAD

**Issue by programmatix** [mylar3/mylar3#1082]
I'm using mylar3 from git, running commit 4d2666d781629771e9170f2f41f9520e22eba8f3 tagged v0.6.4 from 8th Feb.

I have a permanent error box displaying something like 'unknown version of mylar' at the bottom right.  It goes away when I close it but reappears whenever I change pages.

In the logs I see this:
```
02-Mar-2022 23:17:08 - INFO    :: mylar.getVersion.131 : MAIN : cur_commit_hash: v0.6.4
02-Mar-2022 23:17:08 - INFO    :: mylar.getVersion.132 : MAIN : cur_branch: 4d2666d781629771e9170f2f41f9520e22eba8f3
02-Mar-2022 23:17:08 - ERROR   :: mylar.getVersion.135 : MAIN : Output does not look like a hash, not using it
02-Mar-2022 23:17:08 - WARNING :: mylar.getVersion.159 : MAIN : Could not retrieve branch name [None] from git. Defaulting to Master.
```
Looking through the source I see it's grabbing this from `git describe`.  The output of that on my system is:
```
$ git describe --exact-match --tags 2> %s && git rev-parse HEAD --abbrev-ref HEAD
v0.6.4
4d2666d781629771e9170f2f41f9520e22eba8f3
master
```
I am using Windows WSL2 with some variant of Ubuntu, and git version 2.25.1.

**Comment by evilhero** [comment]
In the config.ini, try setting the ``git_user = mylar3``, ``git_branch = master ``, ``check_github_on_startup = True ``.

It sounds like it can find the git executable in your PATH, but the user running mylar has to have access to git, which just means that it should be in your PATH environment.

The python3-dev branch has the updated fixes for the version stuff but is not in master until we can work out some post-processing bugs atm.

**Comment by programmatix** [comment]
Thanks for the reply, I was just about to write saying I'd found the mylar.CONFIG.CHECK_GITHUB_ON_STARTUP and this does indeed seem to do the trick.  Just double-checking that now.

**Comment by programmatix** [comment]
Yep, passing some basic sanity testing so I'll close this out.
Should I be using the python3-dev branch?  Too unstable?  I'm not doing anything with post-processing except wanting the files to be moved (which doesn't seem to be happening, that's next on my list to investigate).
