### ISSUE TITLE
KeyError: 'issues' in nzb_search

### ISSUE THREAD

**Issue by mlsmithjr** [mylar3/mylar3#1085]
**Describe the bug**
Issuing a manual search for a missing (Wanted) issue.

**CarePackage**
[carepackage.zip](https://github.com/mylar3/mylar3/files/8182511/carepackage.zip)

If you're uncomfortable with pasting your CarePackage, include a DEBUG log containing the error from disk. 

Do not paste from the GUI log.
Do not just paste a traceback/error.

**Environment (please complete the following information):**
 - OS: Linux (Docker)
 - Branch / commit: linuxserver/mylar3:latest (as of 3/3/2022 9:00pm EST)

**Additional information**
Results coming back not wrapped in a {'entries':} dictionary.  Even if corrected to wrap, it raises new keying problems elsewhere.

**Comment by evilhero** [comment]
I haven't been able to duplicate this in any way thus far, and receive no errors as well.

Can you enable verbose / debug logging and then perform a manual search again (check [here](https://github.com/mylar3/mylar3/wiki/Debug-logging) if you're unsure how to set it), and throw up a fresh carepackage?

INFO level logging is pretty useless when it comes to troubleshooting problems, and unfortunately that's what your log level was set to.

**Comment by mlsmithjr** [comment]
No problem, here it is:
[carepackage.zip](https://github.com/mylar3/mylar3/files/8182875/carepackage.zip)


BTW, I'm happy to do further analysis on this.  I know it's sometimes difficult to reproduce a problem.  If nothing in the log helps just let me know and I'll do a deep dive this weekend.
Cheers!

**Comment by evilhero** [comment]
Thanks, the debug logs helped pinpoint where it was going wrong.

Was using the wrong dictionary to pull the issues variable from when a pack was being returned in the search results - all straightened out now (tested even with your db and query to make sure - error prior to the fix, no error thereafter).

Fix will be in python3-dev shortly, and if we can nail down a DDL post-processing bug - dev will be merged up into master this weekend.

Cheers!

**Comment by mlsmithjr** [comment]
Great, fast turnaround.

Just one of the challenges of a loosely typed language.  Still my fave though ;-)
