### ISSUE TITLE
Cannot add a series from pull list

### ISSUE THREAD

**Issue by aleaax** [mylar3/mylar3#1088]
**Describe the bug**
Adding a series from the pull list fails. Shows as added but stays at the loading screen and never resolves. Disappears after restart. Debug log states that even though it found the series and it has issues when looking at CV only it finds nothing and states an error. Refreshing the series produces the same trace back error
**CarePackage**
[carepackage.zip](https://github.com/mylar3/mylar3/files/8189307/carepackage.zip)

**Environment (please complete the following information):**
 - OS: macOS 12.2
 - Branch / commit: python3-dev

**Comment by evilhero** [comment]
Gonna guess that you're ComicVine API key is incorrect - you either mis-typed it or you have a space at the beginning / end of the key and it's failing to return any items whatsover. That or the machine it's running on cannot access ComicVine's website.

Adding works fine via the pull (I just tested it against the series you were trying), so it's something isolated to your install.

**Comment by aleaax** [comment]
Thanks for the help, It was that exactly! Sorry to bother closing the issue!
