### ISSUE TITLE
qbittorrent 4.2.1 not working as a downloader

### ISSUE THREAD

**Issue by Arathen** [mylar3/mylar3#109]
**Describe the bug**
Mylar3 can't load torrents into qbittorrent 4.2.1.

**CarePackage**
24-Feb-2020 17:50:44 - DEBUG :: mylar.searcher.2412 : SEARCH-QUEUE : Torrent Provider: torznab
24-Feb-2020 17:50:44 - INFO :: mylar.torsend2client.964 : SEARCH-QUEUE : matched on Justice League
24-Feb-2020 17:50:44 - DEBUG :: mylar.torsend2client.973 : SEARCH-QUEUE : filename for torrent set to : /home/mylar/mylar3/cache/Justice_League_41_2020.torrent
24-Feb-2020 17:50:46 - DEBUG :: mylar.torsend2client.1176 : SEARCH-QUEUE : [torznab] Saved torrent file to : /home/mylar/mylar3/cache/Justice_League_41_2020.torrent
24-Feb-2020 17:50:46 - INFO :: mylar.torsend2client.1254 : SEARCH-QUEUE : Connected to qBittorrent! Will try to add torrent now!
24-Feb-2020 17:50:46 - INFO :: mylar.load_torrent.62 : SEARCH-QUEUE : filepath to torrent file set to : /home/mylar/mylar3/cache/Justice_League_41_2020.torrent
24-Feb-2020 17:50:46 - INFO :: mylar.load_torrent.65 : SEARCH-QUEUE : Checking if Torrent Exists!
24-Feb-2020 17:50:46 - DEBUG :: mylar.load_torrent.75 : SEARCH-QUEUE : FileName (load_torrent): Justice_League_41_2020.torrent
24-Feb-2020 17:50:46 - DEBUG :: mylar.load_torrent.77 : SEARCH-QUEUE : Torrent Hash (load_torrent): "97044016FED31D0775008A67ECD0EDD9AB2181B7"
24-Feb-2020 17:50:46 - DEBUG :: mylar.find_torrent.40 : SEARCH-QUEUE : Finding Torrent hash: 97044016FED31D0775008A67ECD0EDD9AB2181B7
24-Feb-2020 17:50:46 - DEBUG :: mylar.get_torrent.48 : SEARCH-QUEUE : Getting Torrent info hash: 97044016FED31D0775008A67ECD0EDD9AB2181B7
24-Feb-2020 17:50:46 - ERROR :: mylar.get_torrent.52 : SEARCH-QUEUE : Could not get torrent info for 97044016FED31D0775008A67ECD0EDD9AB2181B7
24-Feb-2020 17:50:46 - INFO :: mylar.load_torrent.87 : SEARCH-QUEUE : Torrent not added yet, trying to add it now!
24-Feb-2020 17:50:46 - INFO :: mylar.load_torrent.93 : SEARCH-QUEUE : Setting download label to: Mylar
24-Feb-2020 17:50:46 - ERROR :: mylar.load_torrent.114 : SEARCH-QUEUE : Torrent not added
24-Feb-2020 17:50:46 - INFO :: mylar.torsend2client.1262 : SEARCH-QUEUE : Unable to add torrent to qBittorrent
24-Feb-2020 17:50:46 - ERROR :: mylar.searcher.2430 : SEARCH-QUEUE : Unable to send torrent - check logs and settings (this would be marked as a BAD torrent if Failed Handling was enabled)
24-Feb-2020 17:50:46 - INFO :: mylar.search_init.396 : SEARCH-QUEUE : Could not find Issue 41 of Justice League (2018) using Jackett-ETTV [api]

**Environment (please complete the following information):**
 - OS: Linux Ubuntu 18.04.4 LTS
 - Branch / commit: Master 9c0fd7bc4ada69f373a42f6d4a9ef0187a2f6e47

Mylar host information:
Linux ubuntu 4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Mylar python information:
Python 3.8.0
/usr/bin/python3.8

PIP (freeze) list:
altgraph==0.17
APScheduler==3.6.3
asn1crypto==0.24.0
attrs==17.4.0
Automat==0.6.0
beautifulsoup4==4.8.2
certifi==2018.1.18
cffi==1.14.0
cfscrape==2.1.1
chardet==3.0.4
cheroot==8.2.1
CherryPy==18.5.0
click==6.7
colorama==0.3.7
command-not-found==0.3
configobj==5.0.6
configparser==4.0.2
constantly==15.1.0
cryptography==2.1.4
distro-info===0.18ubuntu0.18.04.1
feedparser==5.2.1
httplib2==0.9.2
hyperlink==17.3.1
idna==2.6
incremental==16.10.1
iotop==0.6
jaraco.classes==3.1.0
jaraco.collections==3.0.0
jaraco.functools==3.0.0
jaraco.text==3.2.0
keyring==10.6.0
keyrings.alt==3.0
language-selector==0.1
Mako==1.1.1
MarkupSafe==1.1.1
more-itertools==8.2.0
natsort==4.0.4
netifaces==0.10.4
PAM==0.4.2
Pillow==7.0.0
portend==2.6
pyasn1==0.4.2
pyasn1-modules==0.2.1
pycparser==2.19
pycrypto==2.6.1
pycurl==7.43.0.1
pygobject==3.26.1
PyInstaller==3.6
pyOpenSSL==17.5.0
PyPDF2==1.26.0
PyQt5==5.12.2
PyQt5-sip==12.7.0
pyserial==3.4
python-apt==1.6.5+ubuntu0.2
python-debian==0.1.32
pytz==2019.3
pyxdg==0.25
PyYAML==3.12
requests==2.23.0
requests-unixsocket==0.1.5
SecretStorage==2.3.1
service-identity==16.0.0
simplejson==3.17.0
six==1.14.0
soupsieve==2.0
speedtest-cli==2.0.0
ssh-import-id==5.7
systemd-python==234
tempora==2.1.0
Twisted==17.9.0
tzlocal==2.0.0
ufw==0.36
unattended-upgrades==0.1
unrar==0.4
unrar-cffi==0.1.0a5
urllib3==1.25.8
zc.lockfile==2.0
zope.interface==4.3.2

Mylar running environment:
                LANG = en_AU.UTF-8
            SUDO_GID = 1000
             DISPLAY = localhost:10.0
            USERNAME = mylar
           JAVA_HOME = /usr/lib/jvm/java-8-oracle
        SUDO_COMMAND = /bin/bash
            J2SDKDIR = /usr/lib/jvm/java-8-oracle
          DERBY_HOME = /usr/lib/jvm/java-8-oracle/db
                USER = mylar
                 PWD = /home/mylar/mylar3
                HOME = /home/mylar
             J2REDIR = /usr/lib/jvm/java-8-oracle/jre
           SUDO_USER = arathen
       XDG_DATA_DIRS = /usr/local/share:/usr/share:/var/lib/snapd/desktop
            SUDO_UID = 1000
                MAIL = /var/mail/mylar
               SHELL = /bin/bash
                TERM = xterm
               SHLVL = 1
            LANGUAGE = en_AU:en
             LOGNAME = mylar
                PATH = /home/mylar/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin
              OLDPWD = /home/mylar
                   _ = /usr/bin/python3.8

Mylar git status:
git version 2.17.1

On branch master
Your branch is up to date with 'origin/master'.
nothing to commit, working tree clean

**Additional information**
Just installed this today after seeing the code freeze announcement in the previous version, so qbittorrent integration has not worked successfully so far.

**Comment by barbequesauce** [comment]
There's a few recent commits on the dev branch that might fix this - would you mind switching over?

1. Shut Mylar down
2. From a command line, navigate to the root of the Mylar install
3. run this command `git checkout -b python3-dev`
4. edit config.ini and change `git_branch = python3-dev`
5. Restart Mylar and try again

**Comment by Arathen** [comment]
Ok, done, but sadly no change in the test result.

```
25-Feb-2020 08:59:47 - INFO :: mylar.torsend2client.964 : SEARCH-QUEUE : matched on Justice League
25-Feb-2020 08:59:47 - DEBUG :: mylar.torsend2client.973 : SEARCH-QUEUE : filename for torrent set to : /home/mylar/mylar3/cache/Justice_League_41_2020.torrent
25-Feb-2020 08:59:49 - DEBUG :: mylar.torsend2client.1176 : SEARCH-QUEUE : [torznab] Saved torrent file to : /home/mylar/mylar3/cache/Justice_League_41_2020.torrent
25-Feb-2020 08:59:49 - INFO :: mylar.torsend2client.1254 : SEARCH-QUEUE : Connected to qBittorrent! Will try to add torrent now!
25-Feb-2020 08:59:49 - INFO :: mylar.load_torrent.62 : SEARCH-QUEUE : filepath to torrent file set to : /home/mylar/mylar3/cache/Justice_League_41_2020.torrent
25-Feb-2020 08:59:49 - INFO :: mylar.load_torrent.65 : SEARCH-QUEUE : Checking if Torrent Exists!
25-Feb-2020 08:59:49 - DEBUG :: mylar.load_torrent.75 : SEARCH-QUEUE : FileName (load_torrent): Justice_League_41_2020.torrent
25-Feb-2020 08:59:49 - DEBUG :: mylar.load_torrent.77 : SEARCH-QUEUE : Torrent Hash (load_torrent): "97044016FED31D0775008A67ECD0EDD9AB2181B7"
25-Feb-2020 08:59:49 - DEBUG :: mylar.find_torrent.40 : SEARCH-QUEUE : Finding Torrent hash: 97044016FED31D0775008A67ECD0EDD9AB2181B7
25-Feb-2020 08:59:49 - DEBUG :: mylar.get_torrent.48 : SEARCH-QUEUE : Getting Torrent info hash: 97044016FED31D0775008A67ECD0EDD9AB2181B7
25-Feb-2020 08:59:49 - ERROR :: mylar.get_torrent.52 : SEARCH-QUEUE : Could not get torrent info for 97044016FED31D0775008A67ECD0EDD9AB2181B7
25-Feb-2020 08:59:49 - INFO :: mylar.load_torrent.87 : SEARCH-QUEUE : Torrent not added yet, trying to add it now!
25-Feb-2020 08:59:49 - INFO :: mylar.load_torrent.93 : SEARCH-QUEUE : Setting download label to: Mylar
25-Feb-2020 08:59:49 - ERROR :: mylar.load_torrent.114 : SEARCH-QUEUE : Torrent not added
25-Feb-2020 08:59:49 - INFO :: mylar.torsend2client.1262 : SEARCH-QUEUE : Unable to add torrent to qBittorrent
25-Feb-2020 08:59:49 - ERROR :: mylar.searcher.2430 : SEARCH-QUEUE : Unable to send torrent - check logs and settings (this would be marked as a BAD torrent if Failed Handling was enabled)
25-Feb-2020 08:59:49 - INFO :: mylar.search_init.396 : SEARCH-QUEUE : Could not find Issue 41 of Justice League (2018) using Jackett-ETTV [api]
```

Now using:

Mylar Version: python3-dev 
-- git (build 41a72034c35899525b7e7ff160ca72d1d5139c5b)
Python Version : 3.8.0
Language : en_AU.UTF-8

Thanks for looking into it.

**Comment by evilhero** [comment]
Can you pull the latest python3-dev again? I just added some exception logging to the ```unable to send``` error so that it will display the actual error being sent back from the client. Hopefully that will help us nail down what's happening.

**Comment by Arathen** [comment]
Done.

`25-Feb-2020 13:42:21 - DEBUG :: mylar.searcher.2412 : SEARCH-QUEUE : Torrent Provider: torznab
25-Feb-2020 13:42:21 - INFO :: mylar.torsend2client.964 : SEARCH-QUEUE : matched on Justice League
25-Feb-2020 13:42:21 - DEBUG :: mylar.torsend2client.973 : SEARCH-QUEUE : filename for torrent set to : /home/mylar/mylar3/cache/Justice_League_41_2020.torrent
25-Feb-2020 13:42:24 - DEBUG :: mylar.torsend2client.1176 : SEARCH-QUEUE : [torznab] Saved torrent file to : /home/mylar/mylar3/cache/Justice_League_41_2020.torrent
25-Feb-2020 13:42:24 - INFO :: mylar.torsend2client.1254 : SEARCH-QUEUE : Connected to qBittorrent! Will try to add torrent now!
25-Feb-2020 13:42:24 - INFO :: mylar.load_torrent.62 : SEARCH-QUEUE : filepath to torrent file set to : /home/mylar/mylar3/cache/Justice_League_41_2020.torrent
25-Feb-2020 13:42:24 - INFO :: mylar.load_torrent.65 : SEARCH-QUEUE : Checking if Torrent Exists!
25-Feb-2020 13:42:24 - DEBUG :: mylar.load_torrent.75 : SEARCH-QUEUE : FileName (load_torrent): Justice_League_41_2020.torrent
25-Feb-2020 13:42:24 - DEBUG :: mylar.load_torrent.77 : SEARCH-QUEUE : Torrent Hash (load_torrent): "97044016FED31D0775008A67ECD0EDD9AB2181B7"
25-Feb-2020 13:42:24 - DEBUG :: mylar.find_torrent.40 : SEARCH-QUEUE : Finding Torrent hash: 97044016FED31D0775008A67ECD0EDD9AB2181B7
25-Feb-2020 13:42:24 - DEBUG :: mylar.get_torrent.48 : SEARCH-QUEUE : Getting Torrent info hash: 97044016FED31D0775008A67ECD0EDD9AB2181B7
25-Feb-2020 13:42:24 - ERROR :: mylar.get_torrent.52 : SEARCH-QUEUE : Could not get torrent info for 97044016FED31D0775008A67ECD0EDD9AB2181B7
25-Feb-2020 13:42:24 - INFO :: mylar.load_torrent.87 : SEARCH-QUEUE : Torrent not added yet, trying to add it now!
25-Feb-2020 13:42:24 - INFO :: mylar.load_torrent.93 : SEARCH-QUEUE : Setting download label to: Mylar
25-Feb-2020 13:42:24 - ERROR :: mylar.load_torrent.114 : SEARCH-QUEUE : Torrent not added - 'dict' object has no attribute 'iteritems'
25-Feb-2020 13:42:24 - INFO :: mylar.torsend2client.1262 : SEARCH-QUEUE : Unable to add torrent to qBittorrent
25-Feb-2020 13:42:24 - ERROR :: mylar.searcher.2430 : SEARCH-QUEUE : Unable to send torrent - check logs and settings (this would be marked as a BAD torrent if Failed Handling was enabled)
25-Feb-2020 13:42:24 - INFO :: mylar.search_init.396 : SEARCH-QUEUE : Could not find Issue 41 of Justice League (2018) using Jackett-ETTV [api]
`

**Comment by Arathen** [comment]
Done.

```
25-Feb-2020 13:42:21 - DEBUG :: mylar.searcher.2412 : SEARCH-QUEUE : Torrent Provider: torznab
25-Feb-2020 13:42:21 - INFO :: mylar.torsend2client.964 : SEARCH-QUEUE : matched on Justice League
25-Feb-2020 13:42:21 - DEBUG :: mylar.torsend2client.973 : SEARCH-QUEUE : filename for torrent set to : /home/mylar/mylar3/cache/Justice_League_41_2020.torrent
25-Feb-2020 13:42:24 - DEBUG :: mylar.torsend2client.1176 : SEARCH-QUEUE : [torznab] Saved torrent file to : /home/mylar/mylar3/cache/Justice_League_41_2020.torrent
25-Feb-2020 13:42:24 - INFO :: mylar.torsend2client.1254 : SEARCH-QUEUE : Connected to qBittorrent! Will try to add torrent now!
25-Feb-2020 13:42:24 - INFO :: mylar.load_torrent.62 : SEARCH-QUEUE : filepath to torrent file set to : /home/mylar/mylar3/cache/Justice_League_41_2020.torrent
25-Feb-2020 13:42:24 - INFO :: mylar.load_torrent.65 : SEARCH-QUEUE : Checking if Torrent Exists!
25-Feb-2020 13:42:24 - DEBUG :: mylar.load_torrent.75 : SEARCH-QUEUE : FileName (load_torrent): Justice_League_41_2020.torrent
25-Feb-2020 13:42:24 - DEBUG :: mylar.load_torrent.77 : SEARCH-QUEUE : Torrent Hash (load_torrent): "97044016FED31D0775008A67ECD0EDD9AB2181B7"
25-Feb-2020 13:42:24 - DEBUG :: mylar.find_torrent.40 : SEARCH-QUEUE : Finding Torrent hash: 97044016FED31D0775008A67ECD0EDD9AB2181B7
25-Feb-2020 13:42:24 - DEBUG :: mylar.get_torrent.48 : SEARCH-QUEUE : Getting Torrent info hash: 97044016FED31D0775008A67ECD0EDD9AB2181B7
25-Feb-2020 13:42:24 - ERROR :: mylar.get_torrent.52 : SEARCH-QUEUE : Could not get torrent info for 97044016FED31D0775008A67ECD0EDD9AB2181B7
25-Feb-2020 13:42:24 - INFO :: mylar.load_torrent.87 : SEARCH-QUEUE : Torrent not added yet, trying to add it now!
25-Feb-2020 13:42:24 - INFO :: mylar.load_torrent.93 : SEARCH-QUEUE : Setting download label to: Mylar
25-Feb-2020 13:42:24 - ERROR :: mylar.load_torrent.114 : SEARCH-QUEUE : Torrent not added - 'dict' object has no attribute 'iteritems'
25-Feb-2020 13:42:24 - INFO :: mylar.torsend2client.1262 : SEARCH-QUEUE : Unable to add torrent to qBittorrent
25-Feb-2020 13:42:24 - ERROR :: mylar.searcher.2430 : SEARCH-QUEUE : Unable to send torrent - check logs and settings (this would be marked as a BAD torrent if Failed Handling was enabled)
25-Feb-2020 13:42:24 - INFO :: mylar.search_init.396 : SEARCH-QUEUE : Could not find Issue 41 of Justice League (2018) using Jackett-ETTV [api]
```

**Comment by evilhero** [comment]
Perfect! Just as I thought too, something that was available in python2 has been depreciated in python3 so we need to adjust how that particular module interacts with the client. Shouldn't be too hard to fix this part at least.

**Comment by evilhero** [comment]
Latest commit addresses the iteritems error that was being indicated in the logs. Not sure if anything subsequent to that will occur, but if you could try it and let us know it'd be much appreciated!

**Comment by Arathen** [comment]
Winner. All fixed. Adds successfully with the correct label.

Nice work and thanks for the quick fix! :)
