### ISSUE TITLE
Unable to start Mylar3 with Python 3.8.10 in Windows 10: no module named requests

### ISSUE THREAD

**Issue by lodasi** [mylar3/mylar3#1094]
Unable to start Mylar3 with Python 3.8.10 in Windows 10: no module named requests.

I am able to start Mylar3 with Python 3.7.9 despite being below the necessary version. (py -3.7 mylar.py works)

I have not attached a CarePackage because the program terminates instantly.

```
C:\PythonPrograms\mylar3>python C:\PythonPrograms\mylar3\mylar.py
Traceback (most recent call last):
  File "C:\PythonPrograms\mylar3\mylar.py", line 27, in <module>
    import mylar
  File "C:\PythonPrograms\mylar3\mylar\__init__.py", line 27, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

**Environment (please complete the following information):**
- Windows 10
- Version: dd3438e97fca9cd2933818310752c0bc09c36cab (master)

**Comment by evilhero** [comment]
You have to do the requirements.txt installation against each python version you use to run Mylar (as per the installation section of the [wiki](https://github.com/mylar3/mylar3/wiki/Installation-Instructions)).

**Comment by lodasi** [comment]
Thank you! I have been running mylar on autopilot for years now, so I was not aware I needed to do that when switching to a new python version.
