### ISSUE TITLE
Error when trying to change Directory Location

### ISSUE THREAD

**Issue by Rumik** [mylar3/mylar3#1109]
Describe the bug
I have migrated my database from Docker to Windows and want to edit the Director Location of each comic so it matches the Windows file structure. But I'm getting an error when I attempt to do update the Directory Location.

CarePackage
Attached

Environment
 Windows10
 Ver 0.6.5.2 (master)

Additional information
Pastebin: https://pastebin.com/K3zqq1cx
[carepackage.zip](https://github.com/mylar3/mylar3/files/8283917/carepackage.zip)

**Comment by evilhero** [comment]
You can't change the directory location in the method you're doing as it's trying to rename the original location to the new location and it can't find the windows point.

Use the wiki entry (https://github.com/mylar3/mylar3/wiki/Moving-to-a-new-filesystem) [here] for instructions on how to migrate your db structure to a new structure en masse.

**Comment by Rumik** [comment]
Hmm okay, I've followed the instructions, but it doesn't seem to like it... is this normal?

17-Mar-2022 14:17:22 - WARNING :: mylar.updateComicLocation.902 : MainThread : [O:\Comics\Collection\DC Comics/Dark Knights of Steel/Dark Knights of Steel (2021)] error during conversion: 'unicodeescape' codec can't decode byte 0x5c in position 0: \ at end of string
17-Mar-2022 14:17:22 - INFO :: mylar.updateComicLocation.912 : MainThread : FFTONEWCOM_DIR is enabled. Applying the existing folder format to ALL directories regardless of existing location paths

**Comment by Rumik** [comment]
Okay the process has finished and it's worked, but the Directory Location now uses a mix of slash directions - e.g. "O:\Comics\Collection\Dark Horse Comics/Appleseed/Appleseed (2007)"

Is that a problem?

**Comment by evilhero** [comment]
I'm guessing you didn't update your folder format to the new OS pathing so it's using the old *nix style. 

Change your ``Folder Format`` directory slashes so they're appropriate for the new system. 

Re-run the locmove as you did it before with the updated folder format path now in place. That should fix things in regards to the paths.

And yes, slashes going the wrong way are considered control characters and will break usage when the slash is followed by a specific character.

**Comment by Rumik** [comment]
I did update the folder format :(

While there's a mix of slashes, downloading and serving content over OPDS is working fine. I am getting a "malformed database" error a lot now. I can't search for new titles, for example, or this happens:

500 Internal Server Error
The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "C:\Users\me\AppData\Local\Programs\Python\Python310\lib\site-packages\cherrypy\_cprequest.py", line 638, in respond
    self._do_respond(path_info)
  File "C:\Users\me\AppData\Local\Programs\Python\Python310\lib\site-packages\cherrypy\_cprequest.py", line 697, in _do_respond
    response.body = self.handler()
  File "C:\Users\me\AppData\Local\Programs\Python\Python310\lib\site-packages\cherrypy\lib\encoding.py", line 223, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "C:\Users\me\AppData\Local\Programs\Python\Python310\lib\site-packages\cherrypy\_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "O:\Apps\mylar3\mylar\webserve.py", line 1032, in searchit
    myDB.upsert("tmp_searches", vals, ctrlid)
  File "O:\Apps\mylar3\mylar\db.py", line 178, in upsert
    self.action(query, list(valueDict.values()) + list(keyDict.values()))
  File "O:\Apps\mylar3\mylar\db.py", line 130, in action
    sqlResult = self.connection.execute(query, args)
sqlite3.DatabaseError: database disk image is malformed

**Comment by evilhero** [comment]
Malformed db means it's corrupt or going corrupt. While it works now, eventually you won't be able to do anything using the db - so you should use a backup copy if you have one (ie. the docker one if you still have it that doesn't reside on the windows system).

Once you have a clean db you'll have to redo the locmove aspect ( the db has to then reside on the windows machine ).

**Comment by Rumik** [comment]
I started from scratch, mass importing some of my 193 comic series, and having to manually click import for the rest- Mylar just couldn't seem to cope with mass importing everything. Comics just never appeared unless I manually imported. Now I'm having issues adding new comics...

Uncaught exception: Traceback (most recent call last):
File "O:\Apps\mylar3\mylar\logger.py", line 337, in new_run
old_run(*args, **kwargs)
File "C:\Users\me\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
self._target(*self._args, **self._kwargs)
File "O:\Apps\mylar3\mylar\importer.py", line 69, in addvialist
addComictoDB(item['comicid'])
File "O:\Apps\mylar3\mylar\importer.py", line 281, in addComictoDB
comvalues = dothedew.folder_create()
File "O:\Apps\mylar3\mylar\filers.py", line 92, in folder_create
folder_format = re.sub('/', '\\', folder_format).strip()
File "C:\Users\me\AppData\Local\Programs\Python\Python310\lib\re.py", line 209, in sub
return _compile(pattern, flags).sub(repl, string, count)
File "C:\Users\me\AppData\Local\Programs\Python\Python310\lib\re.py", line 326, in _subx
template = _compile_repl(template, pattern)
File "C:\Users\me\AppData\Local\Programs\Python\Python310\lib\re.py", line 317, in _compile_repl
return sre_parse.parse_template(repl, pattern)
File "C:\Users\me\AppData\Local\Programs\Python\Python310\lib\sre_parse.py", line 972, in parse_template
s = Tokenizer(source)
File "C:\Users\me\AppData\Local\Programs\Python\Python310\lib\sre_parse.py", line 232, in __init__
self.__next()
File "C:\Users\me\AppData\Local\Programs\Python\Python310\lib\sre_parse.py", line 245, in __next
raise error("bad escape (end of pattern)",
re.error: bad escape (end of pattern) at position 0

**Comment by barbequesauce** [comment]
Ok - tracebacks rarely have the degree of information we need to troubleshoot issues. Can you please pull a carepackage (button on the top of the config page) and attach it here?

**Comment by evilhero** [comment]
That specific error is indicating that your directory format most likely has an incorrect slash (``/``) in it according to your OS. 

Like was mentioned way above, if you have slashes in a directory path that are the opposite of what is normal for that OS, they will be considered character breaks by python and cause errors. While mylar can display said breaks, using them in any calculation will cause that error.

**Comment by Rumik** [comment]
@evilhero I've completely started from scratch since then, because I couldn't fix those errors. I've re-scanned my collection and added everything again, often manually because the mass import didn't work. There's nothing left of my old database or config.

Here's my care package :) and thanks for the help!
[carepackage.zip](https://github.com/mylar3/mylar3/files/8350101/carepackage.zip)

**Comment by barbequesauce** [comment]
First thing I see is that folder format has slashes for linux - all other paths have backslashes (windows)... like EvilHero said, get all the toothpicks leaning the same way...

**Comment by barbequesauce** [comment]
I also see lots of sqlite3.OperationalError: disk I/O error and database disk image is malformed tracebacks in the logs... I expect either your database is mucked up or your harddisk needs repairs...

**Comment by Rumik** [comment]
The drive where my comics are stored is actually a mounted network drive (OneDrive), which could account for the I/O errors, given all read/write operations are happening over the network.

I'm not sure how to fix the slash issue if I can't directly edit the database. I don't understand why it's happening now anyway, with a brand new windows-based database.

**Comment by Rumik** [comment]
Oh I see where the issue might be!

**Comment by barbequesauce** [comment]
Likely the "bad escape" issues are related to that config entry - shut Mylar down and edit the config.ini.

The I/O & malformed DB messages are likely related to the locking OneDrive performs while replicating data - can you try moving it off a replicated drive, or halting replication? Just to rule that out of the equation.

**Comment by Rumik** [comment]
I'm not sure how to halt replication, but honestly now I've sorted the folders in Renaming Options, everything appears to be okay :) Appreciate the help!

**Comment by barbequesauce** [comment]
Note that the database is malformed - you are going to have problems down the road. I'd strong suggest moving the database out of the OneDrive folder...

**Comment by Rumik** [comment]
Alright, I’ll store the database locally. Thanks!
