### ISSUE TITLE
Experimental Search causes KeyError: 'hits'

### ISSUE THREAD

**Issue by kyle-cackett** [mylar3/mylar3#1114]
**Describe the bug**
Experimental Search causes the KeyError below. I do not hit this error for other providers.

```
19-Mar-2022 15:02:13 - DEBUG   :: mylar.NZB_SEARCH.1388 : SEARCH-QUEUE : setting lastrun for experimental to Sat Mar 19 15:02:13 2022
19-Mar-2022 15:02:13 - ERROR   :: mylar.searchforissue.2568 : SEARCH-QUEUE : Traceback (most recent call last):
  File "/app/mylar3/mylar/search.py", line 2496, in searchforissue
    foundNZB, prov = search_init(
  File "/app/mylar3/mylar/search.py", line 538, in search_init
    findit = search_the_matrix(scarios)
  File "/app/mylar3/mylar/search.py", line 4190, in search_the_matrix
    return NZB_SEARCH(
  File "/app/mylar3/mylar/search.py", line 1389, in NZB_SEARCH
    last_run_check(write={str(nzbprov): {'active': provider_stat['active'], 'lastrun': is_info['foundc']['lastrun'], 'type': provider_stat['type'], 'hits': provider_stat['hits']+1}})
KeyError: 'hits'

```

**CarePackage**
[carepackage.zip](https://github.com/mylar3/mylar3/files/8309501/carepackage.zip)

**Mylar.log**
[mylar.log](https://github.com/mylar3/mylar3/files/8309499/mylar.log)

**Environment (please complete the following information):**
 - OS: Docker (Linux)
 - Branch / commit: a032ee4ed23b51fa3791184f95ae78ea3adec5aa

**Comment by kyle-cackett** [comment]
The line which causes the KeyError was modified in commit
[a39db9e0e16f1d298f414eb3cb0e031022d430a3](https://github.com/mylar3/mylar3/pull/1065/commits/a39db9e0e16f1d298f414eb3cb0e031022d430a3#diff-aaa5deb9f5f62d74e8bde441ed87bb6e6b7f12222c87a476f97c1e8299c9c859)

**Comment by evilhero** [comment]
If the any of the above commits have not fixed your issue, as of the current python3-dev branch you can set the value for ``clear_provider_table = True`` in the config.ini, which will blank out the corrupted table so that it can generate a fresh table.

Note that if the ``clear_provider_table`` entry isn't present - starting mylar and then shutting it down will allow it to generate the entry to be edited.

**Comment by evilhero** [comment]
Gonna close this as assuming it's patched now given the length of time.

**Comment by kcpants** [comment]
Yes, this issue can be closed. I pulled the new commits when they were initially pushed and got experimental search working on my machine. Thank you for fixing it so quickly and sorry for not following up to confirm that the problem has been resolved!
