### ISSUE TITLE
Mylar no longer honours the configured listen port

### ISSUE THREAD

**Issue by Arathen** [mylar3/mylar3#1125]
Mylar starts up on port 8090 regardless of what is in the config.ini file. This has just started happening since the latest set of commits.

Log:
25-Mar-2022 09:51:16 - INFO :: mylar.main.384 : MAIN : Starting Mylar on forced port: 8090
25-Mar-2022 09:51:16 - INFO :: mylar.initialize.73 : MAIN : Starting Mylar on http://IP.REDACTED:8090/mylar/

INI:
[Interface]
http_port = 9995

I can confirm that config.ini is being read correctly because all other configuration from it is applied correctly.

Forcing Mylar to start on the desired port using the -p flag on start fixes the problem as a workaround.

Running source from git, python3-dev branch, Linux (Fedora).

Version
[01e32398b18eee44ffdfff670154fc0b1c75087b]

git
python3-dev

MYLAR PROGRAM OPTIONS
Python Version : 3.10.2
Language : en_AU.UTF-8

Mylar Data Directory : /opt/mylar/mylar
Mylar Program Directory : /opt/mylar/mylar
Mylar Cache Directory : /mnt/comics/Mylar/cache
Mylar Config File :/opt/mylar/mylar/config.ini

**Comment by barbequesauce** [comment]
Fix is up in dev...

**Comment by Arathen** [comment]
Looks good. Thanks for the quick fix.
