### ISSUE TITLE
v0.6.6 failing to start

### ISSUE THREAD

**Issue by Jmatt110** [mylar3/mylar3#1127]
New [v0.6.6](https://github.com/mylar3/mylar3/tree/v0.6.6) is failing to start (see attached pic). Py.exe console window opens and closes almost immediately.

Reverting back to [v0.6.5.2](https://github.com/mylar3/mylar3/tree/v0.6.5.2) works fine.

OS: Win10 19044.1586

mylar.log contents:
`26-Mar-2022 00:57:32 - INFO    :: mylar.configure.1142 : MainThread : Ignored Publishers: []
26-Mar-2022 00:57:32 - INFO    :: mylar.configure.1165 : MainThread : [MASS_PUBLISHERS] Auto-add for weekly publishers set to: []
26-Mar-2022 00:57:32 - INFO    :: mylar.configure.1177 : MainThread : [PROBLEM_DATES] Problem dates loaded: ['2021-07-14 04:00:34']
26-Mar-2022 00:57:32 - INFO    :: mylar.configure.1191 : MainThread : [COMICTAGGER] Version detected: 1.3.5
26-Mar-2022 00:57:32 - INFO    :: mylar.configure.1270 : MainThread : Setting DDL Location set to : C:\Server\Mylar3\cache
26-Mar-2022 00:57:32 - INFO    :: mylar.initialize.223 : MainThread : Checking to see if the database has all tables....
26-Mar-2022 00:57:32 - INFO    :: mylar.dbcheck.1577 : MainThread : Ensuring DB integrity - Removing all Erroneous Comics (ie. named None)
26-Mar-2022 00:57:32 - INFO    :: mylar.dbcheck.1587 : MainThread : Correcting Null entries that make the main page break on startup.
26-Mar-2022 00:57:32 - INFO    :: mylar.dbcheck.1598 : MainThread : [<class 'int'>]oldconfig_version: 12
26-Mar-2022 00:57:32 - ERROR   :: mylar.excepthook.315 : MainThread : Uncaught exception: Traceback (most recent call last):
  File "C:\Server\Mylar3\Mylar.py", line 465, in <module>
    main()
  File "C:\Server\Mylar3\Mylar.py", line 252, in main
    mylar.initialize(mylar.CONFIG_FILE)
  File "C:\Server\Mylar3\mylar\__init__.py", line 230, in initialize
    cc.provider_sequence()
  File "C:\Server\Mylar3\mylar\config.py", line 1640, in provider_sequence
    self.write_out_provider_searches()
  File "C:\Server\Mylar3\mylar\config.py", line 1704, in write_out_provider_searches
    writeout = myDB.upsert("provider_searches", t_vals, t_ctrl)
  File "C:\Server\Mylar3\mylar\db.py", line 178, in upsert
    self.action(query, list(valueDict.values()) + list(keyDict.values()))
  File "C:\Server\Mylar3\mylar\db.py", line 130, in action
    sqlResult = self.connection.execute(query, args)
sqlite3.IntegrityError: UNIQUE constraint failed: provider_searches.provider
`

![image](https://user-images.githubusercontent.com/7138425/160144671-526e4f60-cf9a-445e-8884-f07f03777511.png)

**Comment by evilhero** [comment]
If you start mylar via command line, add the ``maintenance - cp``switches (they have to be issued last in the startup command). 

Otherwise, open your config.ini and find the ``clear_provider_table``in the ``[General] `` section of the ini, and set it to ``True``. If it doesn't exist, either start Mylar and shut it down so it can create it, or just add it to the ini manually (``clear_provider_table = True``) and then start up Mylar.

When it starts in either situation, it will identify being in maintenance mode, remove the provider_searches table, flip the ini value to False if it was set and then restart Mylar using your normal settings.
