### ISSUE TITLE
ComicTagger failing since recent update

### ISSUE THREAD

**Issue by lodasi** [mylar3/mylar3#1131]
ComicTagger is no longer tagging issues since the most recent update. 

In Debug, the error message is "[META-TAGGER][WARNING] Make sure that you are using the comictagger included with Mylar."

 - OS: Windows 10
 - Branch / commit: master / 63da

**Additional information**
Add any other information about the problem here.
[carepackage.zip](https://github.com/mylar3/mylar3/files/8354126/carepackage.zip)

**Comment by evilhero** [comment]
You're missing one of the requirements from the requirements.txt file that was recently added to fix some CT issues.

The missing item you need to install is ``user_agent2`` - which can be done either by:
- ``py -m pip install user_agent2``
OR
- ``py -m pip install -r requirements.txt``

**Comment by lodasi** [comment]
That solved it! Thank you!

**Comment by DaveAlton** [comment]
Should this be done automatically for those using docker? Usually docker containers install and run with everything needed. This seems to require users to run a command on their container.

**Comment by DieselTech** [comment]
> Should this be done automatically for those using docker? Usually docker containers install and run with everything needed. This seems to require users to run a command on their container.

The docker container has all the requirements pre-installed that you need.

**Comment by DaveAlton** [comment]
Maybe I'm having a different error then. I'll create a separate issue so I don't clutter this pinned one.
