### ISSUE TITLE
Mylar is not processing SABnzbd download directory properly

### ISSUE THREAD

**Issue by wraith1385** [mylar3/mylar3#1132]
Mylar is not processing the download directory properly. I believe there is an issue in the sabnzbd.py file.  I have "/mnt/downloads" entered in the SABnzbd download directory textbox in the settings and this is the error I see in the logs:

[SAB-DIRECTORY ENABLED] No file found where it should be @ /mnt/downloads//mnt/downloads - sabnzbd passed this: K:\Downloads\Star.Wars.-.Darth.Vader.021.2022.Digital.Kileko-Empire.1\Star Wars - Darth Vader 021 (2022) (Digital) (Kileko-Empire).cbz

Care package attached
[carepackage.zip](https://github.com/mylar3/mylar3/files/8354391/carepackage.zip)

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Branch / commit:  d17a066ffffcfb2169a8c12c68ed4ca5244203cd (python3-dev)

**Comment by evilhero** [comment]
@wraith1385 should be resolved in latest python3-dev commit.

**Comment by wraith1385** [comment]
@evilhero thanks! That fixed it.
