### ISSUE TITLE
Recent error cannot search

### ISSUE THREAD

**Issue by CDarwin7** [mylar3/mylar3#1135]
I'm getting when I try and manually search or when I try to add a series from the weekly pull list.

500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/cherrypy/_cprequest.py", line 638, in respond
    self._do_respond(path_info)
  File "/usr/lib/python3.9/site-packages/cherrypy/_cprequest.py", line 697, in _do_respond
    response.body = self.handler()
  File "/usr/lib/python3.9/site-packages/cherrypy/lib/encoding.py", line 223, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/app/mylar3/mylar/webserve.py", line 995, in searchit
    for x in searchresults:
TypeError: 'bool' object is not iterable

Version

docker master
Python Version : 3.9.7
Language : en_US.UTF-8

Mylar Data Directory : /config/mylar
Mylar Program Directory : /app/mylar3
Mylar Cache Directory : /config/mylar/cache
[Mylar Config File :/config/mylar/config.ini](http://192.168.0.179:8090/mylar/config_dump)
Bragging Rights
# of Series you're watching: 203
# of Series you're watching that are continuing: 82
# of Issues you're watching: 2663
# of Issues you actually have: 2622
... total HD-space being used: 95.56 GB
[](javascript:void(0))Version: v0.6.4 ( master)

Status: CV , WS
Providers: DDL(GetComics):   Experimental:   nzb.su:   nzbplanet:

**Comment by DieselTech** [comment]
Your many versions behind. Make sure to update your install. Current main is at v0.6.6

**Comment by evilhero** [comment]
closing for staleness.
