### ISSUE TITLE
$Type doesn't seem to be working

### ISSUE THREAD

**Issue by pjones112000** [mylar3/mylar3#1146]
**Describe the bug**
I'm using the $Type formatting option for folder creation.  I add a new comic that is clearing TPB, etc... and the book type is ignored.
I'm using the format $Publisher/$Series $Type ($Year)....everything is working except the $Type.  

**Carepackage**
I'll add what I can if desired, but, I'm not finding anything in the log.

**Environment (please complete the following information):**
 - OS: Debian/10
 - Branch / commit: Python3-DEV / 79c81aa14acd25f83d758685296f4ca11082c71b

**Additional information**
I'm mainly trying to ensure that TPBs are not getting confused between series and TPBs that happen to be in the same year.

**Comment by evilhero** [comment]
You need to enable the config.ini option in order to use the $Type format (this will change so that there no ini option needed, just keep on forgetting to to do it) 

Set ``format_booktype = True`` and it will recognise the $Type string.

**Comment by pjones112000** [comment]
That did it...thank you.

**Comment by pjones112000** [comment]
Just keep it on your backlog. :D
