### ISSUE TITLE
Story Arc Folder Named Incorrectly (Wrong Years)

### ISSUE THREAD

**Issue by jakem742** [mylar3/mylar3#1148]
**Describe the bug**
The story arc "Fear Itself" (2011-2014) creates a folder titled "Fear Itself (0 - 2014)" instead of "Fear Itself (2011 - 2014)". The story arc in Mylar has the correct start and finish years, so something is happening with the folder naming? 

In Mylar, the path to the story arc folder includes the correct years in the UI ("Location: /data/media/comics/StoryArcs/Fear Itself (2011 - 2014)"). Symlinks have still been created for existing comics, so I assume it has mapped the location correctly internally.

**CarePackage**

**Environment (please complete the following information):**
 - OS: Linux
 - Branch / commit: docker/master [v0.6.5.2]

**Additional information**
Doesn't seem to have affected any of my other story arcs.

**Comment by barbequesauce** [comment]
The first episode on CV has No Date... it's a CV metadata issue.

.![image](https://user-images.githubusercontent.com/25070944/162180812-18e95e72-41a1-4407-bd72-6d556b169c7c.jpeg)

**Comment by jakem742** [comment]
Ahh, makes sense. 

Still seems a little strange that mylar correctly retrieved the story arc start/end years and then relied on the cv issue meta for creating the folder? Especially since mylar generated the correct location (including folder name) in the interface.

**Comment by barbequesauce** [comment]
It's all CV metadata - what you're seeing is inconsistency in that metadata. The arc object in the CV API has static data indicating the correct start & end dates based on store dates, then later has inconsistent release dates (showing this gap).
