### ISSUE TITLE
Comics no longer updating

### ISSUE THREAD

**Issue by thewindupboy** [mylar3/mylar3#1161]
**Describe the bug**
None of my series are updating with new issues, which means my wanted list isn't either.
(Its been a few weeks since I looked)
[carepackage.zip](https://github.com/mylar3/mylar3/files/8476323/carepackage.zip)

**CarePackage**
On the config page, there is a button labelled "CarePackage". Pressing this button will download a zip file containing a redacted copy of your config, your database, a summary of your operating environment, and your logs. Upload that file here.

If you're uncomfortable with pasting your CarePackage, include a DEBUG log containing the error from disk. 

Do not paste from the GUI log.
Do not just paste a traceback/error.

**Environment (please complete the following information):**
 - OS: [e.g. Windows10]
 - Branch / commit: [e.g. Dev/38aksi1]

**Additional information**
Add any other information about the problem here.

**Comment by evilhero** [comment]
Update. You're 4 months behind.

**Comment by DieselTech** [comment]
Along with updating your dev versions, your version of python is below the recommended version of 3.8.1 . Install at least that as a minimum. Once you install a new python make sure to reinstall the requirements.txt using pip as well.
