### ISSUE TITLE
Issue getting Mylar to show in browser 

### ISSUE THREAD

**Issue by ruinit** [mylar3/mylar3#1168]
**Describe the bug**
Installed using docker on Synology Nas I see in log it is running and so no obvious errors. I have correct local ip and port number but it fails to show up for some reason. I have other docker apps running and have tried changing port but still nothing

**CarePackage**
can't get it to load in browser

If you're uncomfortable with pasting your CarePackage, include a DEBUG log containing the error from disk. 

Do not paste from the GUI log.
Do not just paste a traceback/error.

**Environment (please complete the following information):**
 - OS: 
 - Synology Nas Intel processor
 - Branch / commit: [e.g. Dev/38aksi1]
master/latest 
**Additional information**
Not super familiar with docker so any help getting it started would be great thanks

**Comment by barbequesauce** [comment]
Where did you get the container image, Linuxserver or hotio?

**Comment by ruinit** [comment]
Linuxserver.io

**Comment by evilhero** [comment]
Make sure that the mylar host is set to 0.0.0.0 if you're trying to access mylar from a different machine. You'll have to manually edit the config.ini of mylar and set the ``http_host = 0.0.0.0`` and the ``http_port = 8090``

Otherwise without a log it's almost impossible for us to help you. Check the wiki for instructions on how to enable debug logging and then start up mylar, wait a few seconds and then kill it and grab the log (from the logs directory).  You'll have to paste the log in here as opposed to generating a care package (since that's GUI based).

**Comment by ruinit** [comment]
Thanks here is what it shows in terminal I don't get it 

17-Apr-2022 17:23:13 - INFO :: mylar.initialize.73 : MAIN : Starting Mylar on http://0.0.0.0:8090/                                    
17-Apr-2022 17:23:14 - INFO :: mylar.getVersion.183 : MAIN : [DOCKER-AWARE] Docker installation detected.                             
17-Apr-2022 17:23:14 - INFO :: mylar.getVersion.201 : MAIN : i:  (HEAD -> master, tag: v0.6.7)                                        
                                                                                                                                      
17-Apr-2022 17:23:14 - INFO :: mylar.getVersion.212 : MAIN : [LAST_RELEASE] Branch: master                                            
17-Apr-2022 17:23:14 - INFO :: mylar.getVersion.217 : MAIN : [LAST_RELEASE] Version: v0.6.7                                           
17-Apr-2022 17:23:14 - INFO :: mylar.getVersion.201 : MAIN : i: e33600a30f27d747c60dcdae41ddeab38fa2fa92
17-Apr-2022 17:23:14 - INFO :: mylar.start.609 : MAIN : Background Schedulers successfully started...

**Comment by Dracon23** [comment]
Following a hunch, how do you start the container?

**Comment by ruinit** [comment]
> Following a hunch, how do you start the container?

Docker app on NAS I use layzlibrarian and a few others on docker

**Comment by Dracon23** [comment]
Are you exposing the port?

**Comment by ruinit** [comment]
nas does work that way locally only from outside the network which I am not. All other docker apps on different ports work just having trouble with this for some reason

**Comment by ruinit** [comment]
On another note just tried same package on docker for windows desktop and webpage will not load on that either although log shows the Mylar is running idk

**Comment by Dracon23** [comment]
That does not answer my question. You do need to expose the port to the network. Otherwise you will only be able to talk to Mylar from your NAS.

**Comment by evilhero** [comment]
You pasted the above log snippet, but it wasn't debug - set the ``log_level =2`` in the config.ini as per the wiki.

And then restart Mylar. Does the console stop scrolling after the Background Schedulers line? Or does it continue... cause it should be throwing out tonnes of lines thereafter if it was working as intended.

**Comment by Dracon23** [comment]
> On another note just tried same package on docker for windows desktop and webpage will not load on that either although log shows the Mylar is running idk

How are you starting it there?

**Comment by ruinit** [comment]
> > On another note just tried same package on docker for windows desktop and webpage will not load on that either although log shows the Mylar is running idk
> 
> How are you starting it there?

Docker for windows desktop app runs it I turned the firewall off to alleviate any problems there before I asked for help

**Comment by Dracon23** [comment]
Can you please go to the settings for your Myles container and check in Advanced Settings -> Port Settings if there is a port mapped to Container Port 8090? Just to rule that out.

**Comment by ruinit** [comment]
> You pasted the above log snippet, but it wasn't debug - set the `log_level =2` in the config.ini as per the wiki.
> 
> And then restart Mylar. Does the console stop scrolling after the Background Schedulers line? Or does it continue... cause it should be throwing out tonnes of lines thereafter if it was working as intended.

I am trying to figure out how to edit ini for the log now in a docker container.

**Comment by ruinit** [comment]
> Can you please go to the settings for your Myles container and check in Advanced Settings -> Port Settings if there is a port mapped to Container Port 8090? Just to rule that out.

Ok this was the problem it seems when installing the package it even though I set the port to 8090 and it shows 8090 in log it assigned a different local port of 41960 for whatever reason so now it is changed to 8090 and mylar can be found on the network thanks for the help!! I had been banging my head

**Comment by ruinit** [comment]
resolved ty
