### ISSUE TITLE
Manual PP Not Processing All Files

### ISSUE THREAD

**Issue by jakem742** [mylar3/mylar3#1177]
**Describe the bug**
Pressing the "Automated Manual Run!" button processes some, but not all files. Pressing the "Automated Manual Run!" button a second time PP's a few more. This continues on indefinitely until all files are PP'ed.

**CarePackage**
[CarePackage](https://drive.google.com/file/d/1t9Lz_Vxe4Rih8owTwZiFI-T7PrfZDV9g/view?usp=sharing)

**Environment (please complete the following information):**
 - OS: [Linux (Docker)]
 - Branch / commit: [master/v0.6.7]

**Additional information**
I am attempting to manually import files for the "Fear Itself" story arc without watching all the series in Mylar. I have bulk-downloaded the files and put them in a local folder which the Manual PP task is directed to.

**Comment by barbequesauce** [comment]
```22-Apr-2022 23:39:12 - WARNING :: mylar.file_ops.4569 : Thread-59 : [[Errno 2] No such file or directory: '/data/media/comics/StoryArcs/Fear Itself (2011 - 2014)/118-The Mighty Thor 007 (2011).cbz'] Unable to create symlink. Dropping down to copy mode so that this operation can continue.
22-Apr-2022 23:39:12 - ERROR   :: mylar.file_ops.4574 : Thread-59 : [COPY] error : [Errno 2] No such file or directory: '/data/media/comics/StoryArcs/Fear Itself (2011 - 2014)/118-The Mighty Thor 007 (2011).cbz'
22-Apr-2022 23:39:12 - ERROR   :: mylar.Process.1897 : Thread-59 : [POST-PROCESSING] [ONE-OFF MODE] Failed to softlink /config/mylar/cache/mylar_wzngemxa/Mighty Thor 007 (2011) (Both Covers) (Minutemen-Fiji).cbz: 
2```

That Errno 2 is an OS level error, means "No such file or directory"

**Comment by jakem742** [comment]
I discovered that the file exists as part of a series, but the path to the series folder was incorrect and the Story Arc symlink was broken. I guess Mylar didn't know what to do with importing the duplicate when it came across the broken symlink in the story arc. 

It seems like it was trying to add the new imported file to the Story Arc without checking if it was part of an existing series with a local file first?

I also noticed that Mylar doesn't seem to be correcting sym-links whenever a series folder is renamed (just did a bulk change on my folder structure), breaking any existing symlinks with no obvious solution short of manually deleting the broken symlinks and getting Mylar to re-create them.

**Comment by jakem742** [comment]
On a related note, I have actually just noticed that manual post-processing files that are in an existing watched series will move the files to the series but not tag or convert in any way (the files are still cbr, despite PP config settings). 

This is a bit painful as I've just imported a bunch of story arc files that have been sent to various series all over the place and retained their cbr extension.

**Comment by evilhero** [comment]
Mylar doesn't track symlinks, and probably won't start doing it. If you're switching/renaming directories around then it's kinda up to you to know what you're affecting with the changes. Mylar can't be expected to know right from wrong in regards to symlinks or create new ones vs outdated, as that's a huge undertaking and will differ btwn OS' greatly (junctions, hardlink, symlinks, etc) 

The only solution in all of this is to just avoid using symlinks for arcs and let mylar store them in the arcs folder thereby not having to worry about manual renames taking place. If you're insisting on using symlinks, manually refreshing the arc after you've changed the series folders may be the only solution, and even that probably won't do what you're after I believe.

**Comment by jakem742** [comment]
Not keeping track of symlinks is fair enough, but it would be suuuuper handy. As it stands, I have to go through and manually delete them and then refresh in Mylar for the symlinks to get re-created. 

I don't really know what's involved, but would it be difficult to add a check for broken symlinks when pressing "Re-check files" and try to recreate them if so? Or is your hesitance on this more over concerns with Mylar affecting setups with sym-links created from external sources?

eg.
1. Press "Re-check files"
2. Mylar checks if sym-links are valid
     a) If valid - skip
     b) If invalid - Delete sym-link
3. Mylar runs check of existing series for file matches (this functionality is already in place?) 

[Python command for finding broken symlinks](https://stackoverflow.com/questions/20794/find-broken-symlinks-with-python)

**Comment by jakem742** [comment]
So I guess the conclusion to this is that a broken symlink was breaking the imports. I'm guessing Mylar was trying to drop the file into the arc and having issues with the existing symlink? Instead of simply checking the series for an existing file and dropping the import for that file once it discovered an existing file.
