### ISSUE TITLE
PP of Story Arc issues to include meta-tagging

### ISSUE THREAD

**Issue by jakem742** [mylar3/mylar3#1178]
**Describe the request**
When PP'ing story arc issues that are not part of a watched series, they are left untouched by the post-processor (eg. cbr files are not converted to cbz and tagged). It would be helpful if the tagger runs on these files, even if they are unwatched.

Additionally, a button under each Story Arc to manually tag issues in an arc, so I can easily go back and fix existing cbr files in all my arcs. :)

**How did you come up with the idea?**
My manually PP'ed files are still in cbr format! :(

**Comment by evilhero** [comment]
Mylar will post-process story arc issues that are outside of your watchlist just fine - as long as they're part of an arc being watched and they're sanely named.

Pretty sure this is a user config problem at this point.

Post a carepackage or we can just close this.

**Comment by jakem742** [comment]
Can be closed. Realised my settings changed for some reason and tagging was off. :(
