### ISSUE TITLE
Accidentally rm -rf in ~ folder and deleted everything, re-install not post-processing sab downloads or producting a care package

### ISSUE THREAD

**Issue by Lusiphur** [mylar3/mylar3#1196]
**Describe the bug**
I idiotically typed rm -rf * in my home folder so I had to re-install mylar3.
It will snatch nzb's from my providers fine but it will not post process once Sab is done. The check for Sab integration works.
Logs show 'Key Error : 'nzbid'

**CarePackage**
This doesn't work either, gives KeyError: 'install_type'.

From logs ..
03-May-2022 13:30:30 - DEBUG   :: mylar.runGit.61 : CP Server Thread-2 : Git output: CompletedProcess(args='git log --encoding=UTF-8 --pretty=format:"%h - %cr - %an - %s" -n 5', returncode=0, stdout='835e7757 - 18 hours ago - evilhero - F
IX: duplication of downloads in history table (going forward), IMP: Provider column added to history table and bettter column lengths\n0243f1b2 - 18 hours ago - evilhero - FIX: pip req check would fail on docker installs with not display,
 FIX: installation type included in carepackage\ndc972e9b - 4 days ago - evilhero - FIX:(#1181) CDH hard-coded category mapping\n73808fe3 - 11 days ago - evilhero - FIX: docker startup issues with requirements detection\nfb392902 - 12 day
s ago - evilhero - FIX: forgot the .release_messages check', stderr='')
03-May-2022 13:30:48 - INFO    :: mylar.fly_me_to_the_moon.2988 : CP Server Thread-5 : weeknumber: 18
03-May-2022 13:30:48 - INFO    :: mylar.fly_me_to_the_moon.3091 : CP Server Thread-5 : mismatched: []
03-May-2022 13:30:56 - INFO    :: mylar.retryissue.2211 : Thread-12 : Located snatched download:
03-May-2022 13:30:56 - INFO    :: mylar.retryissue.2212 : Thread-12 : --Referencing : NZBPlanet (newznab) @ 2022-05-02 09:31:11
03-May-2022 13:30:56 - INFO    :: mylar.retryissue.2211 : Thread-12 : Located snatched download:
03-May-2022 13:30:56 - INFO    :: mylar.retryissue.2212 : Thread-12 : --Referencing : NZBPlanet @ 2022-05-02 09:31:11
03-May-2022 13:30:56 - INFO    :: mylar.retryissue.2390 : Thread-12 : fetched via newnzab. Retrying the send.
03-May-2022 13:30:56 - INFO    :: mylar.retryissue.2404 : Thread-12 : newznab detected as : NZBPlanet @ http://api.nzbplanet.net/
03-May-2022 13:30:56 - INFO    :: mylar.retryissue.2405 : Thread-12 : link : http://api.nzbplanet.net//api?apikey=
03-May-2022 13:30:56 - ERROR   :: mylar.excepthook.315 : Thread-12 : Uncaught exception: Traceback (most recent call last):
  File "/home/lusiphur/mylar3/mylar/logger.py", line 337, in new_run
    old_run(*args, **kwargs)
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/lusiphur/mylar3/mylar/webserve.py", line 2418, in retryissue
    sendit = search.searcher(fullprov, nzbname, comicinfo, link=link, IssueID=IssueID, ComicID=ComicID, tmpprov=fullprov, directsend=True, newznab=newznabinfo)
  File "/home/lusiphur/mylar3/mylar/search.py", line 2875, in searcher
    nzbid = comicinfo[0]['nzbid']
KeyError: 'nzbid'

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Branch / commit: python3-dev/835e77572002c2123a708d4fb5a195ed3992ad69

**Additional information**
Add any other information about the problem here.

**Comment by DieselTech** [comment]
Without the carepackage a lot of info used to troubleshoot is missing.

What is your python version?
Did you install the requirements.txt from pip?

**Comment by Lusiphur** [comment]
Major fail on the api key. It's been redacted and changed.
Just setting the files back to wanted got them post processed etc so it is likely the same issue with retry.
Thanks.
