### ISSUE TITLE
Version # is missing so when checking for new version getting: "Updater will only work with the mylar3 repo branches"

### ISSUE THREAD

**Issue by cyberweasel** [mylar3/mylar3#1197]
Had been running for a while with no issues.  
Haven't run update check in a while.  
did some searching and ran git commands from other updating issues posts.
git pull reports "Already up to date."

thoughts?  Thanks.

**Comment by evilhero** [comment]
Please post a carepackage along with the other required information. There's too much info lacking.

**Comment by cyberweasel** [comment]
[carepackage.zip](https://github.com/mylar3/mylar3/files/8611641/carepackage.zip)

**Comment by evilhero** [comment]
```Encountered error: fatal: unsafe repository ('/opt/mylar3' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory /opt/mylar3

03-May-2022 09:45:24 - ERROR   :: mylar.runGit.73 : MAIN : Error: fatal: unsafe repository ('/opt/mylar3' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory /opt/mylar3```

Says exactly what you need to do.

**Comment by evilhero** [comment]
It can't check the directory cause it doesn't have access. 

It's not a mylar aspect at this point, but something with your install that's restricting the git check to run properly. 

Make sure that the user running mylar is the owner (don't do group, do owner) of the mylar directory (make sure to chown recursively) and that it has full access to given directory. There's not really much else we can do at this point, as it has to do with how you installed mylar.

**Comment by cyberweasel** [comment]
ok thanks.  I'll dig deeper.
