### ISSUE TITLE
System Stopped Searching

### ISSUE THREAD

**Issue by wraith1385** [mylar3/mylar3#1214]
My Mylar has decided to just stop searching for new issues.  I have several indexers configured and synced through prowlarr, however I also tried just adding the indexers regularly and the problem still exists.  

Care Package Attached

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Branch / commit: Python3dev - ea41bf30a35e8852b4bccf69d925a97025351d88

[carepackage_ea41bf30a35e8852b4bccf69d925a97025351d88_(python3-dev).zip](https://github.com/mylar3/mylar3/files/8712479/carepackage_ea41bf30a35e8852b4bccf69d925a97025351d88_.python3-dev.zip)

**Comment by DieselTech** [comment]
You don't have all the required dependancies to run mylar 


18-May-2022 00:55:32 - DEBUG   :: mylar.check_the_pip.115 : MAIN : [user_agent2] REQUIRED: 2021.12.11 ---> INSTALLED: FAIL 

18-May-2022 00:55:32 - DEBUG   :: mylar.check_the_pip.104 : MAIN : [simplejson] REQUIRED: 3.17.0 ---> INSTALLED: 3.16.0 [FAIL]
18-May-2022 00:55:32 - DEBUG   :: mylar.check_the_pip.104 : MAIN : [cheroot] REQUIRED: 8.2.1 ---> INSTALLED: 8.6.0 [FAIL]

You need to re-run the `pip3 install -r requirements.txt` command

**Comment by wraith1385** [comment]
Yep, sorry it looks like I had something installed through apt that was causing the pip command to fail to actually install.  Got it fixed and things are working again.  Thanks!
