### ISSUE TITLE
Handle ".black" and ".white" issues of "We Live"

### ISSUE THREAD

**Issue by chelming** [mylar3/mylar3#1254]
**Describe the request**
[We Live (2022)](https://comicvine.gamespot.com/we-live/4050-141860/) has a "Black" and "White" 001 issue and they don't get discovered properly.

**How did you come up with the idea?**
Mostly a stroke of genius but some help from Offspring and scooterpsu.

**Environment (please complete the following information):**
 - OS: Docker / LSIO
 - Branch / commit: Latest

**Additional information**
scooter theorizes that this line needs to be updated for black and white but I'm obviously going to defer to you 😄 
https://github.com/mylar3/mylar3/blob/python3-dev/mylar/__init__.py#L175

**Comment by evilhero** [comment]
Closed as completed
