### ISSUE TITLE
This Week page wont load.

### ISSUE THREAD

**Issue by Dethkiller15** [mylar3/mylar3#1257]
**Describe the bug**
I click on "This Week" in the nav bar and I get this message instead of the page that is supposed to load.
```
500 Internal Server Error
The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/cherrypy/_cprequest.py", line 638, in respond
    self._do_respond(path_info)
  File "/usr/lib/python3.9/site-packages/cherrypy/_cprequest.py", line 697, in _do_respond
    response.body = self.handler()
  File "/usr/lib/python3.9/site-packages/cherrypy/lib/encoding.py", line 223, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/app/mylar3/mylar/webserve.py", line 2756, in pullist
    repoll = self.pullrecreate(weeknumber=weekinfo['weeknumber'],year=weekinfo['year'])
  File "/app/mylar3/mylar/webserve.py", line 2979, in pullrecreate
    statchk = weeklypull.pullit(forcecheck, weeknumber, year)
  File "/app/mylar3/mylar/weeklypull.py", line 115, in pullit
    new_pullcheck(chk_locg['weeknumber'],chk_locg['year'])
  File "/app/mylar3/mylar/weeklypull.py", line 934, in new_pullcheck
    if 'Present' in watch['ComicPublished'] or (helpers.now()[:4] in watch['ComicPublished']) or watch['ForceContinuing'] == 1 or len(listit) >0:
TypeError: argument of type 'NoneType' is not iterable
```

**CarePackage**
On the config page, there is a button labelled "CarePackage". Pressing this button will download a zip file containing a redacted copy of your config, your database, a summary of your operating environment, and your logs. Upload that file here.
[carepackage_v0.6.8.zip](https://github.com/mylar3/mylar3/files/9185609/carepackage_v0.6.8.zip)
My mylar.db file is to large so I removed it.

If you're uncomfortable with pasting your CarePackage, include a DEBUG log containing the error from disk. 

Do not paste from the GUI log.
Do not just paste a traceback/error.

**Environment (please complete the following information):**
 - OS: Synology OS
 - Branch / commit: latest

**Additional information**
Add any other information about the problem here.

**Comment by barbequesauce** [comment]
Couple of things -

- First the logs are not verbose - that's kinda important to make heads or tails of what's breaking 
- Second - I see a lot of "recreate pull lists" towards the end, but not a lot of other "normal" activity. What jobs do you have paused?
- Third - I see kanji in an alt field for One Punch Man. Mylar occasionally struggles with extended character sets; just for giggles can you remove that and see if it recurs after?

**Comment by evilhero** [comment]
An item in your watchlist has an ``Unknown`` value for Publication Run or Status most likely. 

Basically, one or more of the series in your watchlist wasn't able to update properly. Whether that's due to CV having problems, Mylar being unable to interpret the data, or some localised problem you were having - it's hard to tell.

Try sorting by column on either of the above fields on the main index page and see if you can isolate the series (it will have ``Unknown`` most likely in one of the columns). If you find one (or multiples), you'll need to go into the series detail page for those specific series and use the Refresh Series button to try and fix things.

**Comment by Dethkiller15** [comment]
> Couple of things -
> 
> * First the logs are not verbose - that's kinda important to make heads or tails of what's breaking
> * Second - I see a lot of "recreate pull lists" towards the end, but not a lot of other "normal" activity. What jobs do you have paused?
> * Third - I see kanji in an alt field for One Punch Man. Mylar occasionally struggles with extended character sets; just for giggles can you remove that and see if it recurs after?

No idea on how to make logs verbose
nothing but version check
I wasnt having luck with getting one punch man anyways so I removed it and nada





> An item in your watchlist has an `Unknown` value for Publication Run or Status most likely.
> 
> Basically, one or more of the series in your watchlist wasn't able to update properly. Whether that's due to CV having problems, Mylar being unable to interpret the data, or some localised problem you were having - it's hard to tell.
> 
> Try sorting by column on either of the above fields on the main index page and see if you can isolate the series (it will have `Unknown` most likely in one of the columns). If you find one (or multiples), you'll need to go into the series detail page for those specific series and use the Refresh Series button to try and fix things.

I went to /manageComics typed in unknown in the search for the page itself and saw a few. Forced them to recheck and vuala, "This Week" page loaded instead of that error.

Thanks for the help.

**Comment by DieselTech** [comment]
Just out of curiosity, how large is your DB that you couldn't upload it?

**Comment by Dethkiller15** [comment]
> Just out of curiosity, how large is your DB that you couldn't upload it?

102mb
