### ISSUE TITLE
ModuleNotFoundError: No Module named 'libs.utorrent'

### ISSUE THREAD

**Issue by SylentNight37** [mylar3/mylar3#1267]
I am running Python 3.10.6 and am running into an issue when trying to start Mylar3.

I've ran the command to install the requirements.txt, and the files seem to be present. However, utorrent.py seems to be having an issue importing libs.utorrent.

I've tried in a virtual environment and out of one, and the result is the same.

Traceback (most recent call last):
  File "C:\mylar3\mylar.py", line 27, in <module>
    import mylar
  File "C:\mylar3\mylar\__init__.py", line 43, in <module>
    from mylar import logger, versioncheckit, rsscheckit, searchit, weeklypullit, PostProcessor, updater, helpers
  File "C:\mylar3\mylar\logger.py", line 24, in <module>
    from mylar import helpers
  File "C:\mylar3\mylar\helpers.py", line 43, in <module>
    from mylar import db, sabnzbd, nzbget, process, getcomics, getimage
  File "C:\mylar3\mylar\getcomics.py", line 33, in <module>
    from mylar import db, logger, helpers, search_filer
  File "C:\mylar3\mylar\search_filer.py", line 24, in <module>
    from mylar import logger, filechecker, helpers, search
  File "C:\mylar3\mylar\search.py", line 18, in <module>
    from mylar import (
  File "C:\mylar3\mylar\rsscheck.py", line 32, in <module>
    from mylar import db, logger, ftpsshup, helpers, auth32p, utorrent, helpers, filechecker
  File "C:\mylar3\mylar\utorrent.py", line 3, in <module>
    from libs.utorrent.client import UTorrentClient
ModuleNotFoundError: No module named 'libs.utorrent'

**Comment by evilhero** [comment]
Looks like python 3.10.6 depreciated something in regards to importing libraries (or a previous 3.10.x version did). 

Altho it should still be able to load from the correct path on failure, we'll have to adjust for this. A fix will be im the python3-dev branch in a few hrs. 

As an aside, 3.10.6 is bleeding edge  (it came out 1 day ago), and generally it's not great to be running python versions so new as they'll be filled with bugs / problems, along with undocumented problems usually.  Usually, unless it's a security type of fix, 2-3 sub-versions lower is generally better practice (ie. 3.10.3 - 3.10.5. For reference, mylar is coded against Python 3.9.4.)

**Comment by SylentNight37** [comment]
Ah, good point. I didn't check the release date before I installed Python. I tried downgrading to 3.9.4, but venv is now having problems insisting on creating the venv to point to the python310 directory. I ended up just upgrading to 3.10.5 and I'll patiently wait for your next release. 😄

**Comment by SylentNight37** [comment]
I see that you already release it in the dev branch. Man, that was quick! I updated my local files and it's working fine now.
