### ISSUE TITLE
Error When Trying to Add Comic

### ISSUE THREAD

**Issue by SylentNight37** [mylar3/mylar3#1269]
I'm trying to add a new comic, and it seems to have an issue. I started with a classic, Witchblade, and when trying to add comic, I get the following error. This is running the latest version of the dev environment use Python 10.5

At first, I thought it might be because I was using a network path. I then tried mounting the network drive, then tried using a local directory. Each time it produced the following error:

Traceback (most recent call last):
  File "c:\mylar3\mylar\logger.py", line 337, in new_run
    old_run(*args, **kwargs)
  File "C:\Users\((REDACTED))\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "c:\mylar3\mylar\updater.py", line 53, in addvialist
    dbUpdate([item['comicid']], calledfrom='refresh')
  File "c:\mylar3\mylar\updater.py", line 446, in dbUpdate
    chkstatus = mylar.importer.addComictoDB(ComicID, mismatch, annload=annload, csyear=csyear)
  File "c:\mylar3\mylar\importer.py", line 281, in addComictoDB
    comvalues = dothedew.folder_create()
  File "c:\mylar3\mylar\filers.py", line 270, in folder_create
    ddir = pathlib.PurePath(ppath)
  File "C:\Users\((REDACTED))\AppData\Local\Programs\Python\Python310\lib\pathlib.py", line 562, in __new__
    return cls._from_parts(args)
  File "C:\Users\((REDACTED))\AppData\Local\Programs\Python\Python310\lib\pathlib.py", line 594, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "C:\Users\((REDACTED))\AppData\Local\Programs\Python\Python310\lib\pathlib.py", line 578, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

![Comic Add Error](https://user-images.githubusercontent.com/11765187/182712189-fb1fa77f-7ab6-4aca-afd3-ab687fe7e0d5.png)

**Comment by evilhero** [comment]
What value do you currently have for your Comic Location path (Configuration / Web Interface tab) ?

Have you been able to add any series to the watchlist thus far ? That error would seem to indicate nothing has been able to be added thus far.

**Comment by SylentNight37** [comment]
Ok, I think I found the issue. I need to RTFM. I hadn't set the comic location, which is what caused the problem.

That being said, I finished setting up the environment and set my download provider and search provider. Both of those test ok, but when I try to search for a missing file, it can't find the comic. When I do a manual search, I am able to find one that matches the year and name of the comic. This same behavior was observed with two different comics with the same results.

04-Aug-2022 15:23:09 - INFO :: mylar.NZB_SEARCH.1124 : SEARCH-QUEUE : bb: {'entries': []}
04-Aug-2022 15:23:09 - INFO :: mylar.search_init.587 : SEARCH-QUEUE : Could not find Issue 2 of Ultimate Spider-Man (2000) using NZBGeek [rss]
04-Aug-2022 15:23:09 - INFO :: mylar.search_init.598 : SEARCH-QUEUE : attempting to set NZBGeek to not being the active provider.
04-Aug-2022 15:23:09 - INFO :: mylar.search_init.600 : SEARCH-QUEUE : setting last run to: 1659640984.0988138
04-Aug-2022 15:23:09 - INFO :: mylar.search_init.604 : SEARCH-QUEUE : setting took. Current provider is: {'NZBGeek': {'type': 'newznab', 'lastrun': 1659640984.0988138, 'active': False, 'hits': 0, 'id': 2}}
04-Aug-2022 15:23:09 - INFO :: mylar.search_init.326 : SEARCH-QUEUE : cmloopit: 3
04-Aug-2022 15:23:09 - INFO :: mylar.search_init.351 : SEARCH-QUEUE : checked_once: []
04-Aug-2022 15:23:09 - INFO :: mylar.search_init.364 : SEARCH-QUEUE : prov_order[prov_count]: newznab: NZBGeek
04-Aug-2022 15:23:09 - INFO :: mylar.search_init.466 : SEARCH-QUEUE : current_prov: {'NZBGeek': {'type': 'newznab', 'lastrun': 1659640984.0988138, 'active': True, 'hits': 0, 'id': 2}}
04-Aug-2022 15:23:09 - INFO :: mylar.search_init.531 : SEARCH-QUEUE : API searchmode enabled for Ultimate Spider-Man
04-Aug-2022 15:23:09 - INFO :: mylar.gen_altnames.4287 : SEARCH-QUEUE : AlternateSearch: None
04-Aug-2022 15:23:09 - INFO :: mylar.gen_altnames.4326 : SEARCH-QUEUE : searchlist: [{'ComicName': 'Ultimate Spider-Man', 'unaltered_ComicName': 'Ultimate Spider-Man'}]
04-Aug-2022 15:23:09 - INFO :: mylar.search_init.534 : SEARCH-QUEUE : comicname searched for: Ultimate Spider-Man
04-Aug-2022 15:23:09 - INFO :: mylar.NZB_SEARCH.882 : SEARCH-QUEUE : Shhh be very quiet...I'm looking for Ultimate Spider-Man issue: 2 (2000) using NZBGeek (newznab).
04-Aug-2022 15:23:09 - WARNING :: mylar.NZB_SEARCH.1251 : SEARCH-QUEUE : [PROVIDER-SEARCH-DELAY][NZBGeek] Waiting 55 seconds before we search again...

**Comment by DieselTech** [comment]
Would need to see the full debug logs to determine matching problems. It will specifically say why it didn't match.

**Comment by SylentNight37** [comment]
Understood. I've attached the care package for the system
[carepackage_b5b198149bdca86e39d5d9d3c62b58a3b235476e_(python3-dev) (1).zip](https://github.com/mylar3/mylar3/files/9262821/carepackage_b5b198149bdca86e39d5d9d3c62b58a3b235476e_.python3-dev.1.zip)
.

**Comment by evilhero** [comment]
Multiple things probably need to be addressed based off the carepackage:

- your usenet retention is only set to 1500 days by default (which is 4.5yrs roughly) and you're searching for an issue probably posted previous to that. So increase the retention to 3500-4000 maybe (not sure how far back geek goes with retention).
- enable Post-processing. Without this enabled nothing will get moved after it's downloaded.
- enable Completed Download Handling (CDH) for Sabnzbd. This will monitor your sabnzbd client for any downloads that mylar has sent to the client and then post-processes them thereafter (with the option for post-processing enabled).
- set your logs to debug level for future reference. It helps is to help you, provides more info and saves you having to recreate logs for us if you have problems after the fact.  You can set this in the config.ini by setting ``log_level = 2``, or by starting mylar with the -v switch on the command line.

**Comment by SylentNight37** [comment]
Perfect! With your suggestions, I was able to get this working. Thank you very much for your help! You've made an excellent program.

Just for my understanding, is there a way to set the retention on a search provider outside of the config.ini file?

**Comment by evilhero** [comment]
You can set it on the configuration page, in the same tab as your Sabnzbd settings. It's located near the bottom called ``Usenet Retention``. It is a global option tho, so you can't set it per provider - but it only affects nzb providers.

**Comment by SylentNight37** [comment]
Ah, got it. I didn't think to look at the download settings page. Thanks for letting me know!
