### ISSUE TITLE
Alpha and Omega issues

### ISSUE THREAD

**Issue by StevieCoops** [mylar3/mylar3#1277]
There is an issue renaming series where the issues aren't numbers. This series (God Is Dead: The Book of Acts) has two issues where the issue number is Alpha and Omega. I've attached a log

 - OS: Windows 11
 - Branch / commit: [e.g. Dev/38aksi1]

[awdawd.txt](https://github.com/mylar3/mylar3/files/9384458/awdawd.txt)

**Comment by evilhero** [comment]
Please submit a carepackage. 

You have not provided the branch / commit you are running, nor what you were doing in order to get to the rename process. 

A carepackage will provide said information, which is why we ask for it.

**Comment by StevieCoops** [comment]
[carepackage_3ec12af475ee1f4bbec74eec2b36fd612cc16c7f_(python3-dev).zip](https://github.com/mylar3/mylar3/files/9384580/carepackage_3ec12af475ee1f4bbec74eec2b36fd612cc16c7f_.python3-dev.zip)
