### ISSUE TITLE
Mylar + Authentik + NPM reverse proxy troubleshooting (Longshot!) 

### ISSUE THREAD

**Issue by ConnorEMacLean** [mylar3/mylar3#1283]
**Describe the bug**
Attempting to use to [Authentik](https://www.youtube.com/watch?v=CPURnYaW3Zk) to have authentication for Mylar behind my NPM reverse proxy. Using the same Advanced setting within NPM I have been able to configure other similar localhosted programs but Mylar continue to run into a 500 error once the Authentik Advanced reverse proxy information is fille.

**CarePackage**
Not on my machine currently but will provide logs/any code block ASAP!

**Environment (please complete the following information):**
Running on Unraid within a Docker container. Using the hotio container.

**Additional information**
While this isn't a Mylar issue as everything is working great on that side was hoping to see if there was any information in regards to proper proxy_set headers etc. I've been picking this recently so fairly new to this all so might be missing something very obvious. Thanks in advanced!

**Comment by ConnorEMacLean** [comment]
Did a bit more digging and saw https://github.com/evilhero/mylar/issues/1644 from original Mylar, added the proxy paths barbequesauce in the thread mention and everything is working as expected. Sorry for the notifications caused by this!

**Comment by barbequesauce** [comment]
Glad I wrote that up five years ago lol
