### ISSUE TITLE
Feature request - Change Location of StoryArc folder.

### ISSUE THREAD

**Issue by jmurra21** [mylar3/mylar3#1285]
**Describe the request**
I'd like to be able to change the location of the StoryArc folder to be on the same root level as the main comics folder

**How did you come up with the idea?**
Semi-Need. Read a bunch of arcs with friends and it is hell digging through 178 Publisher Folders. It would make it a lot easier to find and enjoy just certain story arcs.

**Environment (please complete the following information):**
 - OS: Windows 10
 - Branch / commit: [52f95ca2ba08f3bf9f2e3b7c3ab9ad255b86ea78]

**Additional information**
All other requirements are met on my server.

**Comment by evilhero** [comment]
Closed as completed and merged into master.
