### ISSUE TITLE
Omega issues not being detected

### ISSUE THREAD

**Issue by war3zlod3r** [mylar3/mylar3#1288]
cannot get it to pick up devil's reign omega no matter what I name it running 
(https://github.com/mylar3/mylar3/issues/1228)

**Environment (please complete the following information):**
 - OS: 22.04.1 LTS
 - Branch / commit: bbccef9c8615063ab7f27354d3ae1e9e1a345574 (master)

Carepackage:
https://drive.google.com/file/d/1rGnFNM-4tW1c_JK0okFH2sDX9Fyt0zkg/view?usp=sharing

**Comment by evilhero** [comment]
You can't add the #Omega issue as part of the overall Devil's Reign series. 

It is not considered to be an annual, thus it won't be properly parsed against if you try to use that method. While adding specials / one-shots / whatever to the annual section can be done manually, it's not built to handle all of those options  as it's intended for annual inclusion (it may work, it may not - obviously the omega numbering is causing the issue I'd wager, but that's also not an annual).

You have to add the Omega issue as a separate series on your watchlist and then it will post-process properly.  You can try to change the series location of the Omega series to point to the main series directory - it should be able to detect it properly, but again, the omega numbering isn't the easiest thing to parse given that series have that as part of their name.
