### ISSUE TITLE
UnboundLocalError: local variable 'targ' referenced before assignment error

### ISSUE THREAD

**Issue by phairplay** [mylar3/mylar3#1289]
**Describe the bug**
error appearing when starting up 

```
  File "C:\Mylar3\Mylar.py", line 496, in <module>
    main()
  File "C:\Mylar3\Mylar.py", line 462, in main
    r.loaders()
  File "C:\Mylar3\mylar\req_test.py", line 52, in loaders
    self.check_the_pip()
  File "C:\Mylar3\mylar\req_test.py", line 144, in check_the_pip
    pip_message = "%s installed %s %s required" % (x['pip_version'], targ, x['req_version'])
UnboundLocalError: local variable 'targ' referenced before assignment

```

**CarePackage**
[carepackage_None_(master).zip](https://github.com/mylar3/mylar3/files/9641256/carepackage_None_.master.zip)

**Environment (please complete the following information):**
 - OS: Windows 10 
 - Branch / commit: e080f6c4251d49da570841e30c797bcb89eb7662 (python3-dev)

**Additional information**
I don't know if this is related but I've noticed Mylar isn't searching for any comics, this seems to have happened since the last update

**Comment by evilhero** [comment]
I believe you're missing some modules that are specified in the requirements.txt file. So you'd need to do the ``py -m pip install -r requirements.txt`` again, assuming your python3 install is tied to ``py`` (if it's not, then it's probably ``py3`` instead)

**Comment by phairplay** [comment]
thank you I really thought I had ran this
