### ISSUE TITLE
Mylar no carga y se congela por un largo tiempo

### ISSUE THREAD

**Issue by BJRironside** [mylar3/mylar3#1292]
**Describe the bug**
![error de carga](https://user-images.githubusercontent.com/108193075/194623115-636b5972-c0d2-4932-8c36-a71c68843eb3.jpg)

**CarePackage**
On the config page, there is a button labelled "CarePackage". Pressing this button will download a zip file containing a redacted copy of your config, your database, a summary of your operating environment, and your logs. Upload that file here.

If you're uncomfortable with pasting your CarePackage, include a DEBUG log containing the error from disk. 

Do not paste from the GUI log.
Do not just paste a traceback/error.

**Environment (please complete the following information):**
 - OS: [e.g. Windows10]
 - Branch / commit: [e.g. Dev/38aksi1]

**Additional information**
Add any other information about the problem here.

no existe registro de log, ya que no genera el recurso
sera que algo estoy haciendo mal, lo instale desde Mylar.py, tambien desde la consola PowerShell
utilizo Win11

![CarePackage](https://user-images.githubusercontent.com/108193075/194624484-33df2876-88ce-4a47-a806-ec8b3276de01.jpg)

**Comment by evilhero** [comment]
Some questions:
- how are you starting Mylar? As in what is the command you're running or are you just double-clicking on Mylar.py?
- what version of python are you running? 

You are several versions behind, so you probably need to update first, and then try running it again and see if the error is still present.

**Comment by BJRironside** [comment]
> Algunas preguntas:
> 
> * ¿Cómo estás empezando Mylar? ¿Cuál es el comando que está ejecutando o simplemente está haciendo doble clic en Mylar.py?
> * que version de python estas ejecutando?
> 
> Tiene varias versiones atrasadas, por lo que probablemente necesite actualizar primero y luego intente ejecutarlo nuevamente y vea si el error aún está presente.

![PYTHON](https://user-images.githubusercontent.com/108193075/194652372-c558f89c-b45f-45e2-9a6e-e1d939c5d579.jpg)

1. Compilo los requerimientos de Mylar
 1.1 pip3 install -r requirements.txt
2. Python Mylar.py
3. Error de carga

1. Mylar.py
2. Error de carga

Probe utilizando 6.9 y 6.52.2 ambos mismo error

**Comment by evilhero** [comment]
Try not using PowerShell to run the command - just use the command prompt.

Is the python your using the Microsoft store version or did you download python from the python website? 

If you are using the store version, try downloading the version from python.org and use that. Note that you should probably uninstall the store version, reinstall requirements.txt once you installed the new version, and don't use 3.10.7 - maybe try a couple versions lower.

**Comment by BJRironside** [comment]
> Intente no usar PowerShell para ejecutar el comando, solo use el símbolo del sistema.
> 
> ¿Python está usando la versión de la tienda de Microsoft o descargó python del sitio web de python?
> 
> Si está utilizando la versión de la tienda, intente descargar la versión de python.org y utilícela. Tenga en cuenta que probablemente debería desinstalar la versión de la tienda, reinstalar los requisitos.txt una vez que instaló la nueva versión y no usar 3.10.7; tal vez intente con un par de versiones más bajas.

![PYTHON2](https://user-images.githubusercontent.com/108193075/194723982-8333432e-7a28-4b83-b1fa-210645d7829c.jpg)
[mylar.log](https://github.com/mylar3/mylar3/files/9740125/mylar.log)

Probe con todas las sugerencias y aun persiste en no cargar.

**Comment by evilhero** [comment]
Mylar had to be running a minimum of 3.8.1, you happened to install a lower version. Try perhaps 3.9.6 as that seems to be the version that docker uses I believe. 

It seems to be starting up fine, does the GUI not display when you open a web browser and browse to the main page?

You can also start Mylar with the ``maintenance --carepackage`` switch and it will generate a carepackage before it even tries to load up the GUI.

How did you install mylar - did you git clone or did you download the source? Is the file structure the same locally as it is on the github - as that's important to running it.

**Comment by BJRironside** [comment]
> Mylar tenía que estar ejecutando un mínimo de 3.8.1, sucedió que instaló una versión inferior. Pruebe quizás 3.9.6, ya que parece ser la versión que usa Docker, creo.
> 
> Parece que se está iniciando bien, ¿no se muestra la GUI cuando abre un navegador web y navega a la página principal?
> 
> También puede iniciar Mylar con el `maintenance --carepackage`interruptor y generará un paquete de atención incluso antes de que intente cargar la GUI.
> 
> ¿Cómo instaló mylar? ¿Git clonó o descargó la fuente? ¿La estructura del archivo es la misma localmente que en el github, ya que eso es importante para ejecutarlo?

descargue directamente desde GITHUB la fuente completa, revisare las sugerencias y te comento.

**Comment by BJRironside** [comment]
> > Mylar tenía que estar ejecutando un mínimo de 3.8.1, sucedió que instaló una versión inferior. Pruebe quizás 3.9.6, ya que parece ser la versión que usa Docker, creo.
> > Parece que se está iniciando bien, ¿no se muestra la GUI cuando abre un navegador web y navega a la página principal?
> > También puede iniciar Mylar con el `maintenance --carepackage`interruptor y generará un paquete de atención incluso antes de que intente cargar la GUI.
> > ¿Cómo instaló mylar? ¿Git clonó o descargó la fuente? ¿La estructura del archivo es la misma localmente que en el github, ya que eso es importante para ejecutarlo?
> 
> descargue directamente desde GITHUB la fuente completa, revisare las sugerencias y te comento.

Amigo lamento no poder instalar Mylar, creo que supera mi basico conocimiento, muchas gracias por la ayuda, lo dejare puedes cerrar este problema.
