### ISSUE TITLE
Human Torch (1940) has an alpha-numeric in the issue

### ISSUE THREAD

**Issue by PawlakMarek** [mylar3/mylar3#1296]
**Describe the bug**
Mylar cannot parse issue numbers for [Human Torch (1940)](https://comicvine.gamespot.com/the-human-torch/4050-832/) due to special numbering like "4 [3]"

**CarePackage**
[carepackage_v0.6.9.zip](https://github.com/mylar3/mylar3/files/9843075/carepackage_v0.6.9.zip)

**Environment (please complete the following information):**
 - OS: docker - lscr.io/linuxserver/mylar3:latest
 - Branch / commit: Master/bbccef9

**Comment by evilhero** [comment]
This has already been fixed in the python3-dev branch (#1294). Either change your docker to pull the nightly image, or wait for the merge to master.

**Comment by evilhero** [comment]
Closed as completed / stale.
