### ISSUE TITLE
Failing to start - Not sure which version was last installed

### ISSUE THREAD

**Issue by Dude77777** [mylar3/mylar3#1305]
**Describe the bug**
Dear Evilhero & team, I hope you are well. Its been some time that I used Mylar (due to a lot of manual importing required). 
However, I see that you continue to improve it at regular intervals, so I would like to give bulk importing another go.
Unfortunately I am not that technical so I cant figure out what exactly is preventing me from starting it:

This is the batch command I run:
A:\DL\Z mylar3> python Mylar.py
Traceback (most recent call last):
  File "A:\DL\Z mylar3\Mylar.py", line 27, in <module>
    import mylar
  File "A:\DL\Z mylar3\mylar\__init__.py", line 27, in <module>
    import requests
  File "C:\Users\micha\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\__init__.py", line 133, in <module>
    from . import utils
  File "C:\Users\micha\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\utils.py", line 21, in <module>
    import zipfile
  File "C:\Users\micha\AppData\Local\Programs\Python\Python310\lib\zipfile.py", line 19, in <module>
    import pathlib
  File "A:\DL\Z mylar3\lib\pathlib.py", line 10, in <module>
    from collections import Sequence
ImportError: cannot import name 'Sequence' from 'collections' (C:\Users\micha\AppData\Local\Programs\Python\Python310\lib\collections\__init__.py)
PS A:\DL\Z mylar3>

My suspicion is that either Python got updated due to other software (see screenshot of Environment variables) or something went wrong during the last Mylar Update a while back. 
Many thanks for helping me out with these basic issues. I just hope I dont have to set Mylar up from scratch again / re import everything to date.

**Environment (please complete the following information):**
 - OS:Windows 11
 - Branch / commit: Not sure

**Additional information**
Add any other information about the problem here.
![Environment Variables](https://user-images.githubusercontent.com/83953593/200163118-015e17c8-2f63-476b-9f95-c26787e8aa41.jpg)

**Comment by evilhero** [comment]
Your version of mylar is rather old based on that error, and I'm guessing you just downloaded the source zip file from github and installed that. The problem with using the source install is that it doesn't delete outdated files, which can then cause problems thereafter - which is what is happening here. 

The preferred method of installation is to use github so updates are handled within the application and this type of problem is avoided. 

But to address your current problem:
- backup just your config.ini, mylar.db and your entire mylar cache directory to a location outside of your mylar install
- delete the entire mylar folder
- download the source file from github as you have previously and unzip it where you want mylar to be  installed
- copy the files you backed up above into the new location, overwriting anything it asks for
- start mylar as you normally do (maybe add the ``-v`` switch to enable verbose logging) 

You may also have to rereun the requirements.txt file installation, but the above will at least get you back to the point of a working install.

**Comment by Dude77777** [comment]
Many thanks for the fast help Evilhero! Its fully working again. I have installed git now, so let me see how this will prevent similar errors in the future. Best regards
