### ISSUE TITLE
Unable to start Mylar3 after Python update

### ISSUE THREAD

**Issue by Obscurax** [mylar3/mylar3#1323]
**Describe the bug**
Mylar3 does not start with Python 3.10 or 3.11.
Mylar3 does start with Python 3.9.

```
python.exe "C:\ProgramData\Mylar3\Mylar.py"
Traceback (most recent call last):
  File "C:\ProgramData\Mylar3\Mylar.py", line 27, in <module>
    import mylar
  File "C:\ProgramData\Mylar3\mylar\__init__.py", line 27, in <module>
    import requests
  File "C:\Python\Python310\lib\site-packages\requests\__init__.py", line 147, in <module>
    from . import packages, utils
  File "C:\Python\Python310\lib\site-packages\requests\utils.py", line 19, in <module>
    import zipfile
  File "C:\Python\Python310\lib\zipfile.py", line 19, in <module>
    import pathlib
  File "C:\ProgramData\Mylar3\lib\pathlib.py", line 10, in <module>
    from collections import Sequence
ImportError: cannot import name 'Sequence' from 'collections' (C:\Python\Python310\lib\collections\__init__.py)
```

**CarePackage**
Unable to start Mylar3

**Environment (please complete the following information):**
 - OS: Windows Server 2022
 - Branch / commit:  v0.7.0 5c1b5e2 

**Additional information**
Add any other information about the problem here.

**Comment by losslesspng** [comment]
Did you install the requirements again with the new python version after you tried changing it? Assuming that you had them installed with python 3.9, they won't be located in the same place and available to python 3.10 or 3.11.

**Comment by Obscurax** [comment]
Yes I have reinstalled the requirements each time on switching versions.
`py -m pip install -r requirements.txt`

**Comment by evilhero** [comment]
The problem in this case is that the file located in the lib folder called pathlib.py was removed a few versions ago. Your version is still present however, as source installations don't remove outdated files, they just create or update existing files. 

This is why we generally tell users to use the git install method, as then it handles updates as well as notifying of new releases, and in doing all of this you don't get stranded outdated files in your directory. 

If however you still want to use source, you should be wiping out the entire mylar directory on each update (making sure to backup the config.ini, mylar.db and cache folder). Then unzip the contents into a clean directory and put the backed up files back. (note that this problem exists if you update via source in mylar, it's a problem with the source installation method)

**Comment by Obscurax** [comment]
Thank you very much for the detailed explanation. Everything is up and running again.
I'm updating via the web interface, should I continue doing that?

**Comment by evilhero** [comment]
Updating via the interface works fine, just keep in mind that if we happen to delete a file from the program intentionally, yours will still be present until you wipe the directory or manually delete the file.

If you like things simple, try to install it via git and get that aspect going. More work upfront, but less problems overall if something arises.

**Comment by Obscurax** [comment]
Alright I'll look into running from git. Thanks again.
