### ISSUE TITLE
Error with every attempted search

### ISSUE THREAD

**Issue by svtcobra1996** [mylar3/mylar3#1328]
**Describe the bug**
Had this all set and working about a week.  Then i started noticing repeat errors:

`  File "C:\mylar3-master\mylar\sabnzbd.py", line 67, in sender
    'nzo_id': ''.join(sendresponse['nzo_ids']),
TypeError: sequence item 0: expected str instance, NoneType found`

I have noticed other similar errors in the logs.  Since this started haven't been able to successfully grab any comics. 
I've tried the following to see if there were any differences:

- removed pip requirements
- removed python
- remove registry entries for python
- removed python folders
- rebooted
- reinstalled python
- reinstalled pip requirements
- retested with the same errors
- re-downloaded the mylar code from git
- repeated the python process and tried with the latest python and pip version, same outcome

**CarePackage**

[carepackage_v0.7.0.zip](https://github.com/mylar3/mylar3/files/10866504/carepackage_v0.7.0.zip)

**Environment (please complete the following information):**
 - OS: Windows Server 2022

**Comment by evilhero** [comment]
You have your host_return value set to just the ip. It needs to be the full url to your mylar instance, including protocol and port (ie. ``http://192.168.1.2:8090``). Note that unless mylar and sab are on seperate machines, or mylar is running in a multi-homed machine, the vast majority of people don't need to set host_return. 

You also seem to be using UNC pathing for some items, which can cause probems. You should try mounting the paths as drive letters and then supplying mylar with the mapped drive letter pathing.

**Comment by svtcobra1996** [comment]
thanks, changing the host_return seems to have worked.  It is multi-homed, when i asked about that on discord i understood the change needed be just the IP, i didnt realize it needed the full path.  Now that its changed it seems good.  I'll look at mapping the drives as well and updated that.
