### ISSUE TITLE
Fresh install on Ubuntu 22.04 errors ?

### ISSUE THREAD

**Issue by nickdemise** [mylar3/mylar3#1330]
Just downloaded and tried installing Mylar on my ubuntu 22.04 vm, but i get the following error with attempting to start:

Traceback (most recent call last):
  File "/home/downloads/mylar3-0.7.0/Mylar.py", line 27, in <module>
    import mylar
  File "/home/downloads/mylar3-0.7.0/mylar/__init__.py", line 38, in <module>
    from apscheduler.schedulers.background import BackgroundScheduler
ModuleNotFoundError: No module named 'apscheduler'

pip install -r requirements.txt returns:
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: APScheduler>=3.6.3 in /home/nick/.local/lib/python3.10/site-packages (from -r requirements.txt (line 7)) (3.10.1)
Requirement already satisfied: beautifulsoup4>=4.8.2 in /home/nick/.local/lib/python3.10/site-packages (from -r requirements.txt (line 8)) (4.11.2)
Requirement already satisfied: cfscrape>=2.0.8 in /home/nick/.local/lib/python3.10/site-packages (from -r requirements.txt (line 9)) (2.1.1)
Requirement already satisfied: cheroot==8.2.1 in /home/nick/.local/lib/python3.10/site-packages (from -r requirements.txt (line 10)) (8.2.1)
Requirement already satisfied: CherryPy>=18.5.0 in /home/nick/.local/lib/python3.10/site-packages (from -r requirements.txt (line 11)) (18.8.0)
Requirement already satisfied: configparser>=4.0.2 in /home/nick/.local/lib/python3.10/site-packages (from -r requirements.txt (line 12)) (5.3.0)
Requirement already satisfied: feedparser>=5.2.1 in /home/nick/.local/lib/python3.10/site-packages (from -r requirements.txt (line 13)) (6.0.10)
Requirement already satisfied: Mako>=1.1.0 in /home/nick/.local/lib/python3.10/site-packages (from -r requirements.txt (line 14)) (1.2.4)
Requirement already satisfied: natsort>=3.5.2 in /home/nick/.local/lib/python3.10/site-packages (from -r requirements.txt (line 15)) (8.3.1)
Requirement already satisfied: Pillow>=8 in /home/nick/.local/lib/python3.10/site-packages (from -r requirements.txt (line 16)) (9.4.0)
Requirement already satisfied: portend>=2.6 in /home/nick/.local/lib/python3.10/site-packages (from -r requirements.txt (line 17)) (3.1.0)
Requirement already satisfied: pystun>=0.1.0 in /home/nick/.local/lib/python3.10/site-packages (from -r requirements.txt (line 18)) (0.1.0)
Requirement already satisfied: pytz>=2019.3 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 19)) (2022.1)
Requirement already satisfied: rarfile>=4.0 in /home/nick/.local/lib/python3.10/site-packages (from -r requirements.txt (line 20)) (4.0)
Requirement already satisfied: requests>=2.22.0 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 21)) (2.25.1)
Requirement already satisfied: simplejson>=3.17.0 in /home/nick/.local/lib/python3.10/site-packages (from -r requirements.txt (line 22)) (3.18.3)
Requirement already satisfied: six>=1.13.0 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 23)) (1.16.0)
Requirement already satisfied: tzlocal>=2.0.0 in /home/nick/.local/lib/python3.10/site-packages (from -r requirements.txt (line 24)) (4.2)
Requirement already satisfied: urllib3>=1.25.7 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 25)) (1.26.5)
Requirement already satisfied: user_agent2>=2021.12.11 in /home/nick/.local/lib/python3.10/site-packages (from -r requirements.txt (line 26)) (2021.12.11)
Requirement already satisfied: jaraco.functools in /home/nick/.local/lib/python3.10/site-packages (from cheroot==8.2.1->-r requirements.txt (line 10)) (3.6.0)
Requirement already satisfied: more-itertools>=2.6 in /usr/lib/python3/dist-packages (from cheroot==8.2.1->-r requirements.txt (line 10)) (8.10.0)
Requirement already satisfied: setuptools>=0.7 in /usr/lib/python3/dist-packages (from APScheduler>=3.6.3->-r requirements.txt (line 7)) (59.6.0)
Requirement already satisfied: soupsieve>1.2 in /home/nick/.local/lib/python3.10/site-packages (from beautifulsoup4>=4.8.2->-r requirements.txt (line 8)) (2.4)
Requirement already satisfied: jaraco.collections in /home/nick/.local/lib/python3.10/site-packages (from CherryPy>=18.5.0->-r requirements.txt (line 11)) (3.8.0)
Requirement already satisfied: zc.lockfile in /home/nick/.local/lib/python3.10/site-packages (from CherryPy>=18.5.0->-r requirements.txt (line 11)) (3.0.post1)
Requirement already satisfied: sgmllib3k in /home/nick/.local/lib/python3.10/site-packages (from feedparser>=5.2.1->-r requirements.txt (line 13)) (1.0.0)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/lib/python3/dist-packages (from Mako>=1.1.0->-r requirements.txt (line 14)) (2.0.1)
Requirement already satisfied: tempora>=1.8 in /home/nick/.local/lib/python3.10/site-packages (from portend>=2.6->-r requirements.txt (line 17)) (5.2.1)
Requirement already satisfied: pytz-deprecation-shim in /home/nick/.local/lib/python3.10/site-packages (from tzlocal>=2.0.0->-r requirements.txt (line 24)) (0.1.0.post0)
Requirement already satisfied: user-agent==0.1.10 in /home/nick/.local/lib/python3.10/site-packages (from user_agent2>=2021.12.11->-r requirements.txt (line 26)) (0.1.10)
Requirement already satisfied: jaraco.classes in /home/nick/.local/lib/python3.10/site-packages (from jaraco.collections->CherryPy>=18.5.0->-r requirements.txt (line 11)) (3.2.3)
Requirement already satisfied: jaraco.text in /home/nick/.local/lib/python3.10/site-packages (from jaraco.collections->CherryPy>=18.5.0->-r requirements.txt (line 11)) (3.11.1)
Requirement already satisfied: tzdata in /home/nick/.local/lib/python3.10/site-packages (from pytz-deprecation-shim->tzlocal>=2.0.0->-r requirements.txt (line 24)) (2022.7)
Requirement already satisfied: jaraco.context>=4.1 in /home/nick/.local/lib/python3.10/site-packages (from jaraco.text->jaraco.collections->CherryPy>=18.5.0->-r requirements.txt (line 11)) (4.3.0)
Requirement already satisfied: inflect in /home/nick/.local/lib/python3.10/site-packages (from jaraco.text->jaraco.collections->CherryPy>=18.5.0->-r requirements.txt (line 11)) (6.0.2)
Requirement already satisfied: autocommand in /home/nick/.local/lib/python3.10/site-packages (from jaraco.text->jaraco.collections->CherryPy>=18.5.0->-r requirements.txt (line 11)) (2.2.2)
Requirement already satisfied: pydantic>=1.9.1 in /home/nick/.local/lib/python3.10/site-packages (from inflect->jaraco.text->jaraco.collections->CherryPy>=18.5.0->-r requirements.txt (line 11)) (1.10.6)
Requirement already satisfied: typing-extensions>=4.2.0 in /home/nick/.local/lib/python3.10/site-packages (from pydantic>=1.9.1->inflect->jaraco.text->jaraco.collections->CherryPy>=18.5.0->-r requirements.txt (line 11)) (4.5.0)

The APScheduler package seems there so whats the issue ?
Thanks

**Comment by evilhero** [comment]
Either you're using a different version of python to run Mylar (do you have more than one version of python installed) or the pip install is not installing to the location needed by python. This is all due to your local installation for some reason.

What is the command you're using to start mylar? Are you by chance using sudo to start it or you're running it as root?

**Comment by nickdemise** [comment]
Yes indeed I'm quite new and overuse sudo, in this case cause it wasn't in a folder with normal access.
I moved it to a local user path and now it works without sudo just fine.
Thanks again!
