### ISSUE TITLE
New Issues not auto downloading from DDL

### ISSUE THREAD

**Issue by nzeminski** [mylar3/mylar3#1344]
**Describe the bug**
New issues coming out in series being tracked do not seem to be auto downloading. I only use DDL. This worked for a while, no changes to my knowledge.

**CarePackage**

[carepackage_v0.7.1.zip](https://github.com/mylar3/mylar3/files/11251624/carepackage_v0.7.1.zip)

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Branch / commit: Using Docker - Linuxserver/docker-mylar3

**Additional information**
Add any other information about the problem here.

**Comment by evilhero** [comment]
Try turning on debug logging and attempt a search. Then upload a new carepackage after it doesn't download.

It does look like you're hitting Cloudflare protection on the site, which means that you can't access getcomics. In a browser on the same machine can you get to GC? It might be that you have to wait a couple days for the CF ban to lift if that's what it is, it can be anywhere from 24hrs to 2 weeks so it's hard to say how long the ban is if that's what it is.

**Comment by nzeminski** [comment]
[carepackage_v0.7.1.zip](https://github.com/mylar3/mylar3/files/11253450/carepackage_v0.7.1.zip)
I turned on debug logging and attempted a search for Batman Incorporated - Issue 06.

Cloudflare makes sense. I did try a curl to GC. I can't make a whole lot of sense of what came out other than complaints about javascript and cookies are disabled. I'll attach that output as well if it is some help.
[curl_GC.txt](https://github.com/mylar3/mylar3/files/11253473/curl_GC.txt)

**Comment by evilhero** [comment]
@Bazzu85 , @bulletproof2k  - if you can't get to GC via mylar then your only solution at this time is to try and use FlareSolverr to bypass the CF. CF is throwing up either a geo or IP based blocking and as such alot of people can't get thru via automated methods (it does seem to be somewhat geographical in some cases).  

While not a guarantee flaresolverr will work, atm that's the only solution we have available until GC drops the Under Attack mode (or CF does it for them). You can enable flaresolver by setting in the config.ini:

``enable_flaresolverr = True
flaresolverr_url = http://192.168.1.2:8191/v1``
(note the **192.168.1.2:8191** would be replaced with your flaresolverr IP and port)

**Comment by nzeminski** [comment]
I ended up connecting my mylar3 container with a wireguard container and am able to download again. Seems this is getting past the CloudFlare protection.

**Comment by NickSica** [comment]
> @Bazzu85 , @bulletproof2k - if you can't get to GC via mylar then your only solution at this time is to try and use FlareSolverr to bypass the CF. CF is throwing up either a geo or IP based blocking and as such alot of people can't get thru via automated methods (it does seem to be somewhat geographical in some cases).
> 
> While not a guarantee flaresolverr will work, atm that's the only solution we have available until GC drops the Under Attack mode (or CF does it for them). You can enable flaresolver by setting in the config.ini:
> 
> `enable_flaresolverr = True flaresolverr_url = http://192.168.1.2:8191/v1` (note the **192.168.1.2:8191** would be replaced with your flaresolverr IP and port)

I have a similar error popping up as @nzeminski with a newer version. I set up flaresolverr, but it says there is no Cloudflare challenge detected.

[carepackage_v0.7.2.zip](https://github.com/mylar3/mylar3/files/11987009/carepackage_v0.7.2.zip)

@nzeminski what kind of setup did you use to get past this?

**Comment by DieselTech** [comment]
@NickSica If flaresolverr isn't detecting the challenge then there isn't anything mylar can do about it. GC is 100% behind cloudflare and the attack mode turns on automatically on new release days.

**Comment by NickSica** [comment]
> @NickSica If flaresolverr isn't detecting the challenge then there isn't anything mylar can do about it. GC is 100% behind cloudflare and the attack mode turns on automatically on new release days.

Ah ok, thank you. It actually seems like it pinged flaresolverr once then never tried again on subsequent grabs. I'm not sure why.

**Comment by nzeminski** [comment]
@NickSica I used flaresolverr and put the container behind a VPN. I've had more stable results after using a VPN.

**Comment by NickSica** [comment]
> @NickSica I used flaresolverr and put the container behind a VPN. I've had more stable results after using a VPN.

Is it just a home VPN? I notice Mylar3 doesn't really contact flaresolverr for some reason even though all the right flags are set.
