### ISSUE TITLE
Unable to write series.json

### ISSUE THREAD

**Issue by hwwilliams** [mylar3/mylar3#1351]
**Describe the bug**
I've been having some issues with empty series.json files, file size of 0, the errors say `Error returned: [Errno 1] Operation not permitted` but it still gives this error even with all files and directories as 0777. I've even logged in as the mylar user and edited the series.json files successfully.

Mylar can download and rename files successfully, its just the empty series.json file I'm noticing having issues.

Is there anything you can suggest based on the logs I provided below?

**CarePackage**
[carepackage_v0.7.2.zip](https://github.com/mylar3/mylar3/files/11439145/carepackage_v0.7.2.zip)

**Environment (please complete the following information):**
 - OS: Debian 11
 - Branch / commit: master/eca80ef

**Comment by hwwilliams** [comment]
> What you could try is to change the path for a particular series to a local folder. 

I'll try this and see if it changes anything.

> create the series.json file by clicking on the series.json marker on the series page (it should be red to denote the file doesn't exist, yellow means it exists).

Does Mylar automatically update these series.json files by itself?

I ask because all the series show the button as yellow since the file does exist its just empty.

**Comment by evilhero** [comment]
It updates them on every Recheck Files, as well as on refreshes (which does a Recheck Files at the end). 

So while technically it doesn't update them automatically, if a series is updated on CV (whether a new issue, or updating an old one), mylar will update the series during its db update check and in doing so will update the json.

You can also call the ``refeshseriesjson`` api endpoint, which can refresh / recreate the json for series that are missing a json file, or for all series in your watchlist. The docs for the endpoint usage are [here](https://github.com/mylar3/mylar3/wiki/refeshseriesjson)

**Comment by hwwilliams** [comment]
I was able to fix these locking issues by moving from NFS v3 to v4.2, I don't know if it was actually the locking issue causing the series.json to be empty but that issue seems to have gone away as well since I updated NFS and configured v4.2 only shares.
