### ISSUE TITLE
Errno 13 When Removing File

### ISSUE THREAD

**Issue by NickSica** [mylar3/mylar3#1378]
**Describe the bug**
Hello, the post processor is trying to remove the downloaded file from the sabnzbd directory, but it is getting an Errno 13 error. This usually points to a permissions issue, however I have used podman exec -it -u=abc and even the exact PUID and PGID I'm feeding the linuxserver container to go into the container and remove the file manually with no issues. The enforce permissions option is also unticked in case that might've been the issue. I'm not sure if something else is getting in the way when the same operation is attempted through the code?

**CarePackage**
[carepackage_v0.7.2.zip](https://github.com/mylar3/mylar3/files/12166011/carepackage_v0.7.2.zip)

**Environment (please complete the following information):**
 - OS: Linuxserver Docker Container
 - Branch / commit: latest

**Comment by evilhero** [comment]
Nope, mylar does a simple os remove, nothing fancy or the like. If it can't do it, it will throw the OS error it encounters. There's not much to go on in the mylar logs as it's just indicating the error. 

I'm assuming you have the same puid, pgid for both sab and mylar containers, but the error it's throwing isn't Mylar itself (I know it probably appears that way), as it's an OS error related to permissions of some kind.

My best guess would be that the user running Mylar might not be able to access the /downloads/comics mount in some capacity, or if it can it doesn't have permission to remove said items. I'd also check to see what the ownership of the /downloads/comics mount is along with the permissions that sab is making them.

Also, don't set your folder monitor to /downloads/comics as that will run every 5 mins and if sab downloads something and the mylar post-processor is trying to do something with the file, the folder monitor will try to do the same thing and it will cause a race condition (or throw an error related to not being able to locate the file usually).

**Comment by NickSica** [comment]
> Nope, mylar does a simple os remove, nothing fancy or the like. If it can't do it, it will throw the OS error it encounters. There's not much to go on in the mylar logs as it's just indicating the error.
> 
> I'm assuming you have the same puid, pgid for both sab and mylar containers, but the error it's throwing isn't Mylar itself (I know it probably appears that way), as it's an OS error related to permissions of some kind.
> 
> My best guess would be that the user running Mylar might not be able to access the /downloads/comics mount in some capacity, or if it can it doesn't have permission to remove said items. I'd also check to see what the ownership of the /downloads/comics mount is along with the permissions that sab is making them.
The odd part is I'm able to go into the container and remove it when I pretend to be the user that linuxserver.io uses. When I meant something funky I meant on the side of the container, because I saw the simple removes and couldn't figure it out that way. It might have to do with my subuid and subgid maps for podman though.

> Also, don't set your folder monitor to /downloads/comics as that will run every 5 mins and if sab downloads something and the mylar post-processor is trying to do something with the file, the folder monitor will try to do the same thing and it will cause a race condition (or throw an error related to not being able to locate the file usually).
Do you mean the sabnzbd folder? It didn't work without that folder. This folder is the final destination for the files once all the downloading is finished.

**Comment by evilhero** [comment]
No, I mean the folder monitor - you have it enabled and set to run every 5 minutes monitoring /downloads/comics for anything. The folder monitor is meant for items you download outside of mylar but you have the series being monitored already. Alot of people mistakingly set the folder monitor to monitor their sabnzbd completed folder because they can't get the completed download handling (CDH) to work. When it's working properly, CDH should be post-processing everything immediately after it downloads based on the sabnzbd directory location being passed to it. 

Im guessing if you have subuids that might be causing some problems when it comes to determining ownerships and permissions. I have no clue about pod an so I can't offer any type of advice in  regards to how it handles things. If you could I'd suggest trying to just use a non-subuids when running the container to see if that solves it.

**Comment by NickSica** [comment]
> No, I mean the folder monitor - you have it enabled and set to run every 5 minutes monitoring /downloads/comics for anything. The folder monitor is meant for items you download outside of mylar but you have the series being monitored already. Alot of people mistakingly set the folder monitor to monitor their sabnzbd completed folder because they can't get the completed download handling (CDH) to work. When it's working properly, CDH should be post-processing everything immediately after it downloads based on the sabnzbd directory location being passed to it.
> 
> I'm guessing if you have subuids that might be causing some problems when it comes to determining ownerships and permissions. I have no clue about pod an so I can't offer any type of advice in regards to how it handles things. If you could I'd suggest trying to just use a non-subuids when running the container to see if that solves it.

I finally got it back up and looked through the settings. I think I did turn on the folder monitor, but there was no folder set. Thanks for the heads up I turned it off again.    

I'll leave the solution I found for podman for anyone else. The big issue was mapping the supplemental group that my user and sabnzbd have. I solved it by adding the following lines to my podman run and making sure the PGID matches what is reported in the container. Thank you again for your help!
`-e PUID=0 \
-e PGID=165536 \
--uidmap "0:0:65535" \
--gidmap "0:0:1" \
--gidmap "165536:1:1" \
--gidmap "1:2:65534" \
--group-add keep-groups \`
