### ISSUE TITLE
Symbolic Link with Story Arc Post Processing

### ISSUE THREAD

**Issue by NickSica** [mylar3/mylar3#1386]
**Describe the bug**
When using soft(I've also seen it on hard) links with the Story Arc directory, the post-processor links against the file in the cache folder which causes issues when it is deleted later in the flow. I'm looking at the code to see if I can find a fix, but it's a lot so I thought I'd open a bug report in case I missed something.

It actually also seems like Mylar isn't correctly creating softlinks either I think because it is trying to link to the cache.

**CarePackage**
[carepackage_v0.7.2.zip](https://github.com/mylar3/mylar3/files/12264070/carepackage_v0.7.2.zip)

**Environment (please complete the following information):**
Latest docker image

**Comment by NickSica** [comment]
Nevermind my issue seems to be cifs related.

**Comment by DieselTech** [comment]
Your also a version behind mainstream release.
