### ISSUE TITLE
Invalid Comic Location Path == produce human readable error message 

### ISSUE THREAD

**Issue by psychogun** [mylar3/mylar3#141]
**Describe the request**
Make (also) the different tabs under Settings read values from `config.ini` "dynamically", in lack of a better word. 

I was about to post this _bug_ report; 

Selecting 'This Week' and Adding a Comic changes the Status to Wanted. But if I select the Comic, the page with "(Comic information is currently being loaded)" is spinning forever.

**tail -f /usr/local/mylar3/log/mylar.log**
`01-Mar-2020 16:06:20 - INFO    :: mylar.addbyid.433 : CP Server Thread-3 : Attempting to add directly by ComicVineID: 120102
01-Mar-2020 16:06:23 - INFO    :: mylar.addComictoDB.125 : Thread-14 : Now adding/updating: Unearth
01-Mar-2020 16:06:23 - INFO    :: mylar.addComictoDB.178 : Thread-14 : Sucessfully retrieved details for Unearth
01-Mar-2020 16:06:23 - INFO    :: mylar.addComictoDB.184 : Thread-14 : Previous version detected as None - seeing if update required
01-Mar-2020 16:06:23 - ERROR   :: mylar.excepthook.315 : Thread-14 : Uncaught exception: Traceback (most recent call last):
  File "/usr/local/mylar3/mylar/filers.py", line 109, in folder_create
    comlocation = os.path.join(mylar.CONFIG.DESTINATION_DIR, helpers.replace_all(chunk_folder_format, values))
  File "/usr/local/lib/python3.7/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/mylar3/mylar/logger.py", line 337, in new_run
    old_run(*args, **kwargs)
  File "/usr/local/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/mylar3/mylar/importer.py", line 217, in addComictoDB
    comlocation = dothedew.folder_create()
  File "/usr/local/mylar3/mylar/filers.py", line 112, in folder_create
    if 'TypeError' in e:
TypeError: argument of type 'TypeError' is not iterable
`

**Environment (please complete the following information):**
 - OS: FreeNAS-11.3-RELEASE w/ jail FreeBSD 11.3-RELEASE-p5 
 - Branch / commit: Version: 966f1754ba798fa23a4227917fcd076505c09ba4 (python3-dev)

**Additional information**
`python -V
Python 3.7.6
`

**_Request_**
So, yeah, basically - this error was because I had two different browsers open, both had loaded the Settings page, and I accidentally altered some settings in one browser and saved the config. 

Then time went by, and I went to the other browser and altered another setting, in another Settings tab. When I did this, the Comic Location Path was already "loaded" with the old value, _None_. Thus when I saved the configuration in this new browser, the Comic Location Path was overwritten with "None".

This made mylar3 unable to write to the directory of where it should add the Comic.

So. Yeah. What to say:

- I'll definitely refresh/click the Settings page before I do any edit now.  Or stick to just one browser when I am editing settings :)

But maybe;
- If mylar3 does not have a valid Comic Location Path, produce a human readable error message?

**Comment by barbequesauce** [comment]
Can you recreate with a debug log running please? This is... interesting...

**Comment by evilhero** [comment]
Right after that exception that tripped is a log line that would have been: 
```Cannot determine Comic Location path properly. Check your Comic Location and Folder Format for any errors.```

Had that not caused an exception it would  have logged this:
```No Comic Location specified. This NEEDS to be set before anything can be added successfully.```

In both cases, had the execution not been stopped by the untrapped error within the exeption itself, it would have logged something stating that the Comic Location was invalid and then stopped   the current execution gracefully (ie. not add the series).

We can fix the exception so it doesn't error - so if this were to happen again (multiple tabs *tsk*tsk), it'll log it properly and not add any series. Or was there another method you were thinking of for the human-readable message ? 

As far as the dynamic loading per tab - I'm not 100% sure if this is possible given how Mylar loads in the Configuration page (it's just one html page, but tabs are within). I know I've been caught prior to the same type of problem as you where the tab isn't updated if you're not viewing it (ie. you update a provider, but you save the config when you're on the notifications tab - the provider won't show as was changed until the entire page is refreshed). Something to look into tho definitely...

**Comment by Bart274** [comment]
@evilhero wouldn’t it be possible to have a check during the save of the config to check the validity of the comic location? Then you could cancel the save and show an error on the screen saying the save can’t be done due to an invalid comic location?

**Comment by evilhero** [comment]
@Bart274 , yep it's possible. It already checks for validity during a save, but it doesn't stop the save from occuring or give a GUI display message. Unfortunately we don't have a lot of error messages popping on the screen when they really should be. Can look into this aspect further tho

**Comment by Bart274** [comment]
That’s the only way I could think of throwing a human readable error, other than checking the logs

**Comment by barbequesauce** [comment]
psychogun, please review the fixes as described above and confirm/close the issue or reply back with findings

**Comment by barbequesauce** [comment]
Please open a new issue and reference this issue (#141) if you're still having an issue.
