### ISSUE TITLE
Unicode Decode Error

### ISSUE THREAD

**Issue by burnshroom** [mylar3/mylar3#142]
01-Mar-2020 20:51:30 - DEBUG   :: mylar.NZB_SEARCH.624 : SEARCH-QUEUE : Sending request to DDL site for : Action Comics 1018
01-Mar-2020 20:51:33 - ERROR   :: mylar.excepthook.315 : SEARCH-QUEUE : Uncaught exception: Traceback (most recent call last):
  File "F:\mylar3\mylar\logger.py", line 337, in new_run
    old_run(*args, **kwargs)
  File "D:\Python37-32\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "F:\mylar3\mylar\helpers.py", line 3114, in search_queue
    ss_queue = mylar.search.searchforissue(item['issueid'])
  File "F:\mylar3\mylar\search.py", line 1873, in searchforissue
    foundNZB, prov = search_init(ComicName, IssueNumber, str(IssueYear), SeriesYear, Publisher, IssueDate, StoreDate, actissueid, AlternateSearch, UseFuzzy, ComicVersion, SARC=SARC, IssueArcID=IssueArcID, mode=mode, rsscheck=rsscheck, ComicID=ComicID, filesafe=Comicname_filesafe, allow_packs=allow_packs, oneoff=oneoff, manual=manual, torrentid_32p=TorrentID_32p, digitaldate=DigitalDate, booktype=booktype)
  File "F:\mylar3\mylar\search.py", line 360, in search_init
    findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="no", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName, allow_packs=allow_packs, oneoff=oneoff, cmloopit=cmloopit, manual=manual, torznab_host=torznab_host, torrentid_32p=torrentid_32p, digitaldate=digitaldate, booktype=booktype)
  File "F:\mylar3\mylar\search.py", line 626, in NZB_SEARCH
    bb = b.search()
  File "F:\mylar3\mylar\getcomics.py", line 68, in search
    return self.search_results()
  File "F:\mylar3\mylar\getcomics.py", line 86, in search_results
    soup = BeautifulSoup(open(self.local_filename), 'html.parser')
  File "D:\Python37-32\lib\site-packages\bs4\__init__.py", line 286, in __init__
    markup = markup.read()
  File "D:\Python37-32\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 30254: character maps to <undefined>

[carepackage (1).zip](https://github.com/mylar3/mylar3/files/4273251/carepackage.1.zip)

**Comment by barbequesauce** [comment]
Update & Try again, please :)

**Comment by burnshroom** [comment]
Fix is in... fix worked.  Thanks.
