### ISSUE TITLE
Series unpauses on new issue release

### ISSUE THREAD

**Issue by falo2k** [mylar3/mylar3#1429]
A series that is paused will unpause when new issues are released and the series updates, rendering the pause redundant.  I've attached a debug log of the events of the unpause (on the 2000 AD series).  I intend to have a dig into this myself at some point but raising the issue for tracking / in case someone more familiar with the code can hone straight in on the problem area.

[mylar.log](https://github.com/mylar3/mylar3/files/12840172/mylar.log)

**Comment by ronlipke** [comment]
I've run into this same issue a few times. Most recently I woke up to hundreds of Wonder Woman and Detective Comics issues that had been downloaded.

**Comment by falo2k** [comment]
Fixed a while back
