### ISSUE TITLE
Auto add publisher 

### ISSUE THREAD

**Issue by typo2014** [mylar3/mylar3#1431]
**Describe the request**
I would like to add ALL future Marvel comics from the weekly pull list - 
i'm a full fledged Marvel fan and i would like an option that mylar3 adds all comics from a certain publisher (e.g. Marvel) 

currently i'm adding those manually based on the weekly pull lists but would prefer to have it autoadded

**Comment by morsok** [comment]
click the mass add button on the weekly pull list, add Marvel and whatever publisher you want, and enjoy.

**Comment by typo2014** [comment]
perfect solution already in place - love it!!! 

thanks a lot
