### ISSUE TITLE
sqlite3.IntegrityError: UNIQUE constraint failed: provider_searches.id

### ISSUE THREAD

**Issue by bulletproof2k** [mylar3/mylar3#1436]
[mylar.log](https://github.com/mylar3/mylar3/files/13222010/mylar.log)
It suddenly stopped running today. I have not been able to establish the reason.

Microsoft Windows [Version 10.0.22621.2506]
(c) Корпорация Майкрософт (Microsoft Corporation). Все права защищены.

E:\DEV\Py\mylar3>python Mylar.py
language detected as non-English (ru_RU). Forcing specific logging module - errors WILL NOT be captured in the logs
Initializing startup sequence....
01-ноя-2023 02:22:33 - INFO :: MainThread : config.py:configure:1088 : [STORYARC LOCATION] Storyarc Base directory location set to: D:\Media\Comics\StoryArcs
01-ноя-2023 02:22:33 - INFO :: MainThread : config.py:configure:1181 : Ignored Publishers: []
01-ноя-2023 02:22:33 - INFO :: MainThread : config.py:configure:1204 : [MASS_PUBLISHERS] Auto-add for weekly publishers set to: []
01-ноя-2023 02:22:33 - INFO :: MainThread : config.py:configure:1216 : [IGNORE_SEARCH_WORDS] Words to flag search result as invalid: ['.exe', '.iso', 'pdf-xpost', 'pdf', 'ebook']
01-ноя-2023 02:22:33 - INFO :: MainThread : config.py:configure:1228 : [PROBLEM_DATES] Problem dates loaded: ['2021-07-14 04:00:34']
01-ноя-2023 02:22:33 - INFO :: MainThread : config.py:configure:1242 : [COMICTAGGER] Version detected: 1.3.5
01-ноя-2023 02:22:33 - INFO :: MainThread : config.py:configure:1321 : Setting DDL Location set to : E:\DEV\Py\mylar3\cache
01-ноя-2023 02:22:33 - INFO :: MainThread : config.py:configure:1335 : [Search Tier Cutoff] Setting Tier-1 cutoff point to 14 days
01-ноя-2023 02:22:33 - INFO :: MainThread : __init__.py:initialize:257 : Checking to see if the database has all tables....
01-ноя-2023 02:22:33 - INFO :: MainThread : __init__.py:dbcheck:1555 : Ensuring DB integrity - Removing all Erroneous Comics (ie. named None)
01-ноя-2023 02:22:33 - INFO :: MainThread : __init__.py:dbcheck:1565 : Correcting Null entries that make the main page break on startup.
01-ноя-2023 02:22:33 - INFO :: MainThread : __init__.py:dbcheck:1576 : [<class 'int'>]oldconfig_version: 12
Error in sys.excepthook:
TypeError: RotatingLogger.handle_exception() missing 1 required positional argument: 'exc_traceback'

Original exception was:
Traceback (most recent call last):
  File "E:\DEV\Py\mylar3\Mylar.py", line 496, in <module>
    main()
  File "E:\DEV\Py\mylar3\Mylar.py", line 279, in main
    mylar.initialize(mylar.CONFIG_FILE)
  File "E:\DEV\Py\mylar3\mylar\__init__.py", line 264, in initialize
    cc.provider_sequence()
  File "E:\DEV\Py\mylar3\mylar\config.py", line 1705, in provider_sequence
    self.write_out_provider_searches()
  File "E:\DEV\Py\mylar3\mylar\config.py", line 1830, in write_out_provider_searches
    writeout = myDB.upsert("provider_searches", vals, ctrls)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\DEV\Py\mylar3\mylar\db.py", line 178, in upsert
    self.action(query, list(valueDict.values()) + list(keyDict.values()))
  File "E:\DEV\Py\mylar3\mylar\db.py", line 130, in action
    sqlResult = self.connection.execute(query, args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: UNIQUE constraint failed: provider_searches.id
 - OS: Windows11

**Comment by barbequesauce** [comment]
Can you generate a care package and attach it please?

**Comment by bulletproof2k** [comment]
> Can you generate a care package and attach it please?

[carepackage_v0.7.5.zip](https://github.com/mylar3/mylar3/files/13222031/carepackage_v0.7.5.zip)
[mylar.log](https://github.com/mylar3/mylar3/files/13222034/mylar.log)

**Comment by evilhero** [comment]
You'll want to follow this to solve things: https://github.com/mylar3/mylar3/wiki/Common-Errors---Problems#on-startup-i-get-an-error-about

It happens if you add nzbsu / dognzb as newznab entries when the built in options were enabled previously, or if you have duplicate providers entered as newznabs.

**Comment by bulletproof2k** [comment]
> You'll want to follow this to solve things:
> 
> https://github.com/mylar3/mylar3/wiki/Common-Errors---Problems#on-startup-i-get-an-error-about
> 
> It happens if you add nzbsu / dognzb as newznab entries when the built in options were enabled previously, or if you have duplicate providers entered as newznabs.

🤔👍
