### ISSUE TITLE
Doesn't download via DDL

### ISSUE THREAD

**Issue by DaveAlton** [mylar3/mylar3#1443]
Describe the bug
Automatic downloading stopped about a week or two ago. On GetComics, the "Download Now" button is missing for upscaled HD but the digital releases still have it. I tried emailing GetComics because I have a suspicion it's a problem with their site, but I didn't get any helpful info.

CarePackage
I have a care package. Please let me know where I can send it.

Environment (please complete the following information):

OS: Docker
Branch / commit: 0.7.5 master

**Comment by evilhero** [comment]
Please don't open multiple tickets regarding the same issue, all it does is put you lower in our queue when we're going thru the tickets. If you need immediate help, I suggest you hop on discord and talk there as you'll get a faster answer.

Without a carepackage, we won't be able to help much, especially when you're not indicating what specific series and issue you're trying to have mylar grab.

FYI, GC purposely does not put a download now option for their upscaled issues, but Mylar will still grab the digital ones. 

Again, hop on discord and discuss the issue on there, as there are more people available to help.
