### ISSUE TITLE
Annuals not being Meta Tagged

### ISSUE THREAD

**Issue by falo2k** [mylar3/mylar3#1444]
I've been retagging a bunch of series, and initiating a series metadata re-tag via the series page or the manage issues pages does not cause Annuals to have metadata tagged.  I'm not sure if this is also the case on import, but I do wonder why many of my annuals seem to have no tagging (except where I've manually initiated it at the issue level).

**Environment (please complete the following information):**
 - OS: Docker
 - Branch / commit:  LinuxServer.io image on nightly 47e54f48f5521e9794ba8cd2ccb1d96fdeb5ea96 (python3-dev)

**Comment by evilhero** [comment]
Can confirm, metatagging via the options on the series page and the manage comics page does not include annuals as part of the metatagging process.

Fixed locally, will be in python3-dev by tonight.

**Comment by falo2k** [comment]
What a turnaround!  Thanks @evilhero
