### ISSUE TITLE
Possibly a bug. But is anyone getting snatches from GetComics?

### ISSUE THREAD

**Issue by Dethkiller15** [mylar3/mylar3#1459]
**Describe the bug**
I am not seeing anything in my history to indicate that I am getting any comics from getcomics.

Don't get me wrong I manually download and throw comics into the watch folder all the time when I find them on getcomics and feel like moving toward completing my collection, but I just want to make sure I am not the only one not getting automatic collection of comics so that this can be brought to the attention of the devs.

**CarePackage**
As per usual the mylar.db is to large to upload at 130,044 KB, but here is everything but that. and I will post a mediafire link or equivalent if need
[carepackage_v0.7.6.zip](https://github.com/mylar3/mylar3/files/13573641/carepackage_v0.7.6.zip)

**Environment (please complete the following information):**
 - OS: Docker(Synology)
 - Branch / commit: Latest

**Additional information**
I did see that DDL was blocked and unblocked it before posting this. Just wanting to make sure I am not the only one that was having this issue.

**Comment by Dethkiller15** [comment]
I disabled DDL and restarted MyLar and will enable DDL reboot MyLar again in 2 days to see if it works after another 2 days. Lets hope that was the issue.

**Comment by Dethkiller15** [comment]
Sorry for the late update but I still have yet to get any snatches from GC. idk what is going on. If you need me to do so I can run a command in the container that is running it for more basic troubleshooting.

**Comment by Dethkiller15** [comment]
Idk if this will bump this to the top of the issues list but I still have this problem.

Again I am running this on docker.

something new I have tried:
I did attempt to install mylar3 in docker on my windows computer and tried to add a couple of series with the same exact settings at a completely diffrent internet connection.(same town and provider) the series added are some new ones. (as an example I added superior-spider-man/4050-154675/) got the exact same errors. here is the care package from that system.
[carepackage_v0.7.8.zip](https://github.com/mylar3/mylar3/files/14057977/carepackage_v0.7.8.zip)

**Comment by evilhero** [comment]
You have blackhole enabled and it's trying to send the ddl download to the blackhole directory. Just set it to use Sabnzbd instead (you don't have to have anything filled out), save the settings then try again.

This was actually a bug along time ago that seems to have resurfaced, but atm, changing the client from blackhole to sabnzbd should be enough for things to fire off normally thereafter.

**Comment by Dethkiller15** [comment]
snatches are now working

downloads as well.

thank you.
