### ISSUE TITLE
Can't postprocess one file from comic series.

### ISSUE THREAD

**Issue by mcsdodo** [mylar3/mylar3#1464]
**Describe the bug**
All files get downloaded with DDL and postprocessed. Only last one fails - can't figure out why. The warning is highlighted in logs below.

Docker log:

25-Dec-2023 18:33:17 - INFO :: mylar.gen_altnames.4326 : SEARCH-QUEUE : searchlist: [{'ComicName': 'Darth Vader', 'unaltered_ComicName': 'Darth Vader'}]
25-Dec-2023 18:33:17 - INFO :: mylar.search_init.534 : SEARCH-QUEUE : comicname searched for: Darth Vader
25-Dec-2023 18:33:17 - INFO :: mylar.NZB_SEARCH.882 : SEARCH-QUEUE : Shhh be very quiet...I'm looking for Darth Vader issue: 1 (2015) using DDL(GetComics).
25-Dec-2023 18:33:17 - INFO :: mylar.parse_search_result.374 : SEARCH-QUEUE : There are 6 results on page 1 (of 1)
25-Dec-2023 18:33:17 - INFO :: mylar._process_entry.974 : SEARCH-QUEUE : [nzbprov:DDL(GetComics)] provider_stat: {'type': 'DDL', 'lastrun': 1703529197.712946, 'active': True, 'hits': 99, 'id': 200}
25-Dec-2023 18:33:17 - INFO :: mylar.searcher.2903 : SEARCH-QUEUE : [nzbprov:DDL(GetComics)] provider_stat:{'type': 'DDL', 'lastrun': 1703529197.712946, 'active': True, 'hits': 99, 'id': 200}
25-Dec-2023 18:33:17 - INFO :: mylar.searcher.2936 : SEARCH-QUEUE : Found Darth Vader (2015) #1 using DDL(GetComics)
25-Dec-2023 18:33:18 - INFO :: mylar.parse_downloadresults.692 : SEARCH-QUEUE : Only one item discovered, changing queue length to accomodate: {'series': 'Darth Vader #1 Director’s Cut', 'site': 'Download Now', 'year': '2015', 'issues': None, 'size': ' 64 MB', 'link': 'https://light.getcomics.info/Comics%20Marvel/A%20-%20E/Darth%20Vader_/Darth%20Vader%20001%20Director%27s%20Cut/Darth%20Vader%20001%20Director%27s%20Cut%20%282015%29%20GetComics.INFO.zip'} [<class 'dict'>]
25-Dec-2023 18:33:18 - INFO :: mylar.searcher.3234 : SEARCH-QUEUE : Successfully snatched Darth Vader #1 Director’s Cut (2015) from DDL site. It is currently being queued to download in position 1
25-Dec-2023 18:33:18 - INFO :: mylar.nzblog.857 : SEARCH-QUEUE : setting the nzbid for this download grabbed by DDL(GetComics) in the nzblog to : 8659
25-Dec-2023 18:33:18 - INFO :: mylar.foundsearch.928 : SEARCH-QUEUE : [UPDATER] Updating status to snatched
25-Dec-2023 18:33:18 - INFO :: mylar.foundsearch.1035 : SEARCH-QUEUE : [UPDATER] Updated the status (Snatched) complete for Darth Vader Issue: 1
25-Dec-2023 18:33:18 - INFO :: mylar.search_init.539 : SEARCH-QUEUE : findit: {'status': True, 'provider': 'DDL(GetComics)', 'lastrun': 1703528955.3617203, 'info': {'nzbid': '8659', 'nzbname': 'Darth Vader #1 Director’s Cut (2015)', 'sent_to': 'is downloading it directly via DDL(GetComics)', 'SARC': None, 'alt_nzbname': None, 't_hash': None}}
25-Dec-2023 18:33:22 - INFO :: mylar.ddl_downloader.3225 : DDL-QUEUE : Now loading request from DDL queue: Darth Vader #1 Director’s Cut
25-Dec-2023 18:33:29 - INFO :: mylar.downloadit.928 : DDL-QUEUE : Zip file detected. Unzipping into new modified path location: /config/mylar/cache/Darth Vader 001 Director's Cut (2015) [__479258__]
25-Dec-2023 18:33:30 - INFO :: mylar.ddl_downloader.3253 : DDL-QUEUE : Darth Vader 001 Director's Cut (2015) [__479258__] successfully downloaded - now initiating post-processing for /config/mylar/cache/Darth Vader 001 Director's Cut (2015) [__479258__].
25-Dec-2023 18:33:32 - INFO :: mylar.postprocess_main.3295 : POST-PROCESS-QUEUE : Now loading from post-processing queue: {'nzb_name': "Darth Vader 001 Director's Cut (2015) [__479258__]", 'nzb_folder': "/config/mylar/cache/Darth Vader 001 Director's Cut (2015) [__479258__]", 'failed': False, 'issueid': None, 'comicid': '79990', 'apicall': True, 'ddl': True, 'download_info': {'provider': 'DDL', 'id': '8659'}}
25-Dec-2023 18:33:32 - INFO :: mylar.traverse_directories.1628 : Thread-13 (Process) : there are 1 files.
25-Dec-2023 18:33:32 - INFO :: mylar.Process.435 : Thread-13 (Process) : I have located 1 files that I should be able to post-process. Continuing...
25-Dec-2023 18:33:32 - INFO :: mylar.Process.751 : Thread-13 (Process) : Now checking: Darth Vader [79990]
25-Dec-2023 18:33:32 - WARNING :: mylar.Process.775 : Thread-13 (Process) : **Darth Vader [2015] is either Paused or in an Ended status with 100% completion. Ignoring for match.**

[carepackage_v0.7.6.zip](https://github.com/mylar3/mylar3/files/13767022/carepackage_v0.7.6.zip)

**Environment (please complete the following information):**
 - OS: Proxmox with Portainer on Alpine
 - Branch / commit: latest

**Additional information**
Add any other information about the problem here.

**Comment by evilhero** [comment]
If the series is paused, unpause it.

If the series is not paused, then it's 100% completed and it won't post-process anything against it unless it's not 100% complete. You would have to remove the issue from the directory, and then mark the issue as Skipped so it could post-process it (otherwise if you refresh/Recheck the series it will find the issue again if it's present int he directory still).

All that being said, the directors cut is a completely different volume /comicid from the darth vader series it's trying to find. So even if you were to mark it as Skipped, and it mistakingly downloaded it, it wouldn't post-process it because it wouldn't match up to the series being searched for.

**Comment by mcsdodo** [comment]
Thanks. Problem was,  that director's cut was toghether with other episodes. I did download manually and then re-check files and everything is green.
