### ISSUE TITLE
Docker install suddenly missing PIP requirements

### ISSUE THREAD

**Issue by NavyGuy81** [mylar3/mylar3#1474]
**Describe the bug**
I logged on to mylar to check that it was operating properly after replacing a failed router. I don't know if it is related but now on the settings page, Mylar indicates that per PIP requirements, Pillow 8 is not installed.

**CarePackage**
My database file made the care package too large to upload as a single file:
[mylar.log](https://github.com/mylar3/mylar3/files/13928480/mylar.log)
[MylarRunningEnvironment.txt](https://github.com/mylar3/mylar3/files/13928481/MylarRunningEnvironment.txt)
[clean_config.zip](https://github.com/mylar3/mylar3/files/13928482/clean_config.zip)
[mylar.zip](https://github.com/mylar3/mylar3/files/13928484/mylar.zip)
[carepackage_v0.7.7.zip](https://github.com/mylar3/mylar3/files/13928486/carepackage_v0.7.7.zip)

**Environment (please complete the following information):**
 - OS: Docker within Ubuntu 22.04.3
 - Branch / commit: master/0.7.7

**Additional information**
Add any other information about the problem here.
I had my router go bad on me. I had to replace it with an old router and spent a day with no internet and various ip address related issues so mylar was up and running without having it's previous address assigned at points, no access to the internet, no access to the comics directory. I don't know if any of those issues could have broken something.

**Comment by evilhero** [comment]
Yep we are already aware of this warning and it's been fixed in python3-dev (nightly in lsio).

It's just a display issue on the config page due to pillow lower-casing their name now. If you're on docker, rest assured that Pillow is still there, installed correctly and can be used by Mylar just fine.

**Comment by NavyGuy81** [comment]
Thanks for the info!
