### ISSUE TITLE
DDL source: ReadComicOnline

### ISSUE THREAD

**Issue by francispeixoto** [mylar3/mylar3#1489]
**Describe the request**
currently, the only source for DDL is GetComics, Is it possible to add Readcomiconline as a second DDL source? 

**How did you come up with the idea?**
but the Mihon app (https://github.com/mihonapp/mihon - Used to be known as Tachiyomi) has great results from its plugin to that source, especially for older back issues.

**Comment by evilhero** [comment]
Unfortunately, outside of the scope of this project - building out a web scraper specific to that particular site, having it search through all the links, downloading all the images to an issue, compressing it into a cbz, etc.

While it can be done, I have no interest in doing this as I've built out web scrapers in the past, and every single one of them (outside of GC) is no longer online - so the amount of effort vs the reward (which could be easily attained by using other sources than just DDL) isn't worth it based on my free time available.
