### ISSUE TITLE
Care Package Clean-Up

### ISSUE THREAD

**Issue by DrSeussFreak** [mylar3/mylar3#151]
**Describe the request**
When you run the carepackage option, it does not clean up the ~/logs directory

**How did you come up with the idea?**
having to manually clean-up the directory in questions

**Environment (please complete the following information):**
 - OS: Ubuntu 19.10
 - Branch / commit: Version: adc9bb5ecad33428fb36b74c53c1b4e9b76f939c (python3-dev)

**Additional information**
n/a

**Comment by evilhero** [comment]
What is being left being in the ~/logs directory exactly ? The only thing that should be in there...is ..well, logs. The carepackage zip should be created in your mylar cache location.

**Comment by DrSeussFreak** [comment]
before I click care package, the only contents of ~/logs are the logs, after clicking care package, it looks like

> drwxrwxrwx  2 mylar mylar     4096 Mar  2 15:11 .
> drwxrwxrwx 14 mylar mylar     4096 Mar  2 15:11 ..
> -rw-rw-rw-  1 mylar mylar 22262423 Mar  2 15:11 carepackage.zip
> -rwxrwxrwx  1 mylar mylar     8419 Mar  2 15:11 clean_config.ini
> -rwxrwxrwx  1 mylar mylar   745989 Mar  2 15:11 mylar.log
> -rw-rw-rw-  1 mylar mylar    12683 Mar  2 15:11 MylarRunningEnvironment.txt

cache is being used, I see recent files there, but not by care package

**Comment by evilhero** [comment]
Oh, well dat dem's a bug. Should be all under cache and/or removed after the zip is created ( I think )

**Comment by DrSeussFreak** [comment]
The only caveat is how would i download the zip of our is removed right away

**Comment by evilhero** [comment]
Lol no - I mean the temporary files that it uses to create the zip should all be removed. The actual zip would remain

**Comment by barbequesauce** [comment]
Should be fixed in #176.

**Comment by DrSeussFreak** [comment]
I just updated and tried to generate a carepackage, I am getting the following error

![Screen Shot 2020-03-09 at 12 35 46 PM](https://user-images.githubusercontent.com/175500/76241153-8a6bd200-6202-11ea-856f-37b65d2181f6.png)

**Comment by barbequesauce** [comment]
blah. #177 fixes that fix...

**Comment by DrSeussFreak** [comment]
it is now cleaning up the files, but I thought you wanted the carepackage.zip in ~/cache, it is still in ~/logs (not that it matters to me)
