### ISSUE TITLE
Adding a comic by ID causes error

### ISSUE THREAD

**Issue by falo2k** [mylar3/mylar3#1510]
**Describe the bug**
Adding a comic by comic ID directly in the search box results in the screenshotted error page.  Note that the comic is still added to mylar correctly in the background.

![image](https://github.com/mylar3/mylar3/assets/1392563/9aef7f4d-25c2-4d61-97b5-82d1e6d711cb)

**Environment (please complete the following information):**
 - OS: Docker (Unraid)
 - Branch / commit: 7fc9493e580ff4980112da85c4975630137f4403 (python3-dev)

Guessing this is related to the new status checks for comic IDs changing.

Note, carepackage has had mylar.db removed for sizing, but I can't see any errors in the log (add starts at 15-Feb-2024 18:02:06)

[carepackage_7fc9493e580ff4980112da85c4975630137f4403_(python3-dev).zip](https://github.com/mylar3/mylar3/files/14300720/carepackage_7fc9493e580ff4980112da85c4975630137f4403_.python3-dev.zip)

**Comment by evilhero** [comment]
Ahh crap, yeah I know where it's causing the problem.

Thanks for bringing it up, and I'll have the fix for it python3-dev later tonight.

**Comment by falo2k** [comment]
Doing some issue cleanup - this has been working consistently since the fixes.
