### ISSUE TITLE
Can't refresh multiple comics or mettatags inside one comic

### ISSUE THREAD

**Issue by tomtom602** [mylar3/mylar3#1524]
**Describe the bug**
When I whant to refresh multiple comics or refresh metatags from one comics, I got an error from comicVine that it is unreachable.
When I try to navigate there, I got an error 403 a few minutes later, I got my access back, but if I try again in mylar, then again I got locked out.
If I manually refresh metatags for each books and wainting a few seconds between each books, then it works without me getting locked out.
Is it possible than mylar refresh from comicVine are to intensive for it's API ?

in my case, the first 5 books are metatagged correctly, then I've got the 403 error.

I konw there is a maximum hit by minute in their API  is it taken into account ?

This is something new, I never had this problem until a few weeks ago, an I can't find a solution on my own.

Help me Evilhero. Your my only hope !

** DEBUG LOGS **
08-Mar-2024 07:24:25 - WARNING :: mylar.run.314 : Thread-49 (thread_that_meta) : [META-TAGGER][COMIC-TAGGER][UNKNOWN-ERROR-DURING-METATAGGING] 403 Client Error: Forbidden for url: https://comicvine.gamespot.com/api/issue/4000-880931?api_key=-REDACTED-&format=json

**Environment (please complete the following information):**
 - OS: Linux, in a docker container
 - Branch / commit: v0.7.8 (master)

**Comment by evilhero** [comment]
It's due to CV blocking the user_agent that mylar is using by default, and because it's a temp IP ban you also cannot browse their website during this.

If you follow the instructions [here] (https://forum.mylarcomics.com/viewtopic.php?p=12660#p12660) it will solve the problem most likely.

**Comment by miracle152005** [comment]
Having the same problem here. I changed the user agent, but it is still happening. Everytime a little more is happening (i.e. adding 3 series at the same time or having an import with metadata tagging) I get blocked out of comicvine.

**Comment by tomtom602** [comment]
That solved my problem, but not immediately!
I changed the agent and retry but the problem persisted.
I, then, waited for about an hour and since, the problem didn't occur!
So there may be some kind of cache on comicvine side that delay the resolution of the problem...

**Comment by Nebelherr23** [comment]
It's probably a temporary ban, because there's an arbitrary undocumented rule they are enforcing on us.
