### ISSUE TITLE
Mylar.py won't launch, says installed modules are missing

### ISSUE THREAD

**Issue by AtomicClown** [mylar3/mylar3#1531]
**Describe the bug**
(Apologies if this isn't properly formatted or executed somehow, I've never really submitted a bug report before!) 

I've updated my Mylar setup in Windows 10 this morning, and successfully installed the necessary requirements.txt packages, but Mylar.py is telling me that three of the installed modules are missing. 

The supposedly missing modules are _packaging-22.0_, _pycryptodome-3.19.0_, and _tenacity-8.2.3_. I've verified in File Explorer that these modules have been installed through Pip, and am including a screenshot showing a successful installation readout in CMD followed by a "MODULES UNAVAILABLE" message from Mylar.py.
![Screenshot_1](https://github.com/mylar3/mylar3/assets/43078569/1b08d096-147f-45c7-810c-bfea066f5bf9)
Any ideas on something I might be doing wrong on my end? I could totally be missing something but I have no clue what.

**Environment (please complete the following information):**
 - OS: Windows 10.
 - Branch / commit: mylar3/v0.8.0

**Additional information**
Version 7.8 had been working completely (Save a frequent loss of CV access for whatever reason.) I've deleted the entire folder and replaced it with v0.7.8 just to see if it still functioned, and it does; upon updating from the webUI, Mylar.py runs through the updating steps and then crashes, only opening long enough to read error messages when run in a separate CMD window.

**Comment by evilhero** [comment]
If you have more than one version of python on your system, calling just ``mylar.py`` would call the default python which may not be what the pip you used to install requirements.txt is. Try issuing a ``python Mylar.py -v`` (-v is verbose logging) and seeing if that does anything.

Even just ``python`` from the command line would indicate the version and everything. ``pip list`` would show the available versions installed for that version of python.

**Comment by AtomicClown** [comment]
Thank you for responding so quickly! It looks like I'm currently running Python 3.10.11, and pip 24.0 from the Python310 folder.

Fascinatingly (to me anyway), _'python Mylar.py -v'_ got Mylar running and seemingly functioning as it should. Not seeing any issues with CV or anything so far. 

Just running mylar.py on its own yields the same issue as before, only seems to work with that full command. Does that help from a diagnostic standpoint at all?

**Comment by evilhero** [comment]
Honestly not entirely sure of what's going on, but windows tends to have it's own special place in hell when it comes to python. 

Typically you can't just type in ``mylar.py`` in Windows as they're not linked to the executable and the python environment isn't loaded properly in guessing (same reason why you also can't double-click on the Mylar.py file in Explorer and have it work).

So I'm not sure there's anything we can do to fix this as it seems to be unrelated to mylar itself and more of an issue with how Windows handles Python being executed.

**Comment by AtomicClown** [comment]
Gotcha, I'll see what I can do to keep it stable on my end then. I appreciate your help very much!

**Comment by rebootsramblings** [comment]
I hope someone else finds this useful. I had exactly the same issue. I went to my mylar directory on windows 10, I held shift and right clicked, ran Powershell. I then reran "pip3 install -r requirements.txt" and after this Mylar opened successfully.
