### ISSUE TITLE
Error when trying to clear db

### ISSUE THREAD

**Issue by Fluff663** [mylar3/mylar3#1536]
**Describe the bug**
Error when trying to clear db

**CarePackage**
19-Mar-2024 13:06:43 - INFO    :: mylar.configure.1266 : MainThread : [DOCKER-AWARE] Docker installation detected.
19-Mar-2024 13:06:43 - INFO    :: mylar.configure.1338 : MainThread : Ignored Publishers: []
19-Mar-2024 13:06:43 - INFO    :: mylar.configure.1365 : MainThread : [MASS_PUBLISHERS] Auto-add for weekly publishers set to: []
19-Mar-2024 13:06:43 - INFO    :: mylar.configure.1389 : MainThread : [PROBLEM_DATES] Problem dates loaded: ['2021-07-14 04:00:34']
19-Mar-2024 13:06:43 - INFO    :: mylar.configure.1403 : MainThread : [COMICTAGGER] Version detected: 1.3.5
19-Mar-2024 13:06:43 - INFO    :: mylar.configure.1530 : MainThread : Setting DDL Location set to : /config/mylar/cache
19-Mar-2024 13:06:43 - INFO    :: mylar.configure.1574 : MainThread : [DDL PRIORITY ORDER] DDL will attempt to use the following 3rd party sites in this specific download order: ['mega', 'm>19-Mar-2024 13:06:43 - INFO    :: mylar.configure.1583 : MainThread : [Search Tier Cutoff] Setting Tier-1 cutoff point to 14 days
19-Mar-2024 13:06:43 - INFO    :: mylar.initialize.263 : MainThread : Checking to see if the database has all tables....
19-Mar-2024 13:06:43 - INFO    :: mylar.dbcheck.1585 : MainThread : Ensuring DB integrity - Removing all Erroneous Comics (ie. named None)
19-Mar-2024 13:06:43 - INFO    :: mylar.dbcheck.1595 : MainThread : Correcting Null entries that make the main page break on startup.
19-Mar-2024 13:06:43 - INFO    :: mylar.dbcheck.1606 : MainThread : [<class 'int'>]oldconfig_version: 14
19-Mar-2024 13:06:43 - INFO    :: mylar.check_failed_update.172 : MainThread : checked is None
19-Mar-2024 13:06:43 - INFO    :: mylar.initialize.373 : MainThread : [IMPRINT_LOADS] Loading Publisher imprints data from local file.
19-Mar-2024 13:06:44 - INFO    :: mylar.initialize.399 : MainThread : [IMPRINT_LOADS] Successfully loaded imprints for 6 publishers
19-Mar-2024 13:06:44 - INFO    :: mylar.initialize.401 : MainThread : Remapping the sorting to allow for new additions.
19-Mar-2024 13:06:44 - INFO    :: mylar.ComicSort.781 : MainThread : Sucessfully ordered 6 series in your watchlist.
19-Mar-2024 13:06:44 - INFO    :: mylar.SABtest.7473 : MainThread : APIKey provided is the FULL API Key which is the correct key.
19-Mar-2024 13:06:44 - INFO    :: mylar.SABtest.7474 : MainThread : Connection to SABnzbd tested sucessfully
19-Mar-2024 13:06:44 - WARNING :: mylar.sab_versioncheck.330 : MainThread : [SABNZBD-VERSION-TEST] Exception encountered trying to retrieve SABnzbd version: UNIQUE constraint failed: provid>19-Mar-2024 13:06:44 - INFO    :: mylar.initialize.411 : MainThread : [SAB-VERSION-CHECK] SABnzbd version detected as: 4.2.3
19-Mar-2024 13:06:44 - INFO    :: mylar.main.386 : MainThread : [CLEAR_PROVIDER_TABLE] forcing over-ride value from config.ini
19-Mar-2024 13:06:44 - INFO    :: mylar.getVersion.188 : MAIN : [DOCKER-AWARE] Docker installation detected.
19-Mar-2024 13:06:44 - INFO    :: mylar.getVersion.209 : MAIN : i:  (HEAD -> master, tag: v0.8.0, tag: v0,8.0)

19-Mar-2024 13:06:44 - INFO    :: mylar.getVersion.220 : MAIN : [LAST_RELEASE] Branch: master
19-Mar-2024 13:06:44 - INFO    :: mylar.getVersion.225 : MAIN : [LAST_RELEASE] Version: v0.8.0, v0,8.0
19-Mar-2024 13:06:44 - INFO    :: mylar.getVersion.209 : MAIN : i: ca4a3736865db0f11ed150b3768665e983c4118b

19-Mar-2024 13:06:44 - INFO    :: mylar.getVersion.231 : MAIN : [LAST_RELEASE] Commit: ca4a3736865db0f11ed150b3768665e983c4118b
19-Mar-2024 13:06:44 - INFO    :: mylar.getVersion.266 : MAIN : Branch detected & set to : master
19-Mar-2024 13:06:44 - INFO    :: mylar.versionload.469 : MAIN : Version information: master [ca4a3736865db0f11ed150b3768665e983c4118b]
19-Mar-2024 13:06:44 - INFO    :: mylar.initialize.72 : MAIN : [MAINTENANCE-MODE] Starting Mylar in maintenance mode on http://0.0.0.0:8090/fluff663/mylar/
19-Mar-2024 13:06:44 - INFO    :: mylar.main.460 : MAIN : [MAINTENANCE-MODE] Initializing maintenance mode
19-Mar-2024 13:06:44 - INFO    :: mylar.main.500 : MAIN : [MAINTENANCE-MODE] method indicated as fix clearprovidertable
19-Mar-2024 13:06:49 - ERROR   :: mylar.excepthook.315 : MAIN : Uncaught exception: Traceback (most recent call last):
  File "/app/mylar3/Mylar.py", line 595, in <module>
    main()
  File "/app/mylar3/Mylar.py", line 502, in main
    j = fs.clear_provider_table()
        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/mylar3/mylar/maintenance.py", line 235, in clear_provider_table
    self.dbmylar.execute("DROP TABLE provider_searches")
sqlite3.OperationalError: database is locked

**Environment (please complete the following information):**
 - OS: [Ubuntu]
 - Branch / commit: [Latest Docker]

**Additional information**
Running on seedhost.eu

**Comment by evilhero** [comment]
Database locked I think is due to the docker image not releasing the db first which can happen on a restart if it's writing something while it's being shutdown. 

I would try to stop the container entirely, make sure that the config.ini value (``clear_provider_table = True``) is there and then start it up.
