### ISSUE TITLE
Unable to work with jackett as search providers

### ISSUE THREAD

**Issue by Fmajor** [mylar3/mylar3#1544]
I try to setup jackett as search providers, but with no luck, here is how i do the setups

In Settings => Search providers tab, I check `Torrents` => `Enable Torznab`

Then I fill in `Torznab Host: http://172.17.0.1` # because i'am in docker
and `Torznab API: /jackett/api/v2.0/indexers/mikan/results/torznab/`

Here I have a big question: to use torznab API, I should setup the API KEY some where, or I do not expect the API call to work, so where should i put my API key in the torznab seetings?

image below: there is no API KEY seetings
![image](https://github.com/mylar3/mylar3/assets/1620897/cf434188-fc62-4564-912d-46484c9fab4e)

if i click the check button anyway, I get log from docker container
```
11-May-2024 10:59:29 - INFO :: mylar.torznab_test.4246 : CP Server Thread-7 : host: http://172.17.0.1
11-May-2024 10:59:29 - WARNING :: mylar.torznab_test.4256 : CP Server Thread-7 : [WARNING] Error attempting to test: no element found: line 1, column 0
11-May-2024 10:59:29 - INFO :: mylar.torznab_test.4261 : CP Server Thread-7 : Connected - Status code returned: 200
11-May-2024 10:59:29 - INFO :: mylar.testtorznab.8307 : CP Server Thread-7 : Successfully tested Ehentai [http://172.17.0.1] - valid api response received
```

It say no element found. And if i save the config and try to do some search in the top search area, I will get a blank page

How can I setup  jackett as search providers, and where should I setup my API KEY for a Torznab API?

configs:
```
docker image: lscr.io/linuxserver/mylar3:latest
docker image hash: 193c74b26cac
```

**Comment by Cducharme84** [comment]
Using Jackett is a very manual process, you'll need to setup your API call including key and desired endpoint, per their documentation accessing the endpoint looks similar to this `/api/v2.0/indexers/<aJackettIndexerName>/results/torznab/api?apikey=<yourJackettApiKey>&t=caps` 

As Jackett's a fairly advanced user implementation of the concepts of using torznab via creating your own API calls you may want to check out a more user-friendly implementation if you're not familiar with creating API calls to then point a program like Mylar to. Prowlarr uses a fork of Jackett for instance with a snazzy GUI.

Example yanked from the sample section here: https://github.com/Jackett/Jackett

**Comment by locke69321** [comment]
You also need to include the port after the ip, and it looks like you're using the docker network ip, which can change, and not the docker host system's network ip. Host should be `http://x.x.x.x:9117` for jackett.

**Comment by evilhero** [comment]
Host : the full url endpoint provided by jackett (``http://x.x.x.x:9117/api/v2.0/... etc``)
API: your api key

You're looking for manga. Mylar is not the program for you. 

I'm assuming you didn't bother to read our website which clearly says:
``If you're looking for a manga downloader or organizer, while it may work in some aspects, mylar is not nor will it ever be built to be used with manga.``

**Comment by Fmajor** [comment]
Thank you for your quick response.
So I suggest that you change `Torznab Host` to `Torznab API Path` and `Torznab API` to `Torznab API key`, which is more clearly.

And yes, I am looking for a manga organizer, I think I need to search for other program.
