### ISSUE TITLE
Allow `null` for `series.json`'s `total_issues`

### ISSUE THREAD

**Issue by luevano** [mylar3/mylar3#1545]
When a series is ongoing/still publishing, some metadata providers like Anilist and MyAnimeList don't provide a value for the `total_issues`. I guess because this value would change really often.

Komga currently uses MyLar3's `series.json` schema and it would help to allow `null`s for the field. Else it would mean that on each issue update the `series.json` needs to be rewritten/updated and the metadata refreshed. And there is not always an easy way to tell how many chapters there currently are.

Thanks in advance for the consideration.

**Comment by Cducharme84** [comment]
I suspect this will not ever get implemented, mylar is 100% intended for western comics and not manga. Each of the metadata providers are manga specific and per the introduction page for mylar's documentation.

`If you're looking for a manga downloader or organizer, while it may work in some aspects, mylar is not nor will it ever be built to be used with manga.`

With mylar's reliance on Comic Vine for metadata it's a minor miracle it's worked in any capacity for manga for you to have  found a need for this request.

**Comment by luevano** [comment]
I understand this, it's just a flexibility that could be added to the schema if it doesn't affect mylar at all. Komga "relies" and uses `series.json` as one of its standards for metadata, so that's why I'm making the request here. The `series.json` is only used for metadata and nothing else, as Komga also works with comics.

**Comment by Cducharme84** [comment]
I do think it'd be beneficial for manga users to ask FMD or a similar project to adopt a compatible schema and ask Komga/any clients to accept null in the total issue count position. Since the chapter by chapter data is often non-existent a series level single file approach would make your guys' lives a ton easier management wise but relying on something to create it for you unintended for manga I don't think is your best bet.

**Comment by luevano** [comment]
FMD?

Also, to be clear, I'm not using mylar to create the metadata nor intend it to do so. I'm only adhering to the schema, and Komga claims to do the same. I already asked Komga to accept nulls (or zeros for that matter), but they really don't want to make any changes (supposedly because the schema doesn't support it): `gotson//komga//issues//1491`.

So this is why I came here asking for flexibility on the schema. Let's see what @\evilhero thinks about it.

**Comment by luevano** [comment]
> That's so odd on their end, theirs is literally the only program I know of that uses the series.json so their unwavering rigidity definitely makes no sense. My apologies for the misunderstanding, I'm assuming EH's response will be a shrug though as it's really something that Komga should be implementing as this is only a "standard" insomuch as it's not used by any other programs at all.

Yeah I think you get what I was trying to accomplish, pretty reasonable I would think. I understand if EH will just discards this, I'm just trying to shoot my shot lol.

> Oh and FMD (freemangadownloader) is a common set of manga acquisition tools often considered comparable-ish to mylar for comics.

Got it, I'm familiar, I've tried it in the past. I use a fork of `mangal` that I'm maintaining for personal use.

I do control the creation of the `series.json` and I *could* just add the total issue count, but it's a bit of a hassle right now (definitely a lot more work than just allowing `null`s lol) and it would mean that I need to refresh the `series.json` on each issue that releases (and then there is the question if Komga will refresh its metadata with the newly added `series.json` right on a new issue update).

**Comment by Cducharme84** [comment]
Oh don't get me wrong, I think the shrugged shoulders will be his ascent for them to implement! I can't see it as breaking anything within mylar (which is what he generally would care the most about) and being just a simple schema revision.

It's just so odd they would even go that extra step as the only implementer, part of the appeal of being the first is leading the way in how implementation works.

**Comment by luevano** [comment]
@evilhero any thoughts?

Also, consider allowing extra values to "status" such as "hiatus", "cancelled"/"abandoned".
Thanks in advance.
