### ISSUE TITLE
CV Exception in fresh install

### ISSUE THREAD

**Issue by Grooovec** [mylar3/mylar3#1546]
**Describe the bug**
ComicVine api always throws an exeption. It is a fresh Docker install and the first comic i added will not refresh. i tried other IDs and they also will not refresh.

```
Uncaught exception: Traceback (most recent call last):
File "/app/mylar3/mylar/logger.py", line 337, in new_run
old_run(*args, **kwargs)
File "/usr/lib/python3.11/threading.py", line 982, in run
self._target(*self._args, **self._kwargs)
File "/app/mylar3/mylar/updater.py", line 53, in addvialist
dbUpdate([item['comicid']], calledfrom='refresh')
File "/app/mylar3/mylar/updater.py", line 463, in dbUpdate
chkstatus = mylar.importer.addComictoDB(ComicID, mismatch, annload=annload, csyear=csyear)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/mylar3/mylar/importer.py", line 148, in addComictoDB
comic = cv.getComic(comicid, 'comic', series=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/mylar3/mylar/cv.py", line 167, in getComic
return GetComicInfo(comicid, dom, series=series)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/mylar3/mylar/cv.py", line 357, in GetComicInfo
comic['FirstIssueID'] = dom.getElementsByTagName('id')[0].firstChild.wholeText
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

**CarePackage**
[carepackage_v0.8.0.zip](https://github.com/mylar3/mylar3/files/15336801/carepackage_v0.8.0.zip)

**Environment (please complete the following information):**
 - OS: Docker on Fedora Linux
 - Branch / commit: 0.8.0 release in linuxserver.io docker

**Comment by evilhero** [comment]
```15-May-2024 21:28:14 - WARNING :: mylar.configure.1290 : CP Server Thread-11 : Comicvine API key starts with a None, working around for now, please fix```

I'd say the CV api key you entered is incorrect based on the error message you pasted and the above line from your logs.
