### ISSUE TITLE
Scan Comic Library settings do not save

### ISSUE THREAD

**Issue by ErenPhayte** [mylar3/mylar3#155]
Saving the comic library settings doesn't actually save. When you restart these fields are clear. Current workaround is to manually edit the .ini file and manually modify:

add_comics = False
comic_dir = None
imp_move = False
imp_paths = False
imp_rename = False
imp_metadata = False
imp_seriesfolders = True

**Comment by barbequesauce** [comment]
ErenPhayte can you confirm the fix please? If it works, close the issue?

**Comment by ErenPhayte** [comment]
works perfectly thanks!
