### ISSUE TITLE
Email for security issues?

### ISSUE THREAD

**Issue by 4rdr** [mylar3/mylar3#1553]
Is there an email address for security issues?

**Comment by evilhero** [comment]
security@mylarcomics.com will work for initial concerns. 

The email itself will be disabled to prevent spamming after 48hrs tho.

**Comment by evilhero** [comment]
I also just enabled vulnerability reporting for the repo, so you can privately report an issue directly via github now as well.

**Comment by 4rdr** [comment]
Submitted via vulnerability reporting.
