### ISSUE TITLE
500 Internal Server Error when trying to switch to a certain series from the watch list.

### ISSUE THREAD

**Issue by bulletproof2k** [mylar3/mylar3#1558]
When I try to switch to this series, I get the following error:
https://comicvine.gamespot.com/spawn-kills-every-spawn/4050-159031/

`500 Internal Server Error
The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "C:\Users\victo\AppData\Roaming\Python\Python311\site-packages\cherrypy\_cprequest.py", line 638, in respond
    self._do_respond(path_info)
  File "C:\Users\victo\AppData\Roaming\Python\Python311\site-packages\cherrypy\_cprequest.py", line 697, in _do_respond
    response.body = self.handler()
                    ^^^^^^^^^^^^^^
  File "C:\Users\victo\AppData\Roaming\Python\Python311\site-packages\cherrypy\lib\encoding.py", line 223, in __call__
    self.body = self.oldhandler(*args, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\victo\AppData\Roaming\Python\Python311\site-packages\cherrypy\_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\DEV\Py\mylar3\mylar\webserve.py", line 535, in comicDetails
    comic['ComicYear'] = comic['Corrected_SeriesYear']
    ~~~~~^^^^^^^^^^^^^
TypeError: 'sqlite3.Row' object does not support item assignment
Powered by [CherryPy 18.8.0](http://www.cherrypy.dev/)`

**Comment by bulletproof2k** [comment]
[Uploading carepackage_v0.8.0.zip…]()

**Comment by bulletproof2k** [comment]
[carepackage_v0.8.0, v0,8.0.zip](https://github.com/user-attachments/files/16380520/carepackage_v0.8.0.v0.8.0.zip)
[mylar.log](https://github.com/user-attachments/files/16380522/mylar.log)

**Comment by evilhero** [comment]
Have you tried removing the series and reading it within mylar? It looks like the year value that it was assigned when it was added initially was invalid for some reason... 

If you go to the Manage Comics page, you can delete the series from there and then go thru the normal way of adding it back.

**Comment by bulletproof2k** [comment]
The last option solved my problem, thanks.
I will close the issue. Will there be an update soon?
