### ISSUE TITLE
Enrich/Improve Importing with Comic Rack XML instead of Filename parsing

### ISSUE THREAD

**Issue by ErenPhayte** [mylar3/mylar3#156]
Not sure if this is done, but it would be great if instead of using various parsing techniques on the filename to determine how it should be imported, perhaps use the XML file inside the CBZ? This will have a wealth of information and if people have used ComicVine to already add metadata to the file as I have, it may make the imported data more accurate.

**Comment by ErenPhayte** [comment]
I am being silly - I assume "Use existing Metadata" is what that is for

**Comment by evilhero** [comment]
Yes - use Existing Metadata is for this purpose. It will however only scan files that have a cbz extension. A coming update will allow for scanning within cbr's as well as some other import improvements that we have in the pipe (such as being able to determine the series in a cbz/cbr by a analyzing a random image within).
