### ISSUE TITLE
Mylar 0.80 install issue

### ISSUE THREAD

**Issue by Dude77777** [mylar3/mylar3#1575]
Dear Evilhero & team
**Describe the bug**
After some time away from mylar I tried today to update to 0.80 (and based on experience made a backup of the whole mylar folder).
I followed your instruction on https://mylarcomics.com/docs/installation/source for that. First I tried the recommend git route (I might not be technical enough for this):
A:\DL\Z mylar3>git clone -b master git@github.com:mylar3/mylar3.git
Cloning into 'mylar3'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
Not sure exactly what that means, I dont use Git for anything besides updating Mylar.

Then I tried source installation, which seemed to go through but then Mylar is not starting anymore:
A:\DL\Z mylar3>python Mylar.py
       __                   _           _____   __
     _| _|  _ __ ___  _   _| | __ _ _ _|___ /  |_ |_
    (_) |  | '_ ` _ \| | | | |/ _` | '__||_ \   | (_)
 _ _ _| |  | | | | | | |_| | | (_| | |  ___) |  | |_ _ _
(_|_|_) |  |_| |_| |_|\__, |_|\__,_|_| |____/   | (_|_|_)
      |__|            |___/                    |__|
------------------------------------------------------------
log language set to en_GB
Initializing startup sequence....
21-Nov-2024 18:16:49 - INFO :: mylar.configure.1338 : MainThread : Ignored Publishers: []
21-Nov-2024 18:16:49 - INFO :: mylar.configure.1365 : MainThread : [MASS_PUBLISHERS] Auto-add for weekly publishers set to: []
21-Nov-2024 18:16:49 - INFO :: mylar.configure.1389 : MainThread : [PROBLEM_DATES] Problem dates loaded: ['2021-07-14 04:00:34']
21-Nov-2024 18:16:49 - INFO :: mylar.configure.1403 : MainThread : [COMICTAGGER] Version detected: 1.3.5
21-Nov-2024 18:16:49 - INFO :: mylar.configure.1499 : MainThread : [CV_USER_AGENT] Agent already identical in comictagger session.
21-Nov-2024 18:16:49 - INFO :: mylar.configure.1530 : MainThread : Setting DDL Location set to : A:\DL\Z mylar3\cache
21-Nov-2024 18:16:49 - INFO :: mylar.configure.1574 : MainThread : [DDL PRIORITY ORDER] DDL will attempt to use the following 3rd party sites in this specific download order: ['mega', 'mediafire', 'pixeldrain', 'main']
21-Nov-2024 18:16:49 - INFO :: mylar.configure.1583 : MainThread : [Search Tier Cutoff] Setting Tier-1 cutoff point to 14 days
21-Nov-2024 18:16:49 - INFO :: mylar.initialize.263 : MainThread : Checking to see if the database has all tables....
21-Nov-2024 18:16:49 - INFO :: mylar.dbcheck.1585 : MainThread : Ensuring DB integrity - Removing all Erroneous Comics (ie. named None)
21-Nov-2024 18:16:49 - INFO :: mylar.dbcheck.1595 : MainThread : Correcting Null entries that make the main page break on startup.
21-Nov-2024 18:16:49 - INFO :: mylar.dbcheck.1606 : MainThread : [<class 'int'>]oldconfig_version: 14
21-Nov-2024 18:16:49 - ERROR :: mylar.excepthook.315 : MainThread : Uncaught exception: Traceback (most recent call last):
  File "A:\DL\Z mylar3\Mylar.py", line 595, in <module>
    main()
  File "A:\DL\Z mylar3\Mylar.py", line 378, in main
    mylar.initialize(mylar.CONFIG_FILE)
  File "A:\DL\Z mylar3\mylar\__init__.py", line 270, in initialize
    cc.provider_sequence()
  File "A:\DL\Z mylar3\mylar\config.py", line 1945, in provider_sequence
    self.write_out_provider_searches()
  File "A:\DL\Z mylar3\mylar\config.py", line 2063, in write_out_provider_searches
    writeout = myDB.upsert("provider_searches", vals, ctrls)
  File "A:\DL\Z mylar3\mylar\db.py", line 178, in upsert
    self.action(query, list(valueDict.values()) + list(keyDict.values()))
  File "A:\DL\Z mylar3\mylar\db.py", line 130, in action
    sqlResult = self.connection.execute(query, args)
sqlite3.IntegrityError: UNIQUE constraint failed: provider_searches.id

Traceback (most recent call last):
  File "A:\DL\Z mylar3\Mylar.py", line 595, in <module>
    main()
  File "A:\DL\Z mylar3\Mylar.py", line 378, in main
    mylar.initialize(mylar.CONFIG_FILE)
  File "A:\DL\Z mylar3\mylar\__init__.py", line 270, in initialize
    cc.provider_sequence()
  File "A:\DL\Z mylar3\mylar\config.py", line 1945, in provider_sequence
    self.write_out_provider_searches()
  File "A:\DL\Z mylar3\mylar\config.py", line 2063, in write_out_provider_searches
    writeout = myDB.upsert("provider_searches", vals, ctrls)
  File "A:\DL\Z mylar3\mylar\db.py", line 178, in upsert
    self.action(query, list(valueDict.values()) + list(keyDict.values()))
  File "A:\DL\Z mylar3\mylar\db.py", line 130, in action
    sqlResult = self.connection.execute(query, args)
sqlite3.IntegrityError: UNIQUE constraint failed: provider_searches.id
 
**CarePackage**
I am sorry but I cant even get into the UI anymore.

**Environment (please complete the following information):**
 - OS: Win 11
 - Branch / commit: Master - tried to install 0.80

**Additional information**
I am a long-time but non technical user...

**Comment by evilhero** [comment]
For the source install, this line is incorrect :

```A:\DL\Z mylar3>git clone -b master git@github.com:mylar3/mylar3.git```

You're supposed to replace git@github.com with your github username (or the email you have assigned to github). You may be able to omit that part entirely depending on how your system is setup, but if not, you need to specify the github info as per github's instructions for cloning a repository.

The sql providers error you mentioned can be fixed by following the instructions [https://github.com/mylar3/mylar3/wiki/Common-Errors---Problems#on-startup-i-get-an-error-about](here).

It's recommended that you use github instead of source it possible as updates are then more streamlined by github.
