### ISSUE TITLE
Error adding from Pull List

### ISSUE THREAD

**Issue by raedwa01** [mylar3/mylar3#162]
[carepackage.zip](https://github.com/mylar3/mylar3/files/4284855/carepackage.zip)
I added items from the pull list.  They turn red to show wanted, but when I go to manage the comics, it shows Comic ID: 111428 (None) and no additional info.

**Environment (please complete the following information):**
 - OS: docker/linux
 - Branch / commit: Mylar3/master

**Comment by evilhero** [comment]
Your Comic Location path doesn't exist - Mylar needs to know where all of your series will reside on your system. You can either change it in the GUI, or with Mylar not running, edit the config.ini and change ```destination_dir = None``` to ```destination_dir = /wherever/your/comics/are```

As per the readme on the main github page:

```Ensure Comic Location is specified in the configuration (Configuration --> Web Interface --> Comic Location).```
```Mylar auto-creates the Comic Series directories under the Comic Location. The directory is displayed on the Comic Detail page).```
```If you do not want directories to be created until there are issues present, set create_folders = False in the config.ini.```

This will also fix #161

**Comment by barbequesauce** [comment]
Please reopen when you have further updates.
