### ISSUE TITLE
Cannot rescan directory

### ISSUE THREAD

**Issue by DrSeussFreak** [mylar3/mylar3#165]
**Describe the bug**
I have moved files into the appropriate directory, which Mylar created.  I hit rescan, and it throws a permission error.

**CarePackage**
(removed)

**Environment (please complete the following information):**
 - OS: Ubuntu 19.10
 - Branch / commit: Version: d066c1135f4cd1bbc7fc47dd28c1955806a1e04d (python3-dev)

**Additional information**
n/a

**Comment by barbequesauce** [comment]
`04-Mar-2020 12:18:17 - ERROR   :: mylar.setperms.1780 : CP Server Thread-11 : [ERROR @ path: /media/comics/Soleil/Orcs & Goblins [2017]] [Errno 1] Operation not permitted: '/media/comics/Soleil/Orcs & Goblins [2017]/Orcs & Goblins - 2017 - 1.cbz'. Exiting...`

That is a permissions error being thrown by the OS, it's not a Mylar thing. Check permissions, any filesystem ACLs, make sure the directory owner is the same as mylar's runtime user, the mylar runtime user is in the right group... 

Looking at the rest of the carepackage data I don't see any indication of docker, Syno, or any odd packaging (although the git status response is odd), so I really have no other advice for you...

**Comment by DrSeussFreak** [comment]
I run this on an Ubuntu VM

<img width="516" alt="Screen Shot 2020-03-07 at 8 26 39 AM" src="https://user-images.githubusercontent.com/175500/76145235-6e72ff80-604d-11ea-9a0b-554c7f368e5b.png">

There is no permissions issue, as other  files are being imported correctly with the same permissions, at the same time,  just not these files.  No matter if I put them in the directory manually or if they are in the torrent black hole.

**Comment by barbequesauce** [comment]
What are you using to snatch them? Is the torrent client / NZB client running under the same user and group?

In general, using "nobody" i[s bad practice](https://wiki.ubuntu.com/nobody)...you should set up a runtime user...

**Comment by evilhero** [comment]
Or just try it with enforce permissions off and see if that does anything.

**Comment by DrSeussFreak** [comment]
The mount points are on a NAS, and I use multiple systems for end-to-end management of my environment.  nobody is a simple way to manage permissions without needed to setup matching users across each of them, ensuring they all have the same ID's.

I disabled enforce permissions, no luck.

In the actual name of this series, there are special characters (L'apogée des dragons), granted mylar set it up 'Lapogee des dragons', could this be related?

[carepackage.zip](https://github.com/mylar3/mylar3/files/4301955/carepackage.zip)

**Comment by DrSeussFreak** [comment]
I just read that wiki, and I am using nobody for NFS shares :)

**Comment by evilhero** [comment]
Just letting you know - found something in the carepackages so I removed them and am patching the latest python3-dev.

Secondly, you have your git values wrong in your ini - it should be:
```git_user = mylar3```
```git_branch = python3-dev```
This is what tells Mylar where to check for updates and such, as well as for displaying purposes in the GUI. _You'll want to make sure you're current before you submit another carepackage file._

Are the NFS mounts being mounted with enough permissions for the given mylar user? You can force certain permissions on mounting which would affect items when trying to move/delete between the filesystems. This has come up in the past, and I believe most of the permissions-type of issues (that initially were thought not to be permissions by the users) came down to commands that they were use to mount the NFS mounts. 

The error in question is due to the setperms module - did you turn off Enforce Permissions (and save the config) prior to doing the last carepackage?

**Comment by DrSeussFreak** [comment]
Thanks, I fixed the git settings.

There has never been a problem with permissons before, and sonarr, radarr and lidarr all run on the same VM as mylar.  This is the only series I am having problems with.

I had saved the config prior to rescanning, and then I re-enabled it, as I had also tried renaming the files to include the special characters in the actual series name.

**Comment by evilhero** [comment]
The only other thing I can think of atm is a special character restriction on the NFS mounts. Are you using NFSv3 or NFSv4  ? Apparently NFSv4 requires that all filenames are UTF-8 encoded, but the same restriction wasn't there for NFSv3 - so if the filenames existed prior to any update to NFSv4, they would be in a different encoding and throw an error.

Within Mylar, on the first tab in the configuration, what is your encoding set to ? That might have some aspect to all of this (or might be totally off, I haven't a clue right now what's going on)

Also, the Sonarr, Radarr, and Lidarr are all based on mono. Mylar is python-based. They have zero similarities aside from being a download/organizational tool. They access network-related shares differently due to their different code-base, so saying that it works for one but not the others isn't really indicative of not being a share-related problem, it all depends on what the code being used to access the shares uses.

**Comment by DrSeussFreak** [comment]
I am using NFSv4 and my encoding is set to "Language : en_US.UTF-8"

I only mentioned the other apps as reference that the NFS shares work without issue.  I understand there are different methods for accessing them, but at the end of the day, so long as they are accessible to the OS, the apps should be able to access them as well.

As for special characters, mylar does not have any in the title of the series, I only looked at that as a possibility.  By within the series, the special characters were removes from the directory title.

**Comment by evilhero** [comment]
Have you tried restarting Mylar? The setperms module being referenced throughout your logs is only accessed when the Enforce Permissions is enabled. So I'm trying to figure out why it's being tirggered when it's not even enabled, and I can't even find one instance where the setperms is being called without first testing if that option is enabled.

**Comment by DrSeussFreak** [comment]
I just restarted after fixing the git settings @barbequesauce mentioned, but if you check https://github.com/mylar3/mylar3/issues/170 I can no longer open a series

**Comment by DrSeussFreak** [comment]
Here is a fresh carepackage with enforce permissions disabled

[carepackage.zip](https://github.com/mylar3/mylar3/files/4302150/carepackage.zip)

**Comment by evilhero** [comment]
Sorry just realized, we're missing the debug information - this is all INFO level stuff ( I was wondering why some lines weren't being referenced...I need another coffee I guess). You have to set it to debug and then perform the required action so it logs it in debug mode, otherwise it'll just log it in INFO.

**Comment by DrSeussFreak** [comment]
I just updated to the latest commit (0762d2bd91ac9aa7040405ec866b77e9760e00cc)

 which each update I run I need to manually run `git reset --hard` and then manually run `git pull` as I keep running into errors like 

> Updating 38b5364..0762d2b
> error: Your local changes to the following files would be overwritten by merge:
>         mylar/carepackage.py
> Please commit your changes or stash them before you merge.
> Aborting

enabled debug mode, and here is the carepackage (with enforcing permissions off)

[carepackage.zip](https://github.com/mylar3/mylar3/files/4302240/carepackage.zip)

**Comment by DrSeussFreak** [comment]
ok, I am an idiot, but I solved the problem.

I was playing earlier with the special characters in the name, but since the directory mylar created by default had none, I assumed this was fine.  

<img width="847" alt="Screen Shot 2020-03-07 at 11 39 21 AM" src="https://user-images.githubusercontent.com/175500/76148079-64aac580-6068-11ea-8f8c-3c59cc60b4b0.png">

So I just edited the alternate search names field, and now it is working.

<img width="970" alt="Screen Shot 2020-03-07 at 11 40 48 AM" src="https://user-images.githubusercontent.com/175500/76148096-8e63ec80-6068-11ea-925c-ca24c57eb5d9.png">

The confusion for me, is that there were no special characters in the directory name, but it kept looking for them in the file names.

<img width="552" alt="Screen Shot 2020-03-07 at 11 41 42 AM" src="https://user-images.githubusercontent.com/175500/76148114-b5bab980-6068-11ea-8713-c8f3ae9de84d.png">

**Comment by DrSeussFreak** [comment]
Mylar added the é, I did not

**Comment by evilhero** [comment]
By default the ini value ```unicode_filename``` is set to True - which means that it will try to enforce the filename as per the series title. If you don't want it to retain the special characters, then you just need to set the ```unicode_filename = False``` and it will remove any extra characters as best it can (sometimes it might not be a 100% reliable substitution based on the encoding).

Mylar should always perform a 'safe' character check with directories - so it will remove any special characters normally ( I think that's the way it was done, I honestly can't recall atm).

What's weird is the Alternate Search Names are only used for searching purposes, and for filechecking - so when it goes to compare names during parsing, it knows all the permutations. It does automatically remove the special characters tho as best it can, but maybe in this case it wasn't.

**Comment by DrSeussFreak** [comment]
I don't care if mylar retains the special characters or not, I guess the confusion for me is that the directory did not have the special characters, and if I have a file that won't be found with the original name, I generally change the filename to match the directory name.  In this case, it did not work.

The original files were in their original French, as they are scanlation files, so no English comicvine entry exists.  Having that 1 special character needed in the file, but not the directory is what through me off.

**Comment by DrSeussFreak** [comment]
I do not have a unicode_filename entry in my config.ini, should I add one?

**Comment by evilhero** [comment]
No don't add it if it didn't create it. I might have added it on my local repo while working on the ```unicode_issuenumber```, but then just junked it so it's not actually being used anywhere anymore (it might be on the py2 repo, but again I have dozens of changes not committed that were all in a WIP so it's hard to gauge exactly where that one came from).

**Comment by DrSeussFreak** [comment]
my config.ini is the py2 version, just copied over (along with the mylar.db and cache).  I have edited the config as needed to match the py3 release.

On a side note,  which each update I run I need to manually run `git reset --hard` and then manually run `git pull` as I keep running into errors like 

> Updating 38b5364..0762d2b
> error: Your local changes to the following files would be overwritten by merge:
>         mylar/carepackage.py
> Please commit your changes or stash them before you merge.
> Aborting

Any ideas?

I ran into this with the py2 release a long time ago, but not in a while.

**Comment by evilhero** [comment]
do a ```git status |more``` and see what branch you're currently on. I'm guessing you're probably on the master branch or something according to git, but you're updating against the dev branch (or vice versa)

**Comment by DrSeussFreak** [comment]
> On branch python3-dev
> Your branch is behind 'origin/python3-dev' by 2 commits, and can be fast-forwarded.
>   (use "git pull" to update your local branch)
> 
> Changes not staged for commit:
>   (use "git add <file>..." to update what will be committed)
>   (use "git checkout -- <file>..." to discard changes in working directory)

**Comment by DrSeussFreak** [comment]
> Updating 0762d2b..a9cfd05
> error: Your local changes to the following files would be overwritten by merge:
>         mylar/importer.py
> Please commit your changes or stash them before you merge.
> Aborting

**Comment by barbequesauce** [comment]
Those messages are telling you there's edits to importer.py that git doesn't recognize - that's why evilhero asked you to delete it and reclone...

**Comment by DrSeussFreak** [comment]
I missed that part of his message, doing so now.

**Comment by DrSeussFreak** [comment]
re-cloned, will see if the issue persists, I'll close this out though
