### ISSUE TITLE
Issue Details Icon missing in Annuals

### ISSUE THREAD

**Issue by kanine** [mylar3/mylar3#166]
With _Enable Series-Annual Integration_ selected, the issue status icon is missing.

![image](https://user-images.githubusercontent.com/1894006/76141183-dd843e80-60b5-11ea-8550-7fc8aaa51c2c.png)

It's looking for interfaces/default/images/issueinfo.png but that folder only contains _blue, _grey and _orange pngs.

Windows 10 64 Bit, Python 3.7.6
Version: 5eb04975a2faabce789b804d5a3a419cbd6246b3 (python3-dev)

**Comment by barbequesauce** [comment]
Give that a try...

**Comment by kanine** [comment]
All good now, thanks!
