### ISSUE TITLE
Mako Runtime Error (When opening a series)

### ISSUE THREAD

**Issue by DrSeussFreak** [mylar3/mylar3#170]
**Describe the bug**
As soon as I click on a series, I receive
<img width="1643" alt="Screen Shot 2020-03-07 at 10 10 32 AM" src="https://user-images.githubusercontent.com/175500/76146827-e516f980-605b-11ea-90f0-404235f0f67b.png">

**CarePackage**
I cannot create a care package, when I try, I received
<img width="804" alt="Screen Shot 2020-03-07 at 10 11 57 AM" src="https://user-images.githubusercontent.com/175500/76146854-18598880-605c-11ea-9618-76fe023b582c.png">

I am also not seeing any events in the logs

**Environment (please complete the following information):**
 - OS: Ubuntu 19.10
 - Branch / commit: Version: a4de2472b2efde3fd94eada3693e0e7154e86b7b (python3-dev)

**Additional information**
Everything was fine prior to updating to the latest commits

**Comment by evilhero** [comment]
Forgot the typo - should be fixed in #171

**Comment by DrSeussFreak** [comment]
Confirming the carepackage fix, I'll keep an eye out for the other fix

**Comment by evilhero** [comment]
Other fix is in python3-dev now. Series detail page should be displaying fine again

**Comment by DrSeussFreak** [comment]
Confirmed
