### ISSUE TITLE
Error installing on Windows - Python 3.7-32

### ISSUE THREAD

**Issue by Budlyte** [mylar3/mylar3#181]
**Describe the bug**
Trying to install the requirements on Windows.

Error while unpacking cffi-0.1.0.a5.tar.gz
[New Text Document.txt](https://github.com/mylar3/mylar3/files/4327329/New.Text.Document.txt)

**Environment (please complete the following information):**
 - OS: Windows 7
 - Branch / commit: master

It installed about 20 other packages before breaking on this one.

**Comment by evilhero** [comment]
It says it can't find a python greater than 3.4... What version of python are you running? If you go to a command prompt and type in ```python -V``` what does it spit back?

Also how are you installing the requirements - ```pip``` or ```pip3```? On some systems where more than one version of python exists, the version of pip that needs to run to install python3 dependencies is pip3. If you have more than one version of python3, then the pip command changes as well.

**Comment by ArathoN** [comment]
On windoows the unrar-cffi package is currently working only up to python 3.7.6.
You can update the package for the latest python version but you need to build it and it requires some modules from visual studio. I tried this but it didn't work so I decided to downgrade my python version.
We need to wait for the developer on unrar-cffi to build it for python 3.8.x

P.S. This solution was found here https://github.com/mylar3/mylar3/issues/75

**Comment by barbequesauce** [comment]
Good stuff @ArathoN thanks.

@Budlyte can you take a look and see if that helps please?

**Comment by Budlyte** [comment]
I had 32-bit Python 3.7.6 installed.  I uninstalled and installed the 64-bit and it now works.

Just for clarity's sake on the readme, the command for installing on windows, at least for me, is `py -m pip install requirements.txt`

**Comment by barbequesauce** [comment]
Thanks for that - I'll add it now.
