### ISSUE TITLE
Having 'Digital' be additional force booktype option for specific series via the series detail page

### ISSUE THREAD

**Issue by evilhero** [mylar3/mylar3#183]
As per @benbeyond from mylar2's issue#[2414](https://github.com/evilhero/mylar/issues/2414):

I have 2 series that Mylar has marked the booktype as "Digital". They are Destiny, NY and Prison Witch. Issues are available on 32p but Mylar will not download them because the 32p issues are marked as "Issue" and not "Digital"...
```2020-02-20 14:35:04 | DEBUG | Booktypes do not match. Looking for Digital, this is a issue. Ignoring this result.```

It would be nice to be able to tell Mylar to ignore this booktype when searching and finding issues.

Also, what is an example of a series that has a "Digital" booktype on 32p?
----
For both of these series, there is no "printed" series to be found on CV, only "Digital". But the issues available on 32p are the exact same as what is shown on CV (based off of cover art, release date, and issues number.)
I understand that this might be an anomaly for the specific series that I am looking for, and that other digital series might not line up like that.

@evilhero: ```If you added the correct edition but it's being flagged wrong, you can force the edition to Print via the Edit Settings tab on that particular series detail page.```

The setting quoted above is exactly what I am asking for, but I can't find it on the Edit Settings tab on these series... There is one to "Forcibly Mark series as TPB/GN", but the tooltip doesn't say anything about booktype or digital, so I didn't think that was it.

@evilhero: ```Also, if you're using Auth mode you can set the 32P ID on the Edit Settings tab in order to force Mylar to search only against that specific series ID.```

I also did this for both series, but the booktype seems to override or ignore the 32p ID.

**Comment by SenorSmartyPants** [comment]
I tried this one Swamp Thing: New Roots, a digital series.  I checked 'Accept all booktype search matches' . Mylar found the issues like a champ.

Thanks.
