### ISSUE TITLE
Installing requirements.txt fails on Server 2019

### ISSUE THREAD

**Issue by Obscurax** [mylar3/mylar3#215]
**Describe the bug**
Running "py -m pip install requirements.txt" from the Mylar3 root directory fails.

`py -m pip install requirements.txt
ERROR: Could not find a version that satisfies the requirement requirements.txt (from versions: none)
ERROR: No matching distribution found for requirements.txt`

**Environment (please complete the following information):**
 - OS: Server 2019
 - Python: 3.7.6 x64
 - Branch / commit: https://github.com/mylar3/mylar3/commit/9a041326e4c2af60f0ec8426a59a5eee75bc025a

**Additional information**
Add any other information about the problem here.

**Comment by barbequesauce** [comment]
should be `py -m pip install **-r** requirements.txt`

**Comment by Obscurax** [comment]
Welll, that was dumb of me. This can be locked.
