### ISSUE TITLE
help 

### ISSUE THREAD

**Issue by binyaminyblatt** [mylar3/mylar3#218]
**Describe the bug**
wont start
**CarePackage**
On the config page, there is a button labelled "CarePackage". Pressing this button will download a zip file containing a redacted copy of your config, your database, a summary of your operating environment, and your logs. Upload that file here.

If you're uncomfortable with pasting your CarePackage, include a DEBUG log containing the error from disk. 

Do not paste from the GUI log.
Do not just paste a traceback/error.

**Environment (please complete the following information):**
 - OS: [e.g. Windows10]
 - Branch / commit:master

**Additional information**
Add any other information about the problem here.
Traceback (most recent call last):
  File "C:\ProgramData\Mylar3\mylar\getimage.py", line 23, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Mylar3\Mylar.py", line 26, in <module>
    import mylar
  File "C:\ProgramData\Mylar3\mylar\__init__.py", line 38, in <module>
    from mylar import logger, versioncheckit, rsscheckit, searchit, weeklypullit, PostProcessor, updater, helpers
  File "C:\ProgramData\Mylar3\mylar\logger.py", line 24, in <module>
    from mylar import helpers
  File "C:\ProgramData\Mylar3\mylar\helpers.py", line 42, in <module>
    from mylar import db, sabnzbd, nzbget, process, getcomics, getimage
  File "C:\ProgramData\Mylar3\mylar\getimage.py", line 28, in <module>
    logger.warn('[WARNING] PIL is not available - it\'s used to resize images for notifications, and other things.')
NameError: name 'logger' is not defined

**Comment by barbequesauce** [comment]
How did you install? If you cloned from git, did you then run `py -m pip install requirements.txt`?

**Comment by binyaminyblatt** [comment]
i frigged it out i was about to close the issue
