### ISSUE TITLE
DDL items show up in the list twice

### ISSUE THREAD

**Issue by Serneum** [mylar3/mylar3#219]
**Describe the bug**
When managing the DDL queue, many, but not all, issues show up twice. I've seen two records get added when a new item is pulled from DDL

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04.4
 - Branch / commit: master / 9a041326e4c2af60f0ec8426a59a5eee75bc025a

**Additional information**
![image](https://user-images.githubusercontent.com/1091716/77653318-e98d4e80-6f45-11ea-8bef-25d111218a06.png)

**Comment by evilhero** [comment]
The years are different on each of those items that you're thinking are duplicates. If the filename /description on getcomics has it listed more than once with incorrect/different years on each, mylar will match on them all if they're all on the same page (if under #5, they list more than one download available mylar might pick both if they match up aside).

If mylar snatches a pack it will snatch everything listed under the pack on that given page, which is probably what's happening here - plus having different years isn't helping.

**Comment by Serneum** [comment]
Ah got it. `Tomorrow` showed up twice with the same year, but it may have actually downloaded twice.
