### ISSUE TITLE
History sorts with oldest first

### ISSUE THREAD

**Issue by Serneum** [mylar3/mylar3#220]
**Describe the bug**
When viewing the History page, history is sorting with the oldest items first. The older version of Mylar put newer items first, so this is a change in behavior. It looks like the issue is that the table is being sorted by the column with the checkboxes instead of Date Added.

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04.4
 - Branch / commit: master / 9a041326e4c2af60f0ec8426a59a5eee75bc025a

**Additional information**
![image](https://user-images.githubusercontent.com/1091716/77653615-56084d80-6f46-11ea-9cc0-497a8bb06aaf.png)

**Comment by barbequesauce** [comment]
It should save state once you've sorted it to your liking - once you've sorted to your preference, try closing and reopening the browser to see if it goes back to oldest first or to your preference?

**Comment by Serneum** [comment]
It does save it, but I use Mylar on a lot of computers and was hoping for the old behavior to be added back since it was a sane default. Sorting on the checkboxes doesn't make too much sense. I'll double-check that being logged out of Mylar does not reset the setting, but I can confirm that closing/reopening the browser kept the setting. I feel like I've had to adjust it several times on this computer, but that may have been this computer, my phone, and another computer.

**Comment by evilhero** [comment]
It's not sorting by checkboxes. This has all been fixed in the development branch, you'll just have to wait for the merge.

**Comment by Serneum** [comment]
Just for clarity, I assume you mean it's not sorting the checkbox column anymore since it's fixed in the development branch. The checkbox column is definitely the one with the light blue header for the sorting in master, and `iSortCol` is 0, which is the checkbox column.

**Comment by evilhero** [comment]
The default sort order is handled on the python side, not the js side. It's sorting by asc instead of desc is all that it's doing, the checkboxes have no date value within them so it can't sort by that

**Comment by Serneum** [comment]
Closing this as it will be fixed once the development branch is merged in
