### ISSUE TITLE
Git not found and unable to determine/update version when on dev branch

### ISSUE THREAD

**Issue by castertr0y357** [mylar3/mylar3#225]
Got mylar3 up and running.  I've copied over my DB from the previous mylar installation, and got the config transferred over as well.  When it starts, I get the message that it's running and unknown version, which is standard, but when I go to update it, it never completes.  I see messages in the logs that say it can't find git, but my path to git is correct according to whereis git.

Log output:

26-Mar-2020 22:52:08 - INFO    :: mylar.shutdown.1374 : MAIN : Mylar is updating...
26-Mar-2020 22:52:08 - DEBUG   :: mylar.runGit.43 : MAIN : Trying to execute: /usr/local/bin/git pull origin python3-dev with shell in /mylar3
26-Mar-2020 22:52:08 - DEBUG   :: mylar.runGit.45 : MAIN : Git output: CompletedProcess(args='/usr/local/bin/git pull origin python3-dev', returncode=0, stdout='Already up to date.\n', stderr='From https://github.com/mylar3/mylar3\n * branch            python3-dev -> FETCH_HEAD\n')
26-Mar-2020 22:52:08 - INFO    :: mylar.shutdown.1385 : MAIN : Mylar is restarting...
26-Mar-2020 22:52:08 - INFO    :: mylar.shutdown.1393 : MAIN : Restarting Mylar with ['/usr/local/bin/python', '/mylar3/Mylar.py']
26-Mar-2020 22:52:09 - INFO    :: mylar.configure.1011 : MainThread : [COMICTAGGER] Version detected: 1.3.2
26-Mar-2020 22:52:09 - INFO    :: mylar.initialize.188 : MainThread : Checking to see if the database has all tables....
26-Mar-2020 22:52:09 - INFO    :: mylar.dbcheck.1320 : MainThread : Ensuring DB integrity - Removing all Erroneous Comics (ie. named None)
26-Mar-2020 22:52:09 - INFO    :: mylar.dbcheck.1322 : MainThread : Correcting Null entries that make the main page break on startup.
26-Mar-2020 22:52:09 - INFO    :: mylar.initialize.202 : MainThread : Successfully discovered local IP and locking it in as : 192.168.1.7
26-Mar-2020 22:52:09 - INFO    :: mylar.initialize.264 : MainThread : Remapping the sorting to allow for new additions.
26-Mar-2020 22:52:09 - INFO    :: mylar.ComicSort.761 : MainThread : Sucessfully ordered 1720 series in your watchlist.
26-Mar-2020 22:52:09 - INFO    :: mylar.validateAndCreateDirectory.1710 : MainThread : [DIRECTORY-CHECK] Found comic directory: /mylar3
26-Mar-2020 22:52:09 - INFO    :: mylar.initialize.72 : MAIN : Starting Mylar on http://0.0.0.0:80/
26-Mar-2020 22:52:09 - ERROR   :: mylar.runGit.51 : MAIN : Encountered error: /bin/sh: git: not found

26-Mar-2020 22:52:09 - ERROR   :: mylar.getVersion.86 : MAIN : Couldn't find latest installed version.
26-Mar-2020 22:52:09 - INFO    :: mylar.getVersion.125 : MAIN : cur_commit_hash:
26-Mar-2020 22:52:09 - INFO    :: mylar.getVersion.126 : MAIN : cur_branch:
26-Mar-2020 22:52:09 - ERROR   :: mylar.getVersion.129 : MAIN : Output does not look like a hash, not using it
26-Mar-2020 22:52:09 - WARNING :: mylar.getVersion.150 : MAIN : Unable to retrieve branch name [None] from git. Setting branch to configuration value of : python3-dev
26-Mar-2020 22:52:10 - INFO    :: mylar.getVersion.156 : MAIN : Branch detected & set to : python3-dev
26-Mar-2020 22:52:10 - INFO    :: mylar.versionload.359 : MAIN : version_info: {'current_version': None, 'current_version_name': None, 'branch': 'python3-dev', 'current_release_name': None}
26-Mar-2020 22:52:10 - INFO    :: mylar.versionload.379 : MAIN : Version information: python3-dev [None]
26-Mar-2020 22:52:10 - INFO    :: mylar.checkGithub.275 : MAIN : You are running an unknown version of Mylar. Run the updater to identify your version

git section of config.ini:
[Git]
git_path = /usr/local/bin/git
git_user = mylar3
git_branch = python3-dev
check_github = True
check_github_on_startup = True

I switched it to being on the master branch in the config and with git checkout master in the mylar directory and it seems to recognize the versions properly after that.  Not sure what's blocking it from recognizing the dev branch

Also as a last note, if I just change the config line to be python3-dev without running the git checkout python3-dev, it still shows me on the master branch.

**Comment by evilhero** [comment]
It's because you don't have git in your path that it's erroring out on the call to find the 'git' executable. I've noticed a problem atm with the way it handles errors and it's accepting them as valid responses when it shouldn't. WIll update shortly.

Also, the ```git_branch``` variable tells Mylar which branch to check against when looking for updates. If you have it set wrong, it will still display your current running version fine within Mylar - but it will check for updates against the wrong branch and would then always display that you're either up-to-date, or always out of date.

**Comment by castertr0y357** [comment]
I do have git in my path though.  Is there somewhere that needs to be referenced though? 

Also, to switch over to the dev branch, is the only thing required to do is update the git_branch variable in the config, or is the git checkout command required as well?

**Comment by evilhero** [comment]
Mylar will not switch your git branches for you - what with people doing stashes and local changes it's just too dangerous to do a clean wipe on the user without their knowledge in advance. If you're running the python3-dev branch, we assume you're knowledgeable enough with git to know how to checkout the new branch.

According to the log 'git' could not be found in the jail (thus the /bin/sh: git not found error) - however your pathed git as per your git_path was resolved fine. If you type in 'git' from within the Mylar jail, does it error or does it resolve? You could always try to remove your path from the git_path in the config.ini, although the /bin/sh error would probably still occur. 

Once the commit above gets merged, pull it down and it should get rid of the dead /bin/sh error that it's assuming is a valid command.

**Comment by castertr0y357** [comment]
@evilhero 

I went ahead and did the git checkout python3-dev and did a pull to update.  Also, Git is in the jail, as shown in the output below.  The git_branch is still set to python3-dev.  When I give the update command, I can see in the debug logs that it's registering the branch, and that it's up to date, but it's not resolving that piece into the version that it is.  Logs snippet is attached at the bottom.

Am I missing something?  Everything starts, and issues are being grabbed as expected, and post-processing seems to be working better than ever.  The only thing that I can think of is that since there weren't any updates for the updater to grab since I did the manual git pull.

Anything else you want me to check?  I've attached a care package if that helps you see the config.
[carepackage.zip](https://github.com/mylar3/mylar3/files/4395033/carepackage.zip)


Config snippet:
[Git]
git_path = /usr/local/bin/git
git_user = mylar3
git_branch = python3-dev
check_github = True
check_github_on_startup = True


Output:
`root@mylar3:/mylar3 # git checkout python3-dev
Switched to branch 'python3-dev'
Your branch is up to date with 'origin/python3-dev'.
root@mylar3:/mylar3 # git
usage: git [--version] [--help] [-C <path>] [-c <name>=<value>]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]

These are common Git commands used in various situations:

start a working area (see also: git help tutorial)
   clone     Clone a repository into a new directory
   init      Create an empty Git repository or reinitialize an existing one

work on the current change (see also: git help everyday)
   add       Add file contents to the index
   mv        Move or rename a file, a directory, or a symlink
   restore   Restore working tree files
   rm        Remove files from the working tree and from the index

examine the history and state (see also: git help revisions)
   bisect    Use binary search to find the commit that introduced a bug
   diff      Show changes between commits, commit and working tree, etc
   grep      Print lines matching a pattern
   log       Show commit logs
   show      Show various types of objects
   status    Show the working tree status

grow, mark and tweak your common history
   branch    List, create, or delete branches
   commit    Record changes to the repository
   merge     Join two or more development histories together
   rebase    Reapply commits on top of another base tip
   reset     Reset current HEAD to the specified state
   switch    Switch branches
   tag       Create, list, delete or verify a tag object signed with GPG

collaborate (see also: git help workflows)
   fetch     Download objects and refs from another repository
   pull      Fetch from and integrate with another repository or a local branch
   push      Update remote refs along with associated objects

'git help -a' and 'git help -g' list available subcommands and some
concept guides. See 'git help <command>' or 'git help <concept>'
to read about a specific subcommand or concept.
See 'git help git' for an overview of the system.
root@mylar3:/mylar3 # git pull
remote: Enumerating objects: 10, done.
remote: Counting objects: 100% (10/10), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 10 (delta 4), reused 6 (delta 4), pack-reused 0
Unpacking objects: 100% (10/10), done.
From https://github.com/mylar3/mylar3
   848a6e0..47567d5  python3-dev -> origin/python3-dev
Updating 848a6e0..47567d5
Fast-forward
 mylar/db.py           |  2 +-
 mylar/versioncheck.py | 10 ++++++++--
 2 files changed, 9 insertions(+), 3 deletions(-)`

Logs:

27-Mar-2020 13:10:43 - DEBUG   :: mylar.toggleVerbose.4056 : CP Server Thread-9 : If you can read this message, debug logging is now working
27-Mar-2020 13:10:43 - INFO    :: mylar.toggleVerbose.4059 : CP Server Thread-9 : config file has been loaded from: /mylar3/config.ini
27-Mar-2020 13:10:48 - INFO    :: mylar.main.373 : MAIN : Received signal: update
27-Mar-2020 13:10:53 - INFO    :: mylar.halt.1345 : MAIN : Shutting down the background schedulers...
27-Mar-2020 13:10:53 - DEBUG   :: mylar.queue_schedule.565 : MAIN : Terminating the NZB auto-complete queue thread
27-Mar-2020 13:10:53 - INFO    :: mylar.nzb_monitor.3148 : AUTO-COMPLETE-NZB : Cleaning up workers for shutdown
27-Mar-2020 13:10:53 - DEBUG   :: mylar.queue_schedule.569 : MAIN : Joined pool for termination -  successful
27-Mar-2020 13:10:53 - INFO    :: mylar.shutdown.1374 : MAIN : Mylar is updating...
27-Mar-2020 13:10:53 - DEBUG   :: mylar.runGit.44 : MAIN : Trying to execute: /usr/local/bin/git pull origin python3-dev with shell in /mylar3
27-Mar-2020 13:10:53 - DEBUG   :: mylar.runGit.46 : MAIN : Git output: CompletedProcess(args='/usr/local/bin/git pull origin python3-dev', returncode=0, stdout='Already up to date.\n', stderr='From https://github.com/mylar3/mylar3\n * branch            python3-dev -> FETCH_HEAD\n')
27-Mar-2020 13:10:53 - INFO    :: mylar.shutdown.1385 : MAIN : Mylar is restarting...
27-Mar-2020 13:10:53 - INFO    :: mylar.shutdown.1393 : MAIN : Restarting Mylar with ['/usr/local/bin/python', '/mylar3/Mylar.py']
27-Mar-2020 13:10:55 - INFO    :: mylar.configure.1011 : MainThread : [COMICTAGGER] Version detected: 1.3.2
27-Mar-2020 13:10:55 - INFO    :: mylar.initialize.188 : MainThread : Checking to see if the database has all tables....
27-Mar-2020 13:10:55 - INFO    :: mylar.dbcheck.1320 : MainThread : Ensuring DB integrity - Removing all Erroneous Comics (ie. named None)
27-Mar-2020 13:10:55 - INFO    :: mylar.dbcheck.1322 : MainThread : Correcting Null entries that make the main page break on startup.
27-Mar-2020 13:10:55 - INFO    :: mylar.initialize.202 : MainThread : Successfully discovered local IP and locking it in as : 192.168.1.7
27-Mar-2020 13:10:55 - INFO    :: mylar.initialize.264 : MainThread : Remapping the sorting to allow for new additions.
27-Mar-2020 13:10:55 - INFO    :: mylar.ComicSort.761 : MainThread : Sucessfully ordered 1724 series in your watchlist.
27-Mar-2020 13:10:55 - INFO    :: mylar.validateAndCreateDirectory.1710 : MainThread : [DIRECTORY-CHECK] Found comic directory: /mylar3
27-Mar-2020 13:10:55 - INFO    :: mylar.initialize.72 : MAIN : Starting Mylar on http://0.0.0.0:80/
27-Mar-2020 13:10:55 - ERROR   :: mylar.runGit.54 : MAIN : Encountered error: /bin/sh: git: not found

27-Mar-2020 13:10:55 - ERROR   :: mylar.runGit.54 : MAIN : Encountered error: /bin/sh: git: not found

27-Mar-2020 13:10:55 - ERROR   :: mylar.getVersion.92 : MAIN : Couldn't find latest installed version.
27-Mar-2020 13:10:55 - INFO    :: mylar.getVersion.131 : MAIN : cur_commit_hash:
27-Mar-2020 13:10:55 - INFO    :: mylar.getVersion.132 : MAIN : cur_branch:
27-Mar-2020 13:10:55 - ERROR   :: mylar.getVersion.135 : MAIN : Output does not look like a hash, not using it
27-Mar-2020 13:10:55 - WARNING :: mylar.getVersion.156 : MAIN : Unable to retrieve branch name [None] from git. Setting branch to configuration value of : python3-dev
27-Mar-2020 13:10:55 - INFO    :: mylar.getVersion.162 : MAIN : Branch detected & set to : python3-dev
27-Mar-2020 13:10:55 - INFO    :: mylar.versionload.385 : MAIN : Version information: python3-dev [None]
27-Mar-2020 13:10:55 - INFO    :: mylar.checkGithub.281 : MAIN : You are running an unknown version of Mylar. Run the updater to identify your version

**Comment by evilhero** [comment]
Well according to the carepackage, your path is:
```Mylar running environment:
                PATH = /sbin:/bin:/usr/sbin:/usr/bin
```
but you're git is located in ```/usr/local/bin/git```, so the PATH would never resolve for the mylar user as ```/usr/local/bin``` is not in the environment path that Mylar is using. Can you add ```/usr/local/bin``` to your environment path, or maybe even just symlink the git executable to one of the paths that are in the path? (ie. ```sudo ln -s /usr/local/bin/git /usr/bin/git```)

Still not sure why it's doing the /bin/sh thing - that's the weirdest thing yet since we haven't changed any of that code from Mylar2, and not sure why this issue hasn't come up previously if that's the case.

**Comment by psychogun** [comment]
I believe we have the same installation, @castertr0y357 ? This is my output from issuing `Update`, don't know if this helps. 
```
27-Mar-2020 19:27:26 - INFO    :: mylar.toggleVerbose.4055 : CP Server Thread-4 : Verbose (DEBUG) logging is enabled
27-Mar-2020 19:27:26 - DEBUG   :: mylar.toggleVerbose.4056 : CP Server Thread-4 : If you can read this message, debug logging is now working
27-Mar-2020 19:27:26 - INFO    :: mylar.toggleVerbose.4059 : CP Server Thread-4 : config file has been loaded from: /usr/local/mylar3/config.ini
27-Mar-2020 19:27:39 - DEBUG   :: mylar.checkGithub.253 : CP Server Thread-5 : Comparing currently installed version [e0864776169923126e376e50f819717f6d76a50e] with latest github version [47567d55f3cd050a016c00b3b7e47a70fc955944]
27-Mar-2020 19:27:40 - INFO    :: mylar.checkGithub.266 : CP Server Thread-5 : New version is available. You are 6 commits behind
27-Mar-2020 19:28:03 - INFO    :: mylar.main.373 : MAIN : Received signal: update
27-Mar-2020 19:28:03 - INFO    :: mylar.halt.1345 : MAIN : Shutting down the background schedulers...
27-Mar-2020 19:28:03 - INFO    :: mylar.shutdown.1374 : MAIN : Mylar is updating...
27-Mar-2020 19:28:03 - DEBUG   :: mylar.runGit.43 : MAIN : Trying to execute: git pull origin python3-dev with shell in /usr/local/mylar3
27-Mar-2020 19:28:05 - DEBUG   :: mylar.runGit.45 : MAIN : Git output: CompletedProcess(args='git pull origin python3-dev', returncode=0, stdout='Updating e086477..47567d5\nFast-forward\n mylar/config.py       |  1 +\n mylar/db.py           |  2 +-\n mylar/search.py       | 11 +++++++----\n mylar/versioncheck.py | 10 ++++++++--\n 4 files changed, 17 insertions(+), 7 deletions(-)\n', stderr='From https://github.com/mylar3/mylar3\n * branch            python3-dev -> FETCH_HEAD\n   e086477..47567d5  python3-dev -> origin/python3-dev\n')
27-Mar-2020 19:28:05 - INFO    :: mylar.shutdown.1381 : MAIN : Removing pidfile /var/run/mylar3/mylar3.pid
27-Mar-2020 19:28:05 - INFO    :: mylar.shutdown.1385 : MAIN : Mylar is restarting...
27-Mar-2020 19:28:05 - INFO    :: mylar.shutdown.1393 : MAIN : Restarting Mylar with ['/usr/local/virtual/mylar/bin/python', '/usr/local/mylar3/Mylar.py', '--daemon', '--nolaunch', '--pidfile', '/var/run/mylar3/mylar3.pid', '--config', '/usr/local/mylar3/config.ini']
27-Mar-2020 19:28:10 - INFO    :: mylar.configure.1011 : MainThread : [COMICTAGGER] Version detected: 1.3.2
27-Mar-2020 19:28:10 - INFO    :: mylar.configure.1071 : MainThread : Setting DDL Location set to : /usr/local/mylar3/cache
27-Mar-2020 19:28:10 - INFO    :: mylar.initialize.188 : MainThread : Checking to see if the database has all tables....
27-Mar-2020 19:28:10 - INFO    :: mylar.dbcheck.1320 : MainThread : Ensuring DB integrity - Removing all Erroneous Comics (ie. named None)
27-Mar-2020 19:28:10 - INFO    :: mylar.dbcheck.1322 : MainThread : Correcting Null entries that make the main page break on startup.
27-Mar-2020 19:28:10 - INFO    :: mylar.initialize.202 : MainThread : Successfully discovered local IP and locking it in as : 192.168.35.30
27-Mar-2020 19:28:10 - INFO    :: mylar.initialize.264 : MainThread : Remapping the sorting to allow for new additions.
27-Mar-2020 19:28:10 - INFO    :: mylar.ComicSort.761 : MainThread : Sucessfully ordered 2723 series in your watchlist.
27-Mar-2020 19:28:10 - INFO    :: mylar.validateAndCreateDirectory.1710 : MainThread : [DIRECTORY-CHECK] Found comic directory: /usr/local/mylar3
27-Mar-2020 19:28:10 - INFO    :: mylar.daemonize.322 : MAIN : Daemonized to PID: 32338
27-Mar-2020 19:28:10 - INFO    :: mylar.daemonize.324 : MAIN : Writing PID 32338 to /var/run/mylar3/mylar3.pid
27-Mar-2020 19:28:10 - INFO    :: mylar.initialize.72 : MAIN : Starting Mylar on http://0.0.0.0:8090/
27-Mar-2020 19:28:11 - INFO    :: mylar.getVersion.131 : MAIN : cur_commit_hash: 47567d55f3cd050a016c00b3b7e47a70fc955944
27-Mar-2020 19:28:11 - INFO    :: mylar.getVersion.132 : MAIN : cur_branch: python3-dev
27-Mar-2020 19:28:11 - INFO    :: mylar.getVersion.162 : MAIN : Branch detected & set to : python3-dev
27-Mar-2020 19:28:11 - INFO    :: mylar.versionload.385 : MAIN : Version information: python3-dev [47567d55f3cd050a016c00b3b7e47a70fc955944]
27-Mar-2020 19:28:11 - INFO    :: mylar.start.358 : MAIN : DB Updater sccheduled to fire every 5 minutes
27-Mar-2020 19:28:11 - INFO    :: mylar.queue_schedule.527 : MAIN : [SEARCH-QUEUE] Attempting to background load the search queue....
27-Mar-2020 19:28:11 - INFO    :: mylar.queue_schedule.530 : MAIN : [SEARCH-QUEUE] Successfully started the Search Queuer...
27-Mar-2020 19:28:11 - INFO    :: mylar.queue_schedule.538 : MAIN : [POST-PROCESS-QUEUE] Post Process queue enabled & monitoring for api requests....
27-Mar-2020 19:28:11 - INFO    :: mylar.queue_schedule.541 : MAIN : [POST-PROCESS-QUEUE] Succesfully started Post-Processing Queuer....
27-Mar-2020 19:28:11 - INFO    :: mylar.queue_schedule.550 : MAIN : [DDL-QUEUE] DDL Download queue enabled & monitoring for requests....
27-Mar-2020 19:28:11 - INFO    :: mylar.queue_schedule.553 : MAIN : [DDL-QUEUE:] Succesfully started DDL Download Queuer....
27-Mar-2020 19:28:11 - INFO    :: mylar.start.407 : MAIN : [WEEKLY] Checking for existance of Weekly Comic listing...
27-Mar-2020 19:28:11 - INFO    :: mylar.start.438 : MAIN : [RSS-FEEDS] Initiating startup-RSS feed checks.
27-Mar-2020 19:28:11 - INFO    :: mylar.start.441 : MAIN : [RSS-FEEDS] RSS last run @ 2020-03-27 05:49:33.535321
27-Mar-2020 19:28:11 - INFO    :: mylar.start.465 : MAIN : [FOLDER MONITOR] Enabling folder monitor for : /mnt/Mylar3_dump/ every 30 minutes.
27-Mar-2020 19:28:11 - INFO    :: mylar.start.473 : MAIN : Firing up the Background Schedulers now....
27-Mar-2020 19:28:11 - INFO    :: mylar.start.477 : MAIN : Background Schedulers successfully started...
27-Mar-2020 19:28:11 - INFO    :: mylar.run.37 : ThreadPoolExecutor-0_0 : [RSS-FEEDS] RSS Feed Check Initalizing....
27-Mar-2020 19:28:11 - INFO    :: mylar.run.54 : ThreadPoolExecutor-0_0 : [RSS-FEEDS] Initiating Torrent RSS Check.
27-Mar-2020 19:28:11 - INFO    :: mylar.run.102 : ThreadPoolExecutor-0_0 : [RSS-FEEDS] Initiating RSS Feed Check for NZB Providers.
27-Mar-2020 19:28:11 - INFO    :: mylar.run.105 : ThreadPoolExecutor-0_0 : [RSS-FEEDS] Initiating RSS Feed Check for DDL Provider.
27-Mar-2020 19:28:11 - INFO    :: mylar.ddl.458 : ThreadPoolExecutor-0_0 : [RSS][DDL] 12 entries have been indexed and are now going to be stored for caching.
27-Mar-2020 19:28:12 - INFO    :: mylar.run.107 : ThreadPoolExecutor-0_0 : [RSS-FEEDS] RSS Feed Check/Update Complete
27-Mar-2020 19:28:12 - INFO    :: mylar.run.108 : ThreadPoolExecutor-0_0 : [RSS-FEEDS] Watchlist Check for new Releases
27-Mar-2020 19:28:12 - INFO    :: mylar.searchforissue.1615 : ThreadPoolExecutor-0_0 : Initiating RSS Search Scan at the scheduled interval of 300 minutes

```

**Comment by castertr0y357** [comment]
@evilhero 
That's what it was.  Even though I had the right path for git, since /usr/local/bin/git wasn't in PATH, it wasn't able to get the current version.  I created a simlink and put it into /usr/bin like you suggested and ran the updater again.  It was able to pull the version this time, and everything seems to be working as intended.

One thing I do wonder is if there is a config line for git_path, why would it be relying on git being accessible in PATH?  Regardless, I appreciate the assistance over the past few days helping me get this up and running.  You guys have been great, and I'll likely be much quieter now that everything is all sorted out.

Hopefully all of this is able to help someone else, or help iron out some these erroneous
