### ISSUE TITLE
API getVersion returning 500 error

### ISSUE THREAD

**Issue by SenorSmartyPants** [mylar3/mylar3#229]
**Describe the bug**
calling getVersion in the mylar API returns a 500 error

**CarePackage**
[carepackage.zip](https://github.com/mylar3/mylar3/files/4396129/carepackage.zip)

**Environment (please complete the following information):**
 - OS: Docker Arm64 Hotio
 - Branch / commit: python3-dev (hotio unstable)

**Comment by SenorSmartyPants** [comment]
Pulled latest and API seems to be working fine (for the calls I use)

Thanks.

**Comment by barbequesauce** [comment]
great - do you mind closing the case please?
