### ISSUE TITLE
DDL connection failure not handled well

### ISSUE THREAD

**Issue by barbequesauce** [mylar3/mylar3#234]
28-Mar-2020 10:08:02 - DEBUG   :: mylar.parseit.1116 : SEARCH-QUEUE : sf_highest_series_pos: ['Sex', 'Criminals']
28-Mar-2020 10:08:02 - DEBUG   :: mylar.parseit.1168 : SEARCH-QUEUE : series title possibly: Sex Criminals
28-Mar-2020 10:08:02 - DEBUG   :: mylar.parseit.1181 : SEARCH-QUEUE : Alternate series / issue title: Sex Criminals Vol2  [None]
28-Mar-2020 10:08:02 - DEBUG   :: mylar.parseit.1207 : SEARCH-QUEUE : Possible UNKNOWN TPB/GN detected - no issue number present, no clarification in filename, but volume present with series title
28-Mar-2020 10:08:02 - DEBUG   :: mylar.NZB_SEARCH.1126 : SEARCH-QUEUE : parsed_info: {'parse_status': 'success', 'sub': None, 'comicfilename': 'Sex Criminals Vol. 2 - Two Worlds, One Cop', 'comiclocation': None, 'series_name': 'Sex Criminals', 'series_name_decoded': 'Sex Criminals', 'issueid': None, 'dynamic_name': 'SexCriminals', 'series_volume': 'v2', 'alt_series': 'Sex Criminals Vol2 ', 'alt_issue': None, 'issue_year': None, 'issue_number': None, 'scangroup': None, 'reading_order': None, 'booktype': 'issue'}
28-Mar-2020 10:08:02 - DEBUG   :: mylar.NZB_SEARCH.1135 : SEARCH-QUEUE : match_check: {'process_status': 'match', 'sub': None, 'volume': 'v2', 'match_type': None, 'comicfilename': 'Sex Criminals Vol. 2 - Two Worlds, One Cop', 'comiclocation': None, 'series_name': 'Sex Criminals', 'series_volume': 'v2', 'alt_series': 'Sex Criminals Vol2 ', 'alt_issue': None, 'issue_year': None, 'issueid': None, 'justthedigits': None, 'annual_comicid': None, 'scangroup': None, 'booktype': 'issue'}
28-Mar-2020 10:08:02 - DEBUG   :: mylar.NZB_SEARCH.1171 : SEARCH-QUEUE : [Vx] Version detected as v2
28-Mar-2020 10:08:02 - DEBUG   :: mylar.NZB_SEARCH.1194 : SEARCH-QUEUE : Series Year not provided but Series Volume detected of v2. Bypassing Year Match.
28-Mar-2020 10:08:02 - DEBUG   :: mylar.NZB_SEARCH.1245 : SEARCH-QUEUE : volume detection commencing - adjusting length.
28-Mar-2020 10:08:02 - DEBUG   :: mylar.NZB_SEARCH.1246 : SEARCH-QUEUE : watch comicversion is None
28-Mar-2020 10:08:02 - DEBUG   :: mylar.NZB_SEARCH.1247 : SEARCH-QUEUE : version found: v2
28-Mar-2020 10:08:02 - DEBUG   :: mylar.NZB_SEARCH.1248 : SEARCH-QUEUE : vers4year: no
28-Mar-2020 10:08:02 - DEBUG   :: mylar.NZB_SEARCH.1249 : SEARCH-QUEUE : vers4vol: v2
28-Mar-2020 10:08:02 - DEBUG   :: mylar.NZB_SEARCH.1278 : SEARCH-QUEUE : FCVersion: 2
28-Mar-2020 10:08:02 - DEBUG   :: mylar.NZB_SEARCH.1279 : SEARCH-QUEUE : DCVersion: 1
28-Mar-2020 10:08:02 - DEBUG   :: mylar.NZB_SEARCH.1280 : SEARCH-QUEUE : SCVersion: 2013
28-Mar-2020 10:08:02 - DEBUG   :: mylar.NZB_SEARCH.1289 : SEARCH-QUEUE : Versions wrong. Ignoring possible match.
28-Mar-2020 10:08:02 - DEBUG   :: mylar.NZB_SEARCH.857 : SEARCH-QUEUE : checking search result: Solid State (2017)
28-Mar-2020 10:08:02 - DEBUG   :: mylar.NZB_SEARCH.867 : SEARCH-QUEUE : sub: Solid State (2017)
28-Mar-2020 10:08:02 - DEBUG   :: mylar.NZB_SEARCH.916 : SEARCH-QUEUE : comsize_b: 148897792
28-Mar-2020 10:08:02 - DEBUG   :: mylar.NZB_SEARCH.953 : SEARCH-QUEUE : size given as: 142.0 MB
28-Mar-2020 10:08:02 - DEBUG   :: mylar.NZB_SEARCH.999 : SEARCH-QUEUE : store date used is : 2015-09-16
28-Mar-2020 10:08:02 - DEBUG   :: mylar.NZB_SEARCH.1000 : SEARCH-QUEUE : date used is : 2015-09-16
28-Mar-2020 10:08:02 - DEBUG   :: mylar.NZB_SEARCH.1043 : SEARCH-QUEUE : usedate: 2015-09-16
28-Mar-2020 10:08:02 - DEBUG   :: mylar.NZB_SEARCH.1089 : SEARCH-QUEUE : [CONV] Mon, 19 Feb 2018 00:00:00 is after store date of 2015-09-16
28-Mar-2020 10:08:02 - DEBUG   :: mylar.NZB_SEARCH.1109 : SEARCH-QUEUE : Entry: Solid State (2017)
28-Mar-2020 10:08:02 - DEBUG   :: mylar.parseit.436 : SEARCH-QUEUE : NEWLY SPLIT REORGD: ['Solid', 'State', '(2017)']
28-Mar-2020 10:08:02 - DEBUG   :: mylar.parseit.471 : SEARCH-QUEUE : checking date : 2017
28-Mar-2020 10:08:02 - DEBUG   :: mylar.parseit.474 : SEARCH-QUEUE : date: 2017
28-Mar-2020 10:08:02 - DEBUG   :: mylar.parseit.802 : SEARCH-QUEUE : datecheck: [{'date': '2017', 'position': 2, 'mod_position': 13}]
28-Mar-2020 10:08:02 - DEBUG   :: mylar.parseit.808 : SEARCH-QUEUE : sctd: 2020
28-Mar-2020 10:08:02 - DEBUG   :: mylar.parseit.816 : SEARCH-QUEUE : year verified as : None
28-Mar-2020 10:08:02 - DEBUG   :: mylar.parseit.824 : SEARCH-QUEUE : year verified as: 2017
28-Mar-2020 10:08:02 - DEBUG   :: mylar.parseit.856 : SEARCH-QUEUE : highest_series_position: 2
28-Mar-2020 10:08:02 - DEBUG   :: mylar.parseit.954 : SEARCH-QUEUE : issue_position: 3
28-Mar-2020 10:08:02 - DEBUG   :: mylar.parseit.979 : SEARCH-QUEUE : No issue number present in filename.
28-Mar-2020 10:08:02 - DEBUG   :: mylar.parseit.1116 : SEARCH-QUEUE : sf_highest_series_pos: ['Solid', 'State']
28-Mar-2020 10:08:02 - DEBUG   :: mylar.parseit.1168 : SEARCH-QUEUE : series title possibly: Solid State
28-Mar-2020 10:08:02 - DEBUG   :: mylar.parseit.1207 : SEARCH-QUEUE : Possible UNKNOWN TPB/GN detected - no issue number present, no clarification in filename, but volume present with series title
28-Mar-2020 10:08:02 - DEBUG   :: mylar.NZB_SEARCH.1126 : SEARCH-QUEUE : parsed_info: {'parse_status': 'success', 'sub': None, 'comicfilename': 'Solid State (2017)', 'comiclocation': None, 'series_name': 'Solid State', 'series_name_decoded': 'Solid State', 'issueid': None, 'dynamic_name': 'SolidState', 'series_volume': 'v1', 'alt_series': None, 'alt_issue': None, 'issue_year': '2017', 'issue_number': None, 'scangroup': None, 'reading_order': None, 'booktype': 'issue'}
28-Mar-2020 10:08:02 - DEBUG   :: mylar.NZB_SEARCH.1135 : SEARCH-QUEUE : match_check: {'process_status': 'fail', 'comicfilename': 'Solid State (2017)', 'sub': None, 'comiclocation': None, 'series_name': 'Solid State', 'alt_series': None, 'alt_issue': None, 'issue_number': None, 'series_volume': 'v1', 'issue_year': '2017', 'issueid': None, 'scangroup': None, 'booktype': 'issue'}
28-Mar-2020 10:08:02 - DEBUG   :: mylar.NZB_SEARCH.1137 : SEARCH-QUEUE : Solid State (2017) was not a match to Sex Criminals (2013)
28-Mar-2020 10:08:02 - INFO    :: mylar.search_init.396 : SEARCH-QUEUE : Could not find Issue 12 of Sex Criminals (2013) using ddl [api]
28-Mar-2020 10:08:02 - DEBUG   :: mylar.NZB_SEARCH.487 : SEARCH-QUEUE : Using Newznab host of : Miatrix
28-Mar-2020 10:08:02 - INFO    :: mylar.NZB_SEARCH.514 : SEARCH-QUEUE : Shhh be very quiet...I'm looking for Sex Criminals issue: 12 (2015) using Miatrix (newznab).
28-Mar-2020 10:08:02 - DEBUG   :: mylar.NZB_SEARCH.578 : SEARCH-QUEUE : findloop: 0 / findcount: 1
28-Mar-2020 10:08:02 - INFO    :: mylar.NZB_SEARCH.740 : SEARCH-QUEUE : Pausing for 60 seconds before continuing to avoid hammering
28-Mar-2020 10:08:02 - DEBUG   :: mylar.NZB_SEARCH.758 : SEARCH-QUEUE : [SSL: True] Search URL: https://www.miatrix.com/api?t=search&q=sex%20criminals%20012&o=xml&cat=7030&apikey=e15c5208f3d96cf392ba62228994efbd
28-Mar-2020 10:08:13 - INFO    :: mylar.NZB_SEARCH.816 : SEARCH-QUEUE : no errors on data retrieval...proceeding
28-Mar-2020 10:08:13 - INFO    :: mylar.search_init.396 : SEARCH-QUEUE : Could not find Issue 12 of Sex Criminals (2013) using Miatrix [api]
28-Mar-2020 10:08:43 - INFO    :: mylar.NZB_SEARCH.514 : SEARCH-QUEUE : Shhh be very quiet...I'm looking for Sex Criminals issue: 12 (2015) using ddl.
28-Mar-2020 10:08:43 - DEBUG   :: mylar.NZB_SEARCH.578 : SEARCH-QUEUE : findloop: 0 / findcount: 1
28-Mar-2020 10:08:43 - DEBUG   :: mylar.NZB_SEARCH.624 : SEARCH-QUEUE : Sending request to DDL site for : Sex Criminals 12
28-Mar-2020 10:08:55 - ERROR   :: mylar.excepthook.315 : SEARCH-QUEUE : Uncaught exception: Traceback (most recent call last):
  File "/home/mylar3/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/home/mylar3/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/home/mylar3/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "/home/mylar3/.local/lib/python3.8/site-packages/urllib3/connection.py", line 386, in connect
    self.sock = ssl_wrap_socket(
  File "/home/mylar3/.local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 370, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/local/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mylar3/.local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/mylar3/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/home/mylar3/.local/lib/python3.8/site-packages/urllib3/util/retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/mylar3/.local/lib/python3.8/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/home/mylar3/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/home/mylar3/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/home/mylar3/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "/home/mylar3/.local/lib/python3.8/site-packages/urllib3/connection.py", line 386, in connect
    self.sock = ssl_wrap_socket(
  File "/home/mylar3/.local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 370, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/local/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/mylar.py3/mylar/logger.py", line 337, in new_run
    old_run(*args, **kwargs)
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/mylar.py3/mylar/helpers.py", line 3132, in search_queue
    ss_queue = mylar.search.searchforissue(item['issueid'])
  File "/opt/mylar.py3/mylar/search.py", line 1873, in searchforissue
    foundNZB, prov = search_init(ComicName, IssueNumber, str(IssueYear), SeriesYear, Publisher, IssueDate, StoreDate, actissueid, AlternateSearch, UseFuzzy, ComicVersion, SARC=SARC, IssueArcID=IssueArcID, mode=mode, rsscheck=rsscheck, ComicID=ComicID, filesafe=Comicname_filesafe, allow_packs=allow_packs, oneoff=oneoff, manual=manual, torrentid_32p=TorrentID_32p, digitaldate=DigitalDate, booktype=booktype)
  File "/opt/mylar.py3/mylar/search.py", line 360, in search_init
    findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="no", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName, allow_packs=allow_packs, oneoff=oneoff, cmloopit=cmloopit, manual=manual, torznab_host=torznab_host, torrentid_32p=torrentid_32p, digitaldate=digitaldate, booktype=booktype)
  File "/opt/mylar.py3/mylar/search.py", line 626, in NZB_SEARCH
    bb = b.search()
  File "/opt/mylar.py3/mylar/getcomics.py", line 58, in search
    cf_cookievalue, cf_user_agent = s.get_tokens(self.url, headers=self.headers)
  File "/home/mylar3/.local/lib/python3.8/site-packages/cfscrape/__init__.py", line 336, in get_tokens
    resp = scraper.get(url, **kwargs)
  File "/home/mylar3/.local/lib/python3.8/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/home/mylar3/.local/lib/python3.8/site-packages/cfscrape/__init__.py", line 120, in request
    resp = super(CloudflareScraper, self).request(method, url, *args, **kwargs)
  File "/home/mylar3/.local/lib/python3.8/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/mylar3/.local/lib/python3.8/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/mylar3/.local/lib/python3.8/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

28-Mar-2020 10:10:40 - DEBUG   :: mylar.dbUpdate.84 : ThreadPoolExecutor-0_1 : Refresh sequence set to fire every 5 minutes for 7 day(s)
28-Mar-2020 10:10:40 - DEBUG   :: mylar.job_management.3585 : ThreadPoolExecutor-0_1 : ReScheduled job: DB Updater to 2020-03-28 14:15:40
28-Mar-2020 10:10:40 - INFO    :: mylar.dbUpdate.352 : ThreadPoolExecutor-0_1 : Update complete
28-Mar-2020 10:13:52 - INFO    :: mylar.run.37 : ThreadPoolExecutor-0_0 : [RSS-FEEDS] RSS Feed Check Initalizing....

**Comment by evilhero** [comment]
So it didn't download the item correct? If I'm reading that right it looks like GC dropped the connection, either forcibly (ie. site went down), or it was timeout on your side.

Either way, yeah we should gracefully kill this with a small tank.

**Comment by barbequesauce** [comment]
Correct. I was thinking to capture the connection drop and force the queue entry to mark as failed?

**Comment by evilhero** [comment]
Mark it as failed, or requeue it again so it can try later. But then any subsequent DDL's (like immediately thereafter) would fail with the same error ? I wonder if this could be used for the blocked_provider thing that's in there now ?
