### ISSUE TITLE
Unable to launch: ModuleNotFoundError: No module named '_sqlite3'

### ISSUE THREAD

**Issue by xandora** [mylar3/mylar3#238]
**Describe the bug**
After running `git clone ...` and installing python 3.7+ on CentOS 7 system, when calling `python3.7 Mylar.py` the following error is produced:

```
# python3.7 Mylar.py                                                                                                                                                           20-04-01 9:58
Traceback (most recent call last):
  File "Mylar.py", line 26, in <module>
    import mylar
  File "/home/mfrank/Downloads/mylar3/mylar/__init__.py", line 24, in <module>
    import sqlite3
  File "/usr/local/lib/python3.7/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/local/lib/python3.7/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'
```

**CarePackage**
On the config page, there is a button labelled "CarePackage". Pressing this button will download a zip file containing a redacted copy of your config, your database, a summary of your operating environment, and your logs. Upload that file here.

If you're uncomfortable with pasting your CarePackage, include a DEBUG log containing the error from disk. 

Do not paste from the GUI log.
Do not just paste a traceback/error.

**Environment (please complete the following information):**
 - OS: CentOS 7
 - Branch / commit: 9a04132

**Additional information**
Add any other information about the problem here.

**Comment by barbequesauce** [comment]
After git clone’ibg, did you run `pip3 install -r requirements.txt` ?

**Comment by psychogun** [comment]
Was your Python built from source? You'll have to add it.
Try `pip3 install pysqlite3`.

**Comment by xandora** [comment]
> 
> 
> After git clone’ibg, did you run `pip3 install -r requirements.txt` ?

Yes, I also ran that command.

> 
> 
> Was your Python built from source? You'll have to add it.
> Try `pip3 install pysqlite3`.

Yes, Python was built from source. I also tried to install `pysqlite3` as well.

**Comment by xandora** [comment]
> 
> 
> You didn't compile sqlite with python when you compiled that, so it's not usable.
> 
> You have to recompile python from source with the proper switches. Quick google:
> 
> ```
> yum install -y gcc make sqlite-devel zlib-devel libffi-devel openssl-devel
> cd Python-3.7.5
> sudo ./configure --enable-optimizations --enable-loadable-sqlite-extensions 
> sudo make 
> sudo make altinstall
> ```
> 
> Otherwise install the pkg and don't do a source installation.

Plug one hole...

```
# python3.7 Mylar.py                                                                                                                                                             20-04-01 12:04
Traceback (most recent call last):
  File "Mylar.py", line 26, in <module>
    import mylar
  File "/home/mfrank/Downloads/mylar3/mylar/__init__.py", line 33, in <module>
    from apscheduler.schedulers.background import BackgroundScheduler
ModuleNotFoundError: No module named 'apscheduler'
```

**Comment by xandora** [comment]
> 
> 
> Since you recompiled, your pip got hosed. You need to do the requirements.txt file again.

Nailed it. I was also running `pip3 ...` which after careful inspection, was running against the system installed python 3.6 pacakge. I ended up needing to run `python3.7 -m pip install -r requirements.txt`

Potentially that was the issue all along, but it seems to be working now. Many thanks for your speedy assistance.

**Comment by btxgit** [comment]
If you're gonna build your own python, you might want to look into venvs.  And by "might want to", I mean "you'd be crazy not to".

**Comment by xandora** [comment]
> 
> 
> If you're gonna build your own python, you might want to look into venvs. And by "might want to", I mean "you'd be crazy not to".

I'll investigate this, thanks for the suggestion.
