### ISSUE TITLE
What method do you recommend for Windows users to run Mylar?

### ISSUE THREAD

**Issue by AtariBaby** [mylar3/mylar3#241]
**Describe the request**
A clear and concise description of what the request is.
I know of three or four ways to run mylar. One is to use nssm or other apps to run as a service. The other is to use the windows startup folder or task scheduler. Do y’all have a preferred means for running mylar?

**How did you come up with the idea?**
Longtime mylar user
**Environment (please complete the following information):**
 - OS: Windows 10
 - Branch / commit: still installing, haven’t run yet.

**Additional information**
Add any other information about the request here.

**Comment by barbequesauce** [comment]
Windows startup folder will be simplest to confirm permissions etc.

**Comment by professionaltart** [comment]
I have it set up in nssm because I use it for my stack.  I also want it running after a power outage when noone is logged in.

Path: c:\Python37\python.exe
Startup directory: c:\Python37\
Arguments: c:\ProgramData\mylar3\Mylar.py

**Comment by AtariBaby** [comment]
For now I’ve renamed mylar.py to mylar.pyw and put a shortcut in the startup folder. I do use nssm for most other apps though. But my server’s always on so downtimes should be rare.

**Comment by barbequesauce** [comment]
@AtariBaby  you good here? can we close the issue?

**Comment by AtariBaby** [comment]
Thank you!
