### ISSUE TITLE
Minor possible graphical bug "care package"

### ISSUE THREAD

**Issue by AtariBaby** [mylar3/mylar3#242]
**Describe the bug**
I was just thinking you may have intended for "care package" to be a button like the items next to it. It's currently just words with a borderless gray square around it.
**CarePackage**
On the config page, there is a link called "CarePackage". Pressing this button will download a zip file containing a redacted copy of your config, your database, a summary of your operating environment, and your logs. Upload that file here.

If you're uncomfortable with pasting your CarePackage, include a DEBUG log containing the error from disk. 

Do not paste from the GUI log.
Do not just paste a traceback/error.

**Environment (please complete the following information):**
 - OS: Windows10]
 - Branch / commit: 
Mylar Version: master [v0.3.3 - Double-crossed by Two-Face] -- git (build 9a041326e4c2af60f0ec8426a59a5eee75bc025a)Python Version : 3.7.7
--

**Additional information**
Add any other information about the problem here.

**Comment by barbequesauce** [comment]
Have you tried to clean out your cache? It should look like this:
<img width="123" alt="Screen Shot 2020-04-06 at 7 52 34 AM" src="https://user-images.githubusercontent.com/25070944/78555719-9f288f00-77db-11ea-8252-d6f993e531b6.png">

**Comment by AtariBaby** [comment]
Ah yes. Cleared cache and now it looks correct!
