### ISSUE TITLE
Datatables accidental reinit on import page buttons

### ISSUE THREAD

**Issue by barbequesauce** [mylar3/mylar3#255]
Discovered by @ajslater 

![](https://i.imgur.com/kvOYYgA.png)

Both the flushImports and markImports?action=massimport buttons at the top are asking the datatable to reload, which is not allowed per https://datatables.net/tn/3. Presumably an upgrade-related item that wasn't found until now.

**Comment by barbequesauce** [comment]
We good here?

**Comment by sebclark** [comment]
Issue still exists in current build

**Comment by evilhero** [comment]
we are aware.

**Comment by barbequesauce** [comment]
Listen you

**Comment by barbequesauce** [comment]
I will forget this if I don't write it down - 

script.js, function doAjaxCall line 314:
```
if ( reload == "table") {
    console.log('refresh'); refreshTable();
```

function refreshTable line 169:
```
function refreshTable() {
	var url =  $(location).attr('href');
	$("table.display").load(url + " table.display tbody, table.display thead", function() { 
                         // ^^^ this load is the real problem - but how to fix? 
                         //     reload the page?
		initThisPage();
	});
}
```

Note this seems to account for both button issues...
