### ISSUE TITLE
DataTables Error when trying in import existing comics

### ISSUE THREAD

**Issue by greycubesgav** [mylar3/mylar3#256]
**Describe the bug**
DataTables Error when trying in import existing comics
I get an error when trying to import existing comics in to a fresh install of Mylar3: Version: v0.3.4(master)

Steps to reproduce:
Home->Manage->Scan Comic Library
Enter path to run against
Hit "Save Changes and Scan"
Hit "Import Results Management"
Check box next to found comic
Hit [Import] on comics' table row
Spinning icon in bottom right
Popup:
"DataTables warning: table id=impresults_table - Cannot reinitialise DateTable....."
![Screenshot 2020-04-19 at 15 25 03](https://user-images.githubusercontent.com/3426859/79687724-fc97f380-8251-11ea-93bd-4d4d2d84acb2.png)

**CarePackage**
[carepackage.zip](https://github.com/mylar3/mylar3/files/4498968/carepackage.zip)

**Environment (please complete the following information):**
Docker Container, Unraid 6.8.3, mylar3 Community App, "latest" branch 

**Additional information**

**Comment by barbequesauce** [comment]
Related to #255?

**Comment by greycubesgav** [comment]
Yes it looks like it's related.
Closing
