### ISSUE TITLE
Mylar 32Pages - Not finding torrents

### ISSUE THREAD

**Issue by joelang1699** [mylar3/mylar3#259]
Hello All

I have an issue with Mylar not being able to find anything on 32Pages. I've been deliberately adding comics known to exist on 32P.

I have tried all the "Year Options" and "Alternate Search Names" names.

There are no errors in the logs except....

2020-04-22 14:35:57 | INFO | Could not find Issue 2 of The Witcher (2014) using 32P [api]
2020-04-22 14:35:56 | INFO | Shhh be very quiet...I'm looking for The Witcher issue: 2 (2014) using 32P.

DDL works perfectly.

Version: v0.3.4 ( master)
Unraid

**Comment by barbequesauce** [comment]
When you're in the series detail page, switch to the "Edit Settings" tab. Towards the bottom, add the series ID (look in the 32p page URL) and check "Enable Pack Downloads". On the next scheduled search (or if you force check on the wanted page), it should start to pull them...

**Comment by evilhero** [comment]
What @barbequesauce said - 32P will put individual items into their respective packs really quickly (like sometimes after just one day of it being on the site). So if you don't grab it when they first drop, Mylar won't be able to grab the individual items as they no longer exist. Pack downloads are the only way to grab them - but you need to be using Auth mode or else the option isn't available.

**Comment by joelang1699** [comment]
I have it running in Auth mode and I have enabled packs. I should have stated that in the original message.

If left it running over night with 32pages as the sole provider. Its not been able to find anything.

**Comment by joelang1699** [comment]
Attached is the required .zip

I left mylar running for a few days to see what it would do, sadly no change.
[carepackage.zip](https://github.com/mylar3/mylar3/files/4535462/carepackage.zip)

**Comment by evilhero** [comment]
It looks like it's not finding anything for 2 reasons:
- titles have to match to what Mylar expects them to. Any deviation from the expected naming title will result in a mismatch. So in say a case like ```Hellraiser```, in Mylar it's called ```Clive Barker's Hellraiser```, but on 32P it's called ```Hellraiser```, so you'll never get any matches to the correct series. In these naming mismatch cases, you need to tell Mylar what the name is on the site(s) you're trying to find by using the ```Alternate Search Name``` field in the Edit Settings for the given series (in the above case you'd enter in just ```Hellraiser```). However the caveat in manipulating the Alternate Search Name fields for a lot of similar series, is that if there are any overlaps of the same name being referenced it might be a crapshoot as to which one matches correctly.

- Most of the older issues you're searching for are already in packs, so they'll never be matched correctly to that one specific issue by default. Unfortunately at this time, the enable pack options with 32P is on a per series basis that has to be enabled for each specific series (Seriesdetail page, Edit Settings, Enable Packs). Once you enable that, packs can be downloaded from 32P if the relevant issue number is within the matching pack.

**Comment by barbequesauce** [comment]
Any news @joelang1699 ?
