### ISSUE TITLE
DDL issues

### ISSUE THREAD

**Issue by professionaltart** [mylar3/mylar3#260]
**Describe the bug**
DDL enabled, no downloads happening, direct or otherwise.

**CarePackage**
I can do a full carepackage if you'd like the the only meaningful lines from the logs are these - I've just set the comic manually as wanted, which fired off the process of finding/getting/etc.
```
22-Apr-2020 07:06:24 - INFO :: mylar.skipped2wanted.2172 : CP Server Thread-9 : Marking issues: ['1'] as Wanted
127.0.0.1 - - [22/Apr/2020:07:06:24] "GET /skipped2wanted?comicid=125678 HTTP/1.1" 303 152 "http://localhost:8090/comicDetails?ComicID=125678" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0"
22-Apr-2020 07:06:24 - WARNING :: mylar.searchIssueIDList.1937 : Thread-12 : There are no search providers enabled atm - not performing the requested search for obvious reasons
127.0.0.1 - - [22/Apr/2020:07:06:24] "GET /comicDetails?ComicID=[%27125678%27] HTTP/1.1" 303 98 "http://localhost:8090/comicDetails?ComicID=125678" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0"
127.0.0.1 - - [22/Apr/2020:07:06:24] "GET /home HTTP/1.1" 200 10178 "http://localhost:8090/comicDetails?ComicID=125678" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0"
127.0.0.1 - - [22/Apr/2020:07:06:26] "GET /comicDetails?ComicID=125678 HTTP/1.1" 200 35907 "http://localhost:8090/comicDetails?ComicID=125678" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0"
127.0.0.1 - - [22/Apr/2020:07:06:26] "GET /cache/125678.jpg?20-04-22%2007:06:26 HTTP/1.1" 200 382959 "http://localhost:8090/comicDetails?ComicID=125678" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0"

```

**Environment (please complete the following information):**
 - OS: ubuntu 20.04 beta
 - Branch / commit:  Version: 91224370f41ad42b6b86bf7e2e81eb0784b14b51 (python3-dev) 

**Additional information**

I'm assuming this is a config issue.  I spun up a new VM, pulled down the pre-reqs, cloned, installed against reqs, and got it up and running.
I added a single comic - Cable (2020), which has a single issue out, for testing and low overhead.

In settings, comic location is /home/nich/Comics and I've added the CV api key.
No Download settings entered.  
Search providers I've selected DDL.  
PP enabled.  
Failed download handling on.  
Metatagging on.

If I mark the issue from skipped to wanted, I get a warning that there are no search providers enabled atm.
so unsurprisingly /queueManage has no entries

**Comment by evilhero** [comment]
This seems to be a problem with the ```skipped 2 wanted``` option being used. So atm, the solution is to just not use it until we can patch it up (normal searches and manual searches via the magnifying glass icon all work with just DDL as an enabled provider).

**Comment by professionaltart** [comment]
Confirmed working.
