### ISSUE TITLE
Better log output/suggested defaults for new users

### ISSUE THREAD

**Issue by professionaltart** [mylar3/mylar3#267]
**Describe the request**
Make it clear where DDL downloads are.... downloaded to - can't PP if you don't know where the file went.
Also better handling of manual PP folder location error.

**How did you come up with the idea?**
I just ran a fresh build of mylar on a fresh VM and found some issues.

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04 Desktop
 - Branch / commit:  d151530f95a6dbd9ec56414c6da4b24153176f1c (python3-dev) 

**Additional information**
Steps to recreate:
Fresh linux install.
Install git and pip3.
Clone mylar3.
requirements.txt
python3 Mylar.py -v
Load Mylar in Firefox.
Watch live logs in console/in log window.

Added comic location, account for permissions, enable annual handling
Added CV API key
Enable DDL
Set min file size, enable failed download handling/automatic retry, enable PP, enable metadata tagging
```
24-Apr-2020 05:58:31 - INFO    :: mylar.ddl_downloader.3048 : DDL-QUEUE : Cable 001 (2020) (Digital) (Zone-Empire).cbr successfully downloaded - now initiating post-processing.
```
That's great but I had to go digging to find where that might be saved to.  As it turns out, /mylar3/cache looks like the default if it's not otherwise specified.  Is something about that able to be added to the log output?

Anyway, it downloads and doesn't PP, so I go to run it manually.  In my excitement I forgot that the default 'path to manually run' is empty if you don't add it to the config file, so I hit 'go' and check out the traceback!  Entering the wrong directory seems to be handled with 'no files there derp' (probably because that's what the OS returns when queried?).

There's the fact that it didn't really CDH and PP automatically, but there's a chance that a) I was just impatient, and b) this is part of a bigger issue related to CDH that's known.

**Comment by barbequesauce** [comment]
I would expect it was impatience :) DDL dl's and pp's just fine on a net-new install here... check the defaults (Manage / Activity-Jobs tab) and wait for the Auto-Search (360m) and Folder Monitor (60m) jobs to complete in succession (720m at minimum, depending on how much it found), and you should be fine...

**Comment by professionaltart** [comment]
Hah, yeah.  If I just hit the magnifying glass/manual search button, it does it all automatically, and not into the auto queues set on timers.  /cache flies up when it hits the PP and does its job.

Just tried adding another comic with 5 issues out, and setting them all to 'wanted', and it went and found them and grabbed and PP'd.

When there is something in the queue that will eventually hit the PP tho', hitting 'manual PP' with no path set still gives a traceback (which then necessitates a restart of Mylar to unfuck it).  I tried this with an empty queue, and it seemed to handle it ok.

**Comment by professionaltart** [comment]
Something funky going on still, maybe this'll make more sense to you guys:
[carepackage(1).zip](https://github.com/mylar3/mylar3/files/4532645/carepackage.1.zip)

**Comment by barbequesauce** [comment]
so manual PP needs a path to know where to look - that's a design choice, not an error. You cant walk into a mechanic and say "car broken", right? :)

**Comment by barbequesauce** [comment]
@professionaltart is this still an issue?

**Comment by barbequesauce** [comment]
Check out History - View Logs button - Exceptions/Tracebacks... evilhero whipped this up to address your idea...
