### ISSUE TITLE
Mylar service doesn't start: NameError: name 'logger' is not defined

### ISSUE THREAD

**Issue by pkreuzt** [mylar3/mylar3#270]
Starting a clean install on Raspbian Buster with "Hail Hydra!" release, I get this error when launching Mylar service (SystemD):
```

● mylar.service - Mylar Service
   Loaded: loaded (/etc/systemd/system/mylar.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2020-04-26 15:59:51 CEST; 4min 14s ago
  Process: 8936 ExecStart=/usr/bin/python3 /opt/mylar/Mylar.py --nolaunch --config /var/lib/mylar/config.ini --datadir /var/lib/mylar (code=exited, status=1/FAILURE)
 Main PID: 8936 (code=exited, status=1/FAILURE)

abr 26 15:59:50 Raspbian python3[8936]:     from mylar import logger, versioncheckit, rsscheckit, searchit, weeklypullit, PostProcessor, updater, helpers
abr 26 15:59:50 Raspbian python3[8936]:   File "/opt/mylar/mylar/logger.py", line 24, in <module>
abr 26 15:59:50 Raspbian python3[8936]:     from mylar import helpers
abr 26 15:59:50 Raspbian python3[8936]:   File "/opt/mylar/mylar/helpers.py", line 42, in <module>
abr 26 15:59:50 Raspbian python3[8936]:     from mylar import db, sabnzbd, nzbget, process, getcomics, getimage
abr 26 15:59:50 Raspbian python3[8936]:   File "/opt/mylar/mylar/getimage.py", line 28, in <module>
abr 26 15:59:50 Raspbian python3[8936]:     logger.warn('[WARNING] PIL is not available - it\'s used to resize images for notifications, and other things.')
abr 26 15:59:50 Raspbian python3[8936]: NameError: name 'logger' is not defined
abr 26 15:59:51 Raspbian systemd[1]: mylar.service: Main process exited, code=exited, status=1/FAILURE
abr 26 15:59:51 Raspbian systemd[1]: mylar.service: Failed with result 'exit-code'.
```

Not sure if relevant, I installed most dependencies manually from apt and then ran `pip3 install -r requirements.txt` just to get the remaining ones that are not present in the repos.

**Comment by barbequesauce** [comment]
`logger.warn(‘[WARNING] PIL is not available - it\’s used to resize images for notifications, and other things.’)`

That seems pretty clear... when you run `pip3 freeze `do you see PIL or pillow in the list? If not, you’ll need to manually install it.

Are you doing the pip3 install’s while logged in as the runtime account, or as root? If not, are you running pyenv, venv, or anything of the like that might be changing the location of python libraries between the runtime account and the logged in account?

**Comment by pkreuzt** [comment]
I run pip3 as root. Regarding the PIL issue, I read it as a warning, so it shouldn't be fatal. Pillow 6.2.2 is installed through apt and appears on pip3 freeze result.

**Comment by evilhero** [comment]
Yeah the logger module should be imported before the Pillow import (and it shouldn't state PIL). However, Pillow is used in various parts of Mylar3 now when we extract images from the cbr/cbz - so you'll end up either getting blank placeholders or possibly even an error. So it is a warning, but it is also in the requirements.txt file for a reason as we require users to have everything running therein. 

The fact remains that if you're hitting the logger warning part, Pillow isn't being recognised by your version of python3, so you're going to encounter similar errors probably until you can get that sorted out - perhaps you should install it using pip3 to ensure it's attached to the correct version of python on your system. You also don't mention which version of python3 you're running...

You can also check by just going to a python command line and do an ```import PIL```. If it throws back a traceback/error then its not being recognised on that specific version of python. No traceback/error, it's installed fine.

**Comment by pkreuzt** [comment]
PIL imports fine in a "python3" command line (its version is 3.7.3), but fails in  "python" (version 2.7.16). My service states
`
ExecStart=/usr/bin/python3 /opt/mylar/Mylar.py --nolaunch`

Debian (and presumably derivatives) policy considers "python" is version 2 and "python3" is version 3. But I found calls to" /usr/bin/python" everywhere in Mylar3. Not sure it should work that way. . .

**Comment by evilhero** [comment]
Except on windows systems where python can work as either. 

If you're talking about the shebangs  - they don't impact anything within Mylar since none of the .py files are run individually as scripts, it's run as a collective group. We have lots of users running all flavours of python3 (debian, ubuntu, windows, fbsd, dockers) and have never encountered any errors in regards to the shebang denoted incorrectly (as opposed to running say ComicRN with an incorrect shebang since that gets invoked as a script from within an external program).

Again, this has nothing to do with your original post - Pillow has imported fine for everyone else using the requirements.txt file, so at this point it's something specific to your system that's causing some discrepancies somewhere along the line, but the question is where and why. The only other aspect I can think of is that you're installing pip as root, which is widely ill advised as it may interfere with system installed packages. Are you running mylar as root as well ?

Try running Mylar from just the cli, and not from systemd and paste what spits back in the console maybe (there are print statements in there prior to the logging being loaded).

**Comment by pkreuzt** [comment]
Seems you were right. Actually I had installed requirements with root account. I've just remade installation but this time installing them only for Mylar user with 
`
pip3 install --user -r requirements.txt`

But the problem persists. When running from console I discovered a previous error:

```
Traceback (most recent call last):
  File "/opt/mylar/mylar/getimage.py", line 23, in <module>
    from PIL import Image
  File "/var/lib/mylar/.local/lib/python3.7/site-packages/PIL/Image.py", line 90, in <module>
    from . import _imaging as core
ImportError: libopenjp2.so.7: cannot open shared object file: No such file or directory
```

For the record, if anyone else catches this error, this is solved by installing libopenjp2-tools and now Mylar service runs just fine.

Thanks for the support.

**Comment by OneCDOnly** [comment]
Just had this same problem when trying to get Mylar running in QTS (QNAP's NAS OS). 

Had to uninstall Pillow v6.2.2 (installed via `pip3` and Mylar's requirements.txt), and used the `python3-pillow` IPKG (v7.1.1-2) instead from OpenWRT. 

Now starts correctly.
