### ISSUE TITLE
adding a series from the search bar fails

### ISSUE THREAD

**Issue by JaBaine** [mylar3/mylar3#272]
**Describe the bug**
When adding a series from the search bar or This Week tab the process does not complete and gets stuck with all fields saying "none". 

**CarePackage**
[carepackage(1).zip](https://github.com/mylar3/mylar3/files/4542799/carepackage.1.zip)

**Environment (please complete the following information):**
 - OS: Windows10
 - Branch / commit: recent migration to  mylar3  v0.3.5 ( master

**Additional information**
I had this same issue when using mylar2 and just migrated to mylar3 to see if it would correct the problem

**Comment by evilhero** [comment]
You're running on a Windows OS - your folder format has slashes appropriate for non-WIndows OS. From your config.ini:
```folder_format = $Publisher/$Series/V$Year/$Annual```
should be :
```folder_format = $Publisher\$Series\V$Year\$Annual```

The example provided beneath the Folder Format string will indicate the correct slashes to use as per the example:
```Use: $Publisher, $Series, $YearE.g.: $Publisher/$Series ($Year) = DC Comics/Action Comics (2011)```

**Comment by JaBaine** [comment]
thank you, all fixed 
.....i've had that wrong since the beginning of time
