### ISSUE TITLE
cant start after migrating handle_exception error

### ISSUE THREAD

**Issue by HypKin** [mylar3/mylar3#274]
**Describe the bug**
I just tried to migrate from the old mylar to mylar3
I installed the 3.7.4 version of python since I'm running it on windows. copied over the database and config file and changed the things in the config as told in the guide on the first page.

```
D:\mylar3>python mylar.py -v
language detected as non-English (de_DE). Forcing specific logging module - errors WILL NOT be captured in the logs
Verbose/Debugging mode enabled...
Initializing startup sequence....
Logging level over-ridden by startup value. Changing from 1 to 2
01-Mai-2020 11:04:36 - DEBUG :: MainThread : config.py:configure:886 : Log dir: d:\mylar3\logs
01-Mai-2020 11:04:36 - DEBUG :: MainThread : config.py:configure:954 : [Grabbag Directory] Setting One-Off directory to default location: Z:\Comics\Mylar\Grabbag
01-Mai-2020 11:04:36 - INFO :: MainThread : config.py:configure:1012 : [COMICTAGGER] Version detected: 1.3.3
01-Mai-2020 11:04:36 - DEBUG :: MainThread : config.py:configure:1050 : [COMICTAGGER] Setting ComicTagger settings default path to : None
Error in sys.excepthook:
TypeError: handle_exception() missing 1 required positional argument: 'exc_traceback'

Original exception was:
Traceback (most recent call last):
  File "mylar.py", line 386, in <module>
    main()
  File "mylar.py", line 203, in main
    mylar.initialize(mylar.CONFIG_FILE)
  File "D:\mylar3\mylar\__init__.py", line 180, in initialize
    CONFIG = cc.read(startup=True)
  File "D:\mylar3\mylar\config.py", line 565, in read
    self.configure(startup=startup)
  File "D:\mylar3\mylar\config.py", line 1052, in configure
    if not os.path.exists(self.CT_SETTINGSPATH):
  File "C:\Python37\lib\genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```

**Environment (please complete the following information):**
 - OS: Windows 10
- source: Git clone
 - Branch / commit: [master] Dev branch merge (#265)
Python: 3.7.4 pip v 20.0

**Additional information**
I tried to start mylar with "-v" option to get a debug log. but its nearly empty. anything else I can to to give you additional information?

[mylar.log](https://github.com/mylar3/mylar3/files/4563141/mylar.log)

**Comment by ElementSixtySix** [comment]
Same except 3.7.7...


`
C:\Users\NXF\AppData\Local\Programs\Python\Python37>python.exe c:\mylar3\Mylar.p
y
log language set to en_US
Initializing startup sequence....
01-May-2020 14:19:24 - INFO :: mylar.configure.1012 : MainThread : [COMICTAGGER]
 Version detected: 1.3.3
01-May-2020 14:19:24 - ERROR :: mylar.excepthook.315 : MainThread : Uncaught exc
eption: Traceback (most recent call last):
  File "c:\mylar3\Mylar.py", line 386, in <module>
    main()
  File "c:\mylar3\Mylar.py", line 203, in main
    mylar.initialize(mylar.CONFIG_FILE)
  File "c:\mylar3\mylar\__init__.py", line 180, in initialize
    CONFIG = cc.read(startup=True)
  File "c:\mylar3\mylar\config.py", line 565, in read
    self.configure(startup=startup)
  File "c:\mylar3\mylar\config.py", line 1052, in configure
    if not os.path.exists(self.CT_SETTINGSPATH):
  File "C:\Users\NXF\AppData\Local\Programs\Python\Python37\lib\genericpath.py",
 line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneT
ype

Traceback (most recent call last):
  File "c:\mylar3\Mylar.py", line 386, in <module>
    main()
  File "c:\mylar3\Mylar.py", line 203, in main
    mylar.initialize(mylar.CONFIG_FILE)
  File "c:\mylar3\mylar\__init__.py", line 180, in initialize
    CONFIG = cc.read(startup=True)
  File "c:\mylar3\mylar\config.py", line 565, in read
    self.configure(startup=startup)
  File "c:\mylar3\mylar\config.py", line 1052, in configure
    if not os.path.exists(self.CT_SETTINGSPATH):
  File "C:\Users\NXF\AppData\Local\Programs\Python\Python37\lib\genericpath.py",
 line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneT
ype
`

**Comment by evilhero** [comment]
In the config.ini there's a section called ```[Metatagging] ```. Therein is a field called ct_settingspath, set it to the root of your mylar installation : ```Ct_settingspath = C:\mylar3\.ComicTagger```.

This is a permissions problem with Windows users on some setups due to trying to create a  directory in the Users home directory and not having correct permissions (ie. we are looking into it still)

**Comment by ElementSixtySix** [comment]
That's solved it... Tnx

**Comment by HypKin** [comment]
yep same here, gonna close this, thx evilhero.
