### ISSUE TITLE
Issue parsing comics with "of <number>" in the title

### ISSUE THREAD

**Issue by Serneum** [mylar3/mylar3#275]
**Describe the bug**
Mylar seems to be struggling with parsing comics that have `of <number>` in the name of the comic, ex: `Night of 1000 Wolves`. My assumption is that this is because Mylar has logic to parse out issue numbers like `01 of 04` like I've seen it do in the past.

**CarePackage**
[carepackage.zip](https://github.com/mylar3/mylar3/files/4567149/carepackage.zip)

**Environment (please complete the following information):**
 - OS: `Ubuntu 20.04`
 - Branch / commit: `python3-dev/874e5d961a1da4884d6c9e9b262b2a2b4667cfc0`

**Additional information**
Add any other information about the problem here.

**Comment by evilhero** [comment]
Yep, you're right that would be problematic and odds are that's exactly what's happening. I'd like to say it's a simple fix, but...well, I won't say that just yet - I have a feeling it might be a bit more involved. I'll take this one to look into more, since I'm pretty sure that @barbequesauce has mentioned in several other instances, that he won't touch the file parser with an elongated 10' pole.

**Comment by barbequesauce** [comment]
@Serneum can you give this a try? The fixes should be in now...

**Comment by Serneum** [comment]
Not at home so doing this from my phone. I ran a Recheck on the files I had in the directory for the comic and got

```
FAILED FILES: [{'parse_status': 'failure', 'sub': None, 'comicfilename': 'Night of 1000 Wolves 001 (2013).cbz', 'comiclocation': '/mnt/Comics/Night of 1000 Wolves (2013)', 'series_name': 'Night 1000 Wolves', 'series_volume': None, 'alt_series': None, 'alt_issue': None, 'issue_year': '2013', 'issue_number': '001', 'issueid': None, 'scangroup': None, 'booktype': 'issue'}]
```

I can set up debugging logging tonight and try again to get more information

**Comment by Serneum** [comment]
Sorry for the delay. I updated again and now it is working. Looks like some new changes were added over the past few hours, so I assume that's where it started working

**Comment by barbequesauce** [comment]
great - can we close the issue?

**Comment by Serneum** [comment]
Yeah. I wasn't sure if it was okay for me to do so, so I left it open. I'll close it with this comment.
