### ISSUE TITLE
DDL Not Finding Results - Issues Are Available

### ISSUE THREAD

**Issue by rutskiuk** [mylar3/mylar3#279]
I have enabled DDL for downloading comics and despite the comics being available on GetComics.info they are not being found / downloaded
Previously, on the PY2 build, I added a comic series which I could see was hosted on GC to see how many issues would come through by DDL and none did (The Walking Dead)

Notably today, Batman - The Adventures Continue #3 did not download (note: I have since manually downloaded the file)

Attempted to attach the carepackage zip but was way too large
https://file.io/ENOggSzn

 - OS: Windows10 64Bit, Python 3.7
 - Branch / commit: Version: 9eefa84457f85f777c01628eb01f76b0a802984b (master)

I had a look through the log and it appears the results are being ignored:

07-May-2020 00:47:43 - INFO    :: mylar.search_init.431 : SEARCH-QUEUE : Finished searching via : api. Issue not found - status kept as Wanted.
07-May-2020 00:47:43 - INFO    :: mylar.searchforissue.1615 : ThreadPoolExecutor-0_2 : Initiating RSS Search Scan at the scheduled interval of 20 minutes
07-May-2020 00:47:43 - INFO    :: mylar.searchforissue.1667 : ThreadPoolExecutor-0_2 : Storyarcs to be searched for : 0
07-May-2020 00:47:43 - INFO    :: mylar.search_init.47 : ThreadPoolExecutor-0_2 : [SEARCH] Special Characters exist within Series Title. Enabling search-safe Name : Batman The Adventures Continue
07-May-2020 00:47:43 - DEBUG   :: mylar.search_init.63 : ThreadPoolExecutor-0_2 : Publisher is : DC Comics
07-May-2020 00:47:43 - DEBUG   :: mylar.search_init.71 : ThreadPoolExecutor-0_2 : Issue Title given as : b'mentors part i'
07-May-2020 00:47:43 - DEBUG   :: mylar.search_init.102 : ThreadPoolExecutor-0_2 : Checking for torrent enabled.
07-May-2020 00:47:43 - DEBUG   :: mylar.search_init.153 : ThreadPoolExecutor-0_2 : nzbprovider(s): ['newznab: Newz69']
07-May-2020 00:47:43 - DEBUG   :: mylar.search_init.156 : ThreadPoolExecutor-0_2 : There are 0 torrent providers you have selected.
07-May-2020 00:47:43 - DEBUG   :: mylar.search_init.161 : ThreadPoolExecutor-0_2 : There are : 1 nzb providers you have selected
07-May-2020 00:47:43 - DEBUG   :: mylar.search_init.163 : ThreadPoolExecutor-0_2 : Usenet Retention : 1100 days
07-May-2020 00:47:43 - DEBUG   :: mylar.search_init.166 : ThreadPoolExecutor-0_2 : there are 1 Direct Download providers that are currently enabled.
07-May-2020 00:47:43 - DEBUG   :: mylar.search_init.180 : ThreadPoolExecutor-0_2 : search provider order is ['DDL', 'newznab: Newz69']
07-May-2020 00:47:43 - DEBUG   :: mylar.search_init.247 : ThreadPoolExecutor-0_2 : calpha/cnumber: None / None
07-May-2020 00:47:43 - DEBUG   :: mylar.search_init.283 : ThreadPoolExecutor-0_2 : Initiating Search via : rss
07-May-2020 00:47:43 - INFO    :: mylar.NZB_SEARCH.514 : ThreadPoolExecutor-0_2 : Shhh be very quiet...I'm looking for Batman: The Adventures Continue issue: 3 (2020) using ddl [RSS].
07-May-2020 00:47:43 - DEBUG   :: mylar.NZB_SEARCH.578 : ThreadPoolExecutor-0_2 : findloop: 0 / findcount: 1
07-May-2020 00:47:43 - DEBUG   :: mylar.NZB_SEARCH.630 : ThreadPoolExecutor-0_2 : Sending request to [ddl] RSS for Batman: The Adventures Continue : 003
07-May-2020 00:47:44 - DEBUG   :: mylar.NZB_SEARCH.857 : ThreadPoolExecutor-0_2 : checking search result: Batman – The Adventures Continue #1 (2020)
07-May-2020 00:47:44 - DEBUG   :: mylar.NZB_SEARCH.867 : ThreadPoolExecutor-0_2 : sub: Batman – The Adventures Continue #1 (2020)
07-May-2020 00:47:44 - DEBUG   :: mylar.NZB_SEARCH.916 : ThreadPoolExecutor-0_2 : comsize_b: 9437184
07-May-2020 00:47:44 - DEBUG   :: mylar.NZB_SEARCH.953 : ThreadPoolExecutor-0_2 : size given as: 9.0 MB
07-May-2020 00:47:44 - DEBUG   :: mylar.NZB_SEARCH.1003 : ThreadPoolExecutor-0_2 : store date used is : 2020-05-06
07-May-2020 00:47:44 - DEBUG   :: mylar.NZB_SEARCH.1004 : ThreadPoolExecutor-0_2 : date used is : 2020-05-06
07-May-2020 00:47:44 - DEBUG   :: mylar.NZB_SEARCH.1047 : ThreadPoolExecutor-0_2 : usedate: 2020-05-06
07-May-2020 00:47:44 - DEBUG   :: mylar.NZB_SEARCH.1089 : ThreadPoolExecutor-0_2 : [CONV] pubdate: 2020-04-01  < storedate: 2020-05-04
07-May-2020 00:47:44 - DEBUG   :: mylar.NZB_SEARCH.1090 : ThreadPoolExecutor-0_2 : Wed, 01 Apr 2020 08:47:58 is before store date of 2020-05-06. Ignoring search result as this is not the right issue.
07-May-2020 00:47:44 - DEBUG   :: mylar.NZB_SEARCH.857 : ThreadPoolExecutor-0_2 : checking search result: Batman – The Adventures Continue #2 (2020)
07-May-2020 00:47:44 - DEBUG   :: mylar.NZB_SEARCH.867 : ThreadPoolExecutor-0_2 : sub: Batman – The Adventures Continue #2 (2020)
07-May-2020 00:47:44 - DEBUG   :: mylar.NZB_SEARCH.916 : ThreadPoolExecutor-0_2 : comsize_b: 10485760
07-May-2020 00:47:44 - DEBUG   :: mylar.NZB_SEARCH.953 : ThreadPoolExecutor-0_2 : size given as: 10.0 MB
07-May-2020 00:47:44 - DEBUG   :: mylar.NZB_SEARCH.1003 : ThreadPoolExecutor-0_2 : store date used is : 2020-05-06
07-May-2020 00:47:44 - DEBUG   :: mylar.NZB_SEARCH.1004 : ThreadPoolExecutor-0_2 : date used is : 2020-05-06
07-May-2020 00:47:44 - DEBUG   :: mylar.NZB_SEARCH.1047 : ThreadPoolExecutor-0_2 : usedate: 2020-05-06
07-May-2020 00:47:44 - DEBUG   :: mylar.NZB_SEARCH.1089 : ThreadPoolExecutor-0_2 : [CONV] pubdate: 2020-04-15  < storedate: 2020-05-04
07-May-2020 00:47:44 - DEBUG   :: mylar.NZB_SEARCH.1090 : ThreadPoolExecutor-0_2 : Wed, 15 Apr 2020 09:58:28 is before store date of 2020-05-06. Ignoring search result as this is not the right issue.
07-May-2020 00:47:44 - DEBUG   :: mylar.NZB_SEARCH.857 : ThreadPoolExecutor-0_2 : checking search result: Batman – The Adventures Continue #3 (2020)
07-May-2020 00:47:44 - DEBUG   :: mylar.NZB_SEARCH.867 : ThreadPoolExecutor-0_2 : sub: Batman – The Adventures Continue #3 (2020)
07-May-2020 00:47:44 - DEBUG   :: mylar.NZB_SEARCH.916 : ThreadPoolExecutor-0_2 : comsize_b: 11534336
07-May-2020 00:47:44 - DEBUG   :: mylar.NZB_SEARCH.953 : ThreadPoolExecutor-0_2 : size given as: 11.0 MB
07-May-2020 00:47:44 - DEBUG   :: mylar.NZB_SEARCH.1003 : ThreadPoolExecutor-0_2 : store date used is : 2020-05-06
07-May-2020 00:47:44 - DEBUG   :: mylar.NZB_SEARCH.1004 : ThreadPoolExecutor-0_2 : date used is : 2020-05-06
07-May-2020 00:47:44 - DEBUG   :: mylar.NZB_SEARCH.1047 : ThreadPoolExecutor-0_2 : usedate: 2020-05-06
07-May-2020 00:47:44 - DEBUG   :: mylar.NZB_SEARCH.1093 : ThreadPoolExecutor-0_2 : [CONV] Wed, 06 May 2020 10:30:20 is after store date of 2020-05-06
07-May-2020 00:47:44 - DEBUG   :: mylar.NZB_SEARCH.1113 : ThreadPoolExecutor-0_2 : Entry: Batman – The Adventures Continue #3 (2020)
07-May-2020 00:47:44 - DEBUG   :: mylar.parseit.436 : ThreadPoolExecutor-0_2 : NEWLY SPLIT REORGD: ['Batman', 'XCV', 'The', 'Adventures', 'Continue', '#3', '(2020)']
07-May-2020 00:47:44 - DEBUG   :: mylar.parseit.522 : ThreadPoolExecutor-0_2 : [SPECIAL-CHARACTER ISSUE] Possible issue # : –
07-May-2020 00:47:44 - DEBUG   :: mylar.parseit.627 : ThreadPoolExecutor-0_2 : Issue number found: #3
07-May-2020 00:47:44 - DEBUG   :: mylar.parseit.471 : ThreadPoolExecutor-0_2 : checking date : 2020
07-May-2020 00:47:44 - DEBUG   :: mylar.parseit.474 : ThreadPoolExecutor-0_2 : date: 2020
07-May-2020 00:47:44 - DEBUG   :: mylar.parseit.802 : ThreadPoolExecutor-0_2 : datecheck: [{'date': '2020', 'position': 6, 'mod_position': 39}]
07-May-2020 00:47:44 - DEBUG   :: mylar.parseit.808 : ThreadPoolExecutor-0_2 : sctd: 2020
07-May-2020 00:47:44 - DEBUG   :: mylar.parseit.816 : ThreadPoolExecutor-0_2 : year verified as : None
07-May-2020 00:47:44 - DEBUG   :: mylar.parseit.824 : ThreadPoolExecutor-0_2 : year verified as: 2020
07-May-2020 00:47:44 - DEBUG   :: mylar.parseit.856 : ThreadPoolExecutor-0_2 : highest_series_position: 6
07-May-2020 00:47:44 - DEBUG   :: mylar.parseit.876 : ThreadPoolExecutor-0_2 : possible_issuenumbers: [{'number': 'XCV', 'position': 1, 'mod_position': 7, 'validcountchk': False}, {'number': '#3', 'position': 5, 'mod_position': 35, 'validcountchk': False}]
07-May-2020 00:47:44 - DEBUG   :: mylar.parseit.925 : ThreadPoolExecutor-0_2 : issue number :#3
07-May-2020 00:47:44 - DEBUG   :: mylar.parseit.954 : ThreadPoolExecutor-0_2 : issue_position: 5
07-May-2020 00:47:44 - DEBUG   :: mylar.parseit.981 : ThreadPoolExecutor-0_2 : issue verified as : 3
07-May-2020 00:47:44 - DEBUG   :: mylar.parseit.1116 : ThreadPoolExecutor-0_2 : sf_highest_series_pos: ['Batman', 'XCV', 'The', 'Adventures', 'Continue']
07-May-2020 00:47:44 - DEBUG   :: mylar.parseit.1168 : ThreadPoolExecutor-0_2 : series title possibly: Batman – The Adventures Continue
07-May-2020 00:47:44 - DEBUG   :: mylar.NZB_SEARCH.1130 : ThreadPoolExecutor-0_2 : parsed_info: {'parse_status': 'success', 'sub': None, 'comicfilename': 'Batman – The Adventures Continue #3 (2020)', 'comiclocation': None, 'series_name': 'Batman – The Adventures Continue', 'series_name_decoded': 'Batman – The Adventures Continue', 'issueid': None, 'dynamic_name': 'Batman||AdventuresContinue', 'series_volume': None, 'alt_series': None, 'alt_issue': None, 'issue_year': '2020', 'issue_number': '3', 'scangroup': None, 'reading_order': None, 'booktype': 'issue'}
07-May-2020 00:47:44 - DEBUG   :: mylar.NZB_SEARCH.1144 : ThreadPoolExecutor-0_2 : Booktypes do not match. Looking for Digital, this is a issue. Ignoring this result.
07-May-2020 00:47:44 - INFO    :: mylar.search_init.349 : ThreadPoolExecutor-0_2 : Alternate Search pattern detected...re-adjusting to : Batman The Adventures Continue
07-May-2020 00:47:44 - INFO    :: mylar.NZB_SEARCH.514 : ThreadPoolExecutor-0_2 : Shhh be very quiet...I'm looking for Batman The Adventures Continue issue: 3 (2020) using ddl [RSS].
07-May-2020 00:47:44 - DEBUG   :: mylar.NZB_SEARCH.578 : ThreadPoolExecutor-0_2 : findloop: 0 / findcount: 1
07-May-2020 00:47:44 - DEBUG   :: mylar.NZB_SEARCH.630 : ThreadPoolExecutor-0_2 : Sending request to [ddl] RSS for Batman The Adventures Continue : 003
07-May-2020 00:47:44 - DEBUG   :: mylar.NZB_SEARCH.857 : ThreadPoolExecutor-0_2 : checking search result: Batman – The Adventures Continue #1 (2020)
07-May-2020 00:47:44 - DEBUG   :: mylar.NZB_SEARCH.867 : ThreadPoolExecutor-0_2 : sub: Batman – The Adventures Continue #1 (2020)
07-May-2020 00:47:44 - DEBUG   :: mylar.NZB_SEARCH.916 : ThreadPoolExecutor-0_2 : comsize_b: 9437184
07-May-2020 00:47:44 - DEBUG   :: mylar.NZB_SEARCH.953 : ThreadPoolExecutor-0_2 : size given as: 9.0 MB
07-May-2020 00:47:44 - DEBUG   :: mylar.NZB_SEARCH.1003 : ThreadPoolExecutor-0_2 : store date used is : 2020-05-06
07-May-2020 00:47:44 - DEBUG   :: mylar.NZB_SEARCH.1004 : ThreadPoolExecutor-0_2 : date used is : 2020-05-06
07-May-2020 00:47:44 - DEBUG   :: mylar.NZB_SEARCH.1047 : ThreadPoolExecutor-0_2 : usedate: 2020-05-06
07-May-2020 00:47:44 - DEBUG   :: mylar.NZB_SEARCH.1089 : ThreadPoolExecutor-0_2 : [CONV] pubdate: 2020-04-01  < storedate: 2020-05-04
07-May-2020 00:47:44 - DEBUG   :: mylar.NZB_SEARCH.1090 : ThreadPoolExecutor-0_2 : Wed, 01 Apr 2020 08:47:58 is before store date of 2020-05-06. Ignoring search result as this is not the right issue.
07-May-2020 00:47:44 - DEBUG   :: mylar.NZB_SEARCH.857 : ThreadPoolExecutor-0_2 : checking search result: Batman – The Adventures Continue #2 (2020)
07-May-2020 00:47:44 - DEBUG   :: mylar.NZB_SEARCH.867 : ThreadPoolExecutor-0_2 : sub: Batman – The Adventures Continue #2 (2020)
07-May-2020 00:47:44 - DEBUG   :: mylar.NZB_SEARCH.916 : ThreadPoolExecutor-0_2 : comsize_b: 10485760
07-May-2020 00:47:44 - DEBUG   :: mylar.NZB_SEARCH.953 : ThreadPoolExecutor-0_2 : size given as: 10.0 MB
07-May-2020 00:47:44 - DEBUG   :: mylar.NZB_SEARCH.1003 : ThreadPoolExecutor-0_2 : store date used is : 2020-05-06
07-May-2020 00:47:44 - DEBUG   :: mylar.NZB_SEARCH.1004 : ThreadPoolExecutor-0_2 : date used is : 2020-05-06
07-May-2020 00:47:44 - DEBUG   :: mylar.NZB_SEARCH.1047 : ThreadPoolExecutor-0_2 : usedate: 2020-05-06
07-May-2020 00:47:44 - DEBUG   :: mylar.NZB_SEARCH.1089 : ThreadPoolExecutor-0_2 : [CONV] pubdate: 2020-04-15  < storedate: 2020-05-04
07-May-2020 00:47:44 - DEBUG   :: mylar.NZB_SEARCH.1090 : ThreadPoolExecutor-0_2 : Wed, 15 Apr 2020 09:58:28 is before store date of 2020-05-06. Ignoring search result as this is not the right issue.
07-May-2020 00:47:44 - DEBUG   :: mylar.NZB_SEARCH.857 : ThreadPoolExecutor-0_2 : checking search result: Batman – The Adventures Continue #3 (2020)
07-May-2020 00:47:44 - DEBUG   :: mylar.NZB_SEARCH.867 : ThreadPoolExecutor-0_2 : sub: Batman – The Adventures Continue #3 (2020)
07-May-2020 00:47:44 - DEBUG   :: mylar.NZB_SEARCH.916 : ThreadPoolExecutor-0_2 : comsize_b: 11534336
07-May-2020 00:47:44 - DEBUG   :: mylar.NZB_SEARCH.953 : ThreadPoolExecutor-0_2 : size given as: 11.0 MB
07-May-2020 00:47:44 - DEBUG   :: mylar.NZB_SEARCH.1003 : ThreadPoolExecutor-0_2 : store date used is : 2020-05-06
07-May-2020 00:47:44 - DEBUG   :: mylar.NZB_SEARCH.1004 : ThreadPoolExecutor-0_2 : date used is : 2020-05-06
07-May-2020 00:47:44 - DEBUG   :: mylar.NZB_SEARCH.1047 : ThreadPoolExecutor-0_2 : usedate: 2020-05-06
07-May-2020 00:47:44 - DEBUG   :: mylar.NZB_SEARCH.1093 : ThreadPoolExecutor-0_2 : [CONV] Wed, 06 May 2020 10:30:20 is after store date of 2020-05-06
07-May-2020 00:47:44 - DEBUG   :: mylar.NZB_SEARCH.1113 : ThreadPoolExecutor-0_2 : Entry: Batman – The Adventures Continue #3 (2020)
07-May-2020 00:47:44 - DEBUG   :: mylar.parseit.436 : ThreadPoolExecutor-0_2 : NEWLY SPLIT REORGD: ['Batman', 'XCV', 'The', 'Adventures', 'Continue', '#3', '(2020)']
07-May-2020 00:47:44 - DEBUG   :: mylar.parseit.522 : ThreadPoolExecutor-0_2 : [SPECIAL-CHARACTER ISSUE] Possible issue # : –
07-May-2020 00:47:44 - DEBUG   :: mylar.parseit.627 : ThreadPoolExecutor-0_2 : Issue number found: #3
07-May-2020 00:47:44 - DEBUG   :: mylar.parseit.471 : ThreadPoolExecutor-0_2 : checking date : 2020
07-May-2020 00:47:44 - DEBUG   :: mylar.parseit.474 : ThreadPoolExecutor-0_2 : date: 2020
07-May-2020 00:47:44 - DEBUG   :: mylar.parseit.802 : ThreadPoolExecutor-0_2 : datecheck: [{'date': '2020', 'position': 6, 'mod_position': 39}]
07-May-2020 00:47:44 - DEBUG   :: mylar.parseit.808 : ThreadPoolExecutor-0_2 : sctd: 2020
07-May-2020 00:47:44 - DEBUG   :: mylar.parseit.816 : ThreadPoolExecutor-0_2 : year verified as : None
07-May-2020 00:47:44 - DEBUG   :: mylar.parseit.824 : ThreadPoolExecutor-0_2 : year verified as: 2020
07-May-2020 00:47:44 - DEBUG   :: mylar.parseit.856 : ThreadPoolExecutor-0_2 : highest_series_position: 6
07-May-2020 00:47:44 - DEBUG   :: mylar.parseit.876 : ThreadPoolExecutor-0_2 : possible_issuenumbers: [{'number': 'XCV', 'position': 1, 'mod_position': 7, 'validcountchk': False}, {'number': '#3', 'position': 5, 'mod_position': 35, 'validcountchk': False}]
07-May-2020 00:47:44 - DEBUG   :: mylar.parseit.925 : ThreadPoolExecutor-0_2 : issue number :#3
07-May-2020 00:47:44 - DEBUG   :: mylar.parseit.954 : ThreadPoolExecutor-0_2 : issue_position: 5
07-May-2020 00:47:44 - DEBUG   :: mylar.parseit.981 : ThreadPoolExecutor-0_2 : issue verified as : 3
07-May-2020 00:47:44 - DEBUG   :: mylar.parseit.1116 : ThreadPoolExecutor-0_2 : sf_highest_series_pos: ['Batman', 'XCV', 'The', 'Adventures', 'Continue']
07-May-2020 00:47:44 - DEBUG   :: mylar.parseit.1168 : ThreadPoolExecutor-0_2 : series title possibly: Batman – The Adventures Continue
07-May-2020 00:47:44 - DEBUG   :: mylar.NZB_SEARCH.1130 : ThreadPoolExecutor-0_2 : parsed_info: {'parse_status': 'success', 'sub': None, 'comicfilename': 'Batman – The Adventures Continue #3 (2020)', 'comiclocation': None, 'series_name': 'Batman – The Adventures Continue', 'series_name_decoded': 'Batman – The Adventures Continue', 'issueid': None, 'dynamic_name': 'Batman||AdventuresContinue', 'series_volume': None, 'alt_series': None, 'alt_issue': None, 'issue_year': '2020', 'issue_number': '3', 'scangroup': None, 'reading_order': None, 'booktype': 'issue'}
07-May-2020 00:47:44 - DEBUG   :: mylar.NZB_SEARCH.1144 : ThreadPoolExecutor-0_2 : Booktypes do not match. Looking for Digital, this is a issue. Ignoring this result.
07-May-2020 00:47:44 - INFO    :: mylar.search_init.396 : ThreadPoolExecutor-0_2 : Could not find Issue 3 of Batman: The Adventures Continue (2020) using ddl [rss]
07-May-2020 00:47:44 - DEBUG   :: mylar.NZB_SEARCH.487 : ThreadPoolExecutor-0_2 : Using Newznab host of : Newz69
07-May-2020 00:47:44 - INFO    :: mylar.NZB_SEARCH.514 : ThreadPoolExecutor-0_2 : Shhh be very quiet...I'm looking for Batman: The Adventures Continue issue: 3 (2020) using Newz69 (newznab) [RSS].
07-May-2020 00:47:44 - DEBUG   :: mylar.NZB_SEARCH.578 : ThreadPoolExecutor-0_2 : findloop: 0 / findcount: 1
07-May-2020 00:47:44 - DEBUG   :: mylar.NZB_SEARCH.637 : ThreadPoolExecutor-0_2 : Sending request to RSS for Batman: The Adventures Continue : 003 (2020)
07-May-2020 00:47:45 - INFO    :: mylar.search_init.349 : ThreadPoolExecutor-0_2 : Alternate Search pattern detected...re-adjusting to : Batman The Adventures Continue
07-May-2020 00:47:45 - DEBUG   :: mylar.NZB_SEARCH.487 : ThreadPoolExecutor-0_2 : Using Newznab host of : Newz69
07-May-2020 00:47:45 - INFO    :: mylar.NZB_SEARCH.514 : ThreadPoolExecutor-0_2 : Shhh be very quiet...I'm looking for Batman The Adventures Continue issue: 3 (2020) using Newz69 (newznab) [RSS].
07-May-2020 00:47:45 - DEBUG   :: mylar.NZB_SEARCH.578 : ThreadPoolExecutor-0_2 : findloop: 0 / findcount: 1
07-May-2020 00:47:45 - DEBUG   :: mylar.NZB_SEARCH.637 : ThreadPoolExecutor-0_2 : Sending request to RSS for Batman The Adventures Continue : 003 (2020)
07-May-2020 00:47:45 - INFO    :: mylar.search_init.396 : ThreadPoolExecutor-0_2 : Could not find Issue 3 of Batman: The Adventures Continue (2020) using Newz69 [rss]
07-May-2020 00:47:45 - INFO    :: mylar.NZB_SEARCH.514 : ThreadPoolExecutor-0_2 : Shhh be very quiet...I'm looking for Batman: The Adventures Continue issue: 3 (2020) using ddl [RSS].
07-May-2020 00:47:45 - DEBUG   :: mylar.NZB_SEARCH.578 : ThreadPoolExecutor-0_2 : findloop: 0 / findcount: 1
07-May-2020 00:47:45 - DEBUG   :: mylar.NZB_SEARCH.630 : ThreadPoolExecutor-0_2 : Sending request to [ddl] RSS for Batman: The Adventures Continue : 03
07-May-2020 00:47:46 - DEBUG   :: mylar.NZB_SEARCH.857 : ThreadPoolExecutor-0_2 : checking search result: Batman – The Adventures Continue #1 (2020)
07-May-2020 00:47:46 - DEBUG   :: mylar.NZB_SEARCH.867 : ThreadPoolExecutor-0_2 : sub: Batman – The Adventures Continue #1 (2020)

**Comment by evilhero** [comment]
According to CV it's a digital series, so it's looking for the digital tag within the filename in order to make sure it's the correct series and volume. Understandably, if this is the only title with that name we should have an option to basically allow any booktype matches (well aside from TPB) - so that way - digital's, print's, and even one-shot's would match regardless of the actual book type.

Couldn't make this a global setting since there are tonnes of series that have overlapping digital/print series with identical numbering - but could force it from the Edit Settings tab only for a digital series (ie. ```Ignore booktype (digital) for search matches```). 

Have to think about this one abit, as it's come up previously but because there's no real structure to the naming we'd have to try and account for the consensus and minimise the outlying casualties.

Also, pretty sure this overlaps is a continuation of #183

**Comment by barbequesauce** [comment]
@rutskiuk this enhancement went into dev this weekend. can you give it a shot please?

**Comment by barbequesauce** [comment]
Can we close this @rutskiuk ?

**Comment by rutskiuk** [comment]
Yes please!
I just did a test and DDL does seem to work now
