### ISSUE TITLE
Question on file touches/updates

### ISSUE THREAD

**Issue by Serneum** [mylar3/mylar3#280]
I'm doing incremental backups of a good chunk of my server, especially my comics after having lost my full collection multiple times. I've been noticing some odd behavior from my comic backups, and only my comic backups: I frequently see comics getting added to the incremental backup files even though they are not new. This implies that something about the file has changed.

At first, I thought it might be because I'm putting my comics on a RAID and the device IDs could be different, though it's just doing a mirror and I don't know if that has an impact on incremental backups or not. I added a `--no-check-device` flag to my `tar` command for my backups, but still saw 6gb of comics that have previously existed get backed up overnight.

Given all of that, I'm wondering if you might have some insight into whether or not Mylar is doing some sort of touch or update on files periodically.

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Branch / commit: python3-dev / 874e5d961a1da4884d6c9e9b262b2a2b4667cfc0

**Comment by evilhero** [comment]
If you're just talking about leaving Mylar alone and not doing anything related to those files from within the system, the short answer is no. Mylar doesn't touch anything on the OS level when it scans for new comics (unless you have rename or metadata options enabled), or even when it refreshes a series (everything is in the db). 

However, if you have enforce permissions on within Mylar, it might try and perform a chown/chmod on the series directory (and probably everything therein as it would be recursive) on each refresh series call (which would happen every X minutes from oldest upated to newest). 

Not sure if the ownership / permissions are identical prior to the chown/chmod from within Mylar if that will hammer the existing with the same, or if it just does a "it's already set, move on" kinda deal. Just disabling the enforce perms option within Mylar and seeing if it changes your backups would be the easiest way to tell if anything is amiss in that regards.

**Comment by Serneum** [comment]
And just to clarify, the rename and metadata options only apply when an issue is newly downloaded anyway, correct? I'll look into the Enforce Permissions change since I do believe that is on

**Comment by evilhero** [comment]
Yes, rename and metadata options will only get done during a post-processing and or a manual call to each (for which the options are present on the series detial page).

**Comment by barbequesauce** [comment]
We good here?

**Comment by Serneum** [comment]
I believe so. I've been monitoring it throughout the week and it appears that turning off the Enforce Permissions settings fixed my issue
