### ISSUE TITLE
Pushbullet notifications not functioning

### ISSUE THREAD

**Issue by BuksheeTester** [mylar3/mylar3#292]
Pushbullet notifications do not appear to function. Have tried using the test function with and without device ID

-  Using Docker
 - 880f5ba278aadb7054f1dfd4b788f0343ad09805 (master) 

When clicking the test function in browser the green notification box appears with nothing in it. Nothing appears in the debug log.

Not sure if this would/should work but tried to send test through URL

https://myurl/Mylar/testpushbullet?apikey={APIKEY}

Response in browser

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/cherrypy/_cprequest.py", line 638, in respond
    self._do_respond(path_info)
  File "/usr/local/lib/python3.7/dist-packages/cherrypy/_cprequest.py", line 697, in _do_respond
    response.body = self.handler()
  File "/usr/local/lib/python3.7/dist-packages/cherrypy/lib/encoding.py", line 219, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/app/mylar/webserve.py", line 6102, in testpushbullet
    pushbullet = notifiers.PUSHBULLET(test_apikey=apikey)
  File "/app/mylar/notifiers.py", line 276, in __init__
    'Authorization': 'Basic %s' % base64.b64encode(self.apikey + ":")}
  File "/usr/lib/python3.7/base64.py", line 58, in b64encode
    encoded = binascii.b2a_base64(s, newline=False)
TypeError: a bytes-like object is required, not 'str'

I am using a reverse proxy but have also tested pushbullet directly with the IP:PORT and have the same results.

**Comment by barbequesauce** [comment]
Need debug logs please, also your OS, branch, current commit etc. The template is there for a reason....

**Comment by BuksheeTester** [comment]
OS Details:
Docker
Using hotio/mylar3 on Dockerhub
Linux version 4.19.97-v7+
Ubuntu 19.10

Branch/Version (I just did a fresh pull):
7d59772438a08e9a8b398c1548472d5ed620f962
Version: v0.3.6 ( master) 


I would put the debug log in here but, as mentioned, absolutely nothing appears in reference to pushbullet. The only thing you can see is:

20-May-2020 12:47:20 - INFO    :: mylar.toggleVerbose.4095 : CP Server Thread-10 : Verbose (DEBUG) logging is enabled
20-May-2020 12:47:20 - DEBUG   :: mylar.toggleVerbose.4096 : CP Server Thread-10 : If you can read this message, debug logging is now working
20-May-2020 12:47:20 - INFO    :: mylar.toggleVerbose.4099 : CP Server Thread-10 : config file has been loaded from: /config/app/config.ini

After clicking the test button in browser nothing is updated in the logs. The next thing to appear was the 'Folder Check' task running on schedule. The only thing of note is the error that is previously mentioned which appears in the docker logs and also appears in the browser when attempting to access 

https://myurl/Mylar/testpushbullet?apikey={APIKEY}

**Comment by barbequesauce** [comment]
Thanks. Any errors showing in the browser's javascript console?

**Comment by BuksheeTester** [comment]
I can't see any javascript errors the only mention is:

GEThttps://myurl/Mylar/testpushbullet?apikey={APIKEY}
[HTTP/1.1 500 Internal Server Error 36ms]

Just to make sure, I have also tried this using a different browser that does not have any browser extensions or add-ons installed. I get the same results.

**Comment by BuksheeTester** [comment]
Can confirm this is now working on the python3-dev branch. Happy to close and thanks!
