### ISSUE TITLE
Cult Classic: Return To Whisper (2018) unable to retrieve issue information

### ISSUE THREAD

**Issue by miracle152005** [mylar3/mylar3#297]
**Describe the bug**
Cult Classic: Return To Whisper (2018) can not retrieve issue information.

**CarePackage**
[mylar.log](https://github.com/mylar3/mylar3/files/4671607/mylar.log)

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04 hotio/mylar3:latest docker
 - Branch / commit: Version: v0.3.6 ( master)

**Additional information**
This is most likely because comicvine lists the latest issues as "2&3" and "4&5"
Error happened at timestamp 2020-05-23 10:46:02

Could you please take a look.
Thanks

Best regards
miracle152005

**Comment by barbequesauce** [comment]
Yup...

```
44352 23-May-2020 08:39:56 - INFO    :: mylar.updateissuedata.1100 : Thread-17 : Now adding/updating issues for Cult Classic: Return To Whisper
44353 23-May-2020 08:39:56 - ERROR   :: mylar.updateissuedata.1257 : Thread-17 : 2 & 3 this has an alpha-numeric in the issue # which I cannot account for.
44354 23-May-2020 08:39:56 - ERROR   :: mylar.excepthook.315 : Thread-17 : Uncaught exception: Traceback (most recent call last):
44355   File "/opt/mylar.py3/mylar/logger.py", line 337, in new_run
44356     old_run(*args, **kwargs)
44357   File "/usr/local/lib/python3.8/threading.py", line 870, in run
44358     self._target(*self._args, **self._kwargs)
44359   File "/opt/mylar.py3/mylar/importer.py", line 348, in addComictoDB
44360     issuedata = updateddata['issuedata']
44361 TypeError: 'NoneType' object is not subscriptable
44362

```

**Comment by barbequesauce** [comment]
@evilhero I managed to get past the "2 & 3" / "4 & 5" error with [this](https://github.com/mylar3/mylar3/commit/781f5c77ed78a0aa6d0a9e4549ec050f4640a5eb), but now it's having trouble inserting into the db and I have NO idea why...  thoughts?

```
45943 23-May-2020 09:07:39 - INFO    :: mylar.addComictoDB.403 : Thread-12 : Updating complete for:
45944 23-May-2020 09:07:39 - ERROR   :: mylar.excepthook.315 : Thread-12 : Uncaught exception: Trace
45945   File "/opt/mylar.py3/mylar/logger.py", line 337, in new_run
45946     old_run(*args, **kwargs)
45947   File "/usr/local/lib/python3.8/threading.py", line 870, in run
45948     self._target(*self._args, **self._kwargs)
45949   File "/opt/mylar.py3/mylar/importer.py", line 424, in addComictoDB
45950     logger.fdebug('issue: ' + latestiss + ' status before chk :' + str(statbefore['Status']))
45951 TypeError: 'NoneType' object is not subscriptable
45952

```

**Comment by barbequesauce** [comment]
@miracle152005 the fix for this went in over the weekend and it tests ok for me - can you give it a shot please?

**Comment by miracle152005** [comment]
Hi,
i updated the installation to a docker container which displays the following version:
 86c9264ec36c7d92276aec036d2bfb3f501cc1bd

Now I can refresh the series but now I am no longer able to view the website in the browser.
No entries in log, just this errormessage in the browser:

Error !
TypeError: object of type 'NoneType' has no len()
<td id="issuenumber">${issue['Issue_Number']}</td> <% if len(issue['IssueName']) > 70: issuename = "%s..." % issue['IssueName'][:70] else: issuename = issue['IssueName'] endif try:
/app/data/interfaces/default/comicdetails.html, line 395:
if len(issue['IssueName']) > 70:
/app/data/interfaces/default/base.html, line 87:
${next.body()}
/usr/local/lib/python3.7/dist-packages/mako/runtime.py, line 947:
callable_(context, *args, **kwargs)
/usr/local/lib/python3.7/dist-packages/mako/runtime.py, line 920:
_exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
/usr/local/lib/python3.7/dist-packages/mako/runtime.py, line 883:
**_kwargs_for_callable(callable_, data)
/usr/local/lib/python3.7/dist-packages/mako/template.py, line 476:
return runtime._render(self, self.callable_, args, data)
/app/mylar/webserve.py, line 56:
return template.render(http_root=mylar.CONFIG.HTTP_ROOT, **kwargs)

**Comment by evilhero** [comment]
PR fix (#315)  for that last bug is awaiting merge into python3-dev.

**Comment by barbequesauce** [comment]
merged - give it a try ;)

**Comment by miracle152005** [comment]
Works now.
Thanks.
