### ISSUE TITLE
object TypeError for 4050-50575

### ISSUE THREAD

**Issue by apiontek** [mylar3/mylar3#312]
**Describe the bug**
I added Captain Marvel (2012) [4050-50575] and it generated the error below; On the front screen of mylar3 I see the Series listed, but when I click it to try again to view it, the same error comes up:

```
TypeError: object of type 'NoneType' has no len()
<td id="issuenumber">${issue['Issue_Number']}</td> <% if len(issue['IssueName']) > 70: issuename = "%s..." % issue['IssueName'][:70] else: issuename = issue['IssueName'] endif try:
/opt/mylar/data/interfaces/default/comicdetails.html, line 395:
if len(issue['IssueName']) > 70:
/opt/mylar/data/interfaces/default/base.html, line 87:
${next.body()}
/home/adam/.virtualenvs/mylar3/lib/python3.8/site-packages/mako/runtime.py, line 947:
callable_(context, *args, **kwargs)
/home/adam/.virtualenvs/mylar3/lib/python3.8/site-packages/mako/runtime.py, line 920:
_exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
/home/adam/.virtualenvs/mylar3/lib/python3.8/site-packages/mako/runtime.py, line 878:
_render_context(
/home/adam/.virtualenvs/mylar3/lib/python3.8/site-packages/mako/template.py, line 476:
return runtime._render(self, self.callable_, args, data)
/opt/mylar/mylar/webserve.py, line 56:
return template.render(http_root=mylar.CONFIG.HTTP_ROOT, **kwargs)
```

**CarePackage**
[carepackage.zip](https://github.com/mylar3/mylar3/files/4693527/carepackage.zip)

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Branch / commit: python3-dev/71e2f14

**Comment by evilhero** [comment]
Logs say there's no ComicVine API key present - do you have one entered into Mylar ?

**Comment by barbequesauce** [comment]
merged - give it a try :)

**Comment by apiontek** [comment]
Having spent the better part of what should have been sleep hours setting up mylar3, I encountered several series with the same problem...

...and now they're all working! I also had issues where "Recheck files" wasn't recognizing files I'd put in place manually, and that also seems to be working now.

Thanks!
