### ISSUE TITLE
One issue downloads then nothing until I restart Mylar?

### ISSUE THREAD

**Issue by paulr24** [mylar3/mylar3#321]
Hi, I recently started using Mylar and I'm experiencing some strange issues. I have set up both NZB and DDL (GetComics) as search providers. For some reason upon opening Mylar it seems that it will often grab one issue of a comic via NZB, but then stop (but not always, sometimes it will not grab anything). If I close and re-open Mylar, it grabs one comic again, then stops. Via DDL comics seem to download at random as well, and it's rare.

What can I do to troubleshoot this? I have set logging to verbose and can post logs but not sure where to start since they're obviously long.

**Comment by barbequesauce** [comment]
on the config page, click the "Care Package" button and post the zip here. It will give us system info, configuration data, a copy of your DB and log files....

**Comment by paulr24** [comment]
[carepackage.zip](https://github.com/mylar3/mylar3/files/4699842/carepackage.zip)

**Comment by paulr24** [comment]
> on the config page, click the "Care Package" button and post the zip here. It will give us system info, configuration data, a copy of your DB and log files....

Thanks, here you go!
[carepackage.zip](https://github.com/mylar3/mylar3/files/4699845/carepackage.zip)

**Comment by paulr24** [comment]
I noticed this was marked invalid, is there anything more I need to do here for troubleshooting? Thanks!

**Comment by barbequesauce** [comment]
No worries - invalid means "something aint right here". I'll take a look at your care package in a bit...

**Comment by barbequesauce** [comment]
Looks like this exception is killing the search queue:

```
28-May-2020 03:08:16 - INFO    :: mylar.sender.42 : SEARCH-QUEUE : parameters set to {'apikey': '-REDACTED-', 'mode': 'addurl', 'name': 'http://192.168.1.-REDACTED-4:8090/api?apikey=-REDACTED-&cmd=downloadNZB&nzbname=Daredevil.013.2020.Digital.Zone-Empire.nzb', 'cmd': 'downloadNZB', 'nzbname': 'Daredevil.013.2020.Digital.Zone-Empire.nzb', 'output': 'json', 'priority': '-100', 'cat': 'comics'}
28-May-2020 03:08:16 - INFO    :: mylar.sender.43 : SEARCH-QUEUE : sending now to http://-REDACTED-.mynetgear.com:8080/api
28-May-2020 03:08:16 - ERROR   :: mylar.excepthook.315 : SEARCH-QUEUE : Uncaught exception: Traceback (most recent call last):
  File "C:\mylar3-0.3.6\mylar\logger.py", line 337, in new_run
    old_run(*args, **kwargs)
  File "C:\Users\paulr\AppData\Local\Programs\Python\Python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\mylar3-0.3.6\mylar\helpers.py", line 3133, in search_queue
    ss_queue = mylar.search.searchforissue(item['issueid'])
  File "C:\mylar3-0.3.6\mylar\search.py", line 1877, in searchforissue
    foundNZB, prov = search_init(ComicName, IssueNumber, str(IssueYear), SeriesYear, Publisher, IssueDate, StoreDate, actissueid, AlternateSearch, UseFuzzy, ComicVersion, SARC=SARC, IssueArcID=IssueArcID, mode=mode, rsscheck=rsscheck, ComicID=ComicID, filesafe=Comicname_filesafe, allow_packs=allow_packs, oneoff=oneoff, manual=manual, torrentid_32p=TorrentID_32p, digitaldate=DigitalDate, booktype=booktype)
  File "C:\mylar3-0.3.6\mylar\search.py", line 360, in search_init
    findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="no", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName, allow_packs=allow_packs, oneoff=oneoff, cmloopit=cmloopit, manual=manual, torznab_host=torznab_host, torrentid_32p=torrentid_32p, digitaldate=digitaldate, booktype=booktype)
  File "C:\mylar3-0.3.6\mylar\search.py", line 1504, in NZB_SEARCH
    searchresult = searcher(nzbprov, nzbname, mylar.COMICINFO, links, IssueID, ComicID, tmpprov, newznab=newznab_host, torznab=torznab_host, rss=RSS)
  File "C:\mylar3-0.3.6\mylar\search.py", line 2645, in searcher
    sendtosab = ss.sender()
  File "C:\mylar3-0.3.6\mylar\sabnzbd.py", line 49, in sender
    sendresponse = sendit.json()
  File "C:\Users\paulr\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\paulr\AppData\Local\Programs\Python\Python37\lib\site-packages\simplejson\__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "C:\Users\paulr\AppData\Local\Programs\Python\Python37\lib\site-packages\simplejson\decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "C:\Users\paulr\AppData\Local\Programs\Python\Python37\lib\site-packages\simplejson\decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Which seems to be a bad response from SAB. Is it really at https://-redacted-mynetgear.com:8080/api ?

**Comment by paulr24** [comment]
Yes actually, that's my DDNS host name. I guess that's probably unnecessary since it won't be accessing SABnzbd remotely so I just changed it to localhost and will see how things go.

**Comment by paulr24** [comment]
That doesn't seem to have fixed the issue. Here is a new care package.
[carepackage (1).zip](https://github.com/mylar3/mylar3/files/4733915/carepackage.1.zip)

**Comment by barbequesauce** [comment]
@evilhero here's the relevant bit - SAB so I'm barely following what broke

```
04-Jun-2020 01:52:20 - INFO    :: mylar.searcher.2138 : SEARCH-QUEUE : Found Avengers (2020) #33 using NZBGeek (newznab)
04-Jun-2020 01:52:23 - INFO    :: mylar.sender.42 : SEARCH-QUEUE : parameters set to {'apikey': '-REDACTED-', 'mode': 'addurl', 'name': 'http://192.168.1.-REDACTED-4:8090/api?apikey=-REDACTED-&cmd=downloadNZB&nzbname=Avengers.033.2020.Digital.Zone-Empire.nzb', 'cmd': 'downloadNZB', 'nzbname': 'Avengers.033.2020.Digital.Zone-Empire.nzb', 'output': 'json', 'priority': '-100', 'cat': 'comics'}
04-Jun-2020 01:52:23 - INFO    :: mylar.sender.43 : SEARCH-QUEUE : sending now to http://-REDACTED-:8080/api
04-Jun-2020 01:52:26 - ERROR   :: mylar.excepthook.315 : SEARCH-QUEUE : Uncaught exception: Traceback (most recent call last):
  File "C:\mylar3-0.3.6\mylar\logger.py", line 337, in new_run
    old_run(*args, **kwargs)
  File "C:\Users\paulr\AppData\Local\Programs\Python\Python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\mylar3-0.3.6\mylar\helpers.py", line 3133, in search_queue
    ss_queue = mylar.search.searchforissue(item['issueid'])
  File "C:\mylar3-0.3.6\mylar\search.py", line 1877, in searchforissue
    foundNZB, prov = search_init(ComicName, IssueNumber, str(IssueYear), SeriesYear, Publisher, IssueDate, StoreDate, actissueid, AlternateSearch, UseFuzzy, ComicVersion, SARC=SARC, IssueArcID=IssueArcID, mode=mode, rsscheck=rsscheck, ComicID=ComicID, filesafe=Comicname_filesafe, allow_packs=allow_packs, oneoff=oneoff, manual=manual, torrentid_32p=TorrentID_32p, digitaldate=DigitalDate, booktype=booktype)
  File "C:\mylar3-0.3.6\mylar\search.py", line 360, in search_init
    findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="no", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName, allow_packs=allow_packs, oneoff=oneoff, cmloopit=cmloopit, manual=manual, torznab_host=torznab_host, torrentid_32p=torrentid_32p, digitaldate=digitaldate, booktype=booktype)
  File "C:\mylar3-0.3.6\mylar\search.py", line 1504, in NZB_SEARCH
    searchresult = searcher(nzbprov, nzbname, mylar.COMICINFO, links, IssueID, ComicID, tmpprov, newznab=newznab_host, torznab=torznab_host, rss=RSS)
  File "C:\mylar3-0.3.6\mylar\search.py", line 2645, in searcher
    sendtosab = ss.sender()
  File "C:\mylar3-0.3.6\mylar\sabnzbd.py", line 49, in sender
    sendresponse = sendit.json()
  File "C:\Users\paulr\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\paulr\AppData\Local\Programs\Python\Python37\lib\site-packages\simplejson\__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "C:\Users\paulr\AppData\Local\Programs\Python\Python37\lib\site-packages\simplejson\decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "C:\Users\paulr\AppData\Local\Programs\Python\Python37\lib\site-packages\simplejson\decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by evilhero** [comment]
Can you do a ```pip list``` and verify what your simplejson version is in the resulting list ? Also, what version of SABnzbd are you running ? 

Also DDL does not use a provider of any kind, it downloads directly via http so it uses a completely different methodology to download the issues as opposed to nzb.

**Comment by paulr24** [comment]
Hi @evilhero! Actually I have recently started a new project and have migrated over to Docker. I'm using the hotio/mylar3 container, which I understand is not an official container, but it's the only one that has been updated to Mylar3 AFAIK.

Things seem to have gone smoothly, except I'm experiencing one little issue. I set up NZBGet as my downloader but after an NZB was grabbed got an error saying "global name 'nzbget_params' is not defined." I'm pretty sure I have my settings setup correctly, but maybe not?

![image](https://user-images.githubusercontent.com/61079482/85254472-64bfad00-b42e-11ea-98d7-b4a5f38913a4.png)

**Comment by barbequesauce** [comment]
OK - can you please check out dev if you're not there already, and update? This should eliminate that error you were getting...

**Comment by paulr24** [comment]
Thanks! I updated to the dev branch but now I'm getting "Unable to send nzb file to NZBGet. There was an unknown parameter error."

**Comment by barbequesauce** [comment]
ok so that clears that up - we are getting an unsuccessful response from NG when you send the NZO. Can you attach the log from NG capturing the attempt at sending please?

**Comment by paulr24** [comment]
Sorry, I've been kind of all over the place here and my new setup has had me doing a lot of various troubleshooting with Docker containers. It turns out at some point I added an NZBGet password and forgot to add it in Mylar settings, whoops...

So that issue is behind me. Now things are downloading, which is great! Only issue left is that after downloading, the issues are not being marked as archived, they still show as snatched. I checked the logs after download and I see the following:

![image](https://user-images.githubusercontent.com/61079482/85626700-70cc8a00-b63b-11ea-906e-8f5a9b23683e.png)

Here are my post-processing settings:

![image](https://user-images.githubusercontent.com/61079482/85626784-8b9efe80-b63b-11ea-8c59-3976af3600a0.png)

Is there anything I have set incorrectly?

**Comment by barbequesauce** [comment]
Is folder monitor watching the same directory that NG is dropping files? Is so, make it a different location... or you will start to see conflicts between CDH & Folder Monitor, with FM picking up files before CDH does...

**Comment by paulr24** [comment]
Hmm yes both FM and CDH are set to the same location. I'm a bit confused, if I were to change the FM location I can't think of one that would make sense. Should I just disable FM?

I'm also wondering about the scripts in general, I know when I had Mylar on my Windows machine I had a scripts folder, but I don't seem to see one within /config in the Docker setup.

**Comment by barbequesauce** [comment]
Glad you figured out the path issue. Can't help you here, i'm not a CR user - maybe @evilhero can provide some advice...

**Comment by evilhero** [comment]
Honestly, I wouldn't use the Organizer in CR if the only thing you're doing with it is putting in publisher folders, as Mylar can do that for you and monitor it in the process.  ( ```Folder Format = $Publisher\$Series ($Year)``` ).  Now if you're doing something else, then that's another thing - but if it's just Organizing the folders, like I said I'd let Mylar do that part and then it can monitor it, and CR would still be able to monitor the folders without you having to do anything therein. Otherwise, you're going to have to manually edit the series paths after each run of your Organizer, which might be on each download. I'm not sure why you would want to add more work to something that's already being done for you.

If you're saying you use the Organizer to also tag - again, Mylar does that when it downloads an issue if the option is enabled, so unless there's something specific that CR is tagging (as far as I know it's the same shizzle), just let Mylar do all the heavy lifting, and then you can use CR to scan the finished issues after it's all been done. 

I mean CR is / has been dead for years - people are using it mainly out of their history with the project and may not even realise there are other alternatives out there, maybe not better, but at the very least as capable in most aspects. Or maybe they don't want to change, which again is totally fine - until something needs fixing or needs to get updated code-wise. Plus the alternatives are probably all open-source and actively developed, so getting something addressed/added/fixed is usually not that big of an issue.

Note. I have used CR in the past. Hell, I posted the first iteration of Mylar on the forums there. I'm not saying it's not a great piece of software by any stretch. I'm just saying, when things break (and they will, computers are gonna compute) - it's not going to be such a fun/easy time getting things back, especially since requirements might break things on updating.

**Comment by barbequesauce** [comment]
Are we OK to close this @paulr24 ?
