### ISSUE TITLE
Mako Runtime Error

### ISSUE THREAD

**Issue by burnshroom** [mylar3/mylar3#329]
When selecting The Flash (2011) (comicvine ID: 4050-43018, an error occurs with a tab titled "Mako Runtime Error"

The page displays this:

Error !
KeyError: 'Issuename'
<td id="aint_issuenumber">${annual_Number}</td> <td id="aissuenumber">${annual['Issue_Number']}</td> <% if annual['Issuename'] is not None: if len(annual['IssueName']) > 70: aissuename = "%s..." % annual['IssueName'][:70] else: aissuename = annual['IssueName'] try:
/mnt/mylar3/data/interfaces/carbon/comicdetails.html, line 587:
if annual['Issuename'] is not None:
/mnt/mylar3/data/interfaces/carbon/base.html, line 87:
${next.body()}
/home/shroom/.local/lib/python3.8/site-packages/mako/runtime.py, line 947:
callable_(context, *args, **kwargs)
/home/shroom/.local/lib/python3.8/site-packages/mako/runtime.py, line 920:
_exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
/home/shroom/.local/lib/python3.8/site-packages/mako/runtime.py, line 878:
_render_context(
/home/shroom/.local/lib/python3.8/site-packages/mako/template.py, line 476:
return runtime._render(self, self.callable_, args, data)
/mnt/mylar3/mylar/webserve.py, line 56:
return template.render(http_root=mylar.CONFIG.HTTP_ROOT, **kwargs)

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Branch / commit: python3-dev / f1cc119

**Comment by barbequesauce** [comment]
@burnshroom give that a shot please

**Comment by burnshroom** [comment]
The issue remains.

Also affecting Fantastic Four volume 1 (comicvine ID: 4050-2045)

**Comment by barbequesauce** [comment]
Which interface?

**Comment by burnshroom** [comment]
Carbon.  Both open fine in default interface.

**Comment by barbequesauce** [comment]
make sure you're current, then give it one more shot please

**Comment by burnshroom** [comment]
Current and tested... will close as it seems to be fixed. 

Thanks.
