### ISSUE TITLE
Error with books with Annuals

### ISSUE THREAD

**Issue by leaderdog** [mylar3/mylar3#336]
Hi,
I just reinstalled windows on the new Ryzen system for the server.  I had copied all the important information and then dropped it back in when I installed Mylar.

Now any series that I click on that has annuals in will give me an error.  nothing in the log tho.

`Error !
KeyError: 'Issuename'
<td id="aint_issuenumber">${annual_Number}</td> <td id="aissuenumber">${annual['Issue_Number']}</td> <% if annual['Issuename'] is not None: if len(annual['IssueName']) > 70: aissuename = "%s..." % annual['IssueName'][:70] else: aissuename = annual['IssueName'] try:
C:/mylar3/data/interfaces/default/comicdetails.html, line 587:
if annual['Issuename'] is not None:
C:/mylar3/data/interfaces/default/base.html, line 87:
${next.body()}
C:\Python37\lib\site-packages\mako\runtime.py, line 947:
callable_(context, *args, **kwargs)
C:\Python37\lib\site-packages\mako\runtime.py, line 920:
_exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
C:\Python37\lib\site-packages\mako\runtime.py, line 883:
**_kwargs_for_callable(callable_, data)
C:\Python37\lib\site-packages\mako\template.py, line 476:
return runtime._render(self, self.callable_, args, data)
C:\mylar3\mylar\webserve.py, line 56:
return template.render(http_root=mylar.CONFIG.HTTP_ROOT, **kwargs)
`

I'm  running python 3.7.7 instead of 3.7.4
but other than that and well the system being better, I don't think anything else has changed.

$Annual is still where it's suppose to be in the Renaming options.

I did a git pull just to see if something was outdated, but it said up to date.

Mylar Version: master [v0.4.0 - Are we still friends?]
-- git (build c11530f4f0510ecd97bc6a3de2a197bcadf2e15f)
Python Version : 3.7.7
Language : en_CA.cp1252
windows 10 fresh install of latest version 2004

**Comment by evilhero** [comment]
We caught this too late to get it into master before the merge unfortunately. The fix is in development atm, but we'll probably have to push an early fix to master way sooner than planned.

**Comment by leaderdog** [comment]
Aw ok.  I screwed up when I installed it. I forgot I was on dev. 

so I did the "git checkout python3-dev (which was in my config.ini already) and it switched. nothing downloaded tho

git pull said already up to date 

Started Mylar up again.  series with Annuals are working again.  /shrug

**Comment by barbequesauce** [comment]
so are we good to close this?

**Comment by leaderdog** [comment]
Yeah sorry. I'll close it.

It's working great now
