### ISSUE TITLE
Unable to send torrent to client. Assuming incomplete

### ISSUE THREAD

**Issue by thedoublejay** [mylar3/mylar3#350]
**Describe the bug**
I'm setting up my Mylar3 via docker in my NAS. I'm using transmission to download my torrents. DDL works fine - post processed and completed. However for torrents, I keep on having the same error with magnet urls. I'm using hotio/mylar.

Magnet files are found, but after that, there's an error - invalid format and unable to send torrent.

![chrome_Cv0V92KXJr](https://user-images.githubusercontent.com/25013382/85149863-6188bd80-b284-11ea-9fa3-70bef0b9c1b7.png)

**Environment (please complete the following information):**
 - OS: Linux (Synology)
 - Branch / commit: python3-dev - 6c7f547b48113c402ac167466f1ada3f19d98932 

**Additional information**
Add any other information about the problem here.

**Comment by evilhero** [comment]
Unfortunately it might be a transmission problem (with the code base we're using not with the client per-se). 

I just tested the same item you did against an rutorrent instance and the magnet worked fine (it took a few minutes to resolve the metadata however). This leads me to believe that we might not be handling magnet links properly in the transmissionrpc client we use. Unfortunately I don't use transmission at all so I can't really test anything in regards to it - might have to tag @barbequesauce to help on this one ;)

**Comment by barbequesauce** [comment]
I knew that would happen 😄 

What version of transmission are you using?

**Comment by thedoublejay** [comment]
I'm using Transmission 3.00 (bb6b5a062e).

**Comment by barbequesauce** [comment]
First review, transmissionrpc hasn't changed since 2013 and there are no significant issues reported for backwards compatibility in 3.0.0. 

It looks like you restarted Mylar without the -v verbose/debug flag, so the log in the carepackage is mssing the useful stuff. If you could reconfigure it to start up in debug mode and then try again, we might get better data in another carepackage.

With that in mind - are regular torrents working, and it's just magnets?

**Comment by thedoublejay** [comment]
[carepackage.zip](https://github.com/mylar3/mylar3/files/4807311/carepackage.zip)

I'm not sure if regular torrents are working. Not sure how to pass it from Mylar to Transmission. Most of my fetches where magnet so I only used it via magnets.

**Comment by barbequesauce** [comment]
Still not in debug...

while you get a debug log, can you take a look at the Batman/Superman #9 torrent file in your cache directory and paste the contents please?

**Comment by thedoublejay** [comment]
I re-uploaded. I don't see any torrent file on the cache directory.
[carepackage.zip](https://github.com/mylar3/mylar3/files/4808980/carepackage.zip)

**Comment by barbequesauce** [comment]
Sorry for the delay on this. Transmission 3 didnt like Raspbian Jessie...

Just to confirm, you don't have a file that matches `/config/app/cache/Batman-Superman_2_2*9.torrent` ? 

I can't reproduce the issue - I've had no issue pulling `Batman/Superman #2 The Last Kryptonian-DCP` from ETTV...

**Comment by barbequesauce** [comment]
Any update here?

**Comment by barbequesauce** [comment]
Feel free to reopen if you have additional details.
