### ISSUE TITLE
Searching for Issues of The Land That Time Forgot (2018) results in an exception

### ISSUE THREAD

**Issue by miracle152005** [mylar3/mylar3#353]
**Describe the bug**
Searching for the issue of "The Land That Time Forgot (2018) (https://comicvine.gamespot.com/the-land-that-time-forgot/4050-115892/)" results in an exception. Searches are no longer possible after this exception.

Could you please take a look.
Thanks
Best regards
miracle152005

**Debug Log**
[mylar.log](https://github.com/mylar3/mylar3/files/4808562/mylar.log)

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04.
 - Branch / commit: 6c7f547b48113c402ac167466f1ada3f19d98932

**Comment by miracle152005** [comment]
My understanding of the issue is that it happens because one result of the nzb search has the name "The Land That Time Forgot 001" as well as "Fear on Four Worlds 004" in the name. This prevents an correct assignment of the required values.

**Comment by barbequesauce** [comment]
What indexer are you finding this on?

**Comment by miracle152005** [comment]
The indexer used is nzbfinder.ws

**Comment by barbequesauce** [comment]
This is a difficult one, largely related to the file naming conflicting with anything resembling "normal" practices. Using "Part" to indicate issue number when most other usages of that article refer to volumes, including issue titles in the filenames, etc.

Not sure we can address this specific edge case; happy to see a PR that addresses the search and filechecker aspects though...
