### ISSUE TITLE
readlist - downloads via opds no longer auto marked as "read" is this a bug?

### ISSUE THREAD

**Issue by HypKin** [mylar3/mylar3#357]
**Describe the bug**
I'm not sure if this is a bug or if this was a bug before.

i'm using chunky comic reader on ios and download comcis via opds. mostly via the readling list feature.

I havent read a lot in the last few months (as there wasnt a lot to read) but i started again in the last few days.

so i just found out, that comics that i download via the reading list opds feed are no longer marked as "read". this was i nice behaviour for me. is this how its supposed to be or did i stumble on a bug?

**CarePackage**
500 error as mentioned in my other issue

**Environment (please complete the following information):**
 - OS: windows 10
 - Master  e29114901810346e52486c8681c6b154639bcf86 (master)

**Comment by barbequesauce** [comment]
can you either switch to the dev branch and update, so you get the new carepackage fix, and then attach a carepackage? Or attach a debug log please?

there were a few tweaks recently around opds that might have had some unintended side effects...

**Comment by HypKin** [comment]
yep, i got you a debug log until then, but i don't see anything related to opds in the logs. 
[mylar.log](https://github.com/mylar3/mylar3/files/4809810/mylar.log)

**Comment by barbequesauce** [comment]
OK - there's some additional logging in place that should help us trace what's happening. Can you switch to dev and update, then try to retrieve via OPDS please?

**Comment by HypKin** [comment]
[mylar.log](https://github.com/mylar3/mylar3/files/4818519/mylar.log)
the log is bit long i had to work in between the update and restart. i started the opds download at about 11:22

**Comment by barbequesauce** [comment]
Wow, that was staring me in the face.... #364 should fix this for you once commited.

**Comment by barbequesauce** [comment]
Yeah no, I was barking up the wrong tree.

@evilhero from the log we clearly get to opds.py line [97](https://github.com/mylar3/mylar3/blob/c24e151d2d078cb3513a0b6b7dc7af02cf4b7a3e/mylar/opds.py#L97)... line 98 calls markasRead, but we never see readinglist.py line [115](https://github.com/mylar3/mylar3/blob/c24e151d2d078cb3513a0b6b7dc7af02cf4b7a3e/mylar/readinglist.py#L115) - not sure why? It's like the thread hangs...

**Comment by barbequesauce** [comment]
@HypKin  that seems to have resolved it from my testing - can you give it a shot please?

**Comment by HypKin** [comment]
I tried it with chunky and the chunky rewrite beta, but after the update my read list is no longer populated with items.

it does show, that it has 76 items, but after load the list is empty...

I'll try to get you a logfile

**Comment by HypKin** [comment]
[mylar.log](https://github.com/mylar3/mylar3/files/4845081/mylar.log)
ok, that is not good, opds is not working at all for me at all. 

I restarted with debugging on. 
then i tried to use opds via the new chunky rewrite (thats a closed beta I'm part of)
at about 13:21 i used the current version of chunky to do the same. always getting no files. i then tried to load something via the publisher folder in opds and it was also empty. 

in the python window i saw something about the path missing or so?

to verify that the file system etc. works i used the web version on my pc to download a comic aftwards. that worked, after that i shutdown the server.

**Comment by HypKin** [comment]
so opening the url with opds?cmd=ReadList appended gives me the following error


`500 Internal Server Error
The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\cherrypy\_cprequest.py", line 638, in respond
    self._do_respond(path_info)
  File "C:\Python37\lib\site-packages\cherrypy\_cprequest.py", line 697, in _do_respond
    response.body = self.handler()
  File "C:\Python37\lib\site-packages\cherrypy\lib\encoding.py", line 219, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "C:\Python37\lib\site-packages\cherrypy\_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "D:\mylar3\mylar\webserve.py", line 5866, in opds
    data = op.fetchData()
  File "D:\mylar3\mylar\opds.py", line 87, in fetchData
    result = methodToCall(**self.kwargs)
  File "D:\mylar3\mylar\opds.py", line 799, in _ReadList
    fileloc = os.path.join(comic['ComicLocation'],issue['Location'])
KeyError: 'Location'`


allTitles does work and responds with the list of comics.

**Comment by barbequesauce** [comment]
@hypkin this should be much more betterer now...

**Comment by HypKin** [comment]
test was positive, thank you @barbequesauce
