### ISSUE TITLE
Charcoal colour combos

### ISSUE THREAD

**Issue by professionaltart** [mylar3/mylar3#365]
**Describe the bug**
Some of the colour combos are too low-contrast.

**Environment (please complete the following information):**
 - OS: Win10 2004
 - Branch / commit: Dev/ a12b530a486c1ddb1b499fdaf39d3c424b0b1cc3 

**Additional information**
![image](https://user-images.githubusercontent.com/28383689/85553795-a71ffe80-b667-11ea-82a4-7abc9bbf37a8.png)
White and grey on light pink background - paused status - makes it too difficult to read.  This is on /pullist
On /home, paused titles appear as just a normal entry on screen, apart from the black (on grey) 'pause' icon

![image](https://user-images.githubusercontent.com/28383689/85554645-75f3fe00-b668-11ea-8c94-46bb25d6abcc.png)
In a given title's index page, moving the mouse over the text on the 'select filtered issues' and 'clear all' buttons makes them unreadable - white on silver.

![image](https://user-images.githubusercontent.com/28383689/85554491-4c3ad700-b668-11ea-8bf0-7169b439fb2c.png)
Moving the mouse over the non-word portion of the button leaves the text as blue on silver.

**Comment by barbequesauce** [comment]
When #384  gets merged, i'd like feedback please

**Comment by barbequesauce** [comment]
@professionaltart when you get a chance to update, feedback please

**Comment by professionaltart** [comment]
Paused looks better now. On mobile ATM so can't test the text/buttons (if that changes was made too) @barbequesauce

**Comment by professionaltart** [comment]
@barbequesauce, just checking on non-mobile, and yep - pause looks better.  

Judging from the change notes, the filter buttons for specific issues are so far untouched?

**Comment by barbequesauce** [comment]
No, I missed that... tonight (tm)

**Comment by barbequesauce** [comment]
#389 should wrap this up.

**Comment by professionaltart** [comment]
Thanks team - resolved.
