### ISSUE TITLE
Next/last page button placement

### ISSUE THREAD

**Issue by professionaltart** [mylar3/mylar3#366]
**Describe the bug**
Some page buttons aren't clickable/shift to a new line.

**CarePackage**
[carepackage.zip](https://github.com/mylar3/mylar3/files/4825348/carepackage.zip)

**Environment (please complete the following information):**
 - OS: Win10 2004
 - Branch / commit: Dev/ a12b530a486c1ddb1b499fdaf39d3c424b0b1cc3 

**Additional information**
Add any other information about the problem here.
![image](https://user-images.githubusercontent.com/28383689/85555135-f1ee4600-b668-11ea-9578-319398543977.png)
eg Walking dead, 193 issues over 8 pages, looks fine.  All buttons are in a row and clickable.

Same for /home index - 43 pages, all appears fine.

![image](https://user-images.githubusercontent.com/28383689/85555539-5dd0ae80-b669-11ea-9fbc-fcdb596b25cb.png)
Spawn has 304 issues, over 13 pages.  But the 13/next/last buttons are pushed to a new row and are not interactive.

Changing the default 25 per page view to a smaller number has the same effect; changing it to 100 per page is enough to 'resolve' the issue.

**Comment by barbequesauce** [comment]
@professionaltart evilhero figured it out - give a shot and let us know please

**Comment by professionaltart** [comment]
Just tested it on latest pull, @barbequesauce  - and no sauce

Tested on Spawn again, same issue: 25 issues per page, 13 pages of comics.  First/Prev/1/2/3/4/5 are fine; 13/next/last are uninteractable

Once I click on page 5, they appear on one line again, and every button interacts fine.

For what it's worth, if I *am* on the last page - 13, then it's same issue - buttons split into two rows, second row doesn't interact.  In this case, top row is First/Prev/1, bottom row is 9/10/11/12/13/next/last


....huh.  Just changed back from carbon to default theme, sorry, and it's showing what I'd expect.

I suspect that 'second row', no matter what's on it, shouldn't be rendering.  It's not in default, but is in charcoal, which is why it's also not interactive.

Sorry for draining: thought I'd already done the theme swap and concluded it was maybe a js rendering issue and not just the theme.

**Comment by evilhero** [comment]
You need to either clear your cache or try using incognito mode. The button placement is correct in both interfaces. 

Also, restarting mylar seems to work as well.

This is due to us making css changes but your local browser is caching the css files.

**Comment by professionaltart** [comment]
Cleared cache, tried incognito, restarted Mylar, not seeing bolded

https://localhost/mylar/comicDetails?ComicID=4937 is the series I'm testing against.

![image](https://user-images.githubusercontent.com/28383689/86018686-0b2c3380-ba69-11ea-9a67-e60175baa8bc.png)

**Comment by professionaltart** [comment]
Success!
