### ISSUE TITLE
Traceback error when adding new comic series

### ISSUE THREAD

**Issue by royaljack** [mylar3/mylar3#369]
**Describe the bug**
After updating a few weeks ago I can no longer add new comic series. When I click to add a comic it attempts to add but produces a page that just has the comic ID and never loads a preview image or details such as series title. It also never creates the comic directory. All of my existing comic series seem to be working fine and have been downloading and processing comics just fine. 

Uncaught exception: Traceback (most recent call last):
File "B:\mylar3\mylar\logger.py", line 337, in new_run
old_run(*args, **kwargs)
File "C:\Program Files\Python37\lib\threading.py", line 870, in run
self._target(*self._args, **self._kwargs)
File "B:\mylar3\mylar\importer.py", line 220, in addComictoDB
comlocation = dothedew.folder_create()
File "B:\mylar3\mylar\filers.py", line 71, in folder_create
folder_format = re.sub('/', '\\', folder_format).strip()
File "C:\Program Files\Python37\lib\re.py", line 192, in sub
return _compile(pattern, flags).sub(repl, string, count)
File "C:\Program Files\Python37\lib\re.py", line 309, in _subx
template = _compile_repl(template, pattern)
File "C:\Program Files\Python37\lib\re.py", line 300, in _compile_repl
return sre_parse.parse_template(repl, pattern)
File "C:\Program Files\Python37\lib\sre_parse.py", line 948, in parse_template
s = Tokenizer(source)
File "C:\Program Files\Python37\lib\sre_parse.py", line 232, in __init__
self.__next()
File "C:\Program Files\Python37\lib\sre_parse.py", line 246, in __next
self.string, len(self.string) - 1) from None
re.error: bad escape (end of pattern) at position 0

**CarePackage**
On the config page, there is a button labelled "CarePackage". Pressing this button will download a zip file containing a redacted copy of your config, your database, a summary of your operating environment, and your logs. Upload that file here.
[carepackage.zip](https://github.com/mylar3/mylar3/files/4838641/carepackage.zip)

If you're uncomfortable with pasting your CarePackage, include a DEBUG log containing the error from disk. 

Do not paste from the GUI log.
Do not just paste a traceback/error.

**Environment (please complete the following information):**
 - OS: Windows 10 Pro 64 Bit
 - Mylar Version: master [v0.4.1 - Bite me, fanboy.] 
-- git (build e29114901810346e52486c8681c6b154639bcf86)

**Additional information**
I have also deleted my old install of mylar3, and have done a fresh pull and then used my original config, cache, and db which produced the same error.

**Comment by evilhero** [comment]
You have your OS slashes going the incorrect way in your folder format and in your destination directory. 

Since it looks like you migrated the config from a Linux to Windows machine, you need to ensure you're using \ and not / in any of the paths.

**Comment by royaljack** [comment]
Wow, I must be losing my mind! That worked. I did pull this config off of my synology about a year ago. Somehow it had been working up until recently. Thank you for the assist and amazing program!
