### ISSUE TITLE
Home page does not render

### ISSUE THREAD

**Issue by Serneum** [mylar3/mylar3#376]
**Describe the bug**
I just updated to `45886c09284cde761000c23d2fe2d0e35dbecaec` and now my home page does not render a list of comics.  The reported error in my browser's console is
```
home:140 Uncaught TypeError: Cannot read property 'length' of null
    at render (home:140)
    at jquery.dataTables.min.js:30
    at Object.b.fnGetData (jquery.dataTables.min.js:24)
    at B (jquery.dataTables.min.js:29)
    at Ja (jquery.dataTables.min.js:36)
    at N (jquery.dataTables.min.js:28)
    at xb (jquery.dataTables.min.js:51)
    at jquery.dataTables.min.js:49
    at i (jquery.dataTables.min.js:47)
    at Object.success (home:264)
```

![image](https://user-images.githubusercontent.com/1091716/85952711-3ca5e180-b939-11ea-80aa-706ed44bfd0d.png)

**CarePackage**
This seems to be entirely related to the front-end. Nothing shows up in the logs related to the home page attempting to load, even with debug logging on.

[carepackage.zip](https://github.com/mylar3/mylar3/files/4842596/carepackage.zip)

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Branch / commit: python3-dev / 45886c09284cde761000c23d2fe2d0e35dbecaec

**Additional information**
N/A

**Comment by evilhero** [comment]
Cannot duplicate this at all. Works for me fine using either the default or carbon interface.

Try maybe to either use incognito mode if you're using Chrome, and/or clear your cache and try from a restarted  mylar instance.

We moved a bunch of html stuff around so it's possible you're still caching some stuff.

**Comment by Serneum** [comment]
Incognito worked. Not sure why I didn't think to try that. Thanks for the reminder, I'll go play with my browser and get it fixed

**Comment by Serneum** [comment]
Minor note: a restart of Mylar seems to have been sufficient.
