### ISSUE TITLE
Config dump page does not render

### ISSUE THREAD

**Issue by Serneum** [mylar3/mylar3#377]
**Describe the bug**
I didn't even realize there was a config dump page until today, but figured I'd try it out. The page does not load, and I get a 500 error in my browser's console log.

![image](https://user-images.githubusercontent.com/1091716/85952782-9ad2c480-b939-11ea-9a70-de82aa5542b6.png)

`Failed to load resource: the server responded with a status of 500 ()`

![image](https://user-images.githubusercontent.com/1091716/85952804-b76efc80-b939-11ea-8933-3235a59552db.png)

**CarePackage**
[carepackage.zip](https://github.com/mylar3/mylar3/files/4842595/carepackage.zip)

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Branch / commit: python3-dev / 45886c09284cde761000c23d2fe2d0e35dbecaec

**Additional information**
N/A

**Comment by evilhero** [comment]
Can confirm this is a decode issue.

**Comment by barbequesauce** [comment]
This should be okay now?

**Comment by Serneum** [comment]
Yep, looks good
