### ISSUE TITLE
Getcomics API should try to prefer single issues before packs (and use a bit more specific search term)

### ISSUE THREAD

**Issue by Micket** [mylar3/mylar3#382]
**Describe the request**
I have had many issues with packs on DDL/Getcomics, occassions of downloading the wrong series all together, or failing to find links because packs where actually split apart.
This is often combined with the fact that only a few issues were missing, meaning a pack would be overkill.

Example of problematic search; https://getcomics.info/?s=The+Immortal+Hulk+31%2C

**How did you come up with the idea?**
I saw some code for 32P that also tries this order first.

*Note* I found that config.ini contains a section `allow_packs = False` (by default), but, this setting doesn't seem to do anything in mylar. I wouldn't really want to turn it off either; i would just prefer single issues.

A possible strategy could be something like;
```python3
b = getcomics.GC(query='%s #%s (%s)' % (findcomic, isssearch, comyear))
bb = b.search()
if len(bb['entries']) == 0: # Gotta go broader
     b = getcomics.GC(query='%s %s' % (findcomic, isssearch))
     bb = b.search()
```
I found it problematic to search for issue 1 in getcomics, necessitating the year (which is typically included).

**Comment by evilhero** [comment]
While I agree it can be problematic, the problem also lies in the fact that some users want packs first, not issues. Not saying that's the answer obviously, but for each Ykng there's always a Yang.

There's also no getcomics api, it's just straight page parsing done from within Mylar. 

The allow_packs is a 32p only option which is why it doesn't do anything for any other provider. You have to have 32p enabled as a provider in order for the option to appear in the Edit Settings section of the given series detail page.

I do think this might be handled in a more graceful way. I think if we sort the result set based on packs or not, it would then give preferential treatment to singles prior to packs (as they would all appear last in the result set). 

Perhaps having a global option to prefer singles over packs which would then decide the sort order.

Reminds me I also want to look at the pack inclusion checker - there should be some minimum requirement for if a pack is downloaded it has to have  a minimum  of X number of issues that are not already Downloaded in it.

**Comment by Micket** [comment]
It's not so much a preference over what type of download; it's just a matter of being able to get anything at all. Every other series have missing issues. Often issue 1 is missing, since searching for "Comicname 1" is pretty much impossible in getcomics, e.g:
https://getcomics.info/?s=immortal+hulk+%231
(one would have to go back lots of pages because the search term "1" finds 10, 11, 12, 13, 14,...

So far I've had gotten
1. Simply not find the issue, as it's hidden 10 pages back on getcomics search results
2. Downloaded packs from a different series, like an earlier volume, or some silver-age comics with the same name.
3. Packs with strange links, like https://getcomics.info/marvel/immortal-hulk-1-31-tpbs-2018-2020/ (where it fails to find any download link)

Unfortunately, the result isn't that it tries something else, it will just fail to ever download anything, stuck forever at "snatched" or "wanted".

So, to get something more robust, I have made some modifications to my search, which has worked somewhat well;
```python3
            # Try a quoted string
            b = getcomics.GC(query='"%s #%s (%s)"' % (findcomic, isssearch, comyear))
            bb = b.search()
            if not bb['entries']:
                # No exact match, try without quotes
                b = getcomics.GC(query='%s #%s (%s)' % (findcomic, isssearch, comyear))
                bb = b.search()
            if not bb['entries']:
                # Ok then try without year (since that sometimes doesn't match with comicvine, sigh...)
                b = getcomics.GC(query='%s #%s' % (findcomic, isssearch))
                bb['entries'] += b.search()['entries']
                # And also include the a broader search, typically this might find packs.
                b = getcomics.GC(query='%s %s' % (findcomic, isssearch))
                bb['entries'] += b.search()['entries']
```

The fact that packs comes last, is simply because it's harder to reliable search for them; so going from most to least precise necessarily prevents them from showing up early.


> The allow_packs is a 32p only option which is why it doesn't do anything for any other provider. You have to have 32p enabled as a provider in order for the option to appear in the Edit Settings section of the given series detail page.

No I mean the config.ini file that mylar generates;
```
[DDL]
allow_packs = False
enable_ddl = True
ddl_location = None  
ddl_autoresume = True
```
( I didn't enter any of these myself, but I understand it's not something that's used anyway after having read all the search/getcomics code )

**Comment by evilhero** [comment]
This should be working now as intended I believe now that we refactored the actual parsing from the searching allowing for better customisation of the search terms and not having it hit GC unnecessarily for the same information retrieved previously. It also iterates thru in the same sequence you pretty much have described above (it has done this for awhile, but I'm just mentioning it now cause ya know).

The added ini options of ``pack_priority`` allows one to specify if packs are prioritised in the results. A value of ``True`` tells Mylar to prioritise packs over single issues, ``False`` (the default) tells Mylar to prefer single issues over packs. Even if you have ``enable_packs`` set, it will still be honored, just according to the pack_priority setting.
