### ISSUE TITLE
TypeError in postprocessing from nzbget

### ISSUE THREAD

**Issue by faethon** [mylar3/mylar3#388]
While postprocessing a download from nzbget, the autoProcessComics.py script throws an error in handling the result. 
Error message and trace is:

...
ComicRN: File "/config/scripts/ComicRN.py", line 49, in <module>
ComicRN: File "/config/scripts/autoProcessComics.py", line 111, in processIssue
ComicRN: if any("Post Processing SUCCESSFUL" in s for s in result):
ComicRN: File "/config/scripts/autoProcessComics.py", line 111, in <genexpr>
ComicRN: if any("Post Processing SUCCESSFUL" in s for s in result):
ComicRN: TypeError: a bytes-like object is required, not 'str'
Post-process-script ComicRN.py failed (terminated with unknown status)

The download and post processing itself however have completed. Apparently the script tries to resolve the 'result' (list of ) string(s) but the Python interpreter doesn't resolve it as a string. This is running both mylar and nzbget in separate dockers.

**Comment by barbequesauce** [comment]
Based on those paths I'm guessing you're using Docker - when you run `python3 autoProcessComics.py` from the command line in that container, are you seeing errors? If not, you'll need to make sure that NG is calling python3 before the script name...

**Comment by barbequesauce** [comment]
Any update here?

**Comment by faethon** [comment]
Yes, the problem is indeed related to the use of python3 mixed with python2. Nzbget docker is running on python3 and the Mylar docker image I'm using is on python2 (older version of mylar). I have for now 'solved' the issue by using the new autoProcess python3 scripts from Mylar into the nzbget docker. I tried moving my Mylar installation to the new python3 build, but I had trouble getting any comics, while on the old Mylar with python2 it worked flawless.
