### ISSUE TITLE
Version Check Error

### ISSUE THREAD

**Issue by Galardin** [mylar3/mylar3#392]
When I start Mylar I get an Error message for Version Check(see last line below), and if there is a newer Version available Mylar wont update.

11-Jul-2020 07:21:46 - INFO    :: MAIN : webstart.py:initialize:73 : Starting Mylar on http://0.0.0.0:8090/
11-Jul-2020 07:21:47 - INFO    :: MAIN : versioncheck.py:getVersion:192 : [LAST_RELEASE] Branch:  master
11-Jul-2020 07:21:47 - INFO    :: MAIN : versioncheck.py:getVersion:197 : [LAST_RELEASE] Version: v0.4.2
11-Jul-2020 07:21:47 - INFO    :: MAIN : versioncheck.py:getVersion:200 : [LAST_RELEASE] Commit: 28d9812f1e38776f74bd26dc01264f205354318b
11-Jul-2020 07:21:48 - INFO    :: MAIN : versioncheck.py:getVersion:214 : Current Release Name: None
11-Jul-2020 07:21:48 - INFO    :: MAIN : versioncheck.py:getVersion:217 : Branch detected & set to : development
11-Jul-2020 07:21:48 - INFO    :: MAIN : versioncheck.py:versionload:385 : Version information: development [28d9812f1e38776f74bd26dc01264f205354318b]
11-Jul-2020 07:21:48 - WARNING :: MAIN : versioncheck.py:checkGithub:253 : [ERROR] Could not get the latest commit from github: 'sha'

I´m running Mylar on a Win10 Maschine.
Any thing I can do, so that Mylar will update?

Thank you

**Comment by HypKin** [comment]
How did you install it? 

Had problems like this as well when I first tried via the executable but then just reinstalled via git and everything was working

**Comment by barbequesauce** [comment]
Assuming you've installed via git clone?

If so, shut Mylar  down and edit your config.ini. Set `git_user` to mylar3 and make sure your `git_branch` is spelled correctly. Then start back up and try again...

**Comment by evilhero** [comment]
Yeah there is no ```development```branch in mylar3, it's called ```python3-dev```.

**Comment by Galardin** [comment]
Thank all of you. Setting git_user & git_branch correctly, solved the problem.
