### ISSUE TITLE
Deleted 2000AD from Mylar but it's still in Wanted Issues

### ISSUE THREAD

**Issue by leaderdog** [mylar3/mylar3#396]
when running the importer I think it accidentally imported 2000 AD.  I must have forgot to remove the file from my folder.  So when I checked my wanted list I was up over 2800 files.  Since at that time I was surprised it was that high that's when I noticed 2000 AD was listed. 

I removed 2000 AD from Mylar as I wasn't ready to deal with it, and I don't think Mylar really is either. :)  It's gone from Mylar but it's still in the Wanted Issues.  

How do I get it out of there?

Configuration Options
Mylar Version: python3-dev
-- git (build d6c3cdabe2d34ca870f92d689b4d8f9276ef75d5)
Python Version : 3.7.7
Language : en_CA.cp1252

**Comment by evilhero** [comment]
Odds are it's deleted, Fu ours just viewing a cached result. I'm guessing you just used the back buttons on the browser to go back to the wanted page after deleting the series.

Shut down mylar. Shut down your browser completely (or go incognito mode if you're using Chrome). Start up mylar. Go to wanted page in browser. View results.

**Comment by leaderdog** [comment]
This was over a couple weeks ago.  I've done a couple Mylar updates in between that time.  I thought maybe it would sort itself out, but it so far hasn't.  I shut down mylar via my service, and started it up again. opened Mylar in firefox instead of palemoon like I normally do and it's still showing over 2800 entries the majority are 2000 AD.

There must be something else I can edit to remove it from the wanted list?  maybe I should add it again and then remove it?  Maybe it just got stuck somehow when it deleted it?

**Comment by leaderdog** [comment]
ok yeah, adding it and removing it again worked.  So it just got hung up some how when it deleted it the first time.  /shrugs.
