### ISSUE TITLE
Mylar runs manually, won't run as a service.

### ISSUE THREAD

**Issue by DaveBrackets** [mylar3/mylar3#397]
**Describe the bug**
I can't make Mylar run at startup - it runs fine manually, but when I go to start it as a service it just sits there and then errors out with "Job for mylar.service was failed because a timeout was exceeded" and pointing me to systemctl and journalctl which don't tell me anything extra.

I didn't throw any errors during the setup process, including the systemctl enable command. All the files are in the right places and look (to me!) as though they have the right things in etc.

**CarePackage**
Attached.
[carepackage.zip](https://github.com/mylar3/mylar3/files/4934353/carepackage.zip)

**Environment (please complete the following information):**
 - OS: Dietpi (trimmed-down Raspbian)
 - Branch / commit: current python3 dev

**Additional information**
I am running this on a first gen raspberry pi - I'm open to the possibility that it's just timing out because the underpowered board can't do the things quickly enough; but it does run when I start it manually so I don't think it's just totally overwhelmed!

Appreciate any help.

**Comment by barbequesauce** [comment]
It's definitely running - you have four logfiles full of imports in that care package. The issue is in the init file somewhere. I run a fleet of pis using different flavors of Raspbian; I can confirm it runs fine on any of the series.

Can you post the contents of your mylar.service file please?

**Comment by DaveBrackets** [comment]
Yep - moving to the new setup because my windows home server won't handle the new version of Python, so having to figure out the import!

I don't think I changed anything in mylar.service:

# Mylar.service to run as $USER with config in $DATA_DIR

[Unit]
SourcePath=/etc/init.d/mylar
Description=starts instance of Mylar
After=all.target

[Service]
Type=forking
Restart=no
TimeoutSec=5min
IgnoreSIGPIPE=no
KillMode=process
GuessMainPID=no
RemainAfterExit=yes
ExecStart=/etc/init.d/mylar start
ExecStop=/etc/init.d/mylar stop

[Install]
WantedBy=multi-user.target

**Comment by barbequesauce** [comment]
ExecStart is referring to the init.d script.Did you add in the mylar startup script to /etc/init.d?

If not, change the ExecStart line to look something like this (customize to your python3 location, mylar location, and preferred command line switches) and remove ExecStop altogether:

`ExecStart=/usr/bin/python3 /opt/mylar/Mylar.py -v --daemon  --nolaunch`

**Comment by DaveBrackets** [comment]
Yes - copied the script to /etc/init.d and renamed it to mylar.

I noticed the script calls /etc/default/mylar so I pulled that up - I had specified user and home, as in the readme, but nothing else. Suddenly occurred to me that my python binary won't be usr/bin/python (which is the default) because that's python 2? I tried it specifying /usr/bin/python3 and then /usr/bin/python3.7 and neither one solved it.

I noticed that the next line is the location of mylar.pid - I can't actually find that file anywhere on my system. Is that the problem?

**Comment by BRTPOB** [comment]
The mylar.pid file only gets created when Mylar's running. What is the error message you're getting when trying to run mylar through the autostart service file? I've had lots of problems with it, and I'm about to migrate back to my own personal version which worked flawlessly, including stopping and starting the service without it yelling at me about the file changing.

**Comment by barbequesauce** [comment]
@BRTPOB share your version please 😀

**Comment by BRTPOB** [comment]
Need to rebuild it, but give me a few minutes and I will.

**Comment by BRTPOB** [comment]
Something like this should work: https://mactaggart.eskimomafia.com/b8pdls3s.service. I'll play with it tonight/tomorrow and make sure it actually does what it should.

**Comment by evilhero** [comment]
This is my mylar.service file, which runs fine on Ubuntu 16.04 LTS: 
```
[Unit]
Description=Systemd script to run Mylar3 as a service
After=network-online.target

[Service]
User=hero
Group=hero
ExecStart=/usr/bin/python3.8 /home/hero/mylar3/Mylar.py -v --daemon  --nolaunch --quiet
GuessMainPID=no
Type=forking
Restart=on-failure

[Install]
WantedBy=multi-user.target
```

I have the mylar.service file symlinked in ```/etc/systemd/system``` from ```/lib/systemd/system``` (where most original systemd files live). 

If you drop the service file into ```/lib/systemd/system```, you can have your system auto-link it via the ```systemctl enable mylar.service``` command, which will then create a symlink in ```/etc/systemd/system/mylar.service```. 

You can then do a ```systemctl daemon-reload``` to reload the configurations, and then can perform ```systemctl start mylar``` / ``` systemctl stop mylar``` / ```systemcl status mylar``` as per normal systemd operations.

**Comment by DaveBrackets** [comment]
evilhero's mylar.service cracked it - originally it threw an error on the arguments, so I deleted all of them except --daemon and then it worked perfectly. I will experiment a bit with it to see what arguments I can get back in, but for now just glad to have it running.

Thanks all.
