### ISSUE TITLE
Extra script fails to process: TypeError: can only concatenate str (not "bytes") to str

### ISSUE THREAD

**Issue by SenorSmartyPants** [mylar3/mylar3#400]
My extra post processing scripts fail when called from mylar. They run fine from the commandline, so it is not a permissions issue.
[carepackage.zip](https://github.com/mylar3/mylar3/files/4961439/carepackage.zip)

I think it has to do with how the subprocess is opened.

https://github.com/mylar3/mylar3/blob/28d9812f1e38776f74bd26dc01264f205354318b/mylar/PostProcessor.py#L191

Add text=true to the arguments of Popen, this should set the script output to be string instead of bytes and solve this issue.
https://docs.python.org/3/library/subprocess.html#module-subprocess

**Comment by evilhero** [comment]
This actually has zero to do with the Popen call itself - the problem is the logger line. It's trying to concat the result using the old ```+``` method, when it should be using the ```%``` method.

**Comment by SenorSmartyPants** [comment]
#401 fixes this. My scripts run, with output displayed when debugging turned on in the log. 

Thanks.
