### ISSUE TITLE
Nothing happening when trying to launch Mylar

### ISSUE THREAD

**Issue by Spectre216** [mylar3/mylar3#402]
**Describe the bug**
Launch Mylar through CMD on Windows 10. No matter if I use "python3 Mylar.py" or "python3 Mylar.py --help" there is no output and CMD returns to a blank line. Nothing launches and I cannot access anything via localhost.

**CarePackage**
Can't get to this page. This is a fresh install downloaded from GitHub and copied to C:\Mylar.

**Environment (please complete the following information):**
 - OS: Windows 10/Python 3.7.2
 - Branch / commit: Master

**Comment by evilhero** [comment]
Try starting it with ```python Mylar.py - v```, but do it from within the root of the mylar directory.

This is assuming you can access python if it's located in your environment path.

**Comment by barbequesauce** [comment]
Small correction, run `python Mylar.py -v` (without the space)

**Comment by barbequesauce** [comment]
@Spectre216 please feel free to reopen when you have an update
