### ISSUE TITLE
Error when trying to display "This week" pull-list

### ISSUE THREAD

**Issue by theotocopulitos** [mylar3/mylar3#406]
**Describe the bug**
While trying to display the current week pull-list, by clicking "This Week" in main menu, I  receive this message:

```
500 Internal Server Error
The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/cherrypy/_cprequest.py", line 638, in respond
    self._do_respond(path_info)
  File "/usr/lib/python3.8/site-packages/cherrypy/_cprequest.py", line 697, in _do_respond
    response.body = self.handler()
  File "/usr/lib/python3.8/site-packages/cherrypy/lib/encoding.py", line 219, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/app/mylar/webserve.py", line 1734, in pullist
    repoll = self.manualpull(weeknumber=weekinfo['weeknumber'],year=weekinfo['year'])
  File "/app/mylar/webserve.py", line 2021, in manualpull
    return mylar.locg.locg(weeknumber=weeknumber,year=year)
  File "/app/mylar/locg.py", line 133, in locg
    myDB.upsert("weekly", newValueDict, controlValueDict)
  File "/app/mylar/db.py", line 174, in upsert
    self.action(query, list(valueDict.values()) + list(keyDict.values()))
  File "/app/mylar/db.py", line 128, in action
    sqlResult = self.connection.execute(query, args)
sqlite3.DatabaseError: database disk image is malformed
Powered by CherryPy 18.6.0
```

**Environment (please complete the following information):**
 - OS: Ubuntu 
 - Branch / commit: hotio/mylar3 docker image - -- source (build ba72dcd0ea6aee2f4be5f634655cb204cd3842ac)
[carepackage (1).zip](https://github.com/mylar3/mylar3/files/5008140/carepackage.1.zip)

**Comment by evilhero** [comment]
That error message would imply that your db file has been corrupted. If you have a backup, you'll have to load that up and use that - or else see if you can get into the corrupted db file and see what was corrupted and remove the entries if possible (don't think it is, but worth a mention regardless).

If you start Mylar with the --backup option, it will create a backup copy of your ini and db at runtime and put said copies in a directory within the root of your mylar install called backup. It will hammer on every startup if enabled (ie. it doesn't check first for validity, corruption atm), so be wary of that - but it will keep the last 2 most recent copies of each file.

**Comment by theotocopulitos** [comment]
Thanks... I ended up doing a fresh install.
