### ISSUE TITLE
Unable to launch MyLar3 due to permission error to logs

### ISSUE THREAD

**Issue by TheDOC1988** [mylar3/mylar3#407]
**Describe the bug**
My installation of Mylar has started acting weird where it just stopped searching for comics. I looked in the logs and it would just simply say it was queing a search but nothing would happen. Decided to move to mylar3, so followed the steps on the github page, but am unable to launch. 

Apologies I'm not overly great on Linux, so not sure if I'm providing the right info below 

**Environment (please complete the following information):**
 - OS: [Ubuntu]
 - Branch / commit: Unable to launch programe. Whatever installed from the git clone 

**Additional information**
When starting mylar3, I'm being given the below error

PermissionError: [Errno 13] Permission denied: '/opt/mylar3/logs/mylar.log'

I understand the error, there is no logs or mylar.log file present. Created a logs folder and tried making a mylar.log, but it still shows this error. Assume its due to the nature of where I installed from git clone, but this is where I have my other similar applications

**Comment by barbequesauce** [comment]
That error is telling you the runtime user of Mylar doesn't have read-write access to the Mylar directory. If you run the following command, you will see the user Mylar needs to be run under:

ls -al /opt/mylar3/logs

Assuming the username is mylar, you would start the program with:

sudo -u mylar-g mylar python3 /opt/mylar3/Mylar.py -v

That -v flag is for verbose logging, aka debug - it will be handy to help diagnose additional problems...

**Comment by evilhero** [comment]
The user that runs mylar has to have permission to the entire /opt/mylar3 directory. The entire /opt path is locked to root by default, so odds are you ran the git clone using sudo, but you're running mylar as a non-root user (which is the right way to run it, never run anything as root). 

What @barbequesauce mentioned will work obviously, but an alternative method is to just chown the entire mylar folder recursively so that the user running mylar has access.

So if you're running mylar using the user ```user1```, you would cd into /opt. Then do a ```sudo chown user1:root -R mylar3 ```. Then when you run Mylar you no longer have to use sudo (provided you're the user running mylar).

**Comment by barbequesauce** [comment]
Yeah what he said -

I'll add a footnote, don't run Mylar as root - from a security perspective, it's just bad practice to run anything other than OS processes as root... who knows what vulnerabilities we haven't spotted yet...

**Comment by TheDOC1988** [comment]
> That error is telling you the runtime user of Mylar doesn't have read-write access to the Mylar directory. If you run the following command, you will see the user Mylar needs to be run under:
> 
> ls -al /opt/mylar3/logs
> 
> Assuming the username is mylar, you would start the program with:
> 
> sudo -u mylar-g mylar python3 /opt/mylar3/Mylar.py -v
> 
> That -v flag is for verbose logging, aka debug - it will be handy to help diagnose additional problems...

`sudo -u pi -g pi python3 /opt/mylar3/Mylar.py -v
log language set to en_GB
Verbose/Debugging mode enabled...
Initializing startup sequence....
Traceback (most recent call last):
  File "/opt/mylar3/Mylar.py", line 386, in <module>
    main()
  File "/opt/mylar3/Mylar.py", line 203, in main
    mylar.initialize(mylar.CONFIG_FILE)
  File "/opt/mylar3/mylar/__init__.py", line 180, in initialize
    CONFIG = cc.read(startup=True)
  File "/opt/mylar3/mylar/config.py", line 562, in read
    logger.initLogger(console=not mylar.QUIET, log_dir=self.LOG_DIR, max_logsize=self.MAX_LOGSIZE, max_logfiles=self.MAX_LOGFILES, loglevel=mylar.LOG_LEVEL)
  File "/opt/mylar3/mylar/logger.py", line 275, in initLogger
    file_handler = RFHandler(filename, "a", maxBytes=max_logsize, backupCount=max_logfiles)
  File "/usr/lib/python3.7/logging/handlers.py", line 147, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python3.7/logging/handlers.py", line 54, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python3.7/logging/__init__.py", line 1092, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.7/logging/__init__.py", line 1121, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
PermissionError: [Errno 13] Permission denied: '/opt/mylar3/logs/mylar.log'
`

**Comment by barbequesauce** [comment]
Can you list out what this command produces?

`ls -al /opt/mylar3/logs
`

**Comment by barbequesauce** [comment]
Any update here?

**Comment by barbequesauce** [comment]
Please reopen when you have additional information to add.
