### ISSUE TITLE
Comics don't import, either through import results management or manual post-processing.

### ISSUE THREAD

**Issue by CougarDraven** [mylar3/mylar3#408]
I have a handful of issues which are not parsing correctly. I've run an import scan a number of times, I've even made sure they have proper tags by running them through comictagger separately, a solution which has thus far been successful to make every comic that I have tried to import so far get picked up and moved into my storage database. But they have, to date, refused to actually be processed correctly.

[Uploading carepackage.zip…](Care Package)

**Environment (please complete the following information):**
 - OS: Windows 10
 - Branch / commit: master (0.4.2)

**Additional information**
It appears from the error that there's something going on specifically with the date in the comic. So far, the comics to date which have the problem all are throwing an error because mylar seems to think that the comics are dated wrong. (The phrasing is "$date is before the issue year of $year that was discovered in the filename".) The problem with that is that they aren't. I've confirmed that a number of times.

Editing to correctly upload the care package zip. I think?

Editing again to note that I have solved this problem by manually changing the year in the file name. This seems similar to [this](https://github.com/evilhero/mylar/issues/902) issue from the py2 version of Mylar, but I have no way of knowing how to fix it.

**Comment by barbequesauce** [comment]
Still no carepackage... try dragging it onto the textbox.

Also filenames would help - In a lot of cases we can quickly see what broke just from the filename.
