### ISSUE TITLE
Unable to add newznab provider

### ISSUE THREAD

**Issue by gviscardi** [mylar3/mylar3#410]
**Describe the bug**
When attempting to add a Newznab provider (nzbgeek), I enter the information and first attempt to "Test" the provider, but nothing happens, no log info. I then attempt to "Save" the settings, but I get an "There was an error" red popup, with no logs being recorded. If I remove the Newznab provider, it saves properly, with a line in the logfile.

**CarePackage**
[carepackage.zip](https://github.com/mylar3/mylar3/files/5066713/carepackage.zip)

**Environment (please complete the following information):**
 - OS: Raspbian GNU/Linux 10 (buster)
 - Branch / commit: master

**Additional information**
This is being run on a Raspberry Pi 4, 4G, python version 3.7.3

This traceback comes up if I launch without daemonizing:
Traceback (most recent call last):
  File "/home/mylar/.local/lib/python3.7/site-packages/cherrypy/_cprequest.py", line 638, in respond
    self._do_respond(path_info)
  File "/home/mylar/.local/lib/python3.7/site-packages/cherrypy/_cprequest.py", line 697, in _do_respond
    response.body = self.handler()
  File "/home/mylar/.local/lib/python3.7/site-packages/cherrypy/lib/encoding.py", line 219, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/home/mylar/.local/lib/python3.7/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/var/lib/mylar/mylar/webserve.py", line 5594, in configUpdate
    newznab_apikey = kwargs['newznab_apikey' + newznab_number]
KeyError: 'newznab_apikey1'

**Comment by evilhero** [comment]
There's something up with a config entry that's aborting the save due to some incompatiblity it looks like.

Your log only shows INFO level logging tho, so I can't see what's happening. Can you go into the GUI, under History, View Logs, and turn on verbose logging. Then perform a save on the config and that will log it in debug and if you can carepackage that up it'd be great.

If you can also, can you screenshot your newznab section from the mylar GUI? It's saying it can't find entry1, but it should be starting at 0 which might mean you have an incorrect / blank entry in there as well and it's causing an issue.

**Comment by gviscardi** [comment]
Here ya go.

![image](https://user-images.githubusercontent.com/105004/90087048-d65aff80-dce9-11ea-8cda-8a124af34d60.png)

[carepackage (1).zip](https://github.com/mylar3/mylar3/files/5066802/carepackage.1.zip)

**Comment by evilhero** [comment]
It seems there's some issues with carbon + the master branch - I can duplicate this error on master branch with carbon, however using the default interface on the master branch works fine and saves ok.

I'm looking at this now, well kinda hard on the phone - but I'm trying to find where one of my kids hid my laptop now (ya, haha I know right). Once I can locate it, I'll fire it up and see if I can locate the problem in the new interface.

**Comment by gviscardi** [comment]
Ok I updated and everything seems to be working! Great job!
