### ISSUE TITLE
Export story arc number to comicinfo.xml

### ISSUE THREAD

**Issue by gotson** [mylar3/mylar3#411]
**Describe the request**
Story arc number is currently stored in the mylar db, but not exported to ComicInfo.xml, due to the lack of such a field to hold the information.

The idea is to add an extra field, for example StoryArcNumber, to hold that information. 

The lack of governance over comicinfo.xml schema means it's pretty open to add some information to it. 

**How did you come up with the idea?**
As part of Komga development, I plan to add readlists, which will be usable to represent story arcs. Importing story arcs from comicinfo.xml would be a nice addition, but without the number the user will need to sort the arc's issues manually. 

**Environment (please complete the following information):**
 I actually don't use Mylar.

**Comment by evilhero** [comment]
The StoryArcNumber field can be added to the XML via CT yes. 

Are we talking about int-style numbering or padded numbering? Keep in mind that if it's int-style, 10 will come before 2 unless your program (don't use it, so dunno) forces it so that's not an issue.

**Comment by gotson** [comment]
it seems the existing XSD uses [`string` for numbers](https://gist.github.com/gotson/29ebdbc7e4a21c127889f065864a363b/472e2dd6a9033b1092a75f4769f86aa4d3b3db03#file-comicinfo-xsd-L8).

I am fine with using a `string`, padded or not. Komga would parse it to an `int` if needed.

**Comment by SenorSmartyPants** [comment]
There are alternateseries and alternate series number fields.

**Comment by gotson** [comment]
> There are alternateseries and alternate series number fields.

But since there is already StoryArc... AlternateSeries doesn't carry the same meaning, and Mylar already fills the StoryArc field.

**Comment by gotson** [comment]
Looks like the discussion already happened : http://forum.mylarcomics.com/viewtopic.php?t=2032

Looks like indeed that StoryArc is within a series, while AlternateSeries with the associated number is outside the series, a cross-over for instance (the current StoryArc in Mylar). But given CV apparently doesn't do the distinction, it's impossible for Mylar to decide if it's one or the other. 

Personally I don't care what field is used, as long as there is a field with the number.

**Comment by barbequesauce** [comment]
@gotson are we ok to close this?

**Comment by gotson** [comment]
> @gotson are we ok to close this?

Just saw that some commits have been done to handle that, sounds good then.
