### ISSUE TITLE
Upgrade from Ubuntu 18.04 to 20.04 results in Mylar not running as a service

### ISSUE THREAD

**Issue by dma9** [mylar3/mylar3#419]
**Describe the bug**
After upgrading the system to Ubuntu to 20.04, Mylar (running as a service) would not start. It threw up a ModuleNotFoundError for a module called 'idna':
```
● mylar.service - Mylar - Comic book downloader
     Loaded: loaded (/etc/systemd/system/mylar.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Fri 2020-08-21 21:15:27 EDT; 1s ago
    Process: 97 ExecStart=/usr/bin/python3 /opt/mylar3/Mylar.py --daemon --datadir=/opt/mylar3 --config=/opt/mylar3/config.i>

Aug 21 21:15:27 mylar python3[97]:   File "/opt/mylar3/mylar/helpers.py", line 22, in <module>
Aug 21 21:15:27 mylar python3[97]:     import requests
Aug 21 21:15:27 mylar python3[97]:   File "/usr/local/lib/python3.8/dist-packages/requests/__init__.py", line 121, in <modul>
Aug 21 21:15:27 mylar python3[97]:     from . import packages
Aug 21 21:15:27 mylar python3[97]:   File "/usr/local/lib/python3.8/dist-packages/requests/packages.py", line 7, in <module>
Aug 21 21:15:27 mylar python3[97]:     locals()[package] = __import__(package)
Aug 21 21:15:27 mylar python3[97]: ModuleNotFoundError: No module named 'idna'
Aug 21 21:15:27 mylar systemd[1]: mylar.service: Control process exited, code=exited, status=1/FAILURE
Aug 21 21:15:27 mylar systemd[1]: mylar.service: Failed with result 'exit-code'.
Aug 21 21:15:27 mylar systemd[1]: Failed to start Mylar - Comic book downloader.
```
Manually running `python3 /opt/mylar3/Mylar.py -d` also produced a similar message:
```
Traceback (most recent call last):
  File "/opt/mylar3/Mylar.py", line 26, in <module>
    import mylar
  File "/opt/mylar3/mylar/__init__.py", line 38, in <module>
    from mylar import logger, versioncheckit, rsscheckit, searchit, weeklypullit, PostProcessor, updater, helpers
  File "/opt/mylar3/mylar/logger.py", line 24, in <module>
    from mylar import helpers
  File "/opt/mylar3/mylar/helpers.py", line 22, in <module>
    import requests
  File "/usr/local/lib/python3.8/dist-packages/requests/__init__.py", line 121, in <module>
    from . import packages
  File "/usr/local/lib/python3.8/dist-packages/requests/packages.py", line 7, in <module>
    locals()[package] = __import__(package)
ModuleNotFoundError: No module named 'idna'
```
I did a bit of googling and a random post somewhere suggested that `pip3 install -I --user idna` would fix things. So I ran it and idna was installed. It seemed to work - manually running `python3 /opt/mylar3/Mylar.py -d` produced no error messages, and Mylar seemed to work just fine - I was able to access the webgui just fine. However, I still get the same error message about the library when trying to start the service. When I look at the .service file, I can't see any reason why that should be:
```
[Unit]
Description=Mylar - Comic book downloader

[Service]
Type=forking
User=mylar
Group=container-data
ExecStart=/usr/bin/python3 /opt/mylar3/Mylar.py --daemon --datadir=/opt/mylar3 --config=/opt/mylar3/config.ini --quiet --nolaunch
GuessMainPID=no

[Install]
WantedBy=multi-user.target
```
`python3 -V` returns Python 3.8.2, as does `python -V`. 

I imagine there must be something simple that I'm missing, but can't seem to figure it out. If anyone has any suggestions on how I might be able to fix this, it would be most appreciated.

**CarePackage**
I tried to download a CarePackage after starting Mylar manually, but clicking on the button doesn't do anything. Perhaps related to the problem I am experiencing?

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04.1 running in an LXC container on Debian/Proxmox
 - Branch / commit: python3-dev / build ec0b7e1b7db0e8a5a838916c94e6446ee131f8ac

**Comment by dma9** [comment]
Hey thanks very much for the suggestion evilhero. I ran requirements.txt but it reported that all requirements were already satisfied.

Just to make sure I wasn't missing something in the .service file, I copied the ExecStart line from it and executed it manually. It started without a hitch. Even though I hadn't changed the .service file, I also did a systemctl daemon-reload and restarted the container. Still the same result - manual runs fine; service dies with the ModuleNotFoundError. 

Do let me know if there might be something else that I'm missing.

Thank you.

**Comment by barbequesauce** [comment]
> Just to make sure I wasn't missing something in the .service file, I copied the ExecStart line from it and executed it manually. It started without a hitch. Even though I hadn't changed the .service file, I also did a systemctl daemon-reload and restarted the container. Still the same result - manual runs fine; service dies with the ModuleNotFoundError.

That tells me there is something different in your user profile/environment allowing the contents of requirements.txt to be used - compared to the user profile/environment under which the container is running. I'd guess it's either a path issue or the like....

**Comment by dma9** [comment]
Thank you barbequesauce. I had set up the mylar service to run as a system user. There didn't appear to be anything different for that user's profile. 

However, I managed to fix it by running `sudo apt install --reinstall python3-idna`. After doing that, it now works just fine. 

Thanks again to both you and evilhero for your assistance - most appreciated.
