### ISSUE TITLE
Care Package not working - 500 internal server error

### ISSUE THREAD

**Issue by HypKin** [mylar3/mylar3#420]
**Describe the bug**
when i try to load the care package i get an 500 internal server error. 

**Environment (please complete the following information):**
Windows 10, Dev branche, current verison

displayed error

`500 Internal Server Error
The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\cherrypy\_cprequest.py", line 638, in respond
    self._do_respond(path_info)
  File "C:\Python37\lib\site-packages\cherrypy\_cprequest.py", line 697, in _do_respond
    response.body = self.handler()
  File "C:\Python37\lib\site-packages\cherrypy\lib\encoding.py", line 219, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "C:\Python37\lib\site-packages\cherrypy\_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "D:\mylar3\mylar\webserve.py", line 5784, in carepackage
    cp = carePackage()
  File "D:\mylar3\mylar\carepackage.py", line 85, in __init__
    self.environment()
  File "D:\mylar3\mylar\carepackage.py", line 101, in environment
    text=True)
  File "C:\Python37\lib\subprocess.py", line 474, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "C:\Python37\lib\subprocess.py", line 939, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "C:\Python37\lib\subprocess.py", line 1288, in _communicate
    stdout = stdout[0]
IndexError: list index out of range`

couldnt find anything in the debug logs that would have anything to do with this error.

**Comment by psychogun** [comment]
I am taking a wild guess: 

@HypKin : Do you have an environment path / symbolic link for `pip3`? 

On Linux it would be as easy as doing `ln -s /usr/local/bin/pip-3.7 /usr/local/bin/pip3` (creating a symbolic link)

On Windows, you'll have to create an environment path; follow this guide: https://www.architectryan.com/2018/03/17/add-to-the-path-on-windows-10/

(So if you open up Command prompt, you can now execute `pip3` by just writing `pip3`- and not have to write `C:\Program Files\pip3\pip3.exe`)

Could you try this?

**Comment by barbequesauce** [comment]
Any news @hypkin?

**Comment by HypKin** [comment]
too much work at the moment, sorry, but I was able to take a look yesterday and from what i can tell the path variables are set. I still have to take a deeper look, maybe I'll find some time in the next week.

**Comment by HypKin** [comment]
still cant figure it out, pip and python already are in the PATH on windows. still looking into it

**Comment by barbequesauce** [comment]
silly question - what happens when you open a command prompt and run `systeminfo` ?

**Comment by psychogun** [comment]
.. and what happens if you write `pip3`?

**Comment by HypKin** [comment]
systeminfo gives

![image](https://user-images.githubusercontent.com/15702664/95782964-2e55b880-0cd1-11eb-9d4b-e80d887efdee.png)


pip3 just shows all possible commands

![image](https://user-images.githubusercontent.com/15702664/95782989-3b72a780-0cd1-11eb-8961-9f3be627d87b.png)

**Comment by evilhero** [comment]
I wonder if that ```text=True``` line we added a few months ago is straight ascii converting the output, and given that your OS is non-English its capping out on the special characters.

**Comment by HypKin** [comment]
well, I'll just install the english language pack, change the language and then will try it again ;)

**Comment by HypKin** [comment]
ok that didn't do the trick, i guess I also need to change some other things, because system locale is still german...

![image](https://user-images.githubusercontent.com/15702664/95784768-c012f500-0cd4-11eb-9ee3-0fafaf4b7ce4.png)

**Comment by evilhero** [comment]
What version of python are you running? Just curious

**Comment by HypKin** [comment]
3.7.4

![image](https://user-images.githubusercontent.com/15702664/95786446-da020700-0cd7-11eb-98fd-59a627b658f1.png)

**Comment by HypKin** [comment]
[carepackage.zip](https://github.com/mylar3/mylar3/files/5440313/carepackage.zip)
one of the changes in the last 2 weeks did it. its working now.
