### ISSUE TITLE
Comics stuck in Loading (refreshing)

### ISSUE THREAD

**Issue by leaderdog** [mylar3/mylar3#426]
Hi Evilhero,

I'm not sure what's happening.  I have 254 comics stuck in loading stage, I hit refresh on a few of them and nothing happens other than "An Error Has Occurred"

`27-Aug-2020 21:53:24 - INFO    :: mylar.dbUpdate.121 : CP Server Thread-2 : Refreshing/Updating: Join the Future (2020) [125500]
27-Aug-2020 21:53:24 - INFO    :: mylar.addComictoDB.87 : CP Server Thread-2 : aliases currently: None
27-Aug-2020 21:53:24 - INFO    :: mylar.validateAndCreateDirectory.1717 : CP Server Thread-2 : [DIRECTORY-CHECK] Found comic directory: H:\Aftershock Comics\Join the Future (2020)
27-Aug-2020 21:53:26 - INFO    :: mylar.addComictoDB.131 : CP Server Thread-2 : Now adding/updating: Join the Future
27-Aug-2020 21:53:26 - INFO    :: mylar.addComictoDB.184 : CP Server Thread-2 : Sucessfully retrieved details for Join the Future
27-Aug-2020 21:53:26 - INFO    :: mylar.addComictoDB.190 : CP Server Thread-2 : Previous version detected as None - seeing if update required
27-Aug-2020 21:53:38 - INFO    :: mylar.toggleVerbose.4147 : CP Server Thread-9 : Verbose (DEBUG) logging is enabled
27-Aug-2020 21:53:38 - DEBUG   :: mylar.toggleVerbose.4148 : CP Server Thread-9 : If you can read this message, debug logging is now working
27-Aug-2020 21:53:38 - INFO    :: mylar.toggleVerbose.4151 : CP Server Thread-9 : config file has been loaded from: C:\mylar3\config.ini
27-Aug-2020 21:54:14 - DEBUG   :: mylar.refreshSeries.1063 : CP Server Thread-5 : Refreshing comic: ['125500']
27-Aug-2020 21:54:14 - INFO    :: mylar.dbUpdate.121 : CP Server Thread-5 : Refreshing/Updating: Join the Future (2020) [125500]
27-Aug-2020 21:54:14 - DEBUG   :: mylar.dbUpdate.140 : CP Server Thread-5 : CV_OneTimer option enabled...
27-Aug-2020 21:54:14 - DEBUG   :: mylar.dbUpdate.142 : CP Server Thread-5 : Gathering the status of all issues for the series.
27-Aug-2020 21:54:14 - DEBUG   :: mylar.dbUpdate.152 : CP Server Thread-5 : Checking how out of whack the series is.
27-Aug-2020 21:54:14 - DEBUG   :: mylar.dbUpdate.168 : CP Server Thread-5 : checking annual db
27-Aug-2020 21:54:14 - DEBUG   :: mylar.dbUpdate.184 : CP Server Thread-5 : Refreshing the series and pulling in new data using only CV.
27-Aug-2020 21:54:14 - INFO    :: mylar.addComictoDB.87 : CP Server Thread-5 : aliases currently: None
27-Aug-2020 21:54:14 - INFO    :: mylar.validateAndCreateDirectory.1717 : CP Server Thread-5 : [DIRECTORY-CHECK] Found comic directory: H:\Aftershock Comics\Join the Future (2020)
27-Aug-2020 21:54:17 - DEBUG   :: mylar.GetComicInfo.233 : CP Server Thread-5 : number of issues I counted: 4
27-Aug-2020 21:54:17 - DEBUG   :: mylar.GetComicInfo.234 : CP Server Thread-5 : number of issues CV says it has: 4
27-Aug-2020 21:54:17 - DEBUG   :: mylar.GetComicInfo.240 : CP Server Thread-5 : vari is set to: no
27-Aug-2020 21:54:17 - DEBUG   :: mylar.GetComicInfo.523 : CP Server Thread-5 : comic[ComicVersion]:None
27-Aug-2020 21:54:17 - DEBUG   :: mylar.GetComicInfo.523 : CP Server Thread-5 : comic[ComicVersion]:None
27-Aug-2020 21:54:17 - INFO    :: mylar.addComictoDB.131 : CP Server Thread-5 : Now adding/updating: Join the Future
27-Aug-2020 21:54:17 - INFO    :: mylar.addComictoDB.184 : CP Server Thread-5 : Sucessfully retrieved details for Join the Future
27-Aug-2020 21:54:17 - INFO    :: mylar.addComictoDB.190 : CP Server Thread-5 : Previous version detected as None - seeing if update required`

says the same thing each time.  But it is still stuck in loading.

I tried it with aeon flux since it's an older series:

`27-Aug-2020 21:57:08 - INFO    :: mylar.dbUpdate.121 : CP Server Thread-2 : Refreshing/Updating: Ưn Flux (2005) [19558]
27-Aug-2020 21:57:08 - DEBUG   :: mylar.dbUpdate.140 : CP Server Thread-2 : CV_OneTimer option enabled...
27-Aug-2020 21:57:08 - DEBUG   :: mylar.dbUpdate.142 : CP Server Thread-2 : Gathering the status of all issues for the series.
27-Aug-2020 21:57:08 - DEBUG   :: mylar.dbUpdate.152 : CP Server Thread-2 : Checking how out of whack the series is.
27-Aug-2020 21:57:08 - DEBUG   :: mylar.dbUpdate.168 : CP Server Thread-2 : checking annual db
27-Aug-2020 21:57:08 - DEBUG   :: mylar.dbUpdate.184 : CP Server Thread-2 : Refreshing the series and pulling in new data using only CV.
27-Aug-2020 21:57:08 - INFO    :: mylar.addComictoDB.87 : CP Server Thread-2 : aliases currently: Aeon Flux
27-Aug-2020 21:57:08 - INFO    :: mylar.validateAndCreateDirectory.1717 : CP Server Thread-2 : [DIRECTORY-CHECK] Found comic directory: H:\Dark Horse Comics\Aeon Flux (2005)
27-Aug-2020 21:57:11 - DEBUG   :: mylar.GetComicInfo.233 : CP Server Thread-2 : number of issues I counted: 4
27-Aug-2020 21:57:11 - DEBUG   :: mylar.GetComicInfo.234 : CP Server Thread-2 : number of issues CV says it has: 4
27-Aug-2020 21:57:11 - DEBUG   :: mylar.GetComicInfo.240 : CP Server Thread-2 : vari is set to: no
27-Aug-2020 21:57:11 - DEBUG   :: mylar.GetComicInfo.523 : CP Server Thread-2 : comic[ComicVersion]:None
27-Aug-2020 21:57:11 - INFO    :: mylar.addComictoDB.131 : CP Server Thread-2 : Now adding/updating: Ưn Flux
27-Aug-2020 21:57:11 - INFO    :: mylar.addComictoDB.184 : CP Server Thread-2 : Sucessfully retrieved details for Ưn Flux
27-Aug-2020 21:57:11 - INFO    :: mylar.addComictoDB.190 : CP Server Thread-2 : Previous version detected as None - seeing if update required
27-Aug-2020 21:57:45 - DEBUG   :: mylar.dbUpdate.84 : ThreadPoolExecutor-0_13 : Refresh sequence set to fire every 5 minutes for 7 day(s)`

I removed the mylar.db as it is 28megs so wouldn't fit.
[carepackage.zip](https://github.com/mylar3/mylar3/files/5140012/carepackage.zip)

I haven't changed anything. Just done the updates as they show up.

There are now 260 files on the loading stage.  I know my internet provider sucked for the past few months cutting in and out, so that may have contributed to the problem... 

In Manage Comics I typed in loading, then changed to all and check marked everything and hit refresh (254 files) and was hoping it would just do it's thing, but they're not refreshing.  I've done this countless times in the past and typically it slaves away in the background removing the files slowly, but it's just not working now.

**Comment by evilhero** [comment]
Was a QOL improvement that I was setting up for, but didn't take Windows escape characters into account so it was throwing a traceback error on an initial refresh, and then that locked up that particular module so no further refreshes would work.

Fixed in PR #427, so once it goes into python3-dev you should be good to go. 
Cheers,

**Comment by bguidotti** [comment]
I also have this issue. I eagerly await the fix! Thanks!

**Comment by barbequesauce** [comment]
Should be good now - update and kick the tires please!

**Comment by leaderdog** [comment]
Yep, that got it.  After selecting the 450+ books and setting them to refresh I now have zero stuck in loading.

Thanks for fixing it. :)
