### ISSUE TITLE
[bug report] Traceback error during manual pp of new titles

### ISSUE THREAD

**Issue by professionaltart** [mylar3/mylar3#429]
**Describe the bug**
CV hasn't updated this week's pull list as out, but I saw them in a manual Hydra check.
I grabbed them and tried to run a manual-pp in Mylar to see if it'd pick them up and move them (so it doesn't re-down them again in a few hours).  Checked logs and saw the traceback error.

**CarePackage**
[carepackage(1).zip](https://github.com/mylar3/mylar3/files/5143462/carepackage.1.zip)

**Environment (please complete the following information):**
 - OS: Windows10 Pro 2004
 - Branch / commit:  85a6354c77a38cda7f1b5e123a8dd58f7d02ef1a (python3-dev)

**Comment by evilhero** [comment]
The exception for the manual post-processing wasn't in the actual log - it looks like it was stopped right as it was logging the error, so no error.

Can you try to redo it with the error included, or even paste the entire traceback?

**Comment by professionaltart** [comment]
[carepackage(2).zip](https://github.com/mylar3/mylar3/files/5148205/carepackage.2.zip)
Sorry about that.  In that care package, tracebacks are in mylar.log and mylar.log.2
With how they're sanitised, I'm not entirely sure if two days ago is still in the logs or has churned - the above two seem related to threading and comictagger.  

I think the Hellions one was also from doing a manual PP, but I'm not 100% it's the same traceback as the manual PP that started this ticket.

Starting to wish I'd pasted the traceback error when I created the ticket :(

**Comment by evilhero** [comment]
There's something messed up in there - it's saying it can't find the directory then when it goes to create it, it says it already exists. Did the permissions or something change on the .ComicTagger folder within the user's home directory ? Are you running it as a different user now perhaps than previously ? 

Maybe if you can, delete the .ComicTagger folder with Mylar not running, and let it auto-recreate on startup. If you have a ```ComicTagger``` or ```.ComicTagger``` directory in the root of your mylar install - delete that too.

**Comment by professionaltart** [comment]
I don't think it's a different user, but can't rule it out since homedir\.ComicTagger was created back in late June
I've just stopped the mylar service and deleted the folder.  There's no .comictagger folder in \mylar3 (where mylar runs from)

After restarting, there's not much for Mylar to do.  I tried a manual pp again for a TMNT annual, but so far I haven't seen it error out, but also .ComicTagger hasn't been recreated in either location

**Comment by evilhero** [comment]
Should also have mentioned that you may have to set your ```ct_settingspath = None``` in the mylar.ini file.

Have you tried running mylar from the cli and seeing if that works? You can always try to retag an existing cbz file - if you have overwrite set (which I think you do), it'll just hammer the existing tags to write the new ones. But it'll log any errors regardless which is what we need to see.

**Comment by professionaltart** [comment]
[carepackage(3).zip](https://github.com/mylar3/mylar3/files/5148643/carepackage.3.zip)
Done and done and done
Set ct_settingspath = None in config.ini
Manually deleted .comictagger dir
Set Mylar to manually metatag an issue of Hellions

Not entirely sure it's being done right - probably by me - as I'm not seeing a re-created .comictagger folder in user homedir or mylar homedir.  But it looked in the logs like it retagged the issue.

**Comment by barbequesauce** [comment]
So is it working as expected, or still problematic?

**Comment by professionaltart** [comment]
I think it may be resolved, @barbequesauce .  I haven't noticed tracebacks relating to this since the change in August, but also haven't found Mylar recreate the .comictagger directory after editing config.ini
