### ISSUE TITLE
Incorrect Issues grab - Empyre

### ISSUE THREAD

**Issue by SenorSmartyPants** [mylar3/mylar3#432]
**Describe the bug**
Mylar tries to grab issues for main series Empyre (2020) but is grabbing tie in issues.

**CarePackage**
[carepackage (1).zip](https://github.com/mylar3/mylar3/files/5147113/carepackage.1.zip)

**Environment (please complete the following information):**
 - OS: Hotio Docker/Debian
 - Branch / commit: mylar3/dev (build ec0b7e1b7db0e8a5a838916c94e6446ee131f8ac)

**Comment by evilhero** [comment]
Can confirm this is an issue. Looking at this now and doing some testing. Got some semi-code working, and correctly taking the right series vs the wrong series now, but still need to do more testing. Should be ready to go at some point later today

**Comment by SenorSmartyPants** [comment]
This update now grabs the correct Empyre issues.
