### ISSUE TITLE
Ubuntu 18: Manually runs fine, times out as service

### ISSUE THREAD

**Issue by sufr3ak** [mylar3/mylar3#435]
I upgraded from old mylar, copied my config.ini, mylar.db, and cache directory to the new path, mylar3. When I run " python3 Mylar.py", everything starts up with no problems. I'm running as an account called "johndoe" (not the account name)

Following the instructions here: https://github.com/mylar3/mylar3/blob/master/init-scripts/systemd/read.me

mylar3 path: /opt/mylar3.  (path and subdirectory owned by johndoe123:johndoe123
/init-scripts/systemd/mylar.service was properly copied as /lib/systemd/system/mylar.service
symlink: /etc/systemd/system/mylar.service created
copied /init-scripts/systemd/mylar.default to /etc/default/mylar
copied /init-scripts/systemd/mylar.initd to /etc/init.d/mylar (permissions +x applied)

/etc/default/mylar edits:  (uncommented)

MYLAR_USER=johndoe123
MYLAR_HOME=/opt/mylar3
MYLAR_DATA=/opt/mylar3
PYTHON_BIN=/usr/bin/python3

/opt$ python3 -V  (Python 3.7.5)
opt$ /usr/bin/python3 -V Python 3.7.5)

systemctl daemon-reload ran without issue
sudo systemctl enable mylar ran without issue
sudo systemctl start mylar hangs

So far, I don't see what could be causing the issue.  But, I did wonder, shouldn't the defaults of /etc/init.d/mylar point to mylar3 and python3 (since /user/bin/python will point to python2 if it exists on the system)

**Comment by evilhero** [comment]
Yeah that needs to be updated.don't do the init.d link crap - it's abit of a janky workaround.

Easiest way to do it is to just create a mylar.service file calling the application directly. You can see an example that I've posted here:  https://github.com/mylar3/mylar3/issues/397#issuecomment-660721128

**Comment by sufr3ak** [comment]
Brilliant.

It worked, I do offer 1 suggestions

ExecStart=/usr/bin/python3 /opt/mylar3/Mylar.py -v --daemon  --nolaunch --quiet

This way it isn't bound to specific python 3.7/3.8, etc.   I changed mine to /opt/, but obviously that's relative.


The instructions in  mylar3/init-scripts/systemd/read.me  should just read: (with the new service file:

Instructions on setting up mylar as a systemd service that will run on startup/via systemctl commands...

1 - copy the mylar.service to /lib/systemd/system/mylar.service
2 - edit the /lib/systemd/system/mylar.service file. (username, group, python path, Mylar.py path)

Make systemd aware of new services: 
sudo systemctl daemon-reload
sudo systemctl enable mylar

Start mylar
sudo systemctl start mylar

check to see if running
sudo systemctl status mylar

**Comment by barbequesauce** [comment]
#436 sumbitted with this change - thank you!

**Comment by evilhero** [comment]
Yeah, but it's system dependent - what one user runs as python3, another one uses as python3.8, and another just calls it as python (ie. Ubuntu 20) - so it's best to keep it as generic as possible - I updated the #436 so it's generic along with updating the service file and removing the old init.d stuff. Should be in dev soon.

**Comment by barbequesauce** [comment]
Merged!

**Comment by barbequesauce** [comment]
We ok to close this @sufr3ak ?

**Comment by sufr3ak** [comment]
I feel so
