### ISSUE TITLE
Can't launch Mylar3

### ISSUE THREAD

**Issue by shpanky73** [mylar3/mylar3#439]
Any ideas why I might be getting this?  Thanks so much in advance.

log language set to en_US
Verbose/Debugging mode enabled...
Initializing startup sequence....
03-Sep-2020 16:29:00 - DEBUG :: mylar.configure.889 : MainThread : Log dir: c:\Mylar3\cache
03-Sep-2020 16:29:00 - INFO :: mylar.configure.1015 : MainThread : [COMICTAGGER] Version detected: 1.3.3
03-Sep-2020 16:29:00 - DEBUG :: mylar.configure.1054 : MainThread : [COMICTAGGER] Setting ComicTagger settings default path to : C:\mylar3\.ComicTagger
03-Sep-2020 16:29:00 - INFO :: mylar.initialize.188 : MainThread : Checking to see if the database has all tables....
03-Sep-2020 16:29:00 - INFO :: mylar.dbcheck.1325 : MainThread : Ensuring DB integrity - Removing all Erroneous Comics (ie. named None)
03-Sep-2020 16:29:00 - INFO :: mylar.dbcheck.1327 : MainThread : Correcting Null entries that make the main page break on startup.
03-Sep-2020 16:29:00 - INFO :: mylar.initialize.202 : MainThread : Successfully discovered local IP and locking it in as : 192.168.86.25
03-Sep-2020 16:29:00 - DEBUG :: mylar.initialize.214 : MainThread : Logger set to use : Rotational Log Handler (default)
03-Sep-2020 16:29:00 - DEBUG :: mylar.initialize.216 : MainThread : ConcurrentLogHandler package not installed. Using builtin log handler for Rotational logs (default)
03-Sep-2020 16:29:00 - DEBUG :: mylar.initialize.217 : MainThread : [Windows Users] If you are experiencing log file locking and want this auto-enabled, you need to install Python Extensions for Windows ( http://sourceforge.net/projects/pywin32/ )
03-Sep-2020 16:29:00 - DEBUG :: mylar.initialize.247 : MainThread : SEARCH_TIER_DATE set to : 2020-08-20
03-Sep-2020 16:29:00 - INFO :: mylar.updateComicLocation.812 : MainThread : Performing a one-time mass update to Comic Location
03-Sep-2020 16:29:00 - INFO :: mylar.validateAndCreateDirectory.1717 : MainThread : [DIRECTORY-CHECK] Found comic directory: G:\Google Drive\comic books
03-Sep-2020 16:29:00 - ERROR :: mylar.excepthook.315 : MainThread : Uncaught exception: Traceback (most recent call last):
  File "mylar.py", line 386, in <module>
    main()
  File "mylar.py", line 203, in main
    mylar.initialize(mylar.CONFIG_FILE)
  File "C:\mylar3\mylar\__init__.py", line 260, in initialize
    helpers.updateComicLocation()
  File "C:\mylar3\mylar\helpers.py", line 889, in updateComicLocation
    com_done = re.sub('%&', os.sep.encode('unicode-escape'), comlocation).strip()
  File "C:\Users\Adam\AppData\Local\Programs\Python\Python37-32\lib\re.py", line 194, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: sequence item 1: expected str instance, bytes found

Traceback (most recent call last):
  File "mylar.py", line 386, in <module>
    main()
  File "mylar.py", line 203, in main
    mylar.initialize(mylar.CONFIG_FILE)
  File "C:\mylar3\mylar\__init__.py", line 260, in initialize
    helpers.updateComicLocation()
  File "C:\mylar3\mylar\helpers.py", line 889, in updateComicLocation
    com_done = re.sub('%&', os.sep.encode('unicode-escape'), comlocation).strip()
  File "C:\Users\Adam\AppData\Local\Programs\Python\Python37-32\lib\re.py", line 194, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: sequence item 1: expected str instance, bytes found

C:\mylar3>

**Comment by evilhero** [comment]
Are you upgrading an existing install?

If you were was it on a different OS previously?

If it's a new installation (new/blank db), what do you have for your destination_dir value in the config.ini for mylar?

**Comment by shpanky73** [comment]
I am installing the new mylar3 in a different directory from the original mylar, then I copied over my files from the original mylar instance into the new one.  I  am on the same OS as I was before.  The destination_dir is destination_dir = G:\Google Drive\comic books

**Comment by shpanky73** [comment]
I've now reinstalled mylar3 into the original directory for previous instance.  I followed the directions provided: 
copy over your config.ini, mylar.db, and cache directory
edit config.ini and change log_dir and cache_dir to the new path; also set git_user to mylar3
from the root of the new Mylar directory, run pip3 install -r requirements.txt

and tried again, but still getting error response.  Is it because my comic collection is on an external drive?

**Comment by shpanky73** [comment]
Here's my log for this: 
03-Sep-2020 17:02:20 - INFO    :: mylar.configure.1015 : MainThread : [COMICTAGGER] Version detected: 1.3.3
03-Sep-2020 17:02:20 - INFO    :: mylar.initialize.188 : MainThread : Checking to see if the database has all tables....
03-Sep-2020 17:02:20 - INFO    :: mylar.dbcheck.1325 : MainThread : Ensuring DB integrity - Removing all Erroneous Comics (ie. named None)
03-Sep-2020 17:02:20 - INFO    :: mylar.dbcheck.1327 : MainThread : Correcting Null entries that make the main page break on startup.
03-Sep-2020 17:02:20 - INFO    :: mylar.initialize.202 : MainThread : Successfully discovered local IP and locking it in as : 192.168.86.25
03-Sep-2020 17:02:20 - INFO    :: mylar.updateComicLocation.812 : MainThread : Performing a one-time mass update to Comic Location
03-Sep-2020 17:02:20 - INFO    :: mylar.validateAndCreateDirectory.1717 : MainThread : [DIRECTORY-CHECK] Found comic directory: G:\Google Drive\comic books
03-Sep-2020 17:02:20 - ERROR   :: mylar.excepthook.315 : MainThread : Uncaught exception: Traceback (most recent call last):
  File "mylar.py", line 386, in <module>
    main()
  File "mylar.py", line 203, in main
    mylar.initialize(mylar.CONFIG_FILE)
  File "C:\mylar\mylar\__init__.py", line 260, in initialize
    helpers.updateComicLocation()
  File "C:\mylar\mylar\helpers.py", line 889, in updateComicLocation
    com_done = re.sub('%&', os.sep.encode('unicode-escape'), comlocation).strip()
  File "C:\Users\Adam\AppData\Local\Programs\Python\Python37-32\lib\re.py", line 194, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: sequence item 1: expected str instance, bytes found

03-Sep-2020 17:05:49 - INFO    :: mylar.configure.1015 : MainThread : [COMICTAGGER] Version detected: 1.3.3
03-Sep-2020 17:05:49 - INFO    :: mylar.initialize.188 : MainThread : Checking to see if the database has all tables....
03-Sep-2020 17:05:50 - INFO    :: mylar.dbcheck.1325 : MainThread : Ensuring DB integrity - Removing all Erroneous Comics (ie. named None)
03-Sep-2020 17:05:50 - INFO    :: mylar.dbcheck.1327 : MainThread : Correcting Null entries that make the main page break on startup.
03-Sep-2020 17:05:50 - INFO    :: mylar.initialize.202 : MainThread : Successfully discovered local IP and locking it in as : 192.168.86.25
03-Sep-2020 17:05:50 - INFO    :: mylar.updateComicLocation.812 : MainThread : Performing a one-time mass update to Comic Location
03-Sep-2020 17:05:50 - INFO    :: mylar.validateAndCreateDirectory.1717 : MainThread : [DIRECTORY-CHECK] Found comic directory: G:\Google Drive\comic books
03-Sep-2020 17:05:50 - ERROR   :: mylar.excepthook.315 : MainThread : Uncaught exception: Traceback (most recent call last):
  File "mylar.py", line 386, in <module>
    main()
  File "mylar.py", line 203, in main
    mylar.initialize(mylar.CONFIG_FILE)
  File "C:\mylar\mylar\__init__.py", line 260, in initialize
    helpers.updateComicLocation()
  File "C:\mylar\mylar\helpers.py", line 868, in updateComicLocation
    ddir = re.sub(r'[\\|/]', '%&', mylar.CONFIG.DESTINATION_DIR)
  File "C:\Users\Adam\AppData\Local\Programs\Python\Python37-32\lib\re.py", line 194, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object

**Comment by barbequesauce** [comment]
Can you post your config.ini please? Don't forget to redact keys & passwords...

**Comment by shpanky73** [comment]
I actually started with a fresh config.ini and filled in the parameters myself and things seem to be working now.
