### ISSUE TITLE
QNAP Installation

### ISSUE THREAD

**Issue by Rumik** [mylar3/mylar3#442]
**Describe the request**
A method of installation for QNAP network hard drives, e.g. an installation package or instructions.

**How did you come up with the idea?**
I've been using Mylar 2 on my QNAP (installed via a package at QnapClub Store) for a few years, but I'd like to run the latest and greatest version!

**Environment (please complete the following information):**
 - OS: Linux
 - Branch / commit: [e.g. Dev/38aksi1]: No idea

**Additional information**
Add any other information about the request here.

**Comment by evilhero** [comment]
Don't use / have access to a QNAP, so I wouldn't know the first thing about making a package or installation instructions. 

The closest thing might be to do what a user of mylar2 posted on the forums [here](https://forum.mylarcomics.com/viewtopic.php?t=1793#p9395) (granted for mylar2 but should still work if py3 is on the system). You'd have to still do the requirements.txt install after the initial git clone of the mylar3 repo, but aside from that it might work as a 'workaround' (haven't a clue, but it might be quicker than waiting for a qpkg).

Leaving this here in case someone else can chime in, but aside from running a docker install of some sort, and of course the normal git install - I can't really help on this unfortunately.

**Comment by Rumik** [comment]
Okay, thanks anyway. Apparently my IP has been banned on the forums? Which I find strange because I haven't logged in in a couple of years! :P

I have docker but I've no idea what to do about installing Mylar3 via a docker image.

**Comment by OneCDOnly** [comment]
@Rumik checkout [sherpa](https://github.com/OneCDOnly/sherpa). ;)

**Comment by Rumik** [comment]
> @Rumik checkout [sherpa](https://github.com/OneCDOnly/sherpa). ;)

I think I love you!

Thanks 👍
