### ISSUE TITLE
ModuleNotFoundError: No module named 'jaraco.collections'

### ISSUE THREAD

**Issue by anizee** [mylar3/mylar3#448]
I'm updating from the old mylar to mylar3.  

My python output:

`/opt/mylar3$ python3 --version
Python 3.8.5
`

this is the output I get when I run mylar:

`
> /opt/mylar3$ python3 Mylar.py
> Traceback (most recent call last):
>   File "Mylar.py", line 26, in <module>
>     import mylar
>   File "/opt/mylar3/mylar/__init__.py", line 36, in <module>
>     import cherrypy
>   File "/home/anizee/.local/lib/python3.8/site-packages/cherrypy/__init__.py", line 66, in <module>
>     from ._cperror import (
>   File "/home/anizee/.local/lib/python3.8/site-packages/cherrypy/_cperror.py", line 135, in <module>
>     from cherrypy.lib import httputil as _httputil
>   File "/home/anizee/.local/lib/python3.8/site-packages/cherrypy/lib/httputil.py", line 20, in <module>
>     import jaraco.collections
> ModuleNotFoundError: No module named 'jaraco.collections'
`

Any idea how to fix this?

**Comment by anizee** [comment]
I did install:

> `pip3 install jaraco.collections
Collecting jaraco.collections
  Using cached https://files.pythonhosted.org/packages/fe/06/a89652069f0a13a33701714c0c8e0cc8656bf6d21b7c6b85fde86cf06ff6/jaraco.collections-3.0.0-py2.py3-none-any.whl
Collecting six>=1.7.0 (from jaraco.collections)
  Using cached https://files.pythonhosted.org/packages/ee/ff/48bde5c0f013094d729fe4b0316ba2a24774b3ff1c52d924a8a4cb04078a/six-1.15.0-py2.py3-none-any.whl
Collecting jaraco.classes (from jaraco.collections)
  Using cached https://files.pythonhosted.org/packages/68/ce/8f43aa0d0f18120e687ae0192fe3168630040841a3e87bed93c5fe024dbe/jaraco.classes-3.1.0-py2.py3-none-any.whl
Collecting jaraco.text (from jaraco.collections)
  Using cached https://files.pythonhosted.org/packages/50/cd/6eda44738065e844bed8fae60a229b6c46f42d0ba8d48205e9fb57e254cd/jaraco.text-3.2.0-py2.py3-none-any.whl
Collecting more-itertools (from jaraco.classes->jaraco.collections)
  Using cached https://files.pythonhosted.org/packages/ec/f7/9c33f38577d9fb9b1aa60c0fd9961d09574f5d47d2b830e5183e6adfc8cc/more_itertools-8.5.0-py3-none-any.whl
Collecting jaraco.functools (from jaraco.text->jaraco.collections)
  Using cached https://files.pythonhosted.org/packages/4f/2b/bbab94f3e461adaf3c7a3a25da0c67c91d8cf7a4ddae7096028601ff940f/jaraco.functools-3.0.1-py3-none-any.whl
Installing collected packages: six, more-itertools, jaraco.classes, jaraco.functools, jaraco.text, jaraco.collections
Successfully installed jaraco.classes-3.1.0 jaraco.collections-3.0.0 jaraco.functools-3.0.1 jaraco.text-3.2.0 more-itertools-8.5.0 six-1.15.0
`

**Comment by evilhero** [comment]
This was from a quick google search: 
https://github.com/sabnzbd/sabnzbd/issues/1522#issuecomment-684002979

Some kind of cherrypy requirement that I guess you're possibly hitting due to having installed it previously as a non-pip entry, and then trying to install it via the pip is throwing the error. 

You'd have to determine how you installed cherrypy (```ie. apt-get install python-cherrypy, easy_install cherrypy, pip install cherrypy, or possibly source```), and either uninstall that method so the requirements.txt would fly. 

Or possibly even simpler -  just comment out the cherrypy requirement in requirements.txt (possibly cheroot too but not 100% sure if that would affect things) which should get things setup properly (assuming the version of cherrypy on your system is at least 18.6.0).

**Comment by barbequesauce** [comment]
@anizee can we close this?
