### ISSUE TITLE
When rechecking files, GUI won't refresh properly leaving 

### ISSUE THREAD

**Issue by evilhero** [mylar3/mylar3#459]
**Describe the bug** (from the forums)
When I hit recheck it won't refresh the page fully. it'll leave the annuals in massive rectangles It updates the file and took issues out of retry status but i have to refresh the browser to sort that out. It used to do that correctly.

forum link [here](http://forum.mylarcomics.com/viewtopic.php?f=8&t=2319&p=11613&sid=bce6f008a1cbdb6b617f50b2fabf9ea6#p11603) for reference.

**Comment by xthursdayx** [comment]
I'm finding this same issue with the annuals and rectangles.

**Comment by evilhero** [comment]
stale and outdated - fixed in recent bulids.
