### ISSUE TITLE
Carbon 404'd images

### ISSUE THREAD

**Issue by barbequesauce** [mylar3/mylar3#462]
Using 61a69c8

<img width="1434" alt="Screen Shot 2020-09-15 at 5 17 32 PM" src="https://user-images.githubusercontent.com/25070944/93266252-c797ba80-f777-11ea-863b-6cdc1b5aa91b.png">

**Comment by evilhero** [comment]
How tf did you manage to do that one, dude ? 

I've tried both carbon and default interface, both with and without restarting Mylar, and haven't been able to duplicate this at all on my side for comparison. Easy q - but did you restart Mylar and/or try incognito mode?

**Comment by barbequesauce** [comment]
Yeah i get the same with incog. I'm wondering if i broke something with the half-baked work on status selectors for the series page... ignore me :)
