### ISSUE TITLE
Find all .cbr files that haven't been metatagged

### ISSUE THREAD

**Issue by BRTPOB** [mylar3/mylar3#465]
This was something that came up while I was working with ajslater's codex, but it would be great to have a list that shows all of the .cbr files that Mylar knows about that haven't been metatagged, so that I could then run through and convert them from cbr to cbz to then get the metatagging added.

**Comment by barbequesauce** [comment]
to clarify - cbr's that do not have comicinfo.xml? you're not concerned with cbzs?

**Comment by BRTPOB** [comment]
CBRs by default don't have ComicInfo.xml, that's how Mylar works as far as evilhero explained it to me. That said, if I could find the CBZs that don't have the ComicInfo.xml as well that would be great as well, yeah.

**Comment by barbequesauce** [comment]
run this from the root of your comics library
`find . -iname *.cbr`

this will check all the cbzs for metatagging, calling out the ones not tagged and the bad zips
```import sys
import zipfile
import os
import subprocess
from zipfile import BadZipFile

results = subprocess.run(['find', '.', '-iname', '*.cbz'], universal_newlines = True, stdout=subprocess.PIPE)

for result in results.stdout.splitlines():
    tagged = 0
    target_zip = str(result)
#    print("file: %s" % target_zip)
    try:
        with zipfile.ZipFile(target_zip) as zip_file:
            for member in zip_file.namelist():
                if 'ComicInfo.xml' in member:
                    tagged = 1
            if tagged == 0:
                print("Filename %s is not metatagged" % target_zip)
            elif tagged == 1:
                next
#                print("filename %s is correctly metatagged" % target_zip)
            else:
                print("Tits up! %s" % target_zip)
    except BadZipFile:
        print("%s is a bad zipfile!" % target_zip)```

**Comment by barbequesauce** [comment]
Created a new 'utilities' folder with both of these scripts in it - if you think of other useful scripts, happy to add them!
