### ISSUE TITLE
Info for annuals on details page

### ISSUE THREAD

**Issue by leaderdog** [mylar3/mylar3#469]
For some reason the annuals for Teen Titans 2014 were added to Teen Titans 2016.

Not sure why, but it is easy to fix if we knew which annuals at the bottom to x out.

At the bottom under Annuals it has:
Teen Titans Annual x Teen Titans Annual x

I've no clue which one is which, or if it goes in order it was added.  Could we have a mouse over or even make it a clickable link to the titles on comicvine?

That way we have the correct information to remove the right one as well as an easy way to add the comicvine id to the correct title.

Thanks :)

**Comment by evilhero** [comment]
Yep, I have something in the pip already for this. Just need to clean it up abit. Should be in dev by later today.

**Comment by evilhero** [comment]
Haven't forgotten about this at all - just trying to clean up some other issues first (unfortunately), and then finish off some spacing in the GUI to account for things.

**Comment by evilhero** [comment]
Closing as this should be resolved (meaning you can clearly see which issues belong to which annual) now in the latest builds.
