### ISSUE TITLE
Odd Title Handling

### ISSUE THREAD

**Issue by jun6lee** [mylar3/mylar3#480]
https://comicvine.gamespot.com/hellboy-makoma-or-a-tale-told-by-a-mummy-in-the-ne/4050-18284/

Struggling to get the 2 issues of this recognised. 
Could you guide if it's too odd a title or how I should name the files to be recognised?

Thus far, I've tried:

Hellboy Makoma or a Tale Told by a Mummy in the New York City Explorers Club on August 16 1993 - 01 (2006)
Hellboy Makoma or a Tale Told by a Mummy in the New York City Explorers Club - 01 (2006)
Hellboy Makoma - 01 (2006)

As an enhancement, it would be great if we could preview what Mylars post-processing would name a file.

**Comment by evilhero** [comment]
The ```’```  in the CV title itself was the problem - Mylar was not matching properly to those types of punctuation for some reason, or at least in this case it wasn't. Fix is in python3-dev branch now.

For it to match however, the title has to match exactly as to how CV has it - which would mean that your first example would match ( and does with the fix ), but the remaining 2 would not match at all.

Also it's impossible to preview what a file is like during post-processing since there is no GUI option to see what's being detected during post-processing, and honestly there never will be - that's far too much work for something of very little use overall. There is a Preview Renamer that is coming whereby you can view how renaming formatting is applied to files that are already downloaded, however it's only for items that are already in a Downloaded state.

**Comment by jun6lee** [comment]
That tool would still be great. I tend to download packs and then pick what I want in my library, so I can rename accordingly.
Found another title that I'm struggling with, this time with " 

https://comicvine.gamespot.com/james-bond-in-reflections-of-death-1-ogn/4000-799856/

**Comment by evilhero** [comment]
Try setting the ```Alternate Search Name``` field in the Edit Settings tab for that series to something that doesn't include the ```"``` (ie. like ```James Bond in Reflections of Death```). 

The Alternate Search Name is used when you have filenames that are named differently than what CV has them as (as CV can have really f'd up naming, as is the case in this case), and it applies to all aspects of matching - so file checking, post-processing, searching.

You might also want to look at the ```Alternate File-Naming``` field on the Edit Settings tab as well. Whatever name is set here is how your files will be renamed to, ie. ```James Bond in Reflections of Death``` as  by default, Mylar will take the series title from CV as the title in a renamed filename (if you have renaming enabled) - which would also then get past the ```"``` in the CV title aspect once it's been renamed. 

Of course, if you just set the Alternate Search Name that would be good enough for Mylar to still see the file, just the file on your system would be possibly different (not too sure if it would actually write ```"``` in the filename itself).

I'll look into the ```"``` not being included in the comparisons.

**Comment by jun6lee** [comment]
Here's another messed up title:
https://comicvine.gamespot.com/god-is-dead-the-book-of-acts/4050-76270/ 

They've put # in the issue number and not even used numbers.

**Comment by evilhero** [comment]
The only way to handle the last one (where the issue numbering is #alpha and #omega for issues #1 and #2 respectively) is to actually use the pound sign to designate that it's an issue numbering (ie. ```#alpha```, or ```#omega```). Doing it this way will ensure that Mylar can detect the issues properly (and it does) as those are the actual issue numbers (and yes, other series have done this in the past).

**Comment by jun6lee** [comment]
I'm struggling with this last one. When I add the comic (not the files), it never seems to get out of the loop of refreshing.
ie; It doesn't know show any issues. Folder is created, but no cvinfo or cover.

I've tried manually putting in a cvinfo file and refreshing comic. No joy.

WARNING | [FILE-RESCAN] you should either Refresh the series, and/or submit an issue on github in regards to the series and the error.
WARNING | [FILE-RESCAN] An error occured trying to get the relevant issue data. This is probably due to the series not having proper issue data.

---

Appreciate the input above, but I've not got that far (yet, I think).

**Comment by evilhero** [comment]
cvinfo doesn't affect file rechecking - as it assumes everything in the given directory belongs to that specific series. The cvinfo file only matters during an import (at least for Mylar's use anyways).

Try putting mylar into debug mode (start it with the -v switch, or go into History, Logs, and then click on the Toggle Verbose Loggin ON option in the upper right).  Once it's in debug mode, try the refresh again and paste / pastebin that in here - INFO level logging isn't enough to debug anything unfortunately.

**Comment by evilhero** [comment]
I'm guessing you're running the master branch of mylar3.

The fixes thus far that have been addressed are in the python3-dev branch atm, awaiting the merge to the master branch.

Also, if you're indicating about the last title, you need to precede both omega and alpha with a poundsign (ie. ```#omega``` or ```#alpha```).

**Comment by jun6lee** [comment]
I can't change my branch. Qnap package seems to default master on startup.
I was referring to the last title though. You can probably replicate this easily enough.

Search: 4050-76270
Details of the comic appear, but not of the issues. 
((Comic information is currently being loaded)) keeps looping.

https://i.imgur.com/VdaTdJz.png

This is before I try to import any issue.

**Comment by evilhero** [comment]
This has already been fixed in the python3-dev branch (#480) - which allows for Mylar to be able to interpret the issue naming of ```Omega``` and ```Alpha```, which are the 2 issues in that particular series that is having problems.

You'll have to wait for the merge to master if you can't switch branches.

**Comment by jun6lee** [comment]
Sure thing, no problem. I'll wait it out. Not in a hurry. Thank you.
