### ISSUE TITLE
TypeError: can only concatenate str (not "NoneType") to str in duplicate_filecheck

### ISSUE THREAD

**Issue by PCurd** [mylar3/mylar3#488]
**Describe the bug**
After migrating config from Mylar2 to Mylar3 I left the dupeconstraint = None from the sample Mylar3 config.ini. This seems to break a debug line in helpers.py/duplicate_filecheck

```
Uncaught exception: Traceback (most recent call last):
File "/app/mylar/logger.py", line 337, in new_run
old_run(*args, **kwargs)
File "/usr/lib/python3.8/threading.py", line 870, in run
self._target(*self._args, **self._kwargs)
File "/app/mylar/PostProcessor.py", line 1736, in Process
dupthis = helpers.duplicate_filecheck(ml['ComicLocation'], ComicID=comicid, IssueID=issueid)
File "/app/mylar/helpers.py", line 2189, in duplicate_filecheck
logger.fdebug('[DUPECHECK] Based on duplication preferences I will retain based on : ' + mylar.CONFIG.DUPECONSTRAINT)
TypeError: can only concatenate str (not "NoneType") to str
```

**CarePackage**
[carepackage.zip](https://github.com/mylar3/mylar3/files/5360256/carepackage.zip)

**Environment (please complete the following information):**
 - OS: [e.g. Windows10] Unraid Docker
 - Branch / commit: [e.g. Dev/38aksi1] 42928b2105f31b75fa03a8b37db9be658421cd35 (master)

**Additional information**
I had "filesize" set in this value in Mylar2 but I have no idea what it does so left at the default!

**Comment by evilhero** [comment]
Set it to ```filesize``` or ```filetype``` of you're editing the ini manually. Otherwise, set the value in the GUI and save it so the correct values can populate.

Will have to look into it when I can get to a machine.

**Comment by PCurd** [comment]
Using the nightly docker build (Python3-dev branch) the files import fine now.
