### ISSUE TITLE
Completed Downloads

### ISSUE THREAD

**Issue by TwistedG** [mylar3/mylar3#491]
I'm having an issue with Mylar telling SABnzbd that a download is completed and remove it from the history. Is there a setting I'm missing that should allow for this? I have Mylar set to "Enable Completed Download Handling"

**Comment by evilhero** [comment]
Mylar doesn't remove items from sabnzbd history. It monitors the history queue to see if something has completed, and then post-processes it from where sabnzbd says it is supposed to be.

You'll have to paste debug logs as per the readme when creating an issue for further assistance as well just be asking for all that information regardless (or you  an do a carepackage via the configuratiom screen after toggling debug mode on and running thru a download / failed completed handling).

**Comment by TwistedG** [comment]
[carepackage (1).zip](https://github.com/mylar3/mylar3/files/5362407/carepackage.1.zip)


Ok here is the carepackage, thank you for taking the time to look this over

**Comment by evilhero** [comment]
I'm not seeing any errors in the logs that indicate that the item(s) failed to post-process successfully. Every SABnzbd download has been successfully post-processed to the /comics path. 

Is the problem that Mylar isn't removing the downloaded item from the SABnzbd history - cause Mylar doesn't do that, so I'm not sure - at least at this point, what problem it is that you're seeing as the downloads are being post-processed just fine according to the logs.

Might look into eventually deleting a successful download from the SAB history, but it's not on the immediate to-do as there's a fairly big list of items on the to-do list atm.

**Comment by TwistedG** [comment]
Thank you for looking over everything, I didn't know that Mylar didn't delete the completed item from the history. I have Sabnzbd to use a script to delete completed history after 2 days. I appreciate your continued effort.
