### ISSUE TITLE
Post Processing Not Working

### ISSUE THREAD

**Issue by DrSeussFreak** [mylar3/mylar3#492]
I have a comic titled "The Battle of Britain Special 2020 (2020)".  When I place the file in the directory, re-check does not work, and the file cannot be found.

I have named the file numerous things
"The Battle of Britain Special 2020 001.cbr"
"The Battle of Britain Special 01.cbr"

and nothing works.  Care package is attached.  I enabled debug mode and performed a manual file scan for log events

[carepackage.zip](https://github.com/mylar3/mylar3/files/5386055/carepackage.zip)

**Comment by psychogun** [comment]
How about "The Battle of Britain Special 2020 001 (2020).cbr"?

**Comment by DrSeussFreak** [comment]
Thanks, that worked!
