### ISSUE TITLE
Titles with (of 05) etc don't get picked up by Mylar

### ISSUE THREAD

**Issue by leaderdog** [mylar3/mylar3#496]
Hi Evilhero,

Adding new titles that I missed and these two have the old (of 05) type of text in their file name and Mylar doesn't care for it.

Bad Mother 01 (of 05) (2020) (digital) (Son of Ultron-Empire)
Bad Mother 02 (of 05) (2020) (digital) (Son of Ultron-Empire)
Bad Mother 03 (of 05) (2020) (digital) (Son of Ultron-Empire)

Grendel, Kentucky 01 (of 04) (2020) (digital) (Son of Ultron-Empire)
Grendel, Kentucky 02 (of 04) (2020) (digital) (Son of Ultron-Empire)

Manual post processing did a stellar job of moving everything else I grabbed but these titles will not work.  Not sure if you can add some type of exclusion for the (or 0*) or what not to allow for Mylar to grab and or manual post these.

Thanks,

Configuration Options
Mylar Version: python3-dev
-- git (build c0d18aea9b65c31bbe2a5c70410ec0d3e981a099)
Python Version : 3.7.7
Language : en_CA.cp1252

**Comment by evilhero** [comment]
Ugh, yeah that was a stupid mistake on my part. Fix is waiting to merge into python3-dev now. Once it's in, you should be good to go again after updating.

**Comment by leaderdog** [comment]
great to hear :)

One other issue that is sort of related to this.
This file name:
XIII Mystery 11 - Jonathan Fly (Europe Comics 2020) (webrip) (MagicMan-DCP).cbr

Didn't download nor pick up via manual post processing because "Europe Comics" was in the year tag.  Once I removed that it manually post processed right away.  

Not sure if it deserves it's own issue or not, frustrating how people name their files so inconveniently. ;)

wasn't sure if this fix was similar enough that it could correct this too, despite it being in the year column.  if not I can start another issue.  May be a fringe case tho many(all?) of the Europe comic releases are like this and have been for some time.

**Comment by evilhero** [comment]
Yeah different issue from the looks of it - if you can create a new issue with the relevant info and maybe some logs showing the file parsing and what it's doing it would be helpful.

**Comment by leaderdog** [comment]
odd, after deleting the file, marking as wanted, refreshing and rechecking the page it worked just fine when I did a manual post process this time.  The log showed it pulling Europe Comics out of the year tag.

  I'll keep an eye on titles like this in future and see if it persists.

**Comment by leaderdog** [comment]
Works great now.

Thanks for fixing this. :)
