### ISSUE TITLE
Double Zero?

### ISSUE THREAD

**Issue by jun6lee** [mylar3/mylar3#499]
Probably one of those oddities will just have to live with, but how would Mylar handle this one:

https://comicvine.gamespot.com/batwoman/4050-36950/.  -- Basically, it has two issues numbered 0. 

Is there a possibility (potential enhancement) to retain these as 0a and 0b? 00?
.. or would that be too much of an overhaul, all thing considered?

**Comment by evilhero** [comment]
Make sure you include the issue year in the filename. 

This has been brought up years ago and the only way you can distinguish between them is by the date is was published - in this case the issue year is enough. Once you include the issue year in the filename (ie. ```Superhero 0 (2011)```, ```Superhero 0 (2012)```), Mylar will be able to do the rest.
