### ISSUE TITLE
Unable to view logs

### ISSUE THREAD

**Issue by Serneum** [mylar3/mylar3#508]
**Describe the bug**
Mylar is unable to render `/logs`

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Branch / commit: python3-dev / 4e619a65dffeb9f3eba25765829515016aa2e139

**Additional information**
![image](https://user-images.githubusercontent.com/1091716/96645929-52308400-12f9-11eb-83b9-79ecbdae277c.png)

It looks like `mylar.LOG_LEVEL` no longer exists?

**Comment by evilhero** [comment]
What is your log_level in the config set to?

**Comment by Serneum** [comment]
Looks like I have two instances: under `[General]`, it's empty. Under `[Logs]`, it's 1

**Comment by evilhero** [comment]
Delete the entire line from the General section (with Mylar not running). It should load up after that

**Comment by Serneum** [comment]
That does not seem to have solved the problem. I shut down Mylar, removed the line, restarted Mylar and am still seeing the same error. I verified `log_level` was `1` on `/config_dump`. Here's a carepackage without the `mylar.db` file since mine is always too big to upload.

[carepackage.zip](https://github.com/mylar3/mylar3/files/5411777/carepackage.zip)

**Comment by evilhero** [comment]
Can I ask how are you starting Mylar up? Like are you using the -q or -v switches on startup?

**Comment by Serneum** [comment]
I am using a service that executes
```
/usr/bin/python3.8 /opt/mylar/Mylar.py --daemon --datadir=/opt/mylar --config=/opt/mylar/config.ini --nolaunch
```

**Comment by Serneum** [comment]
Noticed the new commits. Pulled the latest version down (d1a6e429da848d4c74937357358231d2c0758825) and things are working now. Thanks.
