### ISSUE TITLE
Can't update after 3 tries and manual git pull still 48 commit behind

### ISSUE THREAD

**Issue by leaderdog** [mylar3/mylar3#511]
Did something change for git?  I get an error when trying to update and git pull doesn't work either:

20-Oct-2020 21:45:31 - INFO    :: mylar.shutdown.1393 : MAIN : Mylar is updating...
20-Oct-2020 21:45:32 - ERROR   :: mylar.runGit.54 : MAIN : Encountered error: From https://github.com/mylar3/mylar3
 * branch            python3-dev -> FETCH_HEAD

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'Mylar@Media.(none)')

20-Oct-2020 21:45:32 - ERROR   :: mylar.runGit.62 : MAIN : Error: From https://github.com/mylar3/mylar3
 * branch            python3-dev -> FETCH_HEAD

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'Mylar@Media.(none)')

20-Oct-2020 21:45:32 - ERROR   :: mylar.runGit.63 : MAIN : Git returned bad info. Are you sure this is a git installation? []

**Comment by leaderdog** [comment]
hmm, won't let me edit:  Forgot to add:

Configuration Options

Mylar Version: python3-dev
-- git (build c1099a9fa5ae0b48a174b1b821a12d955dee0034)
Python Version : 3.7.7
Language : en_CA.cp1252

**Comment by evilhero** [comment]
Nothing has changed as far as the way Mylar interacts with git. That error looks like it's something local to your git installation - did you update your git recently or did some funky commands ? 

Do you have local changes in your Mylar install ? (ie. do a ```git status |more```)

If all else fails, and you have no local changes you can always either do what the git is telling you (do the ```git config``` commands), or you can try :  
-```git fetch```
- ```git checkout python3-dev```
-```git reset --hard origin/python3-dev```

**Comment by leaderdog** [comment]
When I do the: git status |more

On branch python3-dev
Your branch and 'origin/python3-dev' have diverged,
and have 13 and 48 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)

nothing to commit, working tree clean

doing git fetch didn't do anything.

doing git checkout python3-dev:

Already on 'python3-dev'
Your branch and 'origin/python3-dev' have diverged,
and have 13 and 48 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)

eyes the git reset --hard warily.  this won't mess up database etc?

I haven't done anything with git this is just a random wtf I guess :)


out of curiosity I tried git pull in lazylibrarian.  It fired off the command and updated it.

**Comment by claym** [comment]
the git reset --hard origin/<branch> fixes it.

**Comment by evilhero** [comment]
Yeah we had to do some git stuff to get things back in track, which probably messed up some things in doing a git pull to get the new update.

Do the git reset --hard origin/python3-dev. It won't mess up anything like your db, config or the like. 
It just forces your local repo to sync to the github one ignoring any errors and extra files (meaning if you had local changes in your repo, you'd lose them after doing this since it would go back to an exact duplicate of the github repo). 

If you had local changes, you would have to save the changes first by doing a ```git stash```, then doing the reset, then doing ```git apply stash``` - but that sequence doesn't seem to apply to you.

So yeah, do the git reset

**Comment by leaderdog** [comment]
ok, so I did as you said:

`c:\mylar3>git reset --hard origin/python3-dev
HEAD is now at d1a6e42 FIX:(#505) Fixes webviewer throwing a large X on new image load (just the cover)`

did a git pull to ensure:
`c:\mylar3>git pull
Already up to date.`

load mylar in my browser, and says a newer version is available, you're 48 commits behind.
hit the Update link.
and now we're good ;)

`Configuration Options
Mylar Version: python3-dev
-- git (build d1a6e429da848d4c74937357358231d2c0758825)
Python Version : 3.7.7
Language : en_CA.cp1252`

Thanks for the help. :)
