### ISSUE TITLE
Comic with "LR" in the issue number crashes post-processor

### ISSUE THREAD

**Issue by cwhits** [mylar3/mylar3#513]
**Describe the bug**
It appears that an issue with "LR" in the issue number crashes the post processor. Interestingly, issues with "MU" in the issue number don't seem to have this problem.

**CarePackage**
[carepackage.zip](https://github.com/mylar3/mylar3/files/5430748/carepackage.zip)

The care package is attached but here's the relevant portion of the logs for search-ability (and so other users don't have to download the care package to see the error).
```
23-Oct-2020 12:40:02 - INFO    :: mylar.Process_next.2195 : Thread-13 : [POST-PROCESSING]  [1/1] Starting Post-Processing for The Amazing Spider-Man issue: 50.LR
23-Oct-2020 12:40:02 - DEBUG   :: mylar.Process_next.2198 : Thread-13 : [POST-PROCESSING] issueid: 813276
23-Oct-2020 12:40:02 - DEBUG   :: mylar.Process_next.2199 : Thread-13 : [POST-PROCESSING] issuenumOG: 50.LR
23-Oct-2020 12:40:02 - ERROR   :: mylar.excepthook.315 : Thread-13 : Uncaught exception: Traceback (most recent call last):
  File "/app/mylar/logger.py", line 337, in new_run
    old_run(*args, **kwargs)
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/app/mylar/PostProcessor.py", line 1749, in Process
    self.Process_next(comicid, issueid, issuenumOG, ml, stat)
  File "/app/mylar/PostProcessor.py", line 2254, in Process_next
    if int(iss_decval) == 0:
ValueError: invalid literal for int() with base 10: 'LR' 
```      

**Environment (please complete the following information):**
 - OS: Docker
 - Branch / commit: Version: v0.4.7, refs/pull/500/head (master)

**Additional information**
None

**Comment by evilhero** [comment]
Yeah I fixed this everywhere else a few days ago, but forgot the post-processing module has a seperate hook.

Will look into in abit, not sure when it will hit master tho.

As a workaround, you can manually move the file into the series directory, do a Recheck Files and then a manual metatag on that issue if you want to add it to your collection.

**Comment by barbequesauce** [comment]
good to close?

**Comment by cwhits** [comment]
I'll leave that up to @evilhero

**Comment by kingfenix** [comment]
there is still an issue in general for text issue numbers, specifically issue "X" in series like Universe X and Paradise X by Marvel.

**Comment by evilhero** [comment]
If you prepend the issue number with a # sign, it will designate it as the issue number, and it will parse just fine. 

The parser will pick up issue X or A, etc but alot depends on how you have your naming structure. Since X also can denote part of a series title, the parser errs on the side of caution and doesn't match it unless it can verify based on some restrictions. 

However if your files are named conventionally and it's not working then that's an issue that needs to be brought forth in a new issue ticket, with the relevant logs / carepackage included.
