### ISSUE TITLE
Exceptions/Traceback "X" to close appearance Issue

### ISSUE THREAD

**Issue by burnshroom** [mylar3/mylar3#522]
**Describe the bug**
When selecting the Exceptions/Traceback button, the pop up window does not display the "x" to close the pop up unless you hover over the "x".  

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Branch / commit: python-dev e7f6bba7e6c37955af8b8a07fb43bd4fb5d5c7dc 

**Additional information**
Using non-carbon theme only (does display on carbon theme)

**Comment by barbequesauce** [comment]
should be fixed with last night's commits

**Comment by burnshroom** [comment]
This has BEEN resolved, sorry for the slowness to close.  Thanks guys!!!
