### ISSUE TITLE
CONFIG_HTTP_ROOT not found in latest develop version

### ISSUE THREAD

**Issue by miracle152005** [mylar3/mylar3#525]
**Describe the bug**
After updating to the latest commit of develop branch because of "LR"-Issue I am getting a "AttributeError: module 'mylar' has no attribute 'CONFIG_HTTP_ROOT'" when searching for issues.

**CarePackage**
[logs.zip](https://github.com/mylar3/mylar3/files/5468648/logs.zip)

**Environment (please complete the following information):**
 - docker container on ubuntu 18.04 (hotio/mylar3:nightly)
 - Branch / commit: 1bedb51dd4f1273c884961b0c34d3a20d6950b2f

Could you please take a look.

Thanks

Best regards
miracle152005

**Comment by barbequesauce** [comment]
based on those logs it appears you have multiple copies of mylar running at the same time? Check out the first and last two lines from this snippet, saw it in mylar.log as well

```
  4 31-Oct-2020 07:32:57 - INFO    :: mylar.initialize.73 : MAIN : Starting Mylar on http://0.0.0.0:8090/
  5 31-Oct-2020 07:32:57 - ERROR   :: mylar.initialize.187 : MAIN : [ERROR] Port 0.0.0.0 is in use on 8090.
  6 31-Oct-2020 07:32:58 - INFO    :: mylar.configure.1028 : MainThread : [COMICTAGGER] Version detected: 1.3.4
  7 31-Oct-2020 07:32:58 - INFO    :: mylar.initialize.192 : MainThread : Checking to see if the database has all tables....
  8 31-Oct-2020 07:32:58 - INFO    :: mylar.dbcheck.1340 : MainThread : Ensuring DB integrity - Removing all Erroneous Comics (ie. named None)
  9 31-Oct-2020 07:32:58 - INFO    :: mylar.dbcheck.1342 : MainThread : Correcting Null entries that make the main page break on startup.
 10 31-Oct-2020 07:32:58 - INFO    :: mylar.initialize.206 : MainThread : Successfully discovered local IP and locking it in as : XX.XX.XX.XX
 11 31-Oct-2020 07:32:58 - INFO    :: mylar.initialize.268 : MainThread : Remapping the sorting to allow for new additions.
 12 31-Oct-2020 07:32:58 - INFO    :: mylar.ComicSort.750 : MainThread : Sucessfully ordered 5378 series in your watchlist.
 13 31-Oct-2020 07:32:58 - INFO    :: mylar.validateAndCreateDirectory.1724 : MainThread : [DIRECTORY-CHECK] Found comic directory: /config/app
 14 31-Oct-2020 07:32:58 - INFO    :: mylar.initialize.73 : MAIN : Starting Mylar on http://0.0.0.0:8090/
 15 31-Oct-2020 07:32:58 - ERROR   :: mylar.initialize.187 : MAIN : [ERROR] Port 0.0.0.0 is in use on 8090.

```

**Comment by miracle152005** [comment]
Somehow the container was behaving strangely with starting mylar multiple times internally.
But after creating the container again and checking is is starting only one time, the exception still happens.
"AttributeError: module 'mylar' has no attribute 'CONFIG_HTTP_ROOT'"

[logs.zip](https://github.com/mylar3/mylar3/files/5469086/logs.zip)

**Comment by miracle152005** [comment]
PS: I found out why the log showed that mylar tried to start 2 times.
This happens if you use the restart button in mylar if it is installed as a container.
I think in that case the container tries to ensure the service is running and the restart most likely also tries to start the service again.

**Comment by miracle152005** [comment]
Resolved
