### ISSUE TITLE
Auto-add new comics from specified publishers 

### ISSUE THREAD

**Issue by BRTPOB** [mylar3/mylar3#537]
**Describe the request**
With the new feature for the pack stuff, it would be great to have an option to auto-add new comics from specified publishers so that it automates a currently manual, and tedious, process.

**How did you come up with the idea?**
This is stolen from SCSi, but evilhero's pack stuff is what really brought it about and it's a great idea and should be added. For great justice.

**Environment (please complete the following information):**
ALL THE THINGS!

**Additional information**
Thank you kindly.

**Comment by barbequesauce** [comment]
See #666

**Comment by evilhero** [comment]
Done AND DONE.
