### ISSUE TITLE
Mylar keeps downloading Amazing Spider-Man Annual 2018

### ISSUE THREAD

**Issue by AtariBaby** [mylar3/mylar3#540]
**Describe the bug**
Mylar keeps downloading Amazing Spider-man 2018 every few days. Thanks for reading my issue, heroes!

**CarePackage**
[carepackage.zip](https://github.com/mylar3/mylar3/files/5519061/carepackage.zip)

If you're uncomfortable with pasting your CarePackage, include a DEBUG log containing the error from disk. 

Do not paste from the GUI log.
Do not just paste a traceback/error.

**Environment (please complete the following information):**
 - OS: WINDOWS 10 PRO
 - Branch / commit: 094147532c35c0704a83e7c6101c33f66c2335dc (master)
**Additional information**
I’ve tried different settings but no luck

**Comment by evilhero** [comment]
Do you have the Annuals as an individual series on your watchlist in addition to being under the series itself ? Is the status set to Downloaded once the issue has downloaded successfully, or does it just stay in a Snatched status ? 

Aside from that - looking at the logs I can't really tell much else since they're all in INFO level logging. You'll have to flip on the verbose/debug mode and try to capture it trying to auto-download the issue.

**Comment by AtariBaby** [comment]
I *think* I only have annuals selected one way. 
![CFE20D76-8F66-4B41-AD8D-14F66ABB0B04](https://user-images.githubusercontent.com/97095/98782934-a3d6a680-23ad-11eb-9c94-c2ff3cd5895e.png)
![27FC43AB-58D6-48EE-B189-A3EA319C0CE3](https://user-images.githubusercontent.com/97095/98782945-a6390080-23ad-11eb-92be-01cb2ef2073f.png)
![4B0ECAAE-8C10-4B7D-8645-54B8428572DE](https://user-images.githubusercontent.com/97095/98782951-a802c400-23ad-11eb-84c7-eefaf0fbb88e.png)

**Comment by evilhero** [comment]
You need to get us the logs in debug mode then as I mentioned earlier. 

Without debug mode enabled in logging, it's impossible to tell what's happening.

**Comment by AtariBaby** [comment]
Okay, thank you. I turned it on. I don’t know how to force it to happen, so I guess I’ll report back when it does.

**Comment by AtariBaby** [comment]
Okay here we go. This has happened four or five times since, but I just happened to have debug on when it occurred most recently.
[carepackage 3.zip](https://github.com/mylar3/mylar3/files/5683862/carepackage.3.zip)

**Comment by AtariBaby** [comment]
Most recently, I added Venom and I believe the same thing is happening with its annuals. The systems has downloaded Annual 2018 and Annual 2019 more than once.

**Comment by AtariBaby** [comment]
Still happening 
![7E5A9C5A-0903-4433-BCE4-658B2C4C6745](https://user-images.githubusercontent.com/97095/106342975-ff4f5c80-6257-11eb-8548-35bbfd5e9c69.jpeg)

**Comment by SenorSmartyPants** [comment]
This seems to happen to me when there is a new issue of a comic and I'm still seeding an annual for that comic. This week it's Justice League. Doesn't download a new Annual, but post processes the one already downloaded.

[carepackage.zip](https://github.com/mylar3/mylar3/files/6158664/carepackage.zip)

**Comment by evilhero** [comment]
should be resolved in latest builds - aside from this issue being a year old now, I'd consider it stale and if it's still happening a new issue can be opened.
