### ISSUE TITLE
OPDS Mako Runtime Error

### ISSUE THREAD

**Issue by nicholasgcotton** [mylar3/mylar3#547]
**Describe the bug**
Unspecified Mako Runtime Error when trying to access OPDS

Error XML attached as text file.

[error.txt](https://github.com/mylar3/mylar3/files/5563799/error.txt)

**CarePackage**
Attached.
[carepackage.zip](https://github.com/mylar3/mylar3/files/5563791/carepackage.zip)

**Environment (please complete the following information):**
Docker (under windows 10, not using WSL)
  mylar3:
    image: hotio/mylar3
    container_name: mylar3
    volumes:
      - /host_mnt/c/config_mylar:/config
      - /host_mnt/f/complete/Comics:/comics
      - /host_mnt/g/Complete/Comics:/Downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    ports:
      - 8090:8090
    restart: unless-stopped

**Additional information**
Carepackage didn't download correctly, had to grab it from the config/app/logs folder.

**Comment by nicholasgcotton** [comment]
Version: v0.4.9, python3-dev (master)

**Comment by barbequesauce** [comment]
Fixed with #533, currently in dev. I'd expect that dev will get merged with master any day now as it's been stable for a while...

**Comment by nicholasgcotton** [comment]
Thanks! 

Closed as expected-to-be-fixed under 533.
