### ISSUE TITLE
Cloudflare DDOS warning prevents DDL RSS feed from working

### ISSUE THREAD

**Issue by VorlonCD** [mylar3/mylar3#566]
**Describe the bug**

Not sure if anything can even be done about this on the Mylar3 end, but I noticed I was getting the following error:

`09-Dec-2020 15:50:09 - INFO :: mylar.run.105 : ThreadPoolExecutor-0_0 : [RSS-FEEDS] Initiating RSS Feed Check for DDL Provider.
Job "RSS Feeds (trigger: interval[1:00:00], next run at: 2020-12-09 21:50:07 UTC)" raised an exception
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Tools\mylar3\mylar\rsscheckit.py", line 106, in run
    rsscheck.ddl(forcerss=forcerss)
  File "C:\Tools\mylar3\mylar\rsscheck.py", line 409, in ddl
    logger.warn('[%s] Status code returned: %s' % (r.status_code))
TypeError: not enough arguments for format string`

So I looked in the rsscheck.py code and manually went to https://getcomics.info/feed/

I get the following message on the site then **IT DOES correctly download the RSS dat after 5 seconds**

![image](https://user-images.githubusercontent.com/7512113/101692114-b213f300-3a3d-11eb-9f7a-c974db55fe26.png)

**Environment:**
 - OS: Windows10
 - Branch / commit: Master (latest)
 - Python Version : 3.7.7

**Comment by burnshroom** [comment]
https://github.com/mylar3/mylar3/pull/564

PR'ed for dev branch earlier today.  Waiting to be pushed through.
