### ISSUE TITLE
Unable to change destination dir

### ISSUE THREAD

**Issue by Serneum** [mylar3/mylar3#579]
**Describe the bug**
I recently migrated my Mylar instance to the Docker image maintained by linuxserver.io. In the process, I redefined the directory layout for my media and now I need to migrate all of my existing comics. I read through the [hidden options](https://forum.mylarcomics.com/viewtopic.php?f=12&t=1025) and then @barbequesauce pointed me to [a forum post](http://forum.mylarcomics.com/viewtopic.php?p=9810&sid=2894f3ce077312658239dbabe8b46be8#p9810) that detailed the same process I was trying. Once I set the `locmov` and `new_comdir` properties and started the server, I got an error on startup:

```
log language set to en_US
Quiet logging mode enabled...
Initializing startup sequence....
Logging level in config over-ridden by startup value. Logging level set to : 0
Traceback (most recent call last):
  File "/app/mylar3/Mylar.py", line 386, in <module>
    main()
  File "/app/mylar3/Mylar.py", line 203, in main
    mylar.initialize(mylar.CONFIG_FILE)
  File "/app/mylar3/mylar/__init__.py", line 264, in initialize
    helpers.updateComicLocation()
  File "/app/mylar3/mylar/helpers.py", line 878, in updateComicLocation
    com_done = re.sub('%&', os.sep.encode('unicode-escape'), comlocation).strip()
  File "/usr/lib/python3.8/re.py", line 210, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: sequence item 0: expected str instance, bytes found
```

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Branch / commit: master, 4.9.2

**Additional information**
The message I posted above is what gets repeated on startup. Since the server does not start, I do not have access to a care package. I can change the settings, get a care package, and then upload it, but I assume that defeats the purpose.

Settings that may matter:
```
[General]
destination_dir = /mnt/Comics

[Update]
newcom_dir = /data/media/Comics
fftonewcom_dir = False
locmove = True
```

**Comment by Serneum** [comment]
Before I forget, I want to add that `/mnt/Comics` no longer exists on my server. Could that be causing my issues?

**Comment by evilhero** [comment]
Looks like a staggler from the conversion from python2 to python3. Python3 has everything as bytes within the program now, whereas with py2 it had to be determined. Odds are it's due to you having an existing python3 Mylar db that you're trying to convert (which shouldn't matter obviously) - I'll see what I can figure out & test with.

**Comment by Serneum** [comment]
Pulled down the latest version and started up my server. A quick spot check implies that your fix worked. Thanks!
