### ISSUE TITLE
locmove does not set itself to False after server startup

### ISSUE THREAD

**Issue by Serneum** [mylar3/mylar3#583]
**Describe the bug**
The python3-dev README states:
> Once it's converted, the locmove value will be automatically set back to a False value so that the process doesn't run on every startup sequence thereafter.

Checking my config.ini after migrating my data, the `locmove` value was still set to `True` after startup

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Branch / commit: python3-dev / d1d6989a3ff6d120153fe3c8b5af2e63cab8f954

**Comment by barbequesauce** [comment]
@Serneum can you confirm you're in better shape after that fix?

**Comment by Serneum** [comment]
Sorry, yeah I haven't run into any issues
