### ISSUE TITLE
Sabnzbd test can show empty or incorrect message

### ISSUE THREAD

**Issue by Serneum** [mylar3/mylar3#584]
**Describe the bug**
If I go to Settings -> Download Settings, set my SABnzbd Host to an invalid value, then click Test SABnzbd, I get a green message popup with no text. It look like an error pops up in the browser console as well:
```
VM209:1 Uncaught SyntaxError: Unexpected token U in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.success (config:2241)
    at o (jquery-1.7.2.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-1.7.2.min.js:2)
    at w (jquery-1.7.2.min.js:4)
    at XMLHttpRequest.d (jquery-1.7.2.min.js:4)
```

If you test with a valid Host setting, you get a message stating that the API key was successfully verified. If you then switch to an invalid host, that message continue to pop up. My guess is that the error is being raised and the message is never updated because of it.

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Branch / commit: python3-dev / d1d6989a3ff6d120153fe3c8b5af2e63cab8f954

**Comment by evilhero** [comment]
A year + in stale - going to assume resolved over the course of previous commits. 

If not, please open a new issue with the relevant information.
