### ISSUE TITLE
Mylar3 migration not working

### ISSUE THREAD

**Issue by akaOMC** [mylar3/mylar3#588]
Trying to upgrade to Mylar3. Every step seemed to work fine, but when launching the program it didn't work. Here is what I saw in the command prompt:

C:\mylar3>python Mylar.py
log language set to en_US
Initializing startup sequence....
31-Dec-2020 00:47:34 - ERROR :: mylar.excepthook.315 : MainThread : Uncaught exception: Traceback (most recent call last):
  File "Mylar.py", line 386, in <module>
    main()
  File "Mylar.py", line 203, in main
    mylar.initialize(mylar.CONFIG_FILE)
  File "C:\mylar3\mylar\__init__.py", line 264, in initialize
    helpers.updateComicLocation()
  File "C:\mylar3\mylar\helpers.py", line 878, in updateComicLocation
    com_done = re.sub('%&', os.sep.encode('unicode-escape'), comlocation).strip()
  File "C:\Users\akaOM\AppData\Local\Programs\Python\Python37\lib\re.py", line 192, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: sequence item 1: expected str instance, bytes found

Traceback (most recent call last):
  File "Mylar.py", line 386, in <module>
    main()
  File "Mylar.py", line 203, in main
    mylar.initialize(mylar.CONFIG_FILE)
  File "C:\mylar3\mylar\__init__.py", line 264, in initialize
    helpers.updateComicLocation()
  File "C:\mylar3\mylar\helpers.py", line 878, in updateComicLocation
    com_done = re.sub('%&', os.sep.encode('unicode-escape'), comlocation).strip()
  File "C:\Users\akaOM\AppData\Local\Programs\Python\Python37\lib\re.py", line 192, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: sequence item 1: expected str instance, bytes found

Any help would be appreciated.

**Comment by barbequesauce** [comment]
Looks like you forgot `pip3 install -r requirements.txt`

**Comment by evilhero** [comment]
I think this is the same as #579, but the fix is in the python3-dev branch only atm.

Perhaps a more important question is why are you trying to import your existing collection with the locmove option if you already have a previous mylar database file?  

Mylar3 will convert your Mylar2 db on startup, so unless your comics directory has changed or you're wanting to enforce the folder formatting for every series on your watchlist, there's no need to use the locmove option when migrating between versions.

**Comment by akaOMC** [comment]
Thanks for replying. I am pretty sure I did that, but did it again just in case with this result:

C:\mylar3>pip3 install -r requirements.txt
Requirement already satisfied: APScheduler>=3.6.3 in c:\users\akaom\appdata\local\programs\python\python37\lib\site-packages (from -r requirements.txt (line 7)) (3.6.3)
Requirement already satisfied: beautifulsoup4>=4.8.2 in c:\users\akaom\appdata\local\programs\python\python37\lib\site-packages (from -r requirements.txt (line 8)) (4.9.3)
Requirement already satisfied: cfscrape>=2.0.8 in c:\users\akaom\appdata\local\programs\python\python37\lib\site-packages (from -r requirements.txt (line 9)) (2.1.1)
Requirement already satisfied: cheroot==8.2.1 in c:\users\akaom\appdata\local\programs\python\python37\lib\site-packages (from -r requirements.txt (line 10)) (8.2.1)
Requirement already satisfied: CherryPy>=18.5.0 in c:\users\akaom\appdata\local\programs\python\python37\lib\site-packages (from -r requirements.txt (line 11)) (18.6.0)
Requirement already satisfied: configparser>=4.0.2 in c:\users\akaom\appdata\local\programs\python\python37\lib\site-packages (from -r requirements.txt (line 12)) (5.0.1)
Requirement already satisfied: feedparser>=5.2.1 in c:\users\akaom\appdata\local\programs\python\python37\lib\site-packages (from -r requirements.txt (line 13)) (6.0.2)
Requirement already satisfied: Mako>=1.1.0 in c:\users\akaom\appdata\local\programs\python\python37\lib\site-packages (from -r requirements.txt (line 14)) (1.1.3)
Requirement already satisfied: natsort>=3.5.2 in c:\users\akaom\appdata\local\programs\python\python37\lib\site-packages (from -r requirements.txt (line 15)) (7.1.0)
Requirement already satisfied: Pillow>=4.2.1,~=6.2.2 in c:\users\akaom\appdata\local\programs\python\python37\lib\site-packages (from -r requirements.txt (line 16)) (6.2.2)
Requirement already satisfied: portend>=2.6 in c:\users\akaom\appdata\local\programs\python\python37\lib\site-packages (from -r requirements.txt (line 17)) (2.7.0)
Requirement already satisfied: pyinstaller>=3.5 in c:\users\akaom\appdata\local\programs\python\python37\lib\site-packages (from -r requirements.txt (line 18)) (4.1)
Requirement already satisfied: pytz>=2019.3 in c:\users\akaom\appdata\local\programs\python\python37\lib\site-packages (from -r requirements.txt (line 19)) (2020.5)
Requirement already satisfied: rarfile>=4.0 in c:\users\akaom\appdata\local\programs\python\python37\lib\site-packages (from -r requirements.txt (line 20)) (4.0)
Requirement already satisfied: requests>=2.22.0 in c:\users\akaom\appdata\local\programs\python\python37\lib\site-packages (from -r requirements.txt (line 21)) (2.25.1)
Requirement already satisfied: simplejson>=3.17.0 in c:\users\akaom\appdata\local\programs\python\python37\lib\site-packages (from -r requirements.txt (line 22)) (3.17.2)
Requirement already satisfied: six>=1.13.0 in c:\users\akaom\appdata\local\programs\python\python37\lib\site-packages (from -r requirements.txt (line 23)) (1.15.0)
Requirement already satisfied: tzlocal>=2.0.0 in c:\users\akaom\appdata\local\programs\python\python37\lib\site-packages (from -r requirements.txt (line 24)) (2.1)
Requirement already satisfied: urllib3>=1.25.7 in c:\users\akaom\appdata\local\programs\python\python37\lib\site-packages (from -r requirements.txt (line 25)) (1.26.2)
Requirement already satisfied: more-itertools>=2.6 in c:\users\akaom\appdata\local\programs\python\python37\lib\site-packages (from cheroot==8.2.1->-r requirements.txt (line 10)) (8.6.0)
Requirement already satisfied: jaraco.functools in c:\users\akaom\appdata\local\programs\python\python37\lib\site-packages (from cheroot==8.2.1->-r requirements.txt (line 10)) (3.1.0)
Requirement already satisfied: setuptools>=0.7 in c:\users\akaom\appdata\local\programs\python\python37\lib\site-packages (from APScheduler>=3.6.3->-r requirements.txt (line 7)) (41.2.0)
Requirement already satisfied: soupsieve>1.2 in c:\users\akaom\appdata\local\programs\python\python37\lib\site-packages (from beautifulsoup4>=4.8.2->-r requirements.txt (line 8)) (2.1)
Requirement already satisfied: pywin32 in c:\users\akaom\appdata\local\programs\python\python37\lib\site-packages (from CherryPy>=18.5.0->-r requirements.txt (line 11)) (300)
Requirement already satisfied: jaraco.collections in c:\users\akaom\appdata\local\programs\python\python37\lib\site-packages (from CherryPy>=18.5.0->-r requirements.txt (line 11)) (3.1.0)
Requirement already satisfied: zc.lockfile in c:\users\akaom\appdata\local\programs\python\python37\lib\site-packages (from CherryPy>=18.5.0->-r requirements.txt (line 11)) (2.0)
Requirement already satisfied: sgmllib3k in c:\users\akaom\appdata\local\programs\python\python37\lib\site-packages (from feedparser>=5.2.1->-r requirements.txt (line 13)) (1.0.0)
Requirement already satisfied: MarkupSafe>=0.9.2 in c:\users\akaom\appdata\local\programs\python\python37\lib\site-packages (from Mako>=1.1.0->-r requirements.txt (line 14)) (1.1.1)
Requirement already satisfied: tempora>=1.8 in c:\users\akaom\appdata\local\programs\python\python37\lib\site-packages (from portend>=2.6->-r requirements.txt (line 17)) (4.0.1)
Requirement already satisfied: pyinstaller-hooks-contrib>=2020.6 in c:\users\akaom\appdata\local\programs\python\python37\lib\site-packages (from pyinstaller>=3.5->-r requirements.txt (line 18)) (2020.11)
Requirement already satisfied: altgraph in c:\users\akaom\appdata\local\programs\python\python37\lib\site-packages (from pyinstaller>=3.5->-r requirements.txt (line 18)) (0.17)
Requirement already satisfied: pywin32-ctypes>=0.2.0 in c:\users\akaom\appdata\local\programs\python\python37\lib\site-packages (from pyinstaller>=3.5->-r requirements.txt (line 18)) (0.2.0)
Requirement already satisfied: pefile>=2017.8.1 in c:\users\akaom\appdata\local\programs\python\python37\lib\site-packages (from pyinstaller>=3.5->-r requirements.txt (line 18)) (2019.4.18)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\akaom\appdata\local\programs\python\python37\lib\site-packages (from requests>=2.22.0->-r requirements.txt (line 21)) (2020.12.5)
Requirement already satisfied: idna<3,>=2.5 in c:\users\akaom\appdata\local\programs\python\python37\lib\site-packages (from requests>=2.22.0->-r requirements.txt (line 21)) (2.10)
Requirement already satisfied: chardet<5,>=3.0.2 in c:\users\akaom\appdata\local\programs\python\python37\lib\site-packages (from requests>=2.22.0->-r requirements.txt (line 21)) (4.0.0)
Requirement already satisfied: future in c:\users\akaom\appdata\local\programs\python\python37\lib\site-packages (from pefile>=2017.8.1->pyinstaller>=3.5->-r requirements.txt (line 18)) (0.18.2)
Requirement already satisfied: jaraco.classes in c:\users\akaom\appdata\local\programs\python\python37\lib\site-packages (from jaraco.collections->CherryPy>=18.5.0->-r requirements.txt (line 11)) (3.1.0)
Requirement already satisfied: jaraco.text in c:\users\akaom\appdata\local\programs\python\python37\lib\site-packages (from .collections->CherryPy>=18.5.0->-r requirements.txt (line 11)) (3.4.0)

It appears everything is satisfied, so I tried to start again:

C:\mylar3>python Mylar.py
log language set to en_US
Initializing startup sequence....
31-Dec-2020 10:18:38 - ERROR :: mylar.excepthook.315 : MainThread : Uncaught exception: Traceback (most recent call last):
  File "Mylar.py", line 386, in <module>
    main()
  File "Mylar.py", line 203, in main
    mylar.initialize(mylar.CONFIG_FILE)
  File "C:\mylar3\mylar\__init__.py", line 264, in initialize
    helpers.updateComicLocation()
  File "C:\mylar3\mylar\helpers.py", line 878, in updateComicLocation
    com_done = re.sub('%&', os.sep.encode('unicode-escape'), comlocation).strip()
  File "C:\Users\akaOM\AppData\Local\Programs\Python\Python37\lib\re.py", line 192, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: sequence item 1: expected str instance, bytes found

Traceback (most recent call last):
  File "Mylar.py", line 386, in <module>
    main()
  File "Mylar.py", line 203, in main
    mylar.initialize(mylar.CONFIG_FILE)
  File "C:\mylar3\mylar\__init__.py", line 264, in initialize
    helpers.updateComicLocation()
  File "C:\mylar3\mylar\helpers.py", line 878, in updateComicLocation
    com_done = re.sub('%&', os.sep.encode('unicode-escape'), comlocation).strip()
  File "C:\Users\akaOM\AppData\Local\Programs\Python\Python37\lib\re.py", line 192, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: sequence item 1: expected str instance, bytes found

**Comment by akaOMC** [comment]
Thanks @evilhero - I had the locmove option because I did just change drives before upgrading, but must not have changed it back. I just did and all seems to be working now. Much appreciated!
