### ISSUE TITLE
[Solved] [DDL] Post-process don't work

### ISSUE THREAD

**Issue by Aerya** [mylar3/mylar3#590]
Hi, thanks for Mylar & v3.
I installed Mylar3 today to give it a try.

**Describe the bug**
I'm new to Mylar3, using it with DDL. I added a few comics to test, DL is ok when Mylar3 finds the files on GetComics but I have a few problems:
 - Files were not processed to the created directories but were downloaded in /cache despite I entered another path in Comic Location on the WUI config
 => I edited the config.ini file and manually set ddl_location = /downloads/unionfs/ComicsAuto/ so it now downloads to the right place
 - However it still don't organize files in the created directories when adding a comic. I activated post-processing (move) in the Quality Post Processing part but it still doesn't work (https://i.imgur.com/1600Txu.png).

**CarePackage**
http://s000.tinyupload.com/index.php?file_id=07973722786357985567

**Environment:**
 - OS: Docker linuxserver/mylar3
 - Mylar Version: master [v0.4.9.2 - Yeah? Well my god has a hammer!]
 - Source (build 813397ba3e70df7996909f04e009de91fae324b2)
 - Python Version : 3.8.5

**Comment by barbequesauce** [comment]
You've set both ddl_location and destination_dir to the same location. They should be two different places.

ddl_location is a staging location for download and holding prior to post-processing.

destination_dir is the comic library, for consumption following all post-processing activities...

**Comment by Aerya** [comment]
Ok, thank you for the tip.
