### ISSUE TITLE
Unable to add annual to comic with all issues downloaded

### ISSUE THREAD

**Issue by rutskiuk** [mylar3/mylar3#610]
I have a problem where I cannot add an annual to a comic which has all of the regular issues already downloaded

If I go to Transformers Robots in Disguise and add the annual I get an error that the annual cannot be added

I checked the log and can see hundreds of lines that all say the same thing:

12-Jan-2021 22:32:26 - WARNING :: mylar.Process.569 : ThreadPoolExecutor-0_12 : The Transformers: More Than Meets The Eye [2012] is either Paused or in an Ended status with 100% completion. Ignoring for match.

The regular issues are all downloaded:
![image](https://user-images.githubusercontent.com/25068977/104821490-22c7df80-5834-11eb-8b02-82ddd84604e2.png)

The annual is marked as wanted:
![image](https://user-images.githubusercontent.com/25068977/104821500-35421900-5834-11eb-9012-ddb86f168f75.png)

I have got the file and put it in my postprocessing folder which returns the message in the logs above
I have also tried putting it in the folder with the regular issues but that isn't recognised either.

Is there something I'm doing wrong here? I think the file name is being detected correctly (named Transformers - More Than Meets the Eye Annual 1 (2012) (HD) (digital-Empire))

 - OS: Windows10
 - Branch / commit: Version: 2100583ea0609c8c2c9243b2ff6dcfb42492e7de (master)

**Comment by evilhero** [comment]
If a series is considered 100% complete, Mylar will ignore it for post-processing matches.  I'm guessing you added the Annual - but the issue counts didn't update after the addition. Try going back into the series and doing a ```ReCheck Files``` (or Refresh, ReCheck is quicker, but Refresh will clear up any errors usually). If you have annuals enabled, the issue count should go up by the number of annuals attached (so series issues + annual issues = total issues or 57/58).  

Once you get to the correct count, you should be able to post-process for the series. Although not too sure about the naming - there is no issue 1 for that annual, it's labelled as 2012 as per the screenshot, so you might have to remove the 1 from your filename if it doesn't get picked up initially (I can't recall if I built in the logistics for that particular type of case-handling offhand).

If your'e still having problems with the counts not lining up, you'll have to post the carepackage in order for us to see what's going on (make sure you have debug logging enabled, and then do a manual post-processing so it's captured in the logs).

**Comment by rutskiuk** [comment]
You're absolutely right, I didn't even think about doing a refresh as the Annual was already listed as wanted. Now I've done the refresh the total count has increased so I no longer have 100% of the issues however the error message remains the same.
I checked the box is ticked to force the series as continuing and have rechecked the files but I can't seem to shift this error.
I tried removing and re-adding the comic but the same thing happened.

**Comment by evilhero** [comment]
Try removing the 1 from the filename and either manually post-process it (from a directory other than the series directory) or Recheck Files if it is in the series directory.

If it still doesn't work, you'll have to attach a carepackage so we can see what's going on.

(also no need to force the series as continuing, it's an ended series - now that the counts are normal it's fine to uncheck that since it will screw up subsequent series named the same if you have them)

**Comment by rutskiuk** [comment]
I've renamed the file with every variation I can think of, moving the file to the same folder as the rest of the comic and removing the release group from the name, the year, the quality, removed it from its own folder and re-scanned the files but each time I get:

 The Transformers: More Than Meets The Eye [2012] is either Paused or in an Ended status with 100% completion. Ignoring for match.
17-Jan-2021 20:58:05 - ERROR :: mylar.issuedigits.1142 : ThreadPoolExecutor-0_1 :  this has an alpha-numeric in the issue # which I cannot account for.

The file is currently named "The Transformers More Than Meets the Eye Annual (2012)"

**Comment by evilhero** [comment]
Oh I see, try renaming it to "... Annual 2012 (2012)“. The issue number is 2012, so it's taking the year as just the issue year (it should be taking it as the issue number as well but that's usually only for TPB that it does that normally).

**Comment by rutskiuk** [comment]
That has fixed it
Is there a better way to name this file so the system recognises it?
I'm happy with whatever works but there's something jarring about seeing the year twice.

**Comment by evilhero** [comment]
You could try it as "... Annual #2012“ which should work I think as well. Normally you can indicate issue number by preceding it with a # sign, I'm just not sure if it has to be before the word Annual since the word is part of the issue numbering as well in this case.

**Comment by evilhero** [comment]
Assuming resolved, so closing at this point in time.
