### ISSUE TITLE
Opensuse Tumbleweed fails to pip3 the requirements

### ISSUE THREAD

**Issue by mgaulton** [mylar3/mylar3#620]
I just found this repo and am trying to install it on my system to prep for migration.
I have removed the old install and put this in the same dir, all contents removed.
after a git clone I attempt the pip3 step and get the below. multiple attempts have failed.

`server6:/opt/mylar/mylar-master # pip3 install --no-cache-dir -U -r requirements.txt
Requirement already satisfied: beautifulsoup4>=4.8.2 in /usr/local/lib/python3.8/site-packages (from -r requirements.txt (line 8)) (4.9.3)
Requirement already satisfied: cfscrape>=2.0.8 in /usr/local/lib/python3.8/site-packages (from -r requirements.txt (line 9)) (2.1.1)
Requirement already satisfied: CherryPy>=18.5.0 in /usr/local/lib/python3.8/site-packages (from -r requirements.txt (line 11)) (18.6.0)
Requirement already satisfied: feedparser>=5.2.1 in /usr/local/lib/python3.8/site-packages (from -r requirements.txt (line 13)) (6.0.2)
Requirement already satisfied: Mako>=1.1.0 in /usr/local/lib/python3.8/site-packages (from -r requirements.txt (line 14)) (1.1.4)
Requirement already satisfied: natsort>=3.5.2 in /usr/local/lib/python3.8/site-packages (from -r requirements.txt (line 15)) (7.1.0)
Requirement already satisfied: portend>=2.6 in /usr/local/lib/python3.8/site-packages (from -r requirements.txt (line 17)) (2.7.0)
Requirement already satisfied: pytz>=2019.3 in /usr/lib/python3.8/site-packages (from -r requirements.txt (line 19)) (2020.5)
Requirement already satisfied: rarfile>=4.0 in /usr/local/lib/python3.8/site-packages (from -r requirements.txt (line 20)) (4.0)
Requirement already satisfied: requests>=2.22.0 in /usr/lib/python3.8/site-packages (from -r requirements.txt (line 21)) (2.25.1)
Requirement already satisfied: simplejson>=3.17.0 in /usr/local/lib64/python3.8/site-packages (from -r requirements.txt (line 22)) (3.17.2)
Requirement already satisfied: six>=1.13.0 in /usr/lib/python3.8/site-packages (from -r requirements.txt (line 23)) (1.15.0)
Requirement already satisfied: tzlocal>=2.0.0 in /usr/local/lib/python3.8/site-packages (from -r requirements.txt (line 24)) (2.1)
Requirement already satisfied: urllib3>=1.25.7 in /usr/lib/python3.8/site-packages (from -r requirements.txt (line 25)) (1.26.2)
Collecting cheroot==8.2.1
  Downloading cheroot-8.2.1-py2.py3-none-any.whl (79 kB)
     |████████████████████████████████| 79 kB 2.3 MB/s
Requirement already satisfied: jaraco.functools in /usr/local/lib/python3.8/site-packages (from cheroot==8.2.1->-r requirements.txt (line 10)) (3.1.0)
Requirement already satisfied: more-itertools>=2.6 in /usr/lib/python3.8/site-packages (from cheroot==8.2.1->-r requirements.txt (line 10)) (8.6.0)
Collecting APScheduler>=3.6.3
  Downloading APScheduler-3.7.0-py2.py3-none-any.whl (59 kB)
     |████████████████████████████████| 59 kB 3.8 MB/s
Requirement already satisfied: setuptools>=0.7 in /usr/lib/python3.8/site-packages (from APScheduler>=3.6.3->-r requirements.txt (line 7)) (44.1.1)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.8/site-packages (from beautifulsoup4>=4.8.2->-r requirements.txt (line 8)) (2.1)
Requirement already satisfied: zc.lockfile in /usr/local/lib/python3.8/site-packages (from CherryPy>=18.5.0->-r requirements.txt (line 11)) (2.0)
Requirement already satisfied: jaraco.collections in /usr/local/lib/python3.8/site-packages (from CherryPy>=18.5.0->-r requirements.txt (line 11)) (3.1.0)
Collecting configparser>=4.0.2
  Downloading configparser-5.0.1-py3-none-any.whl (22 kB)
Requirement already satisfied: sgmllib3k in /usr/local/lib/python3.8/site-packages (from feedparser>=5.2.1->-r requirements.txt (line 13)) (1.0.0)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/lib64/python3.8/site-packages (from Mako>=1.1.0->-r requirements.txt (line 14)) (1.1.1)
Collecting Pillow>=4.2.1,~=6.2.2
  Downloading Pillow-6.2.2-cp38-cp38-manylinux1_x86_64.whl (2.1 MB)
     |████████████████████████████████| 2.1 MB 4.7 MB/s
Requirement already satisfied: tempora>=1.8 in /usr/local/lib/python3.8/site-packages (from portend>=2.6->-r requirements.txt (line 17)) (4.0.1)
Collecting pyinstaller>=3.5
  Downloading pyinstaller-4.2.tar.gz (3.6 MB)
     |████████████████████████████████| 3.6 MB 2.8 MB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 /usr/local/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpflg967t5
         cwd: /tmp/pip-install-bsng9o9m/pyinstaller_ba28f3701b8a45c6add79f4c51244c4c
    Complete output (65 lines):
    running dist_info
    creating /tmp/pip-modern-metadata-uc6lf6rl/pyinstaller.egg-info
    writing /tmp/pip-modern-metadata-uc6lf6rl/pyinstaller.egg-info/PKG-INFO
    writing dependency_links to /tmp/pip-modern-metadata-uc6lf6rl/pyinstaller.egg-info/dependency_links.txt
    writing entry points to /tmp/pip-modern-metadata-uc6lf6rl/pyinstaller.egg-info/entry_points.txt
    writing requirements to /tmp/pip-modern-metadata-uc6lf6rl/pyinstaller.egg-info/requires.txt
    writing top-level names to /tmp/pip-modern-metadata-uc6lf6rl/pyinstaller.egg-info/top_level.txt
    writing manifest file '/tmp/pip-modern-metadata-uc6lf6rl/pyinstaller.egg-info/SOURCES.txt'
    reading manifest file '/tmp/pip-modern-metadata-uc6lf6rl/pyinstaller.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching 'pyinstaller-gui.py'
    no previously-included directories found matching 'bootloader/build'
    no previously-included directories found matching 'bootloader/.waf-*'
    no previously-included directories found matching 'bootloader/.waf3-*'
    no previously-included directories found matching 'bootloader/waf-*'
    no previously-included directories found matching 'bootloader/waf3-*'
    no previously-included directories found matching 'bootloader/_sdks'
    no previously-included directories found matching 'bootloader/.vagrant'
    warning: no previously-included files found matching 'bootloader/.lock-waf*'
    no previously-included directories found matching 'doc/source'
    no previously-included directories found matching 'doc/_build'
    warning: no previously-included files matching '*.tmp' found under directory 'doc'
    warning: no files found matching 'news/_template.rst'
    no previously-included directories found matching 'news'
    no previously-included directories found matching 'old'
    no previously-included directories found matching 'scripts'
    no previously-included directories found matching 'tests/scripts'
    no previously-included directories found matching '.github'
    warning: no previously-included files found matching '.*'
    warning: no previously-included files found matching '*.yml'
    warning: no previously-included files found matching '*~'
    warning: no previously-included files found matching '.directory'
    warning: no previously-included files matching '*.py[co]' found anywhere in distribution
    writing manifest file '/tmp/pip-modern-metadata-uc6lf6rl/pyinstaller.egg-info/SOURCES.txt'
    creating '/tmp/pip-modern-metadata-uc6lf6rl/pyinstaller.dist-info'
    Traceback (most recent call last):
      File "/usr/local/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
        main()
      File "/usr/local/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/usr/local/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 133, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/tmp/pip-build-env-ia1c6nse/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 161, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "/tmp/pip-build-env-ia1c6nse/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 253, in run_setup
        super(_BuildMetaLegacyBackend,
      File "/tmp/pip-build-env-ia1c6nse/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 145, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 75, in <module>
        setup(
      File "/tmp/pip-build-env-ia1c6nse/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib64/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib64/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib64/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-env-ia1c6nse/overlay/lib/python3.8/site-packages/setuptools/command/dist_info.py", line 36, in run
        bdist_wheel.egg2dist(egg_info.egg_info, dist_info_dir)
      File "/usr/local/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 443, in egg2dist
        shutil.copy(license, os.path.join(self.distinfo_dir, license_filename))
      File "/usr/lib64/python3.8/posixpath.py", line 76, in join
        a = os.fspath(a)
    TypeError: expected str, bytes or os.PathLike object, not NoneType
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 /usr/local/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpflg967t5 Check the logs for full command output.
server6:/opt/mylar/mylar-master #
`

**Comment by mgaulton** [comment]
server6:/opt/mylar/mylar-master #  export TMPDIR='/home/testing' ; pip3 install --no-cache-dir -U -r requirements.txt
this commandline using a different temp location also fails with the same result.

**Comment by evilhero** [comment]
Have you tried it without the upgrade switch?

The version of pyinstaller it's trying to install (4.6) seems to be breaking - either removing the -U will fix it since its using locked in values and not trying to update to the latest and greatest, or it won't - in which case it points to either your distools or setuptools being corrupt as it can't utilise them (it happens sometimes), and you'll have to try and correct that.

You can also try installing just the pyinstaller by itself and see if that works. If it does, you should be able to continue the installation via requirements.txt. If it doesn't, you can try forcing the pyinstaller version to a lower version than what it previously tried.

**Comment by mgaulton** [comment]
I manually installed apscheduler after trying to start it to see what it complained about.
after that was installed, it started. which was unexpected.

**Comment by mgaulton** [comment]
I tried ==4.1 and ==4.0 and both failed in teh same way.
I'm puzzled now.

**Comment by evilhero** [comment]
Can you try ==3.6 for pyinstaller? I have that version locally and it works on this side.

Apscheduler will throw an initial error if it's not installed, but that doesn't mean that other modules requirements are met or not met (since they'll only hit when they're triggered).

**Comment by mgaulton** [comment]
Good call, that worked.

Collecting pyinstaller==3.6
  Downloading PyInstaller-3.6.tar.gz (3.5 MB)
     |████████████████████████████████| 3.5 MB 1.7 MB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: setuptools in
/usr/lib/python3.8/site-packages (from pyinstaller==3.6) (44.1.1)
Collecting altgraph
  Downloading altgraph-0.17-py2.py3-none-any.whl (21 kB)
Building wheels for collected packages: pyinstaller
  Building wheel for pyinstaller (PEP 517) ... done
  Created wheel for pyinstaller: filename=PyInstaller-3.6-py3-none-any.whl
size=2938300
sha256=508f6d3e1aa629d141287e3d7e42da2e8348464d22e52c36b76b24432dc6d45f
  Stored in directory:
/tmp/pip-ephem-wheel-cache-7dpvihwh/wheels/57/9a/e0/213da356866201eac897534a77c7af30b48b48c2734e30a25f
Successfully built pyinstaller
Installing collected packages: altgraph, pyinstaller
Successfully installed altgraph-0.17 pyinstaller-3.6

**Comment by mgaulton** [comment]
I changed >=3.6 to ==3.6 and was able to run the requirements.txt with no
errors

**Comment by evilhero** [comment]
Well have to investigate this further then if there's breaking changes down the line for that particular module (as opposed to forcing the version to 3.6). Thanks for bringing it to our attention!

**Comment by mgaulton** [comment]
np, thanks for the help!

**Comment by barbequesauce** [comment]
So pyinstaller jumped to 4.0 after 3.6. Big change in the jump was a refactor of how they handle hooks... and with that, a setuptools upgrade requirement of v45.0.0.

<img width="753" alt="Screen Shot 2021-02-17 at 8 58 31 PM" src="https://user-images.githubusercontent.com/25070944/108293964-e8b76980-7162-11eb-8f7a-6cf7f605333e.png">

<img width="393" alt="Screen Shot 2021-02-17 at 9 00 19 PM" src="https://user-images.githubusercontent.com/25070944/108294086-27e5ba80-7163-11eb-937c-2906d035731c.png">

Sadly I don't have an environment to try adding a setuptools upgrade to requirements.txt; can one of you?

**Comment by evilhero** [comment]
In reading more about this, turns out we probably don't even need pyinstaller at all in the requirements.txt. 

Pyinstaller was a requirement of comictagger when we we had CT in requirements, but since we bundle CT now with Mylar, there's no need to have pyinstaller included.

**Comment by barbequesauce** [comment]
This worked on my test rig - hopefully it works for others.
