### ISSUE TITLE
DDL search provider won't find ANY issues from GetComics

### ISSUE THREAD

**Issue by wisewtf** [mylar3/mylar3#624]
First of all, thank you for your hard work. I appreciate having something like Mylar, but as for what was Mylar2, Mylar3 has the same problem for me:

It **NEVER** finds DDL downloads from the GetComics included parser:

Log snippet:

```
01-Feb-2021 21:51:00 - INFO :: mylar.NZB_SEARCH.807 : SEARCH-QUEUE : Shhh be very quiet...I'm looking for Wolverine issue: 1 (2020) using DDL.
01-Feb-2021 21:51:02 - INFO :: mylar.search_results.174 : SEARCH-QUEUE : There are 12 results
01-Feb-2021 21:51:02 - INFO :: mylar.search_init.633 : SEARCH-QUEUE : Could not find Issue 1 of Wolverine (2020) using DDL [api]
```

I get this on every single comic I have in my library that is correctly imported in Mylar. While the comic actually being present and completely downloadable by hand: https://getcomics.info/marvel/wolverine-1-2020/

I am running the Linuxserver docker image which has Mylar on `Version: v0.4.9.4, python3-dev ( master)`

Is there any knowledge I'm missing?
Is this a broken feature still in need to be fixed?

Would appreciate someone shedding some light on the matter, as I've never been able to make it work.

**Comment by evilhero** [comment]
You need to follow the template for creating a new issue - which in this instance you did not. 

In doing so, you would have been presented with the information that you probably need to include a carepackage file, as pasting a log snippet that's not at debug level, shows absolutely nothing helpful. 

So that means put Mylar into verbose mode (either with the -v switch, or setting the ini value for log_level = 2, or toggling the option via the History tab / View Logs page). 

Then do a search for the given issue. Once it doesn't find it, then generate a carepackage and attach the file so that it can be gleemed over.

**Comment by wisewtf** [comment]
> You need to follow the template for creating a new issue - which in this instance you did not.
> 
> In doing so, you would have been presented with the information that you probably need to include a carepackage file, as pasting a log snippet that's not at debug level, shows absolutely nothing helpful.
> 
> So that means put Mylar into verbose mode (either with the -v switch, or setting the ini value for log_level = 2, or toggling the option via the History tab / View Logs page).
> 
> Then do a search for the given issue. Once it doesn't find it, then generate a carepackage and attach the file so that it can be gleemed over.
> 
> Also of note, that I didn't bold/capitalize words to ensure that you saw them - as I'm assuming you can see the words perfectly fine ;)
> 
> Also of note even more, I hate snow.

You're right, you will have to forgive me doing these things at midnight right before wanting to go to bed. :')

I enabled debug and saw this:

```python
02-Feb-2021 09:31:02 - ERROR :: mylar.searchforissue.3193 : SEARCH-QUEUE : Traceback (most recent call last):
  File "/app/mylar3/mylar/search.py", line 3121, in searchforissue
    foundNZB, prov = search_init(
  File "/app/mylar3/mylar/search.py", line 520, in search_init
    findit = NZB_SEARCH(
  File "/app/mylar3/mylar/search.py", line 2414, in NZB_SEARCH
    nzbname = nzbname_create(
  File "/app/mylar3/mylar/search.py", line 3390, in nzbname_create
    if os.path.exists(mylar.CONFIG.BLACKHOLE_DIR):
  File "/usr/lib/python3.8/genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
Traceback (most recent call last):
  File "/app/mylar3/mylar/search.py", line 3121, in searchforissue
    foundNZB, prov = search_init(
  File "/app/mylar3/mylar/search.py", line 520, in search_init
    findit = NZB_SEARCH(
  File "/app/mylar3/mylar/search.py", line 2414, in NZB_SEARCH
    nzbname = nzbname_create(
  File "/app/mylar3/mylar/search.py", line 3390, in nzbname_create
    if os.path.exists(mylar.CONFIG.BLACKHOLE_DIR):
  File "/usr/lib/python3.8/genericpath.py", line 19, in exists
    os.stat(path)
```

I went to check out my download settings and while I enabled blackhole, I didn't put in a path so it failed during searches at that point. I'm not sure why this is the case when I'm not using blackhole, but this was clearly my mistake.

I will still attach the carepackage if you want to look into it more!

[carepackage.zip](https://github.com/mylar3/mylar3/files/5910119/carepackage.zip)

I have now tried to search and it found the issue, downloaded it and post-processed it, so I definitely found the culprit!
