### ISSUE TITLE
Mylar Does Not Pick Up Completed Downloads from NZBGet

### ISSUE THREAD

**Issue by Raph521** [mylar3/mylar3#626]
**Describe the bug**
Mylar successfully sends an nzb to nzbget, and the download completes, but Mylar does not pick up the completed download.  This used to work, but no longer does.

I think the cause may be a recent change that aimed to fix the behavior for SABnzbd.

**CarePackage**
[carepackage.zip](https://github.com/mylar3/mylar3/files/5922217/carepackage.zip)

**Environment (please complete the following information):**
 - OS: Debian 64-bit, docker (linuxserver/mylar3)
 - Branch / commit: Version: ff4cdd8ac9cc3f02ccab119d52125912786ff179 (master)

**Additional information**
I see the following in the log file:
```
03-Feb-2021 18:43:23 - ERROR   :: mylar.excepthook.315 : AUTO-COMPLETE-NZB : Uncaught exception: Traceback (most recent call last):
  File "/app/mylar3/mylar/logger.py", line 337, in new_run
    old_run(*args, **kwargs)
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/app/mylar3/mylar/helpers.py", line 3240, in nzb_monitor
    tmp_apikey = item['queue'].pop('apikey')
KeyError: 'queue'
```

I noticed that with this commit(https://github.com/mylar3/mylar3/commit/b4a00dbb735b553949d7843b721294fbf8e67e6c), the line to pop the last apikey off a queue was added at line 3240 (`tmp_apikey = item['queue'].pop('apikey')`).  However, I don't think Mylar needs an API key to communicate with NZBGet, so is a pop being done on an empty queue?

**Comment by evilhero** [comment]
Huh, yeah that would definitely cause a problem.

It's not that it's being done on an empty queue, but nzbget isn't returning a value for 'queue' - I think because the nzbget response doesn't contain it on purpose based on the api. 

Will have to spin up nzbget later on and see what's happening - should be a simple fix tho if I'm correct.

Thanks for bringing it to our attention!

**Comment by Raph521** [comment]
Thanks for the quick response!

I just pulled `linuxserver/mylar3:nightly`, which includes this latest commit, and the issue is fixed - Mylar picks up the completed download from NZBGet.

I think this one can be closed now, but I'll defer to you on when you want to do that :smile:

Thanks again for the quick fix!
