### ISSUE TITLE
Unable to access "Story Arcs" page.

### ISSUE THREAD

**Issue by SSoft7** [mylar3/mylar3#628]
**Describe the bug**
Trying to access "Story Arcs" (URI: /storyarc_main) page gives me an error.

```
Error !
TypeError: expected str, bytes or os.PathLike object, not NoneType
<legend>Global StoryArc Options</legend> <div class="row checkbox left clearfix"> <% storyarcdest = os.path.join(mylar.CONFIG.DESTINATION_DIR, 'StoryArcs') %> <input type="checkbox" style="vertical-align: middle; margin: 3px; margin-top: -1px;" onclick="getOption(this)" name="storyarcdir" id="storyarcdir" value="1" ${checked(mylar.CONFIG.STORYARCDIR)} /><label>Arcs in StoryArc Directory </br><small>(${storyarcdest})</small></label> </div> <div id="arc_options"> <div class="row">
/usr/lib/python3.8/posixpath.py, line 76:
a = os.fspath(a)
/app/mylar3/data/interfaces/default/storyarc.html, line 55:
storyarcdest = os.path.join(mylar.CONFIG.DESTINATION_DIR, 'StoryArcs')
/app/mylar3/data/interfaces/default/base.html, line 91:
${next.body()}
/usr/lib/python3.8/site-packages/mako/runtime.py, line 947:
callable_(context, *args, **kwargs)
/usr/lib/python3.8/site-packages/mako/runtime.py, line 920:
_exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
/usr/lib/python3.8/site-packages/mako/runtime.py, line 878:
_render_context(
/usr/lib/python3.8/site-packages/mako/template.py, line 473:
return runtime._render(self, self.callable_, args, data)
/app/mylar3/mylar/webserve.py, line 94:
return template.render(http_root=mylar.CONFIG.HTTP_ROOT, interface=mylar.CONFIG.INTERFACE, icons=icons, **kwargs)
```

**CarePackage**
https://mega.nz/file/g8dVVA5C#r-mdqbRWiyYykJr-bDjZGdTmxqasJn0Uzns8kW-nzk4

**Environment (please complete the following information):**
 - OS: Linux
 - Branch / commit: build 6f44942cba338bfc715754ffeaa1f1d3e9d364ed

**Comment by evilhero** [comment]
It's probably best if you read the readme of the project [here](https://github.com/mylar3/mylar3#usage)

Your Comic Location path isn't set - which is the first thing mentioned in the above docs as being a requirement for usage. Either change it in the GUI and save the settings, or with Mylar not running edit the config.ini and change the value of ```destination_dir``` to point to the path. Either one will accomplish the same thing and then you'll be fine thereafter.

**Comment by SSoft7** [comment]
Thank you for your detailed response. I am not actually a mylar user but I was setting this up for someone and I was checking if all pages are loading fine. So, that explains why I did not read the usage section of the readme.
Anyways, In my opinion, that page should return a simple one-line error rather than a traceback.

**Comment by evilhero** [comment]
One last time.

This is closed, and has been for over a year and a half. 

You are not the ticket police. We close items as we resolve them. 

This conversation is not going to continue further in this issue ticket.
