### ISSUE TITLE
Internal Server Error when searching for "Sonja"

### ISSUE THREAD

**Issue by miracle152005** [mylar3/mylar3#632]
**Describe the bug**
When I search for "Sonja" I get an Internal Server Error.
The log files do not contain any relevant information about the issue.

Could you please take a look.
Thanks.

"Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/cherrypy/_cprequest.py", line 638, in respond
    self._do_respond(path_info)
  File "/usr/lib/python3.8/site-packages/cherrypy/_cprequest.py", line 697, in _do_respond
    response.body = self.handler()
  File "/usr/lib/python3.8/site-packages/cherrypy/lib/encoding.py", line 219, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/app/mylar/webserve.py", line 393, in searchit
    searchresults = mb.findComic(name, mode, issue=None)
  File "/app/mylar/mb.py", line 308, in findComic
    if result.getElementsByTagName('super_url')[0].firstChild.wholeText:
IndexError: list index out of range"

**CarePackage**
[mylar.log](https://github.com/mylar3/mylar3/files/5938622/mylar.log)

**Environment (please complete the following information):**
 - OS: docker container on a ubuntu 18.04 installation
 - Branch / commit: 165e0899de7725fba4c7f106a5349abb37466629

**Comment by evilhero** [comment]
Was probably a problem with CV at the time of you trying to search for a particular series. 

I just tried it today and got back a full listing with no errors with that search query. 

It's possible that one of the series was being updated as you were searching and some null fields were in the XML which threw it off and/or the image link wasn't present - but unsure without being able to fully see the xml (or test it).

**Comment by miracle152005** [comment]
Yes, seems to be the case. It works fine today.
