### ISSUE TITLE
Update Mylar not working

### ISSUE THREAD

**Issue by leaderdog** [mylar3/mylar3#646]
Hitting update doesn't update to the latest build.

20-Feb-2021 05:51:08 - DEBUG   :: mylar.runGit.46 : MAIN : Git output: CompletedProcess(args='git pull origin python3-dev', returncode=128, stdout='', stderr='From https://github.com/mylar3/mylar3\n * branch            python3-dev -> FETCH_HEAD\n\n*** Please tell me who you are.\n\nRun\n\n  git config --global user.email "you@example.com"\n  git config --global user.name "Your Name"\n\nto set your account\'s default identity.\nOmit --global to set the identity only in this repository.\n\nfatal: unable to auto-detect email address (got \'Mylar@Media.(none)\')\n')
20-Feb-2021 05:51:08 - DEBUG   :: mylar.NZB_SEARCH.951 : ThreadPoolExecutor-0_11 : Sending request to RSS for Sevara : 0 (2015)
20-Feb-2021 05:51:08 - ERROR   :: mylar.runGit.54 : MAIN : Encountered error: From https://github.com/mylar3/mylar3
 * branch            python3-dev -> FETCH_HEAD

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'Mylar@Media.(none)')

20-Feb-2021 05:51:08 - ERROR   :: mylar.runGit.62 : MAIN : Error: From https://github.com/mylar3/mylar3
 * branch            python3-dev -> FETCH_HEAD

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'Mylar@Media.(none)')

20-Feb-2021 05:51:08 - ERROR   :: mylar.runGit.63 : MAIN : Git returned bad info. Are you sure this is a git installation? []
20-Feb-2021 05:51:08 - WARNING :: mylar.shutdown.1406 : MAIN : Mylar failed to update: 'NoneType' object has no attribute 'stdout'. Restarting.
20-Feb-2021 05:51:08 - INFO    :: mylar.shutdown.1413 : MAIN : Mylar is restarting...
20-Feb-2021 05:51:08 - INFO    :: mylar.shutdown.1421 : MAIN : Restarting Mylar with ['C:\\Python37\\python.exe', 'C:\\mylar3\\Mylar.py']
20-Feb-2021 05:51:09 - DEBUG   :: mylar.provider_sequence.1275 : MainThread : Original provider_order sequence: 0, Experimental, 1, AltHUB, 2, Nzbgeek
20-Feb-2021 05:51:09 - DEBUG   :: mylar.provider_sequence.1278 : MainThread : Provider sequence already pre-exists. Re-loading and adding/remove any new entries
20-Feb-2021 05:51:09 - DEBUG   :: mylar.provider_sequence.1360 : MainThread : Provider Order is now set : {'0': 'Experimental', '1': 'AltHUB', '2': 'Nzbgeek'} 
20-Feb-2021 05:51:09 - DEBUG   :: mylar.configure.905 : MainThread : Log dir: C:\Mylar3\logs
20-Feb-2021 05:51:09 - INFO    :: mylar.configure.1021 : MainThread : Ignored Publishers: []
20-Feb-2021 05:51:09 - INFO    :: mylar.configure.1040 : MainThread : [COMICTAGGER] Version detected: 1.3.4
20-Feb-2021 05:51:09 - INFO    :: mylar.initialize.193 : MainThread : Checking to see if the database has all tables....
20-Feb-2021 05:51:09 - INFO    :: mylar.dbcheck.1348 : MainThread : Ensuring DB integrity - Removing all Erroneous Comics (ie. named None)
20-Feb-2021 05:51:09 - INFO    :: mylar.dbcheck.1350 : MainThread : Correcting Null entries that make the main page break on startup.

**Comment by evilhero** [comment]
Due to a screwy git merge, it's the same as it was for #511:
(if you have local changes, do ```git stash``` first. After below, do ```git stash apply``` to put local changes back) 


 ```git fetch```

 ```git checkout python3-dev```

 ```git reset --hard origin/python3-dev```

Might have to ```git pull``` at the end.

**Comment by leaderdog** [comment]
Excellent, that fixed it.  

Thanks. :)
