### ISSUE TITLE
Make symlinks relative for StoryArcs

### ISSUE THREAD

**Issue by Shalar** [mylar3/mylar3#652]
I would like to request symlinks be relative (or the option given to be) rather than absolute. I run mylar3 in a docker container with my comics mounted as /comics, but the actual path is something else. If I try to use a terminal or sftp client to access the symlinks it fails due to the actual path not existing.

**Comment by davalanche** [comment]
I can take a look at this request.

**Comment by evilhero** [comment]
@davalanche , sure feel free to - this probably would have been a low priority for us given the current workload, so if you want to take a look at it, much appreciated!

**Comment by evilhero** [comment]
Assuming fixed since this been in for a while now (and it's stale otherwise).
