### ISSUE TITLE
Docker image for mylar3 missing pystun?

### ISSUE THREAD

**Issue by lcmsilek** [mylar3/mylar3#656]
**Describe the bug**
mylar3 docker image missing pystun, errors in mylar.log and issues with downloading.

**Environment (please complete the following information):**
 - OS: docker image
 - Branch / commit: dev  v0.4.9.5

**Additional information**
The docker version of mylar3 does not include the stun module, and errors come up. It does seem to impact the downloading of comics. Work around is to get in the container and simply install pystun with pip.
My carepackage is over 30mb (my db is 21mb alone). File uploaded is missing the DB to get the logs up.
[carepackage.zip](https://github.com/mylar3/mylar3/files/6056889/carepackage.zip)

**Comment by barbequesauce** [comment]
Odd... we don't use this module.

I've looked through the files in the care package, and apart from the `pip freeze` output it's not referenced. Can you capture where you saw the reference please?

**Comment by lcmsilek** [comment]
Wow. quick response.  It should be buried in the mylar.log.3 in the carepackage. I'll cut and paste below. I've found that when I update docker, obviously the error comes back. After manually adding pystun, all of a sudden I get a rush of downloads.

27-Feb-2021 09:54:07 - INFO    :: mylar.searcher.3785 : ThreadPoolExecutor-0_0 : filen: Year_Zero_v2_004_2021_digital_Son_of_Ultron-Empire -- nzbname: Year.Zero.v2.004.2021.digital.Son.of.Ultron-Empire are not identical. Storing extra value as : Year.Zero.v2.004.2021.digital.Son.of.Ultron-Empire
27-Feb-2021 09:54:07 - ERROR   :: mylar.searchforissue.3008 : ThreadPoolExecutor-0_0 : Traceback (most recent call last):
  File "/app/mylar3/mylar/search.py", line 2943, in searchforissue
    foundNZB, prov = search_init(
  File "/app/mylar3/mylar/search.py", line 439, in search_init
    findit = NZB_SEARCH(
  File "/app/mylar3/mylar/search.py", line 2436, in NZB_SEARCH
    searchresult = searcher(
  File "/app/mylar3/mylar/search.py", line 4164, in searcher
    import stun
ModuleNotFoundError: No module named 'stun'
Traceback (most recent call last):
  File "/app/mylar3/mylar/search.py", line 2943, in searchforissue
    foundNZB, prov = search_init(
  File "/app/mylar3/mylar/search.py", line 439, in search_init
    findit = NZB_SEARCH(
  File "/app/mylar3/mylar/search.py", line 2436, in NZB_SEARCH
    searchresult = searcher(
  File "/app/mylar3/mylar/search.py", line 4164, in searcher
    import stun
ModuleNotFoundError: No module named 'stun'

**Comment by barbequesauce** [comment]
WOW that was buried, great catch! Easy fix though, as you pointed out... we must have overlooked it when we externalized the dependencies, `git blame` shows it was added to `lib/` five years ago...

**Comment by barbequesauce** [comment]
Good now?

**Comment by lcmsilek** [comment]
Yes. :) Sorry, had to update my docker image, but I am now seeing  
downloads without any import stun issues.

Also seeing mystun in the docker image:

root@352c120200d9:/usr/lib# find|grep -i stun
./python3.8/site-packages/pystun-0.1.0-py3.8.egg-info

Again, thanks for the quick fix. If there is something I can help with  
in terms of testing, let me know. Happy to help.


Quoting Barbeque Sauce <notifications@github.com>:
