### ISSUE TITLE
Crash after update after dev branch history was rewritten

### ISSUE THREAD

**Issue by dreaganluna** [mylar3/mylar3#660]
**Describe the bug**
After updating to the latest version using the updater in Mylar itself, it won't start up anymore.
It seems I'm on a commit that no longer resides in this dev branch. I think this has happened before. Should I not use that branch?

Is there any risk in performing a hard reset on my machine?

**Environment (please complete the following information):**
 - OS: Windows10
 - Branch / commit: Dev/ba5baa672227224ef8fa0c3d3a48401d6645ebb6]

**Comment by barbequesauce** [comment]
Can you please run `git status` and paste the results here?

**Comment by evilhero** [comment]
Just follow the instructions in #646. 

If you have any local modifications you did, then you would need to ```git stash``` them prior to issuing the command above. Otherwise, there's no danger in doing the reset, it just overwrites anything local with what the repo on git has (aside from your config, db, etc)

**Comment by dreaganluna** [comment]
It looks like you rewrote history for that dev branch again.
Should I not use that branch?

**Comment by evilhero** [comment]
If you feel it's not worth the effort to do the odd git command, in exchange for not waiting the usual week (or more) for merges to the master branch -  that's a personal choice.   It's not an every day occurrence - there were some issues with the merges the past few times that we tried to deal with in the most manageable way.

If any of this is a concern for you, you might want to consider using the master branch.
