### ISSUE TITLE
There are 0 issues for week 10, 2021

### ISSUE THREAD

**Issue by adispi** [mylar3/mylar3#665]
automatic, refesh, manual, all shows no issues:
11-Mar-2021 22:48:37 - INFO    :: mylar.locg.74 : CP Server Thread-7 : [WEEKLY-PULL] There are 0 issues for week 10, 2021
11-Mar-2021 22:48:37 - INFO    :: mylar.locg.135 : CP Server Thread-7 : [PULL-LIST] Successfully populated pull-list into Mylar for week 10 of 2021
i have comicvine api key configured and i have comic location set.

mylar information:
Mylar Version: master
-- source (build 69fc804b048407986add632dc13544120cb8a5e9)
Python Version : 3.8.7
Language : en_US.UTF-8

docker image:  linuxserver/mylar3:nightly

**Comment by BRTPOB** [comment]
Can you attach the debug logs? I'm looking at my This Week right now and it's showing everything. It's also possible there's an issue with the back-end that is causing this, but for sure debug logs are required to help look at this further.

**Comment by adispi** [comment]
i do not see more information on debug log:
11-Mar-2021 23:25:13 - INFO    :: mylar.toggleVerbose.4169 : CP Server Thread-10 : Verbose (DEBUG) logging is enabled
11-Mar-2021 23:25:13 - DEBUG   :: mylar.toggleVerbose.4170 : CP Server Thread-10 : If you can read this message, debug logging is now working
11-Mar-2021 23:25:13 - INFO    :: mylar.toggleVerbose.4173 : CP Server Thread-10 : config file has been loaded from: /config/mylar/config.ini
11-Mar-2021 23:25:16 - INFO    :: mylar.pullist.1744 : CP Server Thread-3 : trying to repopulate to week: 10-2021
11-Mar-2021 23:25:16 - INFO    :: mylar.manualpull.2030 : CP Server Thread-3 : ALT_PULL: 2 PULLBYFILE: False week: 10 year: 2021
11-Mar-2021 23:25:18 - INFO    :: mylar.locg.74 : CP Server Thread-3 : [WEEKLY-PULL] There are 0 issues for week 10, 2021
11-Mar-2021 23:25:18 - INFO    :: mylar.locg.135 : CP Server Thread-3 : [PULL-LIST] Successfully populated pull-list into Mylar for week 10 of 2021
11-Mar-2021 23:25:18 - DEBUG   :: mylar.writeconfig.778 : CP Server Thread-3 : Writing configuration to file
11-Mar-2021 23:25:18 - DEBUG   :: mylar.provider_sequence.1277 : CP Server Thread-3 : Original provider_order sequence: {'0': 'something'}
11-Mar-2021 23:25:18 - DEBUG   :: mylar.provider_sequence.1280 : CP Server Thread-3 : Provider sequence already pre-exists. Re-loading and adding/remove any new entries
11-Mar-2021 23:25:18 - DEBUG   :: mylar.provider_sequence.1362 : CP Server Thread-3 : Provider Order is now set : {'0': 'something'} 
11-Mar-2021 23:25:18 - DEBUG   :: mylar.writeconfig.804 : CP Server Thread-3 : Configuration written to disk.
11-Mar-2021 23:25:20 - INFO    :: mylar.pullrecreate.2048 : CP Server Thread-2 : Deleted existing pull-list data for week 10, 2021. Now Recreating the Pull-list...
11-Mar-2021 23:25:20 - INFO    :: mylar.pullit.71 : CP Server Thread-2 : [PULL-LIST] Populating & Loading pull-list data directly from alternate website
11-Mar-2021 23:25:20 - INFO    :: mylar.pullit.91 : CP Server Thread-2 : [PULL-LIST] Populating & Loading pull-list data directly from alternate website for specific week of 10, 2021
11-Mar-2021 23:25:22 - INFO    :: mylar.locg.74 : CP Server Thread-2 : [WEEKLY-PULL] There are 0 issues for week 10, 2021
11-Mar-2021 23:25:22 - INFO    :: mylar.locg.135 : CP Server Thread-2 : [PULL-LIST] Successfully populated pull-list into Mylar for week 10 of 2021
11-Mar-2021 23:25:22 - DEBUG   :: mylar.writeconfig.778 : CP Server Thread-2 : Writing configuration to file
11-Mar-2021 23:25:22 - DEBUG   :: mylar.provider_sequence.1277 : CP Server Thread-2 : Original provider_order sequence: {'0': 'something'}
11-Mar-2021 23:25:22 - DEBUG   :: mylar.provider_sequence.1280 : CP Server Thread-2 : Provider sequence already pre-exists. Re-loading and adding/remove any new entries
11-Mar-2021 23:25:22 - DEBUG   :: mylar.provider_sequence.1362 : CP Server Thread-2 : Provider Order is now set : {'0': 'something'} 
11-Mar-2021 23:25:22 - DEBUG   :: mylar.writeconfig.804 : CP Server Thread-2 : Configuration written to disk.
11-Mar-2021 23:25:22 - INFO    :: mylar.pullit.99 : CP Server Thread-2 : [PULL-LIST] Weekly Pull List successfully loaded with 0 issues.
11-Mar-2021 23:25:22 - DEBUG   :: mylar.new_pullcheck.994 : CP Server Thread-2 : [WALKSOFTLY] You are watching for: 162 comics

**Comment by BRTPOB** [comment]
yeah, ok, I know @evilhero said there was something with SQL going on, so I'm assuming the backend is currently dead. He hasn't responded on IRC, but hopefully he'll respond here.

**Comment by evilhero** [comment]
Was a problem with some CV series that were renamed mutiple times by CV - everything's back up and running as per normal now. If you're pull-list hasn't updated, just do a ```Recreate Pull-list``` from the weekly page and it'll line things back up.

**Comment by adispi** [comment]
confirmed as fixed
