### ISSUE TITLE
Number padding adds a 0 even if the number already has the correct number of digits

### ISSUE THREAD

**Issue by foux** [mylar3/mylar3#668]
**Describe the bug**
When we choose a number padding, we expect the issue numbering to contains the exact number of digits.

For example, if we choose `0x` we expect issues 0-9 to be 00-09 and issue 10 and over to keep the same numbering. Instead issues 0-9 got correctly renamed to 00-09, but issues 10+ got renamed 010, ... instead of keeping the same number.

**Environment (please complete the following information):**
 - OS: Linux / Docker
 - Branch / commit: Master

**Comment by foux** [comment]
As an added information, number padding `00x` seems to be working.

**Comment by evilhero** [comment]
This has been beaten to death in the py2 version of. ylar. The padding is for OS level sorting - removing the padding from the 10-100 range means that any issues above 100 are logically out of order (01, 10, 100, 101, 102, 11, 12, etc).

You  can check the py2 repo of Mylar and search the issues for "padding" to view the explanations further (I'm too lazy to link them all here).

The padding arrangement will get redone when the preview rename function goes live as that has a bunch of changes to the renaming structure, and adding in various types of padding choices would need to happen in/after that PR.
