### ISSUE TITLE
Mylar hasn’t downloaded anything in over a week and there are “exceptions” in the log

### ISSUE THREAD

**Issue by AtariBaby** [mylar3/mylar3#670]
**Describe the bug**
I realized today my system hadn’t downloaded any comics for 8 days, and I’m usually getting them twice a week. I see errors in the log but no idea what it means. To my knowledge nothing has been changed by me.
**CarePackage**
[carepackage 4.zip](https://github.com/mylar3/mylar3/files/6176076/carepackage.4.zip)

**Environment (please complete the following information):**
Windows 10

b1984c251434cd6c104e408fd5b69ef4d0fa9890
Master
**Additional information**
Add any other information about the problem here.

**Comment by evilhero** [comment]
Turn off experimental search - it's throwing errors for everyone as it's either being constantly hammered, going up/down or just blocking users temporarily if they request too quickly. 

I'll look into it at some point - but in the meantime, disable it (it is called ```experimental``` for a reason).

**Comment by AtariBaby** [comment]
Will do!

**Comment by evilhero** [comment]
experimental being experiemental. Closing due to provider issue, probably already handled in mylar, as well as being as stale.
