### ISSUE TITLE
Comic name / issue title as a rename token

### ISSUE THREAD

**Issue by FrankEBailey** [mylar3/mylar3#672]
It would be very useful to have the comic's title as a rename token, it would help immensely for me to locate specific stories and runs within my collection. I know the titles are visible within Mylar, but to have the issue titles in the filenames as an option would really take the useability of Mylar to the next level for me.

**Comment by evilhero** [comment]
Doing so will break the file parser as it's fragile enough without adding in that kind of context when there is zero-naming conventions that people follow.

If you want the issue title, you should use the metadata aspect as that's what it's for.
