### ISSUE TITLE
"Have" column sorting behavior has changed

### ISSUE THREAD

**Issue by Serneum** [mylar3/mylar3#673]
**Describe the bug**
The "Have" column used to show all incomplete series, then all complete series. Now the series stay mixed and it makes it harder to see when a series has not been downloading properly.

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Branch / commit: python3-dev / 9a12db6399416dfb728f9c33fa5ef0eb667b89fe
 
**Additional information**
![image](https://user-images.githubusercontent.com/1091716/112041421-c5465c80-8b1c-11eb-9091-3f8f7fd01e4b.png)
![image](https://user-images.githubusercontent.com/1091716/112041551-e73fdf00-8b1c-11eb-98ba-f596a833c62b.png)

**Comment by mylar3** [comment]
Try changing to the carbon interface theme via the Configuration and see if that changes the sorting.  From what I can recall, it might not be applying the sorting order to the default interface...

**Comment by Serneum** [comment]
The Carbon theme seems to be doing the same thing. Here's my carepackage just in case it has other settings that matter

[carepackage.zip](https://github.com/mylar3/mylar3/files/6184709/carepackage.zip)

**Comment by mylar3** [comment]
It's sorting by percentage - or well supposed to be. It was working correctly at one point, but not sure exactly what changed on the backend, but yes it should not be mixing up the values (especially the 2/3 one, the first screenshot tho looks correct based on just overall percentage completion 50% comes before 100%). 

I have it adjusted, but just need some feedback on it from some users. Are the following screenshots what you're trying to get to ?

Showing series, in ascending order:
![](https://colder.thanyou.xyz/selif/6icozv6m.png)

Showing series in descending order:
![](https://colder.thanyou.xyz/selif/nan1vok7.png)

**Comment by evilhero** [comment]
It's sorting by percentage - or well supposed to be. It was working correctly at one point, but not sure exactly what changed on the backend, but yes it should not be mixing up the values (especially the 2/3 one, the first screenshot tho looks correct based on just overall percentage completion 50% comes before 100%). 

I have it adjusted, but just need some feedback on it from some users. Are the following screenshots what you're trying to get to ?

Showing series, in ascending order:
![](https://colder.thanyou.xyz/selif/6icozv6m.png)

Showing series in descending order:
![](https://colder.thanyou.xyz/selif/nan1vok7.png)

**Comment by Serneum** [comment]
I don't think the first screenshot I posted is the app behaving as expected, it's just sorting by the number of downloading comics in the series, so `1/2` happens to come before `1/1` because both series have `1` comic downloaded and then it shows up first because it is incomplete. The `2/3` comes before all of the other series that have `2` comics downloaded, etc. Here is another example where the 3 downloaded, but incomplete comes before all of the 3 downloaded and complete comics
![image](https://user-images.githubusercontent.com/1091716/112167764-1a3ead00-8bc7-11eb-89aa-86e3c247da31.png)

As for the screenshots you posted, that looks correct to me

**Comment by Serneum** [comment]
I'm now on 903902e17c9fc77e7c5fecfb89d8a3daad9b96d4 and things look as they used to, thanks!
