### ISSUE TITLE
Tips on better downloading with Mylar and NZBHydra2?

### ISSUE THREAD

**Issue by AtariBaby** [mylar3/mylar3#685]
[carepackage 5.zip](https://github.com/mylar3/mylar3/files/6217905/carepackage.5.zip)
Windows 10 Pro, git (build b1984c251434cd6c104e408fd5b69ef4d0fa9890)

Turns out I was getting 80% of my comics through experimental. Anyone have tips on settings that will improve matters? I have missed 80% of my comics since turning off the setting. If not specific to Hydra, what about just in general when dealing with indexers? Like should I enter usenet categories for comics, for example? Any suggestions appreciated.

**Comment by evilhero** [comment]
not an issue - please ask in the forums / discord.
