### ISSUE TITLE
Non numeric issue id breaks loading comic info

### ISSUE THREAD

**Issue by qubidt** [mylar3/mylar3#692]
**Describe the bug**

Importing [Previews]() never completes. Specifically, [this issue](https://comicvine.gamespot.com/previews-380381/4000-764104/) (`#380/381`) breaks the info importer because it can't parse the issue no.

**CarePackage**
|      Timestamp      |  Level  |                                                  Message                                                   |
|---------------------|---------|------------------------------------------------------------------------------------------------------------|
| 2021-04-02 05:52:44 | WARNING | Previews has not finished loading. Nulling some values so things display properly until they can populate. |
| 2021-04-02 05:52:41 | ERROR   | 380/381 this has an alpha-numeric in the issue # which I cannot account for.                               |
| 2021-04-02 05:52:41 | INFO    | Now adding/updating issues for Previews                                                                    |
| 2021-04-02 05:52:41 | DEBUG   | Finished Annual checking.                                                                                  |
| 2021-04-02 05:52:41 | DEBUG   | there are 0 search results...                                                                              |
| 2021-04-02 05:52:39 | DEBUG   | [IMPORTER-ANNUAL] - Annual Year:1988                                                                       |
| 2021-04-02 05:52:39 | DEBUG   | checking annual db                                                                                         |
| 2021-04-02 05:52:39 | DEBUG   | issuetype: None                                                                                            |
| 2021-04-02 05:52:39 | DEBUG   | latestissueinfo: [{'latestiss': None, 'latestdate': None}]                                                 |
| 2021-04-02 05:52:39 | DEBUG   | issuechk: None                                                                                             |
| 2021-04-02 05:52:39 | DEBUG   | calledfrom: None                                                                                           |
| 2021-04-02 05:52:39 | DEBUG   | comicissues: 301                                                                                           |
| 2021-04-02 05:52:39 | DEBUG   | comicname: Previews                                                                                        |
| 2021-04-02 05:52:39 | DEBUG   | comicid: 54106                                                                                             |
| 2021-04-02 05:52:39 | DEBUG   | issuedata call references...                                                                               |
| 2021-04-02 05:52:39 | INFO    | Sucessfully retrieved issue details for Previews                                                           |
| 2021-04-02 05:52:36 | DEBUG   | Querying & compiling from 300 - 400 out of 301 results                                                     |

**Environment (please complete the following information):**
 - OS: Alpine Linux 3.13.4
 - Branch / commit: master/dd2ab46

**Additional information**

**Comment by barbequesauce** [comment]
What's the file name?

**Comment by evilhero** [comment]
@barbequesauce , the error posted is actually happening during the add of a series from scratch - we just have to add the ```380/381``` to the exceptions aspect and then it'll add fine.

@qubidt, Mylar was built to handle issue numbering that are any of : alphanumeric, float or integer.  The problem being when weird numbering happens for a given issue that doesn't fall into one of those 3 categories, it'll error with a traceback and/or stall. At some point I'll try to add a way to catch the different ones and force them thru - , but atm at least, Mylar has to convert each issue number to an integer value it assigns a value based on what it can parse, and in this case it can't do that (```380/381``` is not an integer, or float by Mylar's definition, but it kinda is - weird case I know). 

Regardless, fix should be up in python3-dev in a few hrs...

**Comment by evilhero** [comment]
Fixed awhile ago - closing.
