### ISSUE TITLE
ComicRN.py Scrip Error

### ISSUE THREAD

**Issue by mccorkled** [mylar3/mylar3#700]
deleted

**Comment by evilhero** [comment]
Whatever ComicRN script you're using, it's not the one included with the mylar3 repo - I'm assuming you're probably still using the ComicRN script from the python2 repo, which isn't compatible with the py3 version.

Also, ComicRN isn't really used except for specific edge cases - the recommended method is enabling Completed Download Handling (CDH).

**Comment by mccorkled** [comment]
You're too fast in responding. I realized after posting that was the case. I fixed that problem and have been trying to troubleshoot a new one since my initial post.

`Loading config from /config/scripts/autoProcessComics.cfg
Opening URL for post-process of /Media/Downloads/Usenet/complete/Comics/the.walking.dead.193.2019.c2c.teachbug @ http://localhost:8090http://10.166.8.139/api/forceProcess:
Unable to open URL: Failed to parse: http://localhost:8090http://10.166.8.139/api`

I would use CDN, however I am using LSIO Docker builds of Sab and 0.8.0 is not available.

**Comment by evilhero** [comment]
LSIO has current builds of SAB - not exactly sure where you're seeing something else.

As far as your new error, you have some extra host values coming from somewhere - check your autoProcessComics.cfg, check that your sabnzbd host within Mylar is set correctly, and probably check to see if you have a host_return value set in the config.ini for Mylar.

**Comment by mccorkled** [comment]
Yes, they have current versions but not old ones such as 0.8.0. Currently using 3.1.1

Sab  in Mylar is showing `http://10.166.8.139:8080`
Host_return is showing `host_return = None`
AutoProcessComics.cfg 
`[Mylar]
host=localhost
port=8090
apikey=ef6c1deca06528de7a91afcbf57261cf
web_root=
ssl=0`

**Comment by evilhero** [comment]
It doesn't have to be exactly 0.8.0, it has to be a SAB version greater than 0.8.0, and 3.1.1 > 0.8.0 (almost everyone is using a v3 version of SAB with Mylar3).

As far as the double host lines in teh error for ComicRN, you might have to attach a carepackage so that I can see exactly what's going on without having to keep on guessing.

**Comment by mccorkled** [comment]
Could you be more specific in what exactly you're looking for? Mylar log? Sab log?

**Comment by evilhero** [comment]
is CDH failing at the point where it tries to find the issue to post-process? 

Like it flips back a message in the logs that says either: 
```Unable to locate directory within <file path> location. I have unsucessfully attempted to locate the following paths: ```
or
```no file found where it should be @ <file path here>```

If it does those both, it might be related to a docker path issuing I'm currently trying to test out the fix for - there were no logs attached to the carepackage you included - so it's kind of hard to guess without seeing some debug logs.

**Comment by mccorkled** [comment]
[Uploading mylar.log…]()

**Comment by mccorkled** [comment]
[mylar.log](https://github.com/mylar3/mylar3/files/6288119/mylar.log)

**Comment by evilhero** [comment]
I mean you had the queue paused, in the logs:
```[WARNING] SABnzbd has the active queue Paused. CDH will not work in this state.```

It looks like you have over 100GB of stuff queued up somehow, and if Mylar isn't part of any of those requests (meaning it wasn't initiated via Mylar) then it wouldn't know what they are until they completed and post-processing kicked in via folder monitor.

I can't see what your sab is doing obviously - so it's hard for me to just sit here and guess at what's happening. Can you clear out the queue and start fresh ? or wait for w/e you have queued to finish and then try CDH from a fresh standpoint ?

**Comment by mccorkled** [comment]
I paused it several minutes after the file finished so I could upload that log. My internet is poor. I had assumed Mylar worked like Sonarr and Radarr, where it knew when the file was finished via API and would then initiate post processing, rather then waiting for the entire queue to empty. Especially when categories are being used.

**Comment by evilhero** [comment]
Mylar doesn't have to wait for the entire queue to finish - it does need to wait tho for an individual item to finish downloading prior to moving on to the next item (it uses the FIFO method). 

It knows when the queue is paused and holds all sends until it's active again and resubmits as required if they haven't been downloaded already - but if you want Mylar to download items you either have to wait for the items to complete or move them to the top of your queue so they can finish downloading. 

Note. that if you're using SAB < 3.2.1, nzo_id searching wasn't introduced until then - so if you had a queue of items ( > 10 I think), Mylar wouldn't be able to track anything past the 10th position and would say it couldn't locate it. In your particular case, you might want to upgrade your SAB to the latest version if you're maintaining a large active queue within SABnzbd.

**Comment by mccorkled** [comment]
I have Sab set to force comic downloads so they always get sent to the front of the queue.

**Comment by mccorkled** [comment]
Here is the log when trying the ComicRN method.
[mylar(1).log](https://github.com/mylar3/mylar3/files/6288274/mylar.1.log)

**Comment by evilhero** [comment]
Not sure if the API honors that - the display would obviously, but the API might be returning it based on some other aspect (ie. date Added as opposed to being forced to the top).

**Comment by mccorkled** [comment]
Here is the log when trying the ComicRN method.
[mylar(1).log](https://github.com/mylar3/mylar3/files/6288274/mylar.1.log)

**Comment by evilhero** [comment]
There's nothing in that log snippet. 

Kill the docker container and start it up again, you're getting port locked usage cause it's not able to restart properly for some reason:
```09-Apr-2021 20:20:51 - ERROR   :: mylar.initialize.187 : MAIN : [ERROR] Port 8090 is in use on 0.0.0.0```

**Comment by mccorkled** [comment]
[mylar.log](https://github.com/mylar3/mylar3/files/6288345/mylar.log)

**Comment by evilhero** [comment]
You didn't disable CDH - the auto-complete will only show if CDH is enabled. If you didn't restart Mylar by shutting it down like I mentioned above, it doens't restart but relinks to the existing session which means it keeps all the locks, etc.

**Comment by mccorkled** [comment]
[mylar.log](https://github.com/mylar3/mylar3/files/6288396/mylar.log)

Okay, hopefully this is finally it :)

**Comment by evilhero** [comment]
It says it sent it, and the downloadNZB command was initiated - but then the log stops. What does your SAB say for that particular issue (if ComicRN ran you should be able to view the script output)

**Comment by mccorkled** [comment]
```
Loading config from /config/scripts/autoProcessComics.cfg
Opening URL for post-process of /Media/Downloads/Usenet/complete/Comics/the.walking.dead.193.2019.c2c.teachbug @ http://10.166.8.139:8090http://10.166.8.139/api/forceProcess:
Unable to open URL: Failed to parse: http://10.166.8.139:8090http://10.166.8.139/api
```

**Comment by mccorkled** [comment]
I am not familiar with code, but looking over the script
`url = protocol + host + ":" + port + web_root + '/api'`

Perhaps something is missing here?

**Comment by evilhero** [comment]
Can you verify the contents of ```/config/scripts/autoProcessComics.cfg``` ? 

It's pulling the values directly from that file (note that ```AutoProcessComics.cfg``` is different than ```autoProcessComics.cfg ```if you have both for some reason).

Either you're looking / editing the wrong cfg file, or you have a webroot specified that's got that full path.

**Comment by mccorkled** [comment]
Okay, so I did have webroot filled. I changed that the other day but apparently the file didn't over write properly. So now I am not getting the error in Sab, but it's still not processing. Here is the new info after the download finishes and the script runs.

```
Loading config from /config/scripts/autoProcessComics.cfg
Opening URL for post-process of /Media/Downloads/Usenet/complete/Comics/the.walking.dead.193.2019.c2c.teachbug @ http://10.166.8.139:8090/api/forceProcess:
statuscode: 200
b'nzb name: the.walking.dead.193.2019.c2c.teachbug\nnzb folder: /Media/Downloads/Usenet/complete/Comics/the.walking.dead.193.2019.c2c.teachbug\nnzbname: the.walking.dead.193.2019.c2c.teachbug\n'
```

**Comment by evilhero** [comment]
You should see something in the mylar.log since you got a 200 status code being returned from submitting. It should start with something like :
```[API] Api Call from ComicRN detected - initiating script post-processing.```
followed by some additional post-processing logging lines (with debug enabled of course)

**Comment by mccorkled** [comment]
The log didn't update since grabbing the issue.

**Comment by mccorkled** [comment]
[mylar.log](https://github.com/mylar3/mylar3/files/6288581/mylar.log)

**Comment by evilhero** [comment]
It's saying it can't locate the path: ```/Media/Downloads/Usenet/complete/Comics/the.walking.dead.193.2019.c2c.teachbug```.

If you're running Mylar in a docker you have to remember that you have to enable the ```Are Mylar / SABnzbd on separate machines``` and the ```SABnzbd directory``` option within Mylar and point it to your mapped /downloads location of the Mylar docker.  Mylar can't see anything outside of the docker unless it's in a shared location - ie. you need to map /downloads in Mylar to the same location that you map /downloads to within SAB (or maybe /downloads/comics in Mylar).

**Comment by mccorkled** [comment]
That did the trick! I wouldn't have thought to use that checkbox. Thank you for your time, maybe in the future I can get CDH working properly.
