### ISSUE TITLE
Files pulled down with DDL just sit in the cache directory and never are moved to their destination folder

### ISSUE THREAD

**Issue by aaronmartin1651** [mylar3/mylar3#703]
The cache folder is filled with files which have been pulled down but they are not being moved to their destination directoyr.  Post-Processing is checked and set to "move" and Metadata Tagging is enabled as well.  Cannot determine reason files are not moving.  No other method of download is enabled.

**Comment by evilhero** [comment]
Please follow the issue template - we require a carepackage generated that contains debug logs if at all possible (cause we'll ask for them if it gets to that point) showing a download occuring and the subsequent attempt at post-processing by Mylar.
