### ISSUE TITLE
Files downloading to cache folder but not transferring to destination folder.

### ISSUE THREAD

**Issue by CubeyGlyph** [mylar3/mylar3#704]
**Describe the bug**
Only DDL and Experimental Search checked (not sure what experimental search does)
Cache contains lots of files, jpg, html, cbr, etc.
Only 37.2% of 50Gb HD used
Quality & Post Processing settings:

> Post-Processing
> Enable Post-Processing (not checked = NO post-processing/post-management) - YES
> When Post-Processing - MOVE FILES
> 
> Enable Folder Monitoring - NO
> Run script BEFORE Post-Processing - NO
> Run script AFTER an item has been snatched and sent to client - NO
> Run script AFTER Post-Processing - NO
>
> Metadata Tagging
> ComicTagger is included 
> Enable Metadata Tagging - NO
> Convert CBR to CBZ ONLY - NO
> Write ComicRack (cr) tags (ComicInfo.xml) - YES
> Write ComicBookLover (Cbl) tags (zip comment) - YES
> Overwrite existing cbz tags (if they exist) - NO

**CarePackage**
Attached all but mylar.db 23mb too big
[MylarRunningEnvironment.txt](https://github.com/mylar3/mylar3/files/6288942/MylarRunningEnvironment.txt)
[mylar.log](https://github.com/mylar3/mylar3/files/6288943/mylar.log)
[clean_config.txt](https://github.com/mylar3/mylar3/files/6288946/clean_config.txt)

**Environment (please complete the following information):**
 - OS: Linux, Ubuntu 20.04 Headless
 - Branch / commit: Mylar version master python 3.8.5

**Comment by evilhero** [comment]
Unfortunately the logging is all INFO level, which makes troubleshooting very difficult.  You'll need to get some DEBUG / VERBOSE logging going on.

You should put Mylar into DEBUG / VERBOSE mode first by one of:
- edit the config.ini with Mylar not running (change ```logging_level = 2```).
- start Mylar with the ```-v``` switch
- in the Mylar GUI, go to the ```History``` tab / ```View Logs``` / ```Toggle Verbose Logging ON``

The 1st option is persistent thru shutdowns and reboots, the 2nd option is persistent thru reboots, the 3rd option is not persistent at all (only works for current session).

Once you're in the correct logging mode, perform a search and get it to log completely. Then submit that log so that we can see what's happening.

Note that the cache directory holds alot of stuff. The jpg files are the images on the series detail page (ie. the covers for the series) and are needed for Mylar to display images. The cbr/cbz files are downloads that were downloaded (usually by DDL) and/or attempted conversions of metatagging. The html files are written by Mylar during searching of the DDL site. 

You can 'clean up' the unnecessary files by setting the ```cleanup_cache = True``` in the config.ini.

**Comment by CubeyGlyph** [comment]
I think that this may have been more of an issue with my understanding of the software.  Upon looking at this History tab I can see a history of 
I also check the DDL queue and see several success and fails.  I have used the history log to identify successful post processed files. 
So my issue becomes this.  There are files which exist in the cache folder (cbr) that show snatched that don't appear to move into the post processed phase.  Once in the post process phase, I plan to monitor over the next 24 hours but what is the rate one would expect this to occur?  does it occur alphabetically, order of download etc?  There definitely seems to be some that move over and some that do not.  Perhaps understanding that piece of the mechanics will shed light on whether I actually have a problem or not.  Here are debug logs now.
[mylar.log](https://github.com/mylar3/mylar3/files/6290126/mylar.log)

**Comment by evilhero** [comment]
Firstly turn off Experimental until the next update to the master branch. Experimental throws an error that doesn't kill subsequent searches, but stop searching for that specific issue during the given run. So if you have experimental prioritised in your search order before any other provider, it will appear as if it's not finding anything - when in fact the error stops it all. This has since been fixed in the python3-dev branch, but has yet to merge up as of yet.

When something is snatched via DDL it goes into a dowloading queue based on FIFO. So if something is downloading while other items are being searched for, matched and subsequently indicated that it's being queued - that's what it's doing queueing stuff up. Now if you turn off Mylar (or restart) while Mylar has items queued it will not restart them automatically once you start things back up again. You have to go into the ```Manage``` / ```Manage DDL``` option and click on the Restart Queue option. Or if something is saying its still downloading, but hasn't moved - just restarting the download is usually enough to start things up again. 

Once the download has finished (it says Completed beside it in the ```Manage DDL``` page), Mylar will automatically initiate a post-process call for that specific item. Unless the naming scheme of the file is different than what Mylar expects it to be (sometimes when it uncompress a pack or even a cbz/cbr the names change) the post-process is pretty straightforward and normally does it's thing without an issue. I don't see any post-processing items in your log so odds are it rolled over into one of the other log files, or it rolled right out of them cause of too many logging items.

DDL is based off of GetComics, which doesn't have an API - so we rely on web parsing techniques. They're not always reliable, as the formatting on GC isn't consistent throughout the website, along with sometimes throwing back links that pass off to a 3rd party downloader - if that's the case, Mylar will say it can't download the file as it can't follow the link.

**Comment by CubeyGlyph** [comment]
Attached are the rest of the logs.  I disabled Experimental search, but as I look at several of those marked "snagged" they do not exist in either the cache or the destination directory so there may still be something up, but I am monitoring.

[mylar.log.2.txt](https://github.com/mylar3/mylar3/files/6290584/mylar.log.2.txt)
[mylar.log.3.txt](https://github.com/mylar3/mylar3/files/6290585/mylar.log.3.txt)

**Comment by FrankEBailey** [comment]
I'd like to add here that it's worth checking whether the particular files in the cache aren't already present in your collection. I found a whole bunch of Doctor Fate issues in the cache that turned out to already have been downloaded and post-processed by some other operation (or manually by me) so Mylar just seemed to ignore the files.

Maybe we need an enhancement to remove files from the cache if they're already present in the completed, fully processed downloads folder.

**Comment by FrankEBailey** [comment]
Another issue is **naming**, as Evilhero noted above. I see Mylar struggles to handle naming where the filename includes, for example, **_Generic Hero 06 (of 06).cbr_** and also older releases that have the 'cover to cover' tag **_(C2C)_** where the 2 in the tag seems to throw off the numbering detection. 

Would it be possible to include pre-emptive checks for these two situations?

**Comment by CubeyGlyph** [comment]
> I'd like to add here that it's worth checking whether the particular files in the cache aren't already present in your collection. I found a whole bunch of Doctor Fate issues in the cache that turned out to already have been downloaded and post-processed by some other operation (or manually by me) so Mylar just seemed to ignore the files.
> 
> Maybe we need an enhancement to remove files from the cache if they're already present in the completed, fully processed downloads folder.

In my case all of the ones I checked did not exist in the destination folder at all.

**Comment by CubeyGlyph** [comment]
> Firstly turn off Experimental until the next update to the master branch. Experimental throws an error that doesn't kill subsequent searches, but stop searching for that specific issue during the given run. So if you have experimental prioritised in your search order before any other provider, it will appear as if it's not finding anything - when in fact the error stops it all. This has since been fixed in the python3-dev branch, but has yet to merge up as of yet.
> 
> When something is snatched via DDL it goes into a dowloading queue based on FIFO. So if something is downloading while other items are being searched for, matched and subsequently indicated that it's being queued - that's what it's doing queueing stuff up. Now if you turn off Mylar (or restart) while Mylar has items queued it will not restart them automatically once you start things back up again. You have to go into the `Manage` / `Manage DDL` option and click on the Restart Queue option. Or if something is saying its still downloading, but hasn't moved - just restarting the download is usually enough to start things up again.
> 
> Once the download has finished (it says Completed beside it in the `Manage DDL` page), Mylar will automatically initiate a post-process call for that specific item. Unless the naming scheme of the file is different than what Mylar expects it to be (sometimes when it uncompress a pack or even a cbz/cbr the names change) the post-process is pretty straightforward and normally does it's thing without an issue. I don't see any post-processing items in your log so odds are it rolled over into one of the other log files, or it rolled right out of them cause of too many logging items.
> 
> DDL is based off of GetComics, which doesn't have an API - so we rely on web parsing techniques. They're not always reliable, as the formatting on GC isn't consistent throughout the website, along with sometimes throwing back links that pass off to a 3rd party downloader - if that's the case, Mylar will say it can't download the file as it can't follow the link.

It’s possible that a reboot occurred, I can’t think of why but it would not surprise me based on my activity during this time frame. I will try to restart the queue and see if that resolves the issue and report back.

**Comment by evilhero** [comment]
@FrankEBailey , adding in an option to account for filenames that are already in a downloaded status would be next to impossible, given that items are renamed usually from what they are downloaded as.  Again, if it's an issue with items in the cache not being cleared out, enable the config option to clear items that aren't needed (occurs on every startup only).

As far as the name parsing - Mylar can handle issues with ```6 (of 6)``` just fine, as well as the ```c2c``` within filenames. If they're not matching up to w/e you have - odds are there is another reason as to why it's rejecting it as a match (if you have more than one series on your watchlist with the same name, you'd need to distinguish which is which by including the issue year within the filename, or including the volume label).  Without additional info, all Mylar has to go on is that it's ```Generic Hero``` and it's issue 6 - which if you have 4 volumes named Generic Hero, it needs to have additional information (the ```of 6``` portion isn't used by Mylar as it can be misleading when overall matching).

If you have ```c2c``` in a location where it's inbetween the series title and issue number, which is possible - but honestly, not the best place - Mylar will assume that c2c is part of the series title as sometimes series titles contain abbreviations that are used by downloaders only.

Both of these issues have little to do with the existing issue - so please start a new issue if you wish to continue this discussion (or hop on the discord / irc).

**Comment by aaronmartin1651** [comment]
I have taken quite a bit of time to ensure that everything is configured correctly and I have been monitoring.  I cleaned up some directories cleared a bunch of logs, etc.  Here is the current state of things.  Many files are downloading just fine.  Others appear to say "Snatched" but they are NOT appearing in the cache folder.  The cache folder only contains the .jpg and .html files plus one .json and one .txt file.  I use mlocate to find any file named "batman".  I try to "retry" the download and no change.  This is the last thing I need to figure out as to why isn't working as expected.

**Comment by CubeyGlyph** [comment]
I have taken quite a bit of time to ensure that everything is configured correctly and I have been monitoring. I cleaned up some directories cleared a bunch of logs, etc. Here is the current state of things. Many files are downloading just fine. Others appear to say "Snatched" but they are NOT appearing in the cache folder. The cache folder only contains the .jpg and .html files plus one .json and one .txt file. I use mlocate to find any file named "batman". I try to "retry" the download and no change. This is the last thing I need to figure out as to why isn't working as expected.

**Comment by evilhero** [comment]
Check your logs and attach them to the issue - making sure they're debug level logging and that an issue that is not post-processing is captured in it. 

Snatched means the item was sent to the queue for downloading - whether or not it makes it out of that queue depends on how many items are waiting and/or if something is holding up the queue for some unknown reason. 

There could be many reasons why it's not downloading - DDL has issues with CF, permissions, network problems, bad CV data, etc.

**Comment by CubeyGlyph** [comment]
Based on the logs I see 

> 20-May-2021 12:01:08 - WARNING :: mylar.search.147 : ThreadPoolExecutor-0_0 : [WARNING] Unable to scrape remote site, stopped by a small tank. Error returned as : Unable to find Cloudflare cookies. Does the site actually have Cloudflare IUAM ("I'm Under Attack Mode") enabled?" 

Repeated several times, other than that I see no errors.  Are there any Cloudflare plugins available for Mylar3?

**Comment by evilhero** [comment]
Make sure you're up to date with your version of Mylar. This should be addressed in the most recent branches of mylar3.

**Comment by CubeyGlyph** [comment]
Hmmm, I am showing verison:
 [6f89e83ba15b3ff80031c810c556dc6b4c7cb8dc]
git master

Showing error when I clicked Check for New Versions

**Comment by evilhero** [comment]
That's a month old, you need to update. 

If you installed mylar via git, you probably need to do a ```git reset -hard origin/master```, followed by a ```git pull```. 

You should then be able to do a update via the built in updater within Mylar if required.

**Comment by CubeyGlyph** [comment]
Updated to:
` [9ec6b1c7a5400c27d446337636cfa5fb61e9de19]`
git master
Will see if that fixes it.

**Comment by evilhero** [comment]
Stale at this point, as it's been a year+. Assuming all the changes over the past year fixed the problem.

Closing, if it's still an issue please create a new issue with the relevant information and a carepackage.
