### ISSUE TITLE
DDL issue: not downloading TPB when it is available on Getcomics

### ISSUE THREAD

**Issue by devilsangel360live** [mylar3/mylar3#712]
**Describe the bug**
Added a TPB "Lumberjanes: Stone Cold (2018)" and I found this issue available on Getcomics. However, Mylar3 was unable to download

2021-04-13 20:03:45 | INFO | There are 0 results
-- | -- | --
2021-04-13 20:03:44 | DEBUG | [DDL-QUERY] Query set to: "Lumberjanes Stone Cold #1 (2018)"
2021-04-13 20:03:44 | DEBUG | Sending request to DDL site for : Lumberjanes Stone Cold 1
2021-04-13 20:03:44 | DEBUG | findloop: 0 / findcount: 1
2021-04-13 20:03:44 | INFO | Shhh be very quiet...I'm looking for Lumberjanes Stone Cold issue: 1 (2018) using DDL.

**CarePackage**
[carepackage.zip](https://github.com/mylar3/mylar3/files/6306429/carepackage.zip)

**Environment (please complete the following information):**
 - OS: OpenMediaVault 5/ Debian
 - Branch / commit: master [v0.5.0]

**Additional information**
Add any other information about the problem here.

**Comment by evilhero** [comment]
The problem is that GC has it listed as ```Lumberjanes Vol. 8 – Stone Cold (TPB) (2018)``` which is vastly different than what it's actually looking for. So that's what the ```Alternate Search Name``` option is used for - set it to ```Lumberjanes Vol. 8 - Stone Cold``` in order to search for that particular issue.

The other problem is that it's assuming a ```#1``` issue, as that's what CV has denoted - but there is no numeric issue numbering due to it being a TPB. I'll have to adjust the query paramters to account for that aspect - but the naming matching aspect is done  by using the above method.

**Comment by devilsangel360live** [comment]
Thanks @evilhero - I had experimented with the alternate search name, but guessed this would be because of the numeric suffix being added. Will look forward to another awesome update. Will need to check how I can update my docker stack with the dev branch. 
A great feature would be if we could auto download from those mega packs that GC, something like Lumberjanes Vol 1 - 7, and so on

**Comment by jakem742** [comment]
This still seems to be an issue? I'm trying to get TPB's from GetComics but the Mylar3 queries all include the issue number ("1") in every search term. My comic: [GetComics](https://getcomics.info/marvel/star-wars-vol-4-shattered-hope-marvel-edition/). I 

Would it be difficult to implement a check for TPB's where if there is only a single issue, an additional search is appended to the end which excludes any sort of issue numbering? ie. In my case, an additional search for "Star Wars A Shattered Hope" would find my TPB. 

Logically, if there is only a single issue in any comic series I would think it would make sense to exclude issue numbers, however I am quite new to comics in general and realise that these naming schemes aren't always dictated by logic aha.

```
05-Jan-2022 16:13:30 - INFO :: mylar.NZB_SEARCH.824 : SEARCH-QUEUE : Shhh be very quiet...I'm looking for Star Wars A Shattered Hope issue: 1 (2014) using DDL.

05-Jan-2022 16:13:30 - DEBUG :: mylar.NZB_SEARCH.884 : SEARCH-QUEUE : findloop: 0 / findcount: 1

05-Jan-2022 16:13:30 - DEBUG :: mylar.NZB_SEARCH.935 : SEARCH-QUEUE : Sending request to DDL site for : Star Wars A Shattered Hope 1

05-Jan-2022 16:13:31 - DEBUG :: mylar.search.96 : SEARCH-QUEUE : [DDL-QUERY] Query set to: "Star Wars A Shattered Hope #1 (2014)"

05-Jan-2022 16:13:31 - INFO :: mylar.search_results.228 : SEARCH-QUEUE : There are 0 results

05-Jan-2022 16:13:33 - DEBUG :: mylar.search.96 : SEARCH-QUEUE : [DDL-QUERY] Query set to: Star Wars A Shattered Hope #1 (2014)

05-Jan-2022 16:13:34 - INFO :: mylar.search_results.228 : SEARCH-QUEUE : There are 0 results

05-Jan-2022 16:13:36 - DEBUG :: mylar.search.96 : SEARCH-QUEUE : [DDL-QUERY] Query set to: Star Wars A Shattered Hope #1

05-Jan-2022 16:13:36 - INFO :: mylar.search_results.228 : SEARCH-QUEUE : There are 0 results

05-Jan-2022 16:13:38 - DEBUG :: mylar.search.96 : SEARCH-QUEUE : [DDL-QUERY] Query set to: Star Wars A Shattered Hope 1
05-Jan-2022 16:13:39 - INFO :: mylar.search_results.228 : SEARCH-QUEUE : There are 0 results 
```

**Comment by evilhero** [comment]
@jakem742 please don't comment on  issues that have been closed for almost a year and expect any kind of relevant answer. 

If you're having a problem , create a new issue with the details therein as asked for by the issue template.

**Comment by jakem742** [comment]
My apologies. :) I figured appending it to an existing problem was better but I'll create a new one.
