### ISSUE TITLE
Mass Renaming

### ISSUE THREAD

**Issue by mccorkled** [mylar3/mylar3#714]
I know that I can bulk rename within each comic, but what about renaming all comics of every series? I’ve been trying to figure out the best way to name my comics and I have been back and forth with naming schemes. I would love to not have to go into 200+ series to click “rename”. 

Also, is it possible to have Vol.# instead of v# for different volumes?

Thank you.

**Comment by burnshroom** [comment]
Under Manage, select Manage Comics.

From there select any title(s) and the choose "Rename Series" from the drop down.

**Comment by mccorkled** [comment]
Thank you. What about for naming volumes differently?

**Comment by evilhero** [comment]
At the moment, you can't deviate from the v# due to consistency more so than anything else. Adding in different format allowances for volume types means that the file parser has to be able to read them properly too, which is the most problematic part of the entire process.

**Comment by mccorkled** [comment]
Just spitballing here, would it be possible to have it do something like this:

If v2 then Vol. 2?

**Comment by evilhero** [comment]
Unfortunately it's not a simple task as that, however there are some upcoming items in development that might be able to accomplish what it is that you're trying to do.
