### ISSUE TITLE
Validating archives before import

### ISSUE THREAD

**Issue by qubidt** [mylar3/mylar3#716]
**Describe the request**
An option that makes mylar test the integrity of archive files (`cbz`/`cbr`) prior to import. Both python's `zipfile` and the vendored `rarfile` packages provide `testzip`/`testrar` to validate the archive contents against their CRCs. The feature would turn on a step that runs the test prior to import and fails comics that are corrupted.

**How did you come up with the idea?**
I occasionally run into files that are corrupted, especially during mass imports where I don't manually check the file first. So far I've caught these by running a `find ./comics -name '*.cbz' -exec unzip -t {} \;` job on my batch directory, but it would be nice to provide this check. 

**Environment (please complete the following information):**
 - OS: this should be platform agnostic, AFAIK
 - Branch / commit: n/a

**Additional information**
Should probably be optional (and disabled by default?) because it substantially increases disk usage/import time as a full file read needs to happen for each import, even when moving/linking the files.

I am happy to work on this feature, provided a PR implementing it would be approved. 🙂

**Comment by evilhero** [comment]
If Mylar can't open the archive during an import, it will return that it's an invalid archive type - which is pretty much what that bash statement does. 

I don't think adding in that aspect would add anything different to what's already in Mylar since it has to open the archive to read the metadata contents during an import if you have that option enabled. 

Now if you don't have metatagging enabled, then it wouldn't try to open the archive (as it just goes by filename parsing then), and you'd get bitten by the invalid bug you're discussing (I'm guessing). 

The import process as a whole is a glaring mess of poop. A rewrite is in process but its a long tedious process as importing based on filenames is a general nightmare. Add to that the different naming conventions, tagging aspects and general mess of comicvine when matching - it becomes more of a mess. 

On a positive however, the rewrite is about 75% done, and has stayed at that stage for a while unfortunately due to time constraints and other hugs needing attention, but I did it so that it will write out the invalid files during a scan so users can take notice of said items as opposed to having to scan thru logs.

**Comment by qubidt** [comment]
tyvm for the explanation. I definitely don't want to step on any toes so I can table this request, esp since this is just a validation step that I can work around manually. I'll wait for the rewrite before suggesting or trying to make any changes to the importer

**Comment by qubidt** [comment]
> I don't think adding in that aspect would add anything different to what's already in Mylar since it has to open the archive to read the metadata contents during an import if you have that option enabled.

Wanted to add that although I haven't reviewed specifically what Mylar does, I don't believe this is accurate. Although this is true for cases where the file is incomplete, there are cases where the archive structure is complete enough to get the full filelist, but the actual files fail the crc check (you won't see this until you do a full decompress, which is what the test methods do). 

for a random example I have on hand, listing archive contents works fine:


```
$ unzip -v "./Justice League of America 035 (2009) (Digital) (Shadowcat-Empire).cbz"
Archive:  ./Justice League of America 035 (2009) (Digital) (Shadowcat-Empire).cbz
 Length   Method    Size  Cmpr    Date    Time   CRC-32   Name
--------  ------  ------- ---- ---------- ----- --------  ----
       0  Stored        0   0% 2018-02-10 21:46 00000000  Justice League of America 035 (2009) (Digital) (Shadowcat-Empire)/
 1565207  Defl:X  1553710   1% 2018-02-10 09:15 59017eaa  Justice League of America 035 (2009) (Digital) (Shadowcat-Empire)/Justice League of America (2006-2011) 035-000.jpg
 1804831  Defl:X  1772133   2% 2018-02-10 09:15 bb011f87  Justice League of America 035 (2009) (Digital) (Shadowcat-Empire)/Justice League of America (2006-2011) 035-001.jpg
 1770597  Defl:X  1752761   1% 2018-02-10 09:15 d7410f50  Justice League of America 035 (2009) (Digital) (Shadowcat-Empire)/Justice League of America (2006-2011) 035-002.jpg
 1864993  Defl:X  1854754   1% 2018-02-10 09:15 91045053  Justice League of America 035 (2009) (Digital) (Shadowcat-Empire)/Justice League of America (2006-2011) 035-003.jpg
 1869339  Defl:X  1857574   1% 2018-02-10 09:15 ab008815  Justice League of America 035 (2009) (Digital) (Shadowcat-Empire)/Justice League of America (2006-2011) 035-004.jpg
 1893330  Defl:X  1881372   1% 2018-02-10 09:15 5d77caad  Justice League of America 035 (2009) (Digital) (Shadowcat-Empire)/Justice League of America (2006-2011) 035-005.jpg
 1468683  Defl:X  1447914   1% 2018-02-10 09:15 fa98669d  Justice League of America 035 (2009) (Digital) (Shadowcat-Empire)/Justice League of America (2006-2011) 035-006.jpg
 1347774  Defl:X  1326546   2% 2018-02-10 09:15 0a7d251d  Justice League of America 035 (2009) (Digital) (Shadowcat-Empire)/Justice League of America (2006-2011) 035-007.jpg
 1298036  Defl:X  1277977   2% 2018-02-10 09:15 2bb0d6d9  Justice League of America 035 (2009) (Digital) (Shadowcat-Empire)/Justice League of America (2006-2011) 035-008.jpg
 1706644  Defl:X  1685932   1% 2018-02-10 09:15 7ff148fd  Justice League of America 035 (2009) (Digital) (Shadowcat-Empire)/Justice League of America (2006-2011) 035-009.jpg
 1671268  Defl:X  1657700   1% 2018-02-10 09:15 f56af304  Justice League of America 035 (2009) (Digital) (Shadowcat-Empire)/Justice League of America (2006-2011) 035-010.jpg
 1445554  Defl:X  1431552   1% 2018-02-10 09:15 e605e2ca  Justice League of America 035 (2009) (Digital) (Shadowcat-Empire)/Justice League of America (2006-2011) 035-011.jpg
 1858265  Defl:X  1842327   1% 2018-02-10 09:15 84c33843  Justice League of America 035 (2009) (Digital) (Shadowcat-Empire)/Justice League of America (2006-2011) 035-012.jpg
 1822969  Defl:X  1807310   1% 2018-02-10 09:15 2cbbe996  Justice League of America 035 (2009) (Digital) (Shadowcat-Empire)/Justice League of America (2006-2011) 035-013.jpg
 1631068  Defl:X  1622060   1% 2018-02-10 09:15 87796a25  Justice League of America 035 (2009) (Digital) (Shadowcat-Empire)/Justice League of America (2006-2011) 035-014.jpg
 1581056  Defl:X  1567214   1% 2018-02-10 09:15 3d203101  Justice League of America 035 (2009) (Digital) (Shadowcat-Empire)/Justice League of America (2006-2011) 035-015.jpg
 1849298  Defl:X  1833429   1% 2018-02-10 09:15 79108eb5  Justice League of America 035 (2009) (Digital) (Shadowcat-Empire)/Justice League of America (2006-2011) 035-016.jpg
 1870549  Defl:X  1856467   1% 2018-02-10 09:15 e0cd9def  Justice League of America 035 (2009) (Digital) (Shadowcat-Empire)/Justice League of America (2006-2011) 035-017.jpg
 2121604  Defl:X  2105820   1% 2018-02-10 09:15 a2f60b80  Justice League of America 035 (2009) (Digital) (Shadowcat-Empire)/Justice League of America (2006-2011) 035-018.jpg
 1860296  Defl:X  1849252   1% 2018-02-10 09:15 f774d53a  Justice League of America 035 (2009) (Digital) (Shadowcat-Empire)/Justice League of America (2006-2011) 035-019.jpg
 1509003  Defl:X  1493253   1% 2018-02-10 09:15 7134548b  Justice League of America 035 (2009) (Digital) (Shadowcat-Empire)/Justice League of America (2006-2011) 035-020.jpg
 1428602  Defl:X  1412341   1% 2018-02-10 09:15 6f4dbb68  Justice League of America 035 (2009) (Digital) (Shadowcat-Empire)/Justice League of America (2006-2011) 035-021.jpg
 1679397  Defl:X  1665707   1% 2018-02-10 09:15 a0277cf6  Justice League of America 035 (2009) (Digital) (Shadowcat-Empire)/Justice League of America (2006-2011) 035-022.jpg
 1209606  Defl:X  1178009   3% 2018-02-10 09:15 65c39eef  Justice League of America 035 (2009) (Digital) (Shadowcat-Empire)/Justice League of America (2006-2011) 035-023.jpg
  340669  Defl:X   338402   1% 2018-01-16 00:10 510b92a8  Justice League of America 035 (2009) (Digital) (Shadowcat-Empire)/zzzzshadowcat002.jpg
--------          -------  ---                            -------
40468638         40071516   1%                            26 files
```

but performing the test reveals the invalid file:

```
$ unzip -t "./Justice League of America 035 (2009) (Digital) (Shadowcat-Empire).cbz"
Archive:  ./Justice League of America 035 (2009) (Digital) (Shadowcat-Empire).cbz
    testing: Justice League of America 035 (2009) (Digital) (Shadowcat-Empire)/   OK
    testing: Justice League of America 035 (2009) (Digital) (Shadowcat-Empire)/Justice League of America (2006-2011) 035-000.jpg   OK
    testing: Justice League of America 035 (2009) (Digital) (Shadowcat-Empire)/Justice League of America (2006-2011) 035-001.jpg   OK
    testing: Justice League of America 035 (2009) (Digital) (Shadowcat-Empire)/Justice League of America (2006-2011) 035-002.jpg   OK
    testing: Justice League of America 035 (2009) (Digital) (Shadowcat-Empire)/Justice League of America (2006-2011) 035-003.jpg   OK
    testing: Justice League of America 035 (2009) (Digital) (Shadowcat-Empire)/Justice League of America (2006-2011) 035-004.jpg   OK
    testing: Justice League of America 035 (2009) (Digital) (Shadowcat-Empire)/Justice League of America (2006-2011) 035-005.jpg   bad CRC 5c5fa017  (should be 5d77caad)
    testing: Justice League of America 035 (2009) (Digital) (Shadowcat-Empire)/Justice League of America (2006-2011) 035-006.jpg   OK
    testing: Justice League of America 035 (2009) (Digital) (Shadowcat-Empire)/Justice League of America (2006-2011) 035-007.jpg   OK
    testing: Justice League of America 035 (2009) (Digital) (Shadowcat-Empire)/Justice League of America (2006-2011) 035-008.jpg   OK
    testing: Justice League of America 035 (2009) (Digital) (Shadowcat-Empire)/Justice League of America (2006-2011) 035-009.jpg   OK
    testing: Justice League of America 035 (2009) (Digital) (Shadowcat-Empire)/Justice League of America (2006-2011) 035-010.jpg   OK
    testing: Justice League of America 035 (2009) (Digital) (Shadowcat-Empire)/Justice League of America (2006-2011) 035-011.jpg   OK
    testing: Justice League of America 035 (2009) (Digital) (Shadowcat-Empire)/Justice League of America (2006-2011) 035-012.jpg   OK
    testing: Justice League of America 035 (2009) (Digital) (Shadowcat-Empire)/Justice League of America (2006-2011) 035-013.jpg   OK
    testing: Justice League of America 035 (2009) (Digital) (Shadowcat-Empire)/Justice League of America (2006-2011) 035-014.jpg   OK
    testing: Justice League of America 035 (2009) (Digital) (Shadowcat-Empire)/Justice League of America (2006-2011) 035-015.jpg   OK
    testing: Justice League of America 035 (2009) (Digital) (Shadowcat-Empire)/Justice League of America (2006-2011) 035-016.jpg   OK
    testing: Justice League of America 035 (2009) (Digital) (Shadowcat-Empire)/Justice League of America (2006-2011) 035-017.jpg   OK
    testing: Justice League of America 035 (2009) (Digital) (Shadowcat-Empire)/Justice League of America (2006-2011) 035-018.jpg   OK
    testing: Justice League of America 035 (2009) (Digital) (Shadowcat-Empire)/Justice League of America (2006-2011) 035-019.jpg   OK
    testing: Justice League of America 035 (2009) (Digital) (Shadowcat-Empire)/Justice League of America (2006-2011) 035-020.jpg   OK
    testing: Justice League of America 035 (2009) (Digital) (Shadowcat-Empire)/Justice League of America (2006-2011) 035-021.jpg   OK
    testing: Justice League of America 035 (2009) (Digital) (Shadowcat-Empire)/Justice League of America (2006-2011) 035-022.jpg   OK
    testing: Justice League of America 035 (2009) (Digital) (Shadowcat-Empire)/Justice League of America (2006-2011) 035-023.jpg   OK
    testing: Justice League of America 035 (2009) (Digital) (Shadowcat-Empire)/zzzzshadowcat002.jpg   OK
At least one error was detected in ./Justice League of America 035 (2009) (Digital) (Shadowcat-Empire).cbz.
```

**Comment by evilhero** [comment]
You're correct in the check not working unless it's decompressed wih regards to Mylar. However, I guess what I was eluding to was that during post-processing of a file with metatagging enabled, Mylar has to uncompress the contents of the file in order to recreate the zip archive - so in those particular instances it would get flagged as an invalid crc (which Mylar does report it as) when it tries to either unzip/unrar or recreate the zip itself.

During the current iteration of the importer however, it does read in the contents of each file within the zip - but only up until it reaches the comicinfo.xml file (which, if it's first, then it doesn't hit anything else). 

Now the next iteration of the import will use the same in-memory image extractor that's currently in place for when specific issues are viewed via the ```i``` icon on the series detail page, as well as when notifs are sent out with the cover option enabled. The iterator reads into memory each file within the compressed archive, but doesn't wirte it out - it keeps it in memory, which I believe if a crc is invalid in that it will return it as such and, as an example, the ```i``` will respond accordingly with an error saying it can't display the image properly (I'm not 100% sure on this as I can't remember all the testing that was done on that particular method). 

Easy way to test it out, if you have a file with a crc error, add the series into Mylar - place the corrupt file in the given series directory, and then hit Recheck Files to scan it. Once it's in a Downloaded status, you'll see a blue ```i``` icon, clicking on that will run the image iterator/extractor and you'll see if it's something that we need to address in some other method (I don't have any corrupt ones atm to test, so thus my asking).

**Comment by qubidt** [comment]
Thanks for the clarification, that clears up a lot. I followed your suggestionusing the info dialog with the file I mentioned in my previous reply, and this is what I see after adding the corrupt file to the series:

![image](https://user-images.githubusercontent.com/6306455/114970534-405f1200-9e40-11eb-8d05-a750ca7471e7.png)

unfortunately, no errors from what I can tell. I assume this is probably because there's no `comicinfo.xml` so it doesn't attempt to decompress anything. I also don't use metatagging, I like to stick to non destructive operations w/ my media management, for things like torrent or handling duplication-detection/de-duplication at the filesystem level. 

I also don't have a lot of corrupt files to test against since I usually delete any I run across, but I'll start saving them for future testing when I run across some.
