### ISSUE TITLE
Searching for comics with acronym names does not return expected results

### ISSUE THREAD

**Issue by qubidt** [mylar3/mylar3#717]
**Describe the bug**
Searching for series with names that are acronyms (e.g. [S.H.I.E.L.D.](https://comicvine.gamespot.com/shield/4050-32430/) or [R.E.B.E.L.S.](https://comicvine.gamespot.com/rebels/4050-25833/)) doesn't return the expected series. For example, searching for `R.E.B.E.L.S.` results in 1000 (the max?) results, none of which are [R.E.B.E.L.S. vol 2 (2009)](https://comicvine.gamespot.com/rebels/4050-25833/) or any other R.E.B.E.L.S. comic.

I'm not sure how search queries are parsed, but this case should either be handled or a feature should be provided to allow the user to add specific comicvine volumes (e.g. query parsing such that `comicvine:25833` queries are supported and return a specific series).

**CarePackage**
n/a

**Environment (please complete the following information):**
 - OS: Linux
 - Branch / commit: Release (master/v0.5.0)

**Additional information**
I haven't looked at the search code at all but I'd be happy to work on this issue. Just wanted to get a sanity check first.

**Comment by evilhero** [comment]
It's a limitation of the CV API which is a general nightmare to use with generalized search queries. I believe spaces are denoted as OR not AND, or used to be that way at least and they've changed it numerous times as well without notice. 

However, you can add a series by:
 - enclosing the search term in double quotation marks for an exact match query. 
- enter in the comicid of the series into the search box in the format of 4050-XXXXXX (where XXXXXX is the actual comicid from CV).

**Comment by qubidt** [comment]
ah terrific, thank you for the tips, the comic ID one in particular. I tried searching by comicid but not with the `4050-` prefix. 

> you can search for a series by enclosing the search term in double quotation marks for an exact match query

just to be clear, you are referring to the 'filter' search box on the results page, right? so if there are missing results from hitting the 1000 results limit, it would still be missing, yeah? 

OTOH, quotation marks don't seem to have an effect on the actual CV results.
