### ISSUE TITLE
[Errno 1] Operation not permitted

### ISSUE THREAD

**Issue by mccorkled** [mylar3/mylar3#727]
**Describe the bug**
When running a manual metatagging I get error `[Errno 1] Operation not permitted:`

**CarePackage**
[carepackage.zip](https://github.com/mylar3/mylar3/files/6343906/carepackage.zip)

**Environment (please complete the following information):**
 - OS: Docker
 - Version: v0.5.0

Mylar wouldn't import some comics. I thought there was an issue with the file name so I changed it to what it would be post processing and it still wouldn't process them. I manually moved the comic to the finished directory and rescanned the directory. The comic shows in Mylar now as `Downloaded` but when I run manual matatagging I get the error....
`[ERROR @ path: /Comics/Daredevil (1964)] [Errno 1] Operation not permitted: '/Comics/Daredevil (1964)/Daredevil #239 (1987).cbz'. Exiting...`

**Comment by evilhero** [comment]
The user running mylar doesn't have permissions to write to that directory. You need to make sure the user is mapped correctly

**Comment by mccorkled** [comment]
It's only happening for some of the books.

**Comment by evilhero** [comment]
It's a permissions issue - the error being thrown back is from the OS, no Mylar itself.  You're running docker so you have to make sure you have  the correct paths mounted with the correct id's and such.

**Comment by mccorkled** [comment]
I have my GUID and PUID set within the Docker. The user has permissions to R/W to the comics folder. I also set the GUID and PUID within the Mylar GUI. I'm not sure how to troubleshoot this. I don't think post processing and moving comics would be working if the permissions were borked.

**Comment by evilhero** [comment]
Try turning off enforce permissions within Mylar. It's possible that there's something in your setup that's confusing the issue between the id's and it can't perform the enforcement routine. Its still some kind of docker mounting issue, but turning off the enforce option won't force Mylar to keep on trying to change permissions if it can't. 

Are you sure it's ```/Comics``` and not ```/comics```?

**Comment by mccorkled** [comment]
Turning off force permission fixed the issue. Thank you.

**Comment by mccorkled** [comment]
Can you explain this? The log says completed then it says it didn't tag it.


```
2021-04-20 22:23:42 | WARNING | [MANUAL  META-TAGGING] [/Comics/The Avengers (1963)/The Avengers #174  (1978).cbz] Unable to complete metatagging : [Errno 1] Operation not  permitted: '/Comics/The Avengers (1963)/The Avengers #174 (1978).cbz'  [1]
-- | -- | --
2021-04-20 22:23:42 | INFO | [META-TAGGER][COMIC-TAGGER]  Successfully wrote ComicRack tagging  [/config/mylar/cache/mylar_jiz042xd/The Avengers #174 (1978).cbz]
2021-04-20 22:23:42 | INFO | None
2021-04-20 22:23:42 | INFO | b'Save complete.\n\nSuccessful matches:\n------------------\n/config/mylar/cache/mylar_jiz042xd/The Avengers #174 (1978).cbz\n'
```

**Comment by evilhero** [comment]
Permission issue still from the looks of it. It competed the operation but it wasn't successful. 

It tagged it ok, but then it couldn't move the file back into the series location from the cache (where it copies items to metatag it). Related to the previous errors saying the same error which revolved around the Mylar user not being able to access the /Comics mount

**Comment by mccorkled** [comment]
So I took a look at the Enforce Permissions settings again and noticed that they were set to 0777 and 0660. They were set to this when I installed the program. I have changed them to 777 and 660 and that seems to have solved the issue.

**Comment by mccorkled** [comment]
Nope, that didn't work either. It seems to be tagging them when moving from my completed download folder, but if I manually run a metatagging on them from the /Comics directory it fails.

**Comment by evilhero** [comment]
What are the permissions of the /Comics directory - and one of the series sub-directories that is being written to?
What are the permissions of the file if it's present therein ?
Is the Enforce Permissions still off ? (if you're changing the perms values with Mylar, then you have them enabled as the option is hidden otherwise).

This is still a permissions issue that's localised to your system - unfortunately we're not getting enough information as to what the system setup is - maybe post your docker-compose while you're at it ?

**Comment by mccorkled** [comment]
I've been messing around with this a bit more and I think I tracked down the issue. The temp folders in the cache directory were being made but when the metatagging failed, the folders were not being deleted. I believe that when I ran manual metatagging it was failing because hundreds of temp folders already existed. I deleted all of the folders in the cache directory and re-ran manual metatagging. It seems to be going okay now, but I've thought that multiple times over the last few days. I'll report back

**Comment by mccorkled** [comment]
the cleanup_cache setting keeps defaulting to False after every restart. Is that normal?

**Comment by evilhero** [comment]
No, it's not normal. 

It could mean that your ini file is either open while Mylar is running (did you shutdown Mylar prior to editing the file?), and thereby locking the file so it can't be updated. Or that the the user running mylar doesn't have the right permissions to be able to save the config file.

**Comment by mccorkled** [comment]
Just updated to Version: v0.5.0 ( master)  and I am having a problem with post processing again. 

`


2021-05-26 22:29:53 | WARNING | [META-TAGGER] Unable to create temporary directory to perform meta-tagging. Processing without metatagging.
-- | -- | --
2021-05-26 22:29:53 | WARNING | [META-TAGGER] Unexpected Error:  [[Errno 2] No such file or directory: '/config/mylar/cache/mylar_fak1hbjt/The New Teen Titans v2 #16 (1986).cbz']



`

**Comment by evilhero** [comment]
Since this issue was closed almost a month ago, and you're 3 versions behind in updating (v0.5.3 is the latest) - odds are that it's still a permissions issue of some kind (as per the error) that either reverted or was never truly resolved. 

If this is still an issue after verifying permissions and that the settings are correct for Enforce Permissions (not enabled), please create a new issue with the required information and include a carepackage with debug logging. 

Closing this as this is a stale issue due to the versioning.
