### ISSUE TITLE
unable to init? 

### ISSUE THREAD

**Issue by mgaulton** [mylar3/mylar3#731]
**Describe the bug**
Unable to start the app as it cannot connect to database, complaining about number of parameters.

**CarePackage**
unable to retrieve, gui won't start 
Can i switch to debug from command line?

Initializing startup sequence....
22-Apr-2021 19:36:12 - ERROR :: mylar.initialize.204 : MainThread : Cannot connect to the database: not enough values to unpack (expected 2, got 1)
22-Apr-2021 19:36:13 - ERROR :: mylar.excepthook.315 : MAIN : Uncaught exception: Traceback (most recent call last):
  File "Mylar.py", line 386, in <module>
    main()
  File "Mylar.py", line 353, in main
    versioncheck.versionload()
  File "/opt/mylar/mylar-master/mylar/versioncheck.py", line 372, in versionload
    version_info = getVersion()
  File "/opt/mylar/mylar-master/mylar/versioncheck.py", line 114, in getVersion
    if git[0]['name'] is not None:
KeyError: 0

Traceback (most recent call last):
  File "Mylar.py", line 386, in <module>
    main()
  File "Mylar.py", line 353, in main
    versioncheck.versionload()
  File "/opt/mylar/mylar-master/mylar/versioncheck.py", line 372, in versionload
    version_info = getVersion()
  File "/opt/mylar/mylar-master/mylar/versioncheck.py", line 114, in getVersion
    if git[0]['name'] is not None:
KeyError: 0

**Environment (please complete the following information):**
 - OS: opensuse tumbleweed
 - Branch / commit: up to date master on mylar3 repo

**Additional information**
Add any other information about the problem here.

**Comment by evilhero** [comment]
Is it a git install, or source file, or docker?

Try starting Mylar with the ```-v``` switch to get it log verbose.

Can you attach or link to your mylar.db file so that we can try to reproduce the error on our side?

**Comment by mgaulton** [comment]
git install ,using a separate data folder.
python3 Mylar.py  --nolaunch --pidfile=/var/run/mylar/mylar.pid --datadir=/opt/MYconfig
grabbing the db now

```
server6:/opt/mylar/mylar-master # python3 Mylar.py -v  --nolaunch --pidfile=/var/run/mylar/mylar.pid --datadir=/opt/MYconfig
log language set to en_US
Verbose/Debugging mode enabled...
Not running in daemon mode. PID file creation disabled.
Initializing startup sequence....
Logging level in config over-ridden by startup value. Logging level set to : 2
22-Apr-2021 20:39:14 - DEBUG :: mylar.provider_sequence.1296 : MainThread : Original provider_order sequence: 0, Experimental, 1, DDL, 2, nzbgeek, 3, jackett
22-Apr-2021 20:39:14 - DEBUG :: mylar.provider_sequence.1299 : MainThread : Provider sequence already pre-exists. Re-loading and adding/remove any new entries
22-Apr-2021 20:39:14 - DEBUG :: mylar.provider_sequence.1381 : MainThread : Provider Order is now set : {'0': 'Experimental', '1': 'DDL', '2': 'nzbgeek', '3': 'jackett'}
22-Apr-2021 20:39:14 - DEBUG :: mylar.configure.918 : MainThread : Log dir: /tmp/mylar
22-Apr-2021 20:39:14 - INFO :: mylar.configure.1034 : MainThread : Ignored Publishers: []
22-Apr-2021 20:39:14 - INFO :: mylar.configure.1057 : MainThread : [MASS_PUBLISHERS] Auto-add for weekly publishers set to: []
22-Apr-2021 20:39:14 - INFO :: mylar.configure.1061 : MainThread : [COMICTAGGER] Version detected: 1.3.4
22-Apr-2021 20:39:14 - DEBUG :: mylar.configure.1100 : MainThread : [COMICTAGGER] Setting ComicTagger settings default path to : /home/vpnuser/.ComicTagger
22-Apr-2021 20:39:14 - INFO :: mylar.configure.1126 : MainThread : Setting DDL Location set to : /opt/mylar/mylar-master/cache/
22-Apr-2021 20:39:14 - INFO :: mylar.initialize.200 : MainThread : Checking to see if the database has all tables....
22-Apr-2021 20:39:14 - ERROR :: mylar.initialize.204 : MainThread : Cannot connect to the database: not enough values to unpack (expected 2, got 1)
22-Apr-2021 20:39:14 - INFO :: mylar.initialize.214 : MainThread : Successfully discovered local IP and locking it in as : 192.168.2.5
22-Apr-2021 20:39:14 - DEBUG :: mylar.initialize.226 : MainThread : Logger set to use : Rotational Log Handler (default)
22-Apr-2021 20:39:14 - DEBUG :: mylar.initialize.259 : MainThread : SEARCH_TIER_DATE set to : 2021-04-08
22-Apr-2021 20:39:14 - INFO :: mylar.initialize.281 : MainThread : [IMPRINT_LOADS] Loading Publisher imprints data from local file.
22-Apr-2021 20:39:14 - INFO :: mylar.initialize.307 : MainThread : [IMPRINT_LOADS] Successfully loaded imprints for 6 publishers
22-Apr-2021 20:39:14 - INFO :: mylar.initialize.314 : MainThread : Remapping the sorting to allow for new additions.
22-Apr-2021 20:39:15 - INFO :: mylar.ComicSort.752 : MainThread : Sucessfully ordered 1345 series in your watchlist.
22-Apr-2021 20:39:15 - INFO :: mylar.validateAndCreateDirectory.1723 : MainThread : [DIRECTORY-CHECK] Found comic directory: /opt/MYconfig
22-Apr-2021 20:39:15 - DEBUG :: mylar.runGit.44 : MAIN : Trying to execute: /usr/bin/git describe --exact-match --tags 2> /dev/null && git rev-parse HEAD --abbrev-ref HEAD with shell in /opt/mylar/mylar-master
22-Apr-2021 20:39:15 - DEBUG :: mylar.runGit.46 : MAIN : Git output: CompletedProcess(args='/usr/bin/git describe --exact-match --tags 2> /dev/null && git rev-parse HEAD --abbrev-ref HEAD', returncode=0, stdout='v0.5.1\n6f89e83ba15b3ff80031c810c556dc6b4c7cb8dc\nmaster\n', stderr='')
22-Apr-2021 20:39:16 - ERROR :: mylar.excepthook.315 : MAIN : Uncaught exception: Traceback (most recent call last):
  File "Mylar.py", line 386, in <module>
    main()
  File "Mylar.py", line 353, in main
    versioncheck.versionload()
  File "/opt/mylar/mylar-master/mylar/versioncheck.py", line 372, in versionload
    version_info = getVersion()
  File "/opt/mylar/mylar-master/mylar/versioncheck.py", line 114, in getVersion
    if git[0]['name'] is not None:
KeyError: 0

Traceback (most recent call last):
  File "Mylar.py", line 386, in <module>
    main()
  File "Mylar.py", line 353, in main
    versioncheck.versionload()
  File "/opt/mylar/mylar-master/mylar/versioncheck.py", line 372, in versionload
    version_info = getVersion()
  File "/opt/mylar/mylar-master/mylar/versioncheck.py", line 114, in getVersion
    if git[0]['name'] is not None:
KeyError: 0

```

**Comment by mgaulton** [comment]
[mylar.zip](https://github.com/mylar3/mylar3/files/6361970/mylar.zip)

**Comment by evilhero** [comment]
See that usually happens when git isn't responding or you're requesting too fast (ie. you restarted it several times rapidly in succession) - it looks like a temporary kind of block.

Have you tried just doing a ```git pull`` from within the root of the repo directory and see if that works?

The db error is one thing (need to see the db file to see what's wrong), but the git error is something different which might be due to what I've just mentioned above.

**Comment by mgaulton** [comment]
The first thing I did was going into the report and do a git pull. No messages other than already up to date.
I was expecting mismatches or something and could nuke and rebuild it. Easy enough keeping the config seperate.

**Comment by evilhero** [comment]
Well the git errors is due to the db not connecting - it would fail, retry and just keep on attempting to check github so you would hit the threshold and be temporarily locked out from hitting the github api (it's free for anonymous, but rate-limited). That clears out usually within the hour at most - usually 20 minutes I think.

So in looking at your db, it looks like the last_date field is throwing the error for some reason, which I can't really figure out why atm. I can see kind of what it's doing and what happened, I'm just not sure of a solution that works going forward, or if this is just one of those weird things that happened.

So the easy way to just get past that error and continue is to go into the mylar.db file and blow away the field that's causing the problems (once it gets past that in the startup, it rewrites it and it corrects it based on my testing - so the error literally goes away). 

(first, make sure Mylar isn't running)

To get into the sqlite db if you're not familiar, from a command line:

``` sqlite3 mylar.db```

then (note that this is case-senstive)

```update jobhistory set last_date=NULL where JobName='DB Updater';```

type in ```.exit``` to close the file. 

Then start it up - you won't get that error and things should return to normal.

I'll look into why it's happening and possibly try to adjust things, hopefully without breaking anything else going forward.

**Comment by mgaulton** [comment]
Appear to be past the db connect but I'm going to disable it for an hour, see if i can get around the git messages.

 I see this in the log, which seems like a response from git, but its not being parsed?
22-Apr-2021 23:11:46 - DEBUG :: mylar.runGit.44 : MAIN : Trying to execute: /usr/bin/git describe --exact-match --tags 2> /dev/null && git rev-parse HEAD --abbrev-ref HEAD with shell in /opt/mylar/mylar-master
22-Apr-2021 23:11:46 - DEBUG :: mylar.runGit.46 : MAIN : Git output: CompletedProcess(args='/usr/bin/git describe --exact-match --tags 2> /dev/null && git rev-parse HEAD --abbrev-ref HEAD', returncode=0, stdout='v0.5.1\n6f89e83ba15b3ff80031c810c556dc6b4c7cb8dc\nmaster\n', stderr='')

**Comment by evilhero** [comment]
if you have a personal github token, you can enter in the value in the config.ini under ```github_token``` which will allow you to bypass the restrictions if there are any and it might let things flow thru.

The response being returned is that there's nothing to parse so it throws the error - it's not a game breaker, as it's only temporary, but there's not really else that can be done aside from logging an error message to indicate that something is wrong.

**Comment by mgaulton** [comment]
What perms do I need to have on the token? I can generate a new one.

**Comment by evilhero** [comment]
No perms needed, it just has to access the github api to give you extra api hits above the free threshold, it's not requesting anything specific that would require any perms.

**Comment by mgaulton** [comment]
OK, and your user is the default, I assume I change that to mine?

**Comment by evilhero** [comment]
Which user? You should be doing this from the settings section of your github profile. 

All you need to do is give the token a name and select generate. That'll generate the key and paste that into the config.ini. No declaration of a user needed.

**Comment by mgaulton** [comment]
Ah in the config.ini I saw a username in the same config block as the token, assumed it mattered.
Added and got the same error, regardless of user. I'm going to leave it idle over night and see what it does in the morning.
Thanks for the help, i'll update you soonest! 
have a good night

**Comment by mgaulton** [comment]
So I renamed the Mylar.py so no automation would restart and its been about 12 hrs.
I ran it again and got the same keyerror.

```
23-Apr-2021 16:31:03 - INFO :: mylar.validateAndCreateDirectory.1723 : MainThread : [DIRECTORY-CHECK] Found comic directory: /opt/MYconfig
23-Apr-2021 16:31:03 - DEBUG :: mylar.runGit.44 : MAIN : Trying to execute: /usr/bin/git describe --exact-match --tags 2> /dev/null && git rev-parse HEAD --abbrev-ref HEAD with shell in /opt/mylar/mylar-master
23-Apr-2021 16:31:03 - DEBUG :: mylar.runGit.46 : MAIN : Git output: CompletedProcess(args='/usr/bin/git describe --exact-match --tags 2> /dev/null && git rev-parse HEAD --abbrev-ref HEAD', returncode=0, stdout='v0.5.1\n6f89e83ba15b3ff80031c810c556dc6b4c7cb8dc\nmaster\n', stderr='')
23-Apr-2021 16:31:03 - ERROR :: mylar.excepthook.315 : MAIN : Uncaught exception: Traceback (most recent call last):
  File "Mylar.py", line 386, in <module>
    main()
  File "Mylar.py", line 353, in main
    versioncheck.versionload()
  File "/opt/mylar/mylar-master/mylar/versioncheck.py", line 372, in versionload
    version_info = getVersion()
  File "/opt/mylar/mylar-master/mylar/versioncheck.py", line 114, in getVersion
    if git[0]['name'] is not None:
KeyError: 0

Traceback (most recent call last):
  File "Mylar.py", line 386, in <module>
    main()
  File "Mylar.py", line 353, in main
    versioncheck.versionload()
  File "/opt/mylar/mylar-master/mylar/versioncheck.py", line 372, in versionload
    version_info = getVersion()
  File "/opt/mylar/mylar-master/mylar/versioncheck.py", line 114, in getVersion
    if git[0]['name'] is not None:
KeyError: 0

```

**Comment by mgaulton** [comment]
``
server6:/opt/mylar/mylar-master # /usr/bin/git describe --exact-match --tags 2> /dev/null && git rev-parse HEAD --abbrev-ref HEAD
v0.5.1
6f89e83ba15b3ff80031c810c556dc6b4c7cb8dc
master
```

**Comment by evilhero** [comment]
Did you change the ```git_user``` and ```git_branch``` values within the config from the default values of ```mylar3``` and ```master```  respectively? Those values tell Mylar which repo to check for releases, so if you change it (say to your username), you won't get back valid results.

If you can hit : https://api.github.com/repos/mylar3/mylar3/tags in a browser, then you're not banned anylonger as a general user accessing the open api. You should see a json response in the browser with the "name" field, along with some url's for the repo's builds. If you see anything else, then something else is amiss.

**Comment by mgaulton** [comment]
so, when i checked the config originally, it showed evilhero and master, I changed it to mylar3 /master and it started.
weird.
Thank you for your paitence, I think i'm working now.
