### ISSUE TITLE
Covers are displayed if the image format in the comic file is .PNG

### ISSUE THREAD

**Issue by war3zlod3r** [mylar3/mylar3#734]
**Describe the bug**
The covers and metadata from tags aren't displayed if the files aren't in .JPG format, I haven't experiemented with other types but know its an issue with PNG files at least.

[WARNING] Unable to resize existing image: cannot write mode RGBA as JPEG

**CarePackage**

https://drive.google.com/file/d/1XcLpT1TOdq26PiInX-VChqN8seysPxeP/view?usp=sharing

If you're uncomfortable with pasting your CarePackage, include a DEBUG log containing the error from disk. 

Do not paste from the GUI log.
Do not just paste a traceback/error.

**Environment (please complete the following information):**
 - OS: Ubuntu Desktop 20.10
 - Branch / commit: Main

**Comment by evilhero** [comment]
Yeah probably cause png hasn't really caught on for images within a comics archive file overall. I haven't come across any during my testing over the years, so it never really came up until this post.

We can get it to return the image - I have a working version atm. Just need to make sure it doesn't break non-png formats and it'll be in the python3-dev branch before the day is over.

**Comment by war3zlod3r** [comment]
Awesome I'll give that a try, I haven't run across it much either but I did recently get the entire run of Exiles (2001) in all png and it would be just such a pain to convert them all over
