### ISSUE TITLE
[Bug] Cannot save any changes to settings

### ISSUE THREAD

**Issue by DrSeussFreak** [mylar3/mylar3#742]
**Describe the bug**
I cannot save any changes I made in settings.  I am not sure what I did, but nothing is getting logged for this (that I have seen) and anytime I hit save I get this error message
![Screen Shot 2021-04-28 at 3 21 16 PM](https://user-images.githubusercontent.com/175500/116467525-653a8880-a835-11eb-83e6-117bffb14a5f.png)

**CarePackage**
[carepackage.zip](https://github.com/mylar3/mylar3/files/6394593/carepackage.zip)

**Environment (please complete the following information):**
 - OS: Docker on Ubuntu 20.10
 - Branch / commit: Version: f72159a1b4615831de56ecdca258fb94ee0ebbd2 (python3-dev)

**Additional information**
HotIO docker image in use

**Comment by evilhero** [comment]
Your log file is empty - so there's something going on most likely with permissions I would imagine.  The configuration page saves changes fine as far as I can tell (tested here), so it's something localised to your docker. And since dockers don't modify the codebase, most likely the perms were modified in such a way that the configuration file cannot be written to any longer (and with the the log files).

**Comment by DrSeussFreak** [comment]
I thought the same thing, I've spent quite a bit of time troubleshooting permissions, and even with UMASK set to 000, chmod 777 and ownership reset to the user, I cannot save anything.

The logs were empty because I was playing around, but the log does work (here is a new carepackage with logs) - yet even with debug enabled, this error never logs anything.
[carepackage.zip](https://github.com/mylar3/mylar3/files/6399886/carepackage.zip)

**Comment by evilhero** [comment]
Make sure that you don't have the config file open anywhere else. 
Also make sure that you're referencing the correct ini file - you can see which one Mylar is using by going to the first tab in the configuration. If I recall hotio changed some folder locations around related to the configs a while ago - but I'm not 100% sure what it involved.

If you're using Chrome to view the pages, you can enable Developer Mode by going into the Chrome settings (the 3 veritical dots), selecting ```More tools``` and then selecting ```Developer tools```. Once you have that showing, you can try to resave the config and see what error messages appear in the console window.

**Comment by DrSeussFreak** [comment]
It is the right config, if I stop the container, make a change and restart it reflects those changes. Also checking the gui, the path is correct on the info tab of settings.

When I click save, the error I get in the console is

![Screen Shot 2021-04-29 at 10 57 27 AM](https://user-images.githubusercontent.com/175500/116581502-01b66680-a8da-11eb-8d9b-08a363745cb8.png)

**Comment by evilhero** [comment]
Ok, with Mylar still running and the devtools open with that particular error - click on the link specified there (the ```GET``` portion). It should open another window with a (hopefully) traceback or some kind of error in it.

I just tried on the LSIO docker and was able to save no issues - so this appears to be somthing localised to your installation possibly.

**Comment by DrSeussFreak** [comment]
I am seeing an nginx error there with config listed.  Do i need to set my entry of
`http_host = 0.0.0.0`
to something else?  It has been set to this for years, not sure what else to set it to.

**Comment by evilhero** [comment]
Try to set it to the IP of the docker container if you can - otherwise, the only thing I can think of is that something in the config is causing nginx to crap out on the response. Did you recently change something in your config - like a password or apikey or something  ?

**Comment by DrSeussFreak** [comment]
I just rebuild my config.ini from a new install via hotio (just to match their config).  if I connect publically I cannot save, if I connect locally I can, so clearly this is an nginx issue only.  

Do you have a recommended nginx setup?   Either way, I will close this as it is not your issue, thanks.
