### ISSUE TITLE
Wanted issues in pull list not recognized in download folder

### ISSUE THREAD

**Issue by mlsmithjr** [mylar3/mylar3#744]
**Describe the bug**
This is inconsistent - it doesn't seem to happen with all titles.  But for example, Darth Vader under Manage Title shows 10 issues, all downloaded.  However, #11 is available in the downloads folder. Since the title doesn't think there are more than 10 issues it doesn't try to import #11.  I've seen this with other titles too.

I have tried to refresh the title and rescan the files but nothing changes.  It won't import because it doesn't know there are now 11 issues.

**CarePackage**

[carepackage.zip](https://github.com/mylar3/mylar3/files/6402088/carepackage.zip)

**Environment (please complete the following information):**
 - OS: Linux (ubuntu) (docker)
 - Branch / commit: master ([v0.5.1])

**Additional information**
A little more detail.  Since the new issue isn't being pulled on it's own I tried direct downloading and dropping into my download folder.  Then I run a manual post-processing but still not recognized. Manual processing works great in all other situations.

**Comment by evilhero** [comment]
The issue has to be present on ComicVine for mylar to recognize it and do anything about it (search for it, post-process it, etc). Until CV updates that series to show the new issue, Mylar has no way of knowing or verifying what issue it is.

CV has taken to updating issues later in the given week as opposed to how it was a year or so ago when it was almost on release date. Now it might be Friday, Saturday or most recently Sunday even before they update CV.

**Comment by mlsmithjr** [comment]
I figured it was a metadata issue.  Thanks for the explanation.
