### ISSUE TITLE
Manual Import / Manual Intervention / Unable to select existing series.

### ISSUE THREAD

**Issue by Chudz** [mylar3/mylar3#750]
I am trying to manually import "Cyborg #1 (2016)". When I got to Manage and then do a scan and try to import it says It required "Manual Intervention" when I click Select it shows 2 series one that is existing but I am unable to import the issue into that series.

![1](https://user-images.githubusercontent.com/1077083/117059104-595c3400-ad17-11eb-80f1-3bf31ac80d41.JPG)
![2](https://user-images.githubusercontent.com/1077083/117059107-59f4ca80-ad17-11eb-822a-181c829ca22c.JPG)
![3](https://user-images.githubusercontent.com/1077083/117059108-59f4ca80-ad17-11eb-8dca-d42cd83d473a.JPG)
![4](https://user-images.githubusercontent.com/1077083/117059111-59f4ca80-ad17-11eb-9849-25daa2332faa.JPG)

**Comment by evilhero** [comment]
You might want to scope out the wiki for some additional information - import is for series that do not exist in your watchlist.

If you want to add files to series that exist in your watchlist (Already in Library), you need to Manually post-process those items by pointing the manual post-processing option (2nd tab in Manage) to the specific folder.

**Comment by Chudz** [comment]
Yes that is what I did, Click on Manage at top enter the path /config/import save and scanned. Viewed import results and click import and then it came up with intervention required.

**Comment by Chudz** [comment]
Yeh that worked. Strange it worked the other way with some stuff but then Batman and Cyborg was not working.

Thanks
