### ISSUE TITLE
"_downloadNZB() got an unexpected keyword argument" with .amp;. in file name

### ISSUE THREAD

**Issue by PCurd** [mylar3/mylar3#752]
**Describe the bug**
Using with NZBHydra and SabNZBD, search for an issue that contains .amp;. in the filename (for example "sacred six 001" on DogNZB). Note that SabNZBD gets stuck and eventually fails "URL Fetching failed". If the URL of the NZB is requested manually in a browser, for example: `http://192.168.0.XX:8090/api?apikey=<apikey>&cmd=downloadNZB&nzbname=Sacred.Six.001.2020.5.covers.Digital.DR.amp;.Quinch-Empire.nzb`, note the error:

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/cherrypy/_cprequest.py", line 638, in respond
    self._do_respond(path_info)
  File "/usr/lib/python3.8/site-packages/cherrypy/_cprequest.py", line 697, in _do_respond
    response.body = self.handler()
  File "/usr/lib/python3.8/site-packages/cherrypy/lib/encoding.py", line 219, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/app/mylar/webserve.py", line 5987, in api
    data = a.fetchData()
  File "/app/mylar/api.py", line 142, in fetchData
    result = methodToCall(**self.kwargs)
TypeError: _downloadNZB() got an unexpected keyword argument '.Quinch-Empire.nzb'
```

**CarePackage**
[carepackage.zip](https://github.com/mylar3/mylar3/files/6433188/carepackage.zip)

**Environment (please complete the following information):**
 - OS: Unraid/Linux Docker (hotio/mylar3)
 - Branch / commit: python3-dev/2bdbc2189427defdeafbc587f4cd7a8be81080ce

**Comment by PCurd** [comment]
I've done some limited debugging (I'm getting this again today with a different comic), and by the time the code gets to fetchData in api.py the kwargs['nzbname'] is already chopped off - instead of (for example) Vampirella.versus.Purgatori.003.2021.5.covers.Digital.DR.amp;.Quinch-Empire.nzb the value seems to be Vampirella.versus.Purgatori.003.2021.5.covers.Digital.DR.amp

Does this mean that the extra content is lost somewhere inside CherryPi?

If I manually encode the nzbname with a HTTP encode: Vampirella.versus.Purgatori.003.2021.5.covers.Digital.DR.amp%3B.Quinch-Empire.nzb
it works and the NZB downloads. So it's definitely the ";" that is causing the problem.

**Comment by evilhero** [comment]
Totally forgot about this as not many people are using comicrn and are instead using CDH (the recommended method).

I'll look into it this afternoon and see what can be done.

**Comment by PCurd** [comment]
I am using CDH - no scripts in SAB. I attach a more recent [carepackage.zip] (https://github.com/mylar3/mylar3/files/7117070/carepackage.zip) in case I was (although I don't think I was) back then

**Comment by evilhero** [comment]
Ok so in doing some testing, files containing ``.DR.amp;.Quinch-Empire`` are not a problem directly from dognzb via the api, nor a problem with any other indexer (even tested thru prowlarr), nor with other indexes in hydra.

The moment dognzb is added to hydra - the ``&amp;`` becomes just ``.amp;`` - I'm assuming dog tries to replace the & as it's an argument declaration but I really haven't a clue what's going on on that side of things.  There are checks within mylar that replace ``&amp;`` with just ``and`` when generating the nzbname, so adding in the ``.amp;`` was enough for things to work properly.

Also, I was absolutely wrong about the ComicRN - I forgot about the downloadnzb command being utilised still in that regards with CDH.

Fix up shortly to python3-dev!

**Comment by evilhero** [comment]
Assuming fixed.

Closing.
