### ISSUE TITLE
[Feature Request] Add Post-Processing with Cover

### ISSUE THREAD

**Issue by DrSeussFreak** [mylar3/mylar3#754]
**Describe the request**
For telegram notifications, you have the option to add the Cover image, Discord allows for this as well, I would love to see this added.

**How did you come up with the idea?**
Switched from telegram to discord, I miss the cover images

**Environment (please complete the following information):**
 - OS: Ubuntu 20.10 (Docker running on top of this)
 - Branch / commit: Version: 2bdbc2189427defdeafbc587f4cd7a8be81080ce (python3-dev)

**Additional information**
n/a

**Comment by evilhero** [comment]
Will have to look into it more - the discord code was done via a PR by someone else, so we'll need to familiarise ourselves with the code first in order to see if we can attach images like we do with the other notifs the same way.

**Comment by evilhero** [comment]
Discord notifications with images have been present for a few months, and since this issue dates back to sprint 2021, going to close this.

If you have an issue with the notifications themselves, please create an issue with the relevant information.
