### ISSUE TITLE
Can't access the webgui on mobile devices any more

### ISSUE THREAD

**Issue by hbllq** [mylar3/mylar3#761]
Strictly speaking this isn't a Mylar problem because Mylar works fine on my computer that I host it on. But I used to be able to enter my pc's ip and the right port and I could also access it on my phone and tablet. Now it says "server stopped responding". I don't think I had adjust anything on my previous router so I'm not sure what the issue could be. 
[carepackage.zip](https://github.com/mylar3/mylar3/files/6480027/carepackage.zip)

**Comment by barbequesauce** [comment]
Lots of variables outside of Mylar with this one - most likely is a local firewall of some kind. Check the security configuration of the PC....

**Comment by hbllq** [comment]
reinstalling mylar worked. Don't know what the issue was.
