### ISSUE TITLE
Error during conversion: 'unicodeescape' codec can't decode byte 0x5c in position 0: \ at end of string

### ISSUE THREAD

**Issue by Dude77777** [mylar3/mylar3#767]
**Describe the bug**
During startup I seem to be getting more and more of the above errors in the GUI log
26-May-2021 07:19:27 - WARNING :: mylar.updateComicLocation.883 : MainThread : [A:\COMICS\X1\X2] error during conversion: 'unicodeescape' codec can't decode byte 0x5c in position 0: \ at end of string
This seems to be related to Python 2/3 issues, although I am not a developer https://stackoverflow.com/questions/1347791/unicode-error-unicodeescape-codec-cant-decode-bytes-cannot-open-text-file

**Environment (please complete the following information):**
 - OS: Windows10
 - Branch / commit: 0.51

**Additional information**
Many thanks for looking into this

**Comment by evilhero** [comment]
Are you intentionally trying to alter your db comic location paths to a different location?

That error is indicating you have the locmove option enabled (set to True in the config.ini), so on every start of Mylar its attempting to modify all your existing paths to a different one.

**Comment by Dude77777** [comment]
Thanks so much, indeed I moved the collection to a different root folder. I thought that the setting would be refreshed at new start but I guess not. Cheers
