### ISSUE TITLE
unban my ip adress in the forum?

### ISSUE THREAD

**Issue by HypKin** [mylar3/mylar3#771]
I can log in from work, but ever since i've moved places and changed my provider 2 years ago, my ip adress is bannend in the mylar forum...

85.238.183.99 is my current ip. no idea why. :/

**Comment by evilhero** [comment]
It wasn't anything you did, it was an automated mass ban to that entire subnet due to spammers awhile ago. I unblocked that IP so you won't have any further issues, unless your IP changes again to the same subnet of course.

**Comment by HypKin** [comment]
thank you!
