### ISSUE TITLE
Torznab with multiple categories

### ISSUE THREAD

**Issue by TupaNegreiros** [mylar3/mylar3#777]
**Describe the bug**
Error setting torznab search providers with multiple categories

**CarePackage**
Attached.
[carepackage.zip](https://github.com/mylar3/mylar3/files/6626654/carepackage.zip)

**Environment (please complete the following information):**
 - OS: Raspbian GNU/Linux 10 (buster)
 - Branch / commit: master/[9ec6b1c7a5400c27d446337636cfa5fb61e9de19]

**Additional information**
All Torznab servers are set in only one line "extra_torznabs" of config.ini, separated by comma ",".
As far as I know, to set multiple categories, I use commas, like "8000, 7030". But it's the same separator of other fields. Putting a comma in one of the fields break the settings. If commas are forbidden, interface could alert user, or remove then before storage.

**Comment by evilhero** [comment]
Should be addressed in PR #780 - use ```,``` to separate torznab categories within the GUI. 

The config.ini will store the values as being separated by ```#```'s.

Conversion btwn the 2 is all under the hood so GUi users will only see the normal separators of ```,```

**Comment by barbequesauce** [comment]
All good here?
