### ISSUE TITLE
Support for multiple values in StoryArcNumber in ComicInfo.xml

### ISSUE THREAD

**Issue by foinse** [mylar3/mylar3#797]
**Describe the request**
StoryArcNumber support in the ComicInfo.xml was added in #411 This works for issues in a single StoryArc, but not for issues in multiple StoryArcs

**How did you come up with the idea?**
Talking with the developer of Komga about the possibility of auto sorting StoryArcs once they have been imported and noticed the issue

**Environment (please complete the following information):**
 - OS: Fedora 34
 - Branch / commit: python3-dev 4794759

**Additional information**
An example issue is https://comicvine.gamespot.com/the-uncanny-x-men-495-x-men-divided-part-one/4000-122405/

This issue is part of two StoryArcs. "Divided" and "Divided We Stand". I tested by adding "Divided We Stand" via StoryArcs in Mylar and in the ComicInfo.xml StoryArcNumber field, the correct value of 5 was present. I then added "Divided", where the StoryArcNumber for this should be 1. The StoryArcNumber field was no longer in the ComicInfo.xml.

In all cases the StoryArc field contains both StoryArcs seperated by a comma. e.g. 

`<StoryArc>Divided, Divided We Stand</StoryArc>
`

**Comment by gotson** [comment]
I think we could have the number separated by a comma in the `StoryArcNumber` field, with the same index as the values in `StoryArc`. The type of the 'StoryArcNumber` field would be String and would need to be parsed for numbers, but that should be easy.

**Comment by evilhero** [comment]
@gotson, yeah I'm ok with that. 

It might take me a few to get that into Mylar for writing out, as the post-processing is having some other issues atm I'm working thru and don't want to mix that into it until I get the other sorted out.

**Comment by gotson** [comment]
As talked on Discord, we should get either:
- a single `StoryArc` and its `StoryArcNumber`
- multiple pairs of `StoryArc` / `StoryArcNumber` as described above

But not a mix of multiple values in one, and none in the other.

I don't have the comics background as to whether a particular issue could or could not be in multiple read lists, i leave that to you :)

**Comment by foinse** [comment]
This has been added to python3-dev with  #868
