### ISSUE TITLE
Mylar sending wrong NZB URL to sabnzbd

### ISSUE THREAD

**Issue by dskaggs** [mylar3/mylar3#814]
**Describe the bug**
In trying to configure Mylar to work with SABNzbd, Mylar is sending the wrong IP address in the link after snatching the NZB file.

I run Mylar, SABNzbd, and other apps in a Docker Swarm. Both are joined to a Docker Swarm network in the address range 10.0.11.0/24 where Docker manages DNS for hosts on the network. 

Below is the result of running `ip a` from within the Mylar container:
```
root@a381e6cc4b3c:/# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
725074: eth0@if725075: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1450 qdisc noqueue state UP 
    link/ether 02:42:0a:00:0b:23 brd ff:ff:ff:ff:ff:ff
    inet 10.0.11.35/24 brd 10.0.11.255 scope global eth0
       valid_lft forever preferred_lft forever
725076: eth2@if725077: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue state UP 
    link/ether 02:42:ac:12:00:05 brd ff:ff:ff:ff:ff:ff
    inet 172.18.0.5/16 brd 172.18.255.255 scope global eth2
       valid_lft forever preferred_lft forever
725078: eth1@if725079: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1450 qdisc noqueue state UP 
    link/ether 02:42:0a:00:01:ed brd ff:ff:ff:ff:ff:ff
    inet 10.0.1.237/24 brd 10.0.1.255 scope global eth1
       valid_lft forever preferred_lft forever
```

Mylar sends the following URL to sabnzbd to be downloaded but sabnzbd is never able to download the nzb file:
http://172.18.0.5:8090/api?apikey=<snipped>

If I manually add an entry to sabnzbd and replace the IP address with the hostname using either of the URLs below, sabnzbd successfully downloads the nzb file from Mylar and then downloads the files:
http://mylar:8090/api?apikey=<snipped>
http://10.0.11.35:8090/api?apikey=<snipped>

I've attempted to set the "Host" value in Settings to both `mylar` and `10.0.0.0` but neither of those worked. I can't set the Host entry to the full IP address because it it not stable with how Docker manages containers and IP addresses within the stack.

**CarePackage**
[carepackage.zip](https://github.com/mylar3/mylar3/files/6826389/carepackage.zip)

**Environment (please complete the following information):**
 - OS: Docker version 20.10.5, build 55c4c88
 - Branch / commit: linuxserver/mylar3:latest (v0.5.4)

**Additional information**
I am using NZBHydra2 as the indexer for Mylar, Sonarr, Radarr, etc. It is on the same 10.0.11.0/24 network as Mylar and Sabnzbd.

**Comment by evilhero** [comment]
If you're using the ComicRN script - try setting the ```host_return``` value in your config.ini to the direct IP that mylar is running on (ie. ```http://10.0.11.35:8090```). For the host return to be set, it has to be some static value since it needs to know where it's polling to - you can't assign an IP range or similar, but you might be able to set it to ```http://mylar:8090``` but I'm not sure if that will resolve properly.

The easier solution would be to just enable Completed Download Handling and not have to worry about the host_return aspect, let alone the ComicRN script.

**Comment by dskaggs** [comment]
I can't hard code an IP because you never know what Docker is going to assign to it. I'll try the `http://mylar:8090` setting you mention and see where that gets me.

I see the ComicRN script in the `scripts/sabnzbd` folder. Does that mean that it's active? I haven't specifically set anything in the UI to enable it.

I do have Completed Download Handling toggled on:
![image](https://user-images.githubusercontent.com/432500/125874807-7eb653c2-e15b-4801-a446-9381a48bb513.png)

**Comment by evilhero** [comment]
Yeah you have both enabled - which isn't good.

Stick with CDH as it's more reliable once you get any permissions-related problems worked out with docker (if there are any). 

Disable/remove the script from your comics category within SABnzbd - if you're seeing SABnzbd trying to download the nzb from Mylar then you still have the ComicRN script active somewhere.

**Comment by dskaggs** [comment]
I first tested changing that `host_return` value as you described and Mylar sent the correct URL to SABnzbd.

Then I changed `host_return` back to `None`, deleted the ComicRN script, and restarted. I've successfully downloaded multiple issues from multiple series.

Thanks so much for your help. This was the last missing piece that I needed.
