### ISSUE TITLE
Post Processor Stopped Working

### ISSUE THREAD

**Issue by rutskiuk** [mylar3/mylar3#821]
I am able to run Mylar and it seems to work but I've noticed that PostProcessing has stopped

When I launch Mylar I now get a message that says:  

ERROR :: mylar.runGit.54 : MAIN : Encountered error: The filename, directory name, or volume label syntax is incorrect.

If I try to manually process a scan Mylar becomes unresponsive and the terminal window doesn't show any processing in progress.
Looking at the logs I see:

17-Jul-2021 17:32:03 - WARNING :: mylar.decrypt_it.45 : CP Server Thread-18 : Error not an encryption that I recognize.
17-Jul-2021 17:32:07 - ERROR   :: mylar.runGit.54 : CP Server Thread-10 : Encountered error: The filename, directory name, or volume label syntax is incorrect.

I have reinstalled git for windows and see no difference.
I have gone to the config and amended the git path to: blank, 'C:\Program Files\Git\bin\git.exe', 'C:\Program Files\Git\cmd\git.exe' but see no difference.
I've tried doing a fresh git reset and pull but it hasn't made any difference.
I've checked environmental variables and can see it set to: C:\Program Files\Git\cmd
I have changed that value to C:\Program Files\Git\bin but the behaviour is exactly the same.

 - OS: Windows10
 - Python version 3.7.9
 - Branch / commit: Master/ 8ef3325676e5bbea117d0827d32b673f8d004a3d

**Comment by evilhero** [comment]
Git has nothing to do with post-processing, they are independent of each other.

You'll need to put mylar into debug/verbose mode, start up mylar, get it to throw the error and then generate a carepackage and attach it so we can see what's going on.

**Comment by rutskiuk** [comment]
Ahh my bad, I just saw the gitrun error and made presumptions.
The file in question not being post processed is: Star Wars Darth Vader By Greg Pak Into The Fire 1 [(2021).cbz](url)
[carepackage-db.zip](https://github.com/mylar3/mylar3/files/6835059/carepackage-db.zip)
I tried to upload the carepackage but it's too large to add here so I've uploaded it without the db file.

**Comment by evilhero** [comment]
Ok, several things:
- if you have an ini value with a space in it, you need to put the entire value in double quotation marks (ie. "C:\Program Files\Git\bin\git.exe") ,not single quotation marks.
- your newznabs entry in the ini has been modified and is missing the enable/disable option:
   ```extra_newznabs = Newz69, xXX[REMOVED]XXx, 0, xXX[REMOVED]XXx, xXX[REMOVED]XXx, 0```
   you need to have an extra 0 or 1 at the end of that to tell mylar if it's enabled or disabled, like this:
   ```extra_newznabs = Newz69, xXX[REMOVED]XXx, 0, xXX[REMOVED]XXx, xXX[REMOVED]XXx, 0, 0```
- because that enable/disable opition is missing, mylar is assuming that it's by default enabled when searching but not when viewing the provider order. Basically, please don't edit the newznabs line manually - let the GUI correctly save it.

**Comment by rutskiuk** [comment]
Thank you, I have made the changes and the initial error in the terminal is now gone but the problem is still the same.
Looking at the logs I see a fresh entry: WARNING :: mylar.decrypt_it.45 : CP Server Thread-10 : Error not an encryption that I recognize.
Similarly, as soon as I click to run a scan manually the interface becomes completely unresponsive and the terminal shows no indication that any scan or processing is taking place. If I click anywhere in the browser I get a red box advising to check the logs for errors.

**Comment by evilhero** [comment]
Your ```Comic Location``` value (```D:/Comics```in the GUI has the incorrect slash for your OS - so when the ```/``` value gets passed as a variable, in Windows that's a control character which causes things to break - correct the slash and then Mylar should be able to search.

Also, I have no clue what you're talking about when you say 'scan manually' - what is it that you're trying to accomplish? Are you searching? Importing something already downloaded? Trying to post-process something? 

Your newz69 provider is down or offline - you should just disable it as it's doing nothing but spamming the logs continuously.

**Comment by rutskiuk** [comment]
Thank you, I had already disabled newz69 as indicated by the values you saw and for the exact reason you pointed out.
The comic location has never been d:/Comics, I'm not sure where that has come from, I checked the file I uploaded and it is d:\Comics
What I am trying to achieve is postprocessing, usually if I place a correctly named file in the fetch folder Mylar postprocesses within moments and that no longer happens. I manually postprocess by going to Manage and Manual Post-Processing, provide the path and submit.
The comic in question is named Star Wars Darth Vader By Greg Pak Into The Fire 1 (2021) and matches https://comicvine.gamespot.com/star-wars-darth-vader-by-greg-pak-into-the-fire/4050-137137/
I have tried postprocessing a different comic but Mylar nipped in with a DDL download before the file could be detected in the fetch folder.

**Comment by evilhero** [comment]
I'm looking directly at the ini value that is attached to the carepackage it has it as exactly:
```destination_dir = D:/Comics``` - either change it in the Comic Location path, or shut down mylar and change the value in the ini manually - either way, the reason why it can't do anything is due to that control character. Mylar is checking your destination_dir + series directory path combined to see if the directory exists prior to post-processing or when it goes to post-process - it can't because of that control character.

**Comment by rutskiuk** [comment]
You're absolutely right, what has me utterly baffled is how these misconfigurations worked like an absolute dream until the latest update.

What's more, looking at the D:\Comics path Mylar had successfully created a folder today with the name Star Wars Darth Vader By Greg Pak Into The Fire (2021) in that folder with the misconfiguration in place.

I have corrected that and downloaded a dummy file for a comic with a wanted issue and placed that in the fetch folder.
The dummy file has been fetched and postprocessed so it must be something about the file Star Wars Darth Vader By Greg Pak Into The Fire 01 (2021).cbz which isn't liked. Normally for any comic my idea (probably wrong) was to call the file the name of the comic according to comicvine followed by the issue number followed by the year. I've swapped the name to have the issue following the year but still it doesn't postprocess.

**Comment by evilhero** [comment]
If the directory exists, you'll see a green checkmark beside the Directory option on the series detail page. If it doesn't exist you'll see a red x. What value do you see currently ?

Make sure you put mylar into debug mode ([check the wiki](https://github.com/mylar3/mylar3/wiki/Debug-logging)), and then try to post-process the item again. Once you've done that generate another care package and throw that up - the previous carepackage had nothing about post-processing in any of the log files.

**Comment by rutskiuk** [comment]
I don't see any green ticks or red crosses in the series detail directory, only the path.

I've looked at the debug log and it seems to say it's an exact match and an incorrect match:

<html><body>


2021-07-17 20:32:57 | DEBUG | [POST-PROCESSING]  There are 0 files found that match on your watchlist, 0 files are  considered one-off's, and 2 files do not match anything
-- | -- | --
2021-07-17 20:32:57 | DEBUG | Star  Wars Darth Vader By Greg Pak Into The Fire 01 in filename don't match  up to what's in the dB for Star Wars: Darth Vader By Greg Pak: Into The  Fire [137137]. This is a wrong match. Continuing...
2021-07-17 20:32:57 | DEBUG | name match exact : starwarsdarthvaderbygregpakintofire - starwarsdarthvaderbygregpakintofire
2021-07-17 20:32:57 | DEBUG | possible match - issue in dB (1000) is greater than issue in file (1000)
2021-07-17 20:32:57 | DEBUG | [POST-PROCESSING][ISSUE-VERIFY] Now checking against Star Wars: Darth Vader By Greg Pak: Into The Fire - 137137
2021-07-17 20:32:57 | DEBUG | tmplatestissueint: 1000
2021-07-17 20:32:57 | DEBUG | tmplatestissue: 1
2021-07-17 20:32:57 | INFO | Now checking: Star Wars: Darth Vader By Greg Pak: Into The Fire [137137]
2021-07-17 20:32:57 | INFO | I have located 2 files that I should be able to post-process. Continuing...
2021-07-17 20:32:57 | DEBUG | series title possibly: Star Wars Darth Vader By Greg Pak Into The Fire


</body>
</html>

**Comment by evilhero** [comment]
You should see this or a red x beside the directory name. If you don't you're not current, or your version has been modified ?
![](https://colder.thanyou.xyz/selif/uu1nvxbi.png)

The post-processing issues  should be almost all addressed, save for the one patch that's currently in the python3-dev branch.

**Comment by rutskiuk** [comment]
I can't recall ever seeing a tick next to the directory for any comics:
![image](https://user-images.githubusercontent.com/25068977/126052424-a9e5dd3f-91dd-4fcb-8c94-80c4a137e868.png)
I have noticed also that if I edit the folder path for a comic and start typing it doesn't detect the folder that is already in place.
For example with the above comic, if I go to edit the path, remove the last bracket and put it back in I do not see a match.
I have a second machine I set up a while ago and checked there too, no tick or cross and on the same build/version.
I also checked my Synology running docker and that has the same build, it too has no tick or cross next to the directory.

**Comment by evilhero** [comment]
Ok, - so there's a few problems going on, and it looks like the end result (after the directory slash thing and git problem of course), lies in the fact that one aspect didn't get released properly, and the 2nd aspect was never taken into consideration.

1) The code for the checkmark/x to represent whether a comic directory was physically present on the file-system was not being shown if you weren't using the ```multiple_dest_dirs``` option.
2) When doing post-processing it compares against the pull if it's a Continuing series. The pull doesn't list TPB's, so it couldn't compare properly and just defaulted to the failure option.

Both of these will get addressed in the python3-dev branch shortly - and I believe it might make it in to the main merge that I have tentatively scheduled for late Sunday.

**Comment by rutskiuk** [comment]
Thank you! I've updated and the tick is present and the tpb processed
