### ISSUE TITLE
Fresh install of Mylar3 fails to add any items

### ISSUE THREAD

**Issue by barbequesauce** [mylar3/mylar3#825]
Copied from https://github.com/linuxserver/docker-mylar3/issues/15#issue-947963638

Expected Behavior

Add item as normal

Current Behavior

Adds item, never finishes refreshing it, outputs the python error as shown

Steps to Reproduce

See below compose file
Try to add any item to the list
See errors
Environment

**OS: Debian
CPU architecture: x86_64
How docker service was installed:

Per docker documentation

Command used to create docker container (run/create/compose/screenshot)

mylar3:
image: ghcr.io/linuxserver/mylar3
container_name: mylar3
environment:
- PUID=1000
- PGID=1000
volumes:
- /dockerssd/mylar/config:/config
- /dockerssd/mylar/comics:/comics
- /dockerssd/mylar/downloads:/downloads
ports:
- 8090:8090
restart: unless-stopped

Docker logs

Initializing startup sequence....
172.16.42.20 - - [19/Jul/2021:19:28:58] "GET /home HTTP/1.1" 200 8642 "http://192.168.1.40:8090/home" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0"
172.16.42.20 - - [19/Jul/2021:19:28:59] "GET /home HTTP/1.1" 200 8642 "http://192.168.1.40:8090/home" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0"
172.16.42.20 - - [19/Jul/2021:19:29:01] "GET /home HTTP/1.1" 200 8642 "http://192.168.1.40:8090/home" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0"
172.16.42.20 - - [19/Jul/2021:19:29:03] "GET /home HTTP/1.1" 200 8642 "http://192.168.1.40:8090/home" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0"
172.16.42.20 - - [19/Jul/2021:19:29:04] "GET /home HTTP/1.1" 200 8642 "http://192.168.1.40:8090/home" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0"
172.16.42.20 - - [19/Jul/2021:19:29:06] "GET /home HTTP/1.1" 200 8642 "http://192.168.1.40:8090/home" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0"
172.16.42.20 - - [19/Jul/2021:19:29:07] "GET /home HTTP/1.1" 200 8642 "http://192.168.1.40:8090/home" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0"
172.16.42.20 - - [19/Jul/2021:19:29:11] "GET /home HTTP/1.1" 200 8642 "http://192.168.1.40:8090/home" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0"
172.16.42.20 - - [19/Jul/2021:19:29:13] "GET /home HTTP/1.1" 200 8642 "http://192.168.1.40:8090/home" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0"
172.16.42.20 - - [19/Jul/2021:19:29:18] "GET /home HTTP/1.1" 200 8642 "http://192.168.1.40:8090/home" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0"
172.16.42.20 - - [19/Jul/2021:19:29:34] "GET /home HTTP/1.1" 200 8642 "http://192.168.1.40:8090/home" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0"
172.16.42.20 - - [19/Jul/2021:19:29:36] "GET /pullist HTTP/1.1" 200 310641 "http://192.168.1.40:8090/home" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0"
172.16.42.20 - - [19/Jul/2021:19:29:37] "GET /get_the_pubs HTTP/1.1" 200 2 "" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0"
172.16.42.20 - - [19/Jul/2021:19:29:43] "GET /queueit?ComicName=Silver+City&ComicID=135999&IssueID=None&ComicIssue=3&mode=pullwant&Publisher=AfterShock%20Comics&pullinfo=2021-07-21&pullweek=29&pullyear=2021&BookType=None HTTP/1.1" 200 - "" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0"
19-Jul-2021 19:29:43 - INFO :: mylar.queueissue.1701 : Thread-12 : [PULL-LIST] Now Queueing Silver City (2021) #3 for search
172.16.42.20 - - [19/Jul/2021:19:29:46] "GET /pullist HTTP/1.1" 200 310641 "" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0"
172.16.42.20 - - [19/Jul/2021:19:29:46] "GET /get_the_pubs HTTP/1.1" 200 2 "" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0"
19-Jul-2021 19:29:46 - INFO :: mylar.search_queue.3200 : SEARCH-QUEUE : [SEARCH-QUEUE] Now loading item from search queue: {'issueid': 'None', 'comicname': 'Silver City', 'seriesyear': '2021', 'comicid': '135999', 'issuenumber': '3', 'booktype': 'None'}
19-Jul-2021 19:29:46 - WARNING :: mylar.searchforissue.3216 : SEARCH-QUEUE : There are no search providers enabled atm - not performing an Force Check for obvious reasons
172.16.42.20 - - [19/Jul/2021:19:29:46] "GET /home HTTP/1.1" 200 8642 "" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0"
172.16.42.20 - - [19/Jul/2021:19:29:48] "GET /home HTTP/1.1" 200 8642 "http://192.168.1.40:8090/home" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0"
172.16.42.20 - - [19/Jul/2021:19:29:51] "GET /manage HTTP/1.1" 200 24730 "http://192.168.1.40:8090/home" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0"
172.16.42.20 - - [19/Jul/2021:19:29:53] "GET /pullist HTTP/1.1" 200 310641 "http://192.168.1.40:8090/manage" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0"
172.16.42.20 - - [19/Jul/2021:19:29:53] "GET /get_the_pubs HTTP/1.1" 200 2 "" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0"
19-Jul-2021 19:29:56 - INFO :: mylar.addbyid.629 : CP Server Thread-6 : Attempting to add directly by ComicVineID: 132602
172.16.42.20 - - [19/Jul/2021:19:29:56] "GET /addbyid?comicid=132602&calledby=True HTTP/1.1" 200 - "" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0"
172.16.42.20 - - [19/Jul/2021:19:29:59] "GET /get_the_pubs HTTP/1.1" 200 2 "" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0"
172.16.42.20 - - [19/Jul/2021:19:29:59] "GET /pullist HTTP/1.1" 200 309587 "" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0"
19-Jul-2021 19:29:59 - WARNING :: mylar.havetotals.1429 : CP Server Thread-8 : Comic ID: 132602 has not finished loading. Nulling some values so things display properly until they can populate.
172.16.42.20 - - [19/Jul/2021:19:29:59] "GET /home HTTP/1.1" 200 9744 "" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0"
19-Jul-2021 19:29:59 - INFO :: mylar.addComictoDB.151 : Thread-13 : Now adding/updating: Second Coming: Only Begotten Son
19-Jul-2021 19:29:59 - INFO :: mylar.addComictoDB.208 : Thread-13 : Sucessfully retrieved details for Second Coming: Only Begotten Son
19-Jul-2021 19:29:59 - INFO :: mylar.addComictoDB.219 : Thread-13 : Previous version detected as None - seeing if update required
19-Jul-2021 19:29:59 - INFO :: mylar.addComictoDB.222 : Thread-13 : Updated version to :v2
19-Jul-2021 19:29:59 - ERROR :: mylar.excepthook.315 : Thread-13 : Uncaught exception: Traceback (most recent call last):
File "/app/mylar3/mylar/logger.py", line 337, in new_run
old_run(*args, **kwargs)
File "/usr/lib/python3.8/threading.py", line 870, in run
self._target(*self._args, **self._kwargs)
File "/app/mylar3/mylar/importer.py", line 252, in addComictoDB
comvalues = dothedew.folder_create()
File "/app/mylar3/mylar/filers.py", line 212, in folder_create
ddir = pathlib.PurePath(mylar.CONFIG.DESTINATION_DIR)
File "/app/mylar3/lib/pathlib.py", line 585, in new
return cls._from_parts(args)
File "/app/mylar3/lib/pathlib.py", line 613, in _from_parts
drv, root, parts = self._parse_args(args)
File "/app/mylar3/lib/pathlib.py", line 603, in _parse_args
raise TypeError(
TypeError: argument should be a path or str object, not <class 'NoneType'>

Traceback (most recent call last):
File "/app/mylar3/mylar/logger.py", line 337, in new_run
old_run(*args, **kwargs)
File "/usr/lib/python3.8/threading.py", line 870, in run
self._target(*self._args, **self._kwargs)
File "/app/mylar3/mylar/importer.py", line 252, in addComictoDB
comvalues = dothedew.folder_create()
File "/app/mylar3/mylar/filers.py", line 212, in folder_create
ddir = pathlib.PurePath(mylar.CONFIG.DESTINATION_DIR)
File "/app/mylar3/lib/pathlib.py", line 585, in new
return cls._from_parts(args)
File "/app/mylar3/lib/pathlib.py", line 613, in _from_parts
drv, root, parts = self._parse_args(args)
File "/app/mylar3/lib/pathlib.py", line 603, in _parse_args
raise TypeError(
TypeError: argument should be a path or str object, not <class 'NoneType'>

**Comment by evilhero** [comment]
Comic Location path needs to be set and accessible - see the 1st point [https://github.com/mylar3/mylar3/wiki/Tips-and-Tricks](here)
