### ISSUE TITLE
Unable to update Mylar

### ISSUE THREAD

**Issue by war3zlod3r** [mylar3/mylar3#834]
The internal updater appears to be broken and I can't seem to figure it out even replaced all files with the newest release. Here's a post from my logs

27-Jul-2021 07:37:49 - INFO    :: mylar.main.373 : MAIN : Received signal: update
27-Jul-2021 07:37:49 - INFO    :: mylar.halt.1465 : MAIN : Shutting down the background schedulers...
27-Jul-2021 07:37:49 - INFO    :: mylar.shutdown.1494 : MAIN : Mylar is updating...
27-Jul-2021 07:37:50 - INFO    :: mylar.search_results.228 : ThreadPoolExecutor-0_1 : There are 1 results
27-Jul-2021 07:37:51 - ERROR   :: mylar.runGit.54 : MAIN : Encountered error: hint: Pulling without specifying how to reconcile divergent branches is
hint: discouraged. You can squelch this message by running one of the following
hint: commands sometime before your next pull:
hint: 
hint:   git config pull.rebase false  # merge (the default strategy)
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint: 
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
From https://github.com/mylar3/mylar3
 * branch              master     -> FETCH_HEAD
error: Your local changes to the following files would be overwritten by merge:
	README.md
	data/css/style.css
	data/images/irc-icon.png
	data/interfaces/carbon/css/style.css
	data/interfaces/default/comicdetails.html
	data/interfaces/default/config.html
	data/interfaces/default/css/style.css
	data/interfaces/default/storyarc_detail.html
	data/interfaces/default/storyarc_detail.poster.html
	data/interfaces/default/upcoming.html
	mylar/Failed.py
	mylar/PostProcessor.py
	mylar/__init__.py
	mylar/api.py
	mylar/config.py
	mylar/cv.py
	mylar/filechecker.py
	mylar/filers.py
	mylar/findcomicfeed.py
	mylar/helpers.py
	mylar/importer.py
	mylar/locg.py
	mylar/nzbget.py
	mylar/process.py
	mylar/sabnzbd.py
	mylar/search.py
	mylar/updater.py
	mylar/webserve.py
	mylar/webstart.py
	mylar/weeklypull.py
	requirements.txt
Please commit your changes or stash them before you merge.
error: The following untracked working tree files would be overwritten by merge:
	data/interfaces/carbon/images/irc-icon-carbon.png
	mylar/series_metadata.py
Please move or remove them before you merge.
Aborting

27-Jul-2021 07:37:51 - INFO    :: mylar.shutdown.1501 : MAIN : Removing pidfile /var/run/mylar/mylar.pid
27-Jul-2021 07:37:51 - INFO    :: mylar.shutdown.1505 : MAIN : Mylar is restarting...
27-Jul-2021 07:37:51 - INFO    :: mylar.shutdown.1513 : MAIN : Restarting Mylar with ['/usr/bin/python3', '/home/war3zlod3r/mylar3/Mylar.py', '--daemon', '--nolaunch', '--pidfile=/var/run/mylar/mylar.pid', '--datadir=/home/war3zlod3r/mylar3']

**Comment by evilhero** [comment]
Same method used in #511 and #646. 

I'm assuming you're getting that error because it's been awhile since you last updated?

Provided you have no local changes, doing the below commands in order, should fix things:

git fetch
git checkout master
git reset --hard origin/master

Note that if you're on the python3-dev branch just replace any instance of ``master`` above with ``python3-dev``.

**Comment by war3zlod3r** [comment]
Yes I'm not very consistent about remembering to check for updates, would be nice if we could automate the process but I can understand why its manual

**Comment by war3zlod3r** [comment]
when I run "git- reset --hard origin/master" my output is: "HEAD is now at 85341995 Merge branch 'python3-dev'"

**Comment by war3zlod3r** [comment]
I was able to successfully upgrade to v0.5.5 but now I get an error when I try to go to the "Wanted" page error is as follows:

Error !
IndexError: No item with that key
issueid = issue['IssueID'] if any(d['IssueID'] == str(issue['IssueID']) for d in ann_list): adjcomicname = issue['ReleaseComicName'] else: adjcomicname = issue['ComicName'] endif try:
/home/war3zlod3r/mylar3/data/interfaces/default/upcoming.html, line 110:
adjcomicname = issue['ReleaseComicName']
/home/war3zlod3r/mylar3/data/interfaces/default/base.html, line 91:
${next.body()}
/usr/lib/python3/dist-packages/mako/runtime.py, line 947:
callable_(context, *args, **kwargs)
/usr/lib/python3/dist-packages/mako/runtime.py, line 920:
_exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
/usr/lib/python3/dist-packages/mako/runtime.py, line 878:
_render_context(
/usr/lib/python3/dist-packages/mako/template.py, line 476:
return runtime._render(self, self.callable_, args, data)
/home/war3zlod3r/mylar3/mylar/webserve.py, line 102:
return template.render(http_root=mylar.CONFIG.HTTP_ROOT, interface=mylar.CONFIG.INTERFACE, icons=icons, **kwargs)

**Comment by evilhero** [comment]
This has been fixed in the python3-dev branch as of this morning. If you're running a non docker version of Mylar you can switch to the python3-dev branch by doing:
- git checkout python3-dev
- git pull
Then, with Mylar not running, edit your config.ini and change the ``git_branch`` value to ``python3-dev``.

It might still be a few days before it hits master.

**Comment by war3zlod3r** [comment]
Thanks for the quick and friendly support!
