### ISSUE TITLE
Mako Error "SyntaxException" on StoryArc

### ISSUE THREAD

**Issue by Berserkir-Wolf** [mylar3/mylar3#837]
This occurs on both default and carbon interfaces.
When attempting to view the "Future State" StoryArc, mylar throws a Mako error (below).
This does not occur on the King in Black storyarc (used to test it).
I am using Mylar 0.5.4, with python 3.8.3

## Error !
__SyntaxException: Expected: \|,} in file 'c:/Services/Mylar3/data/interfaces/default/storyarc_detail.html' at line: 340 char: 2__
`$(document).ready(function() { initThisPage(); initActions(); }); </script> </%def>`
c:\Python38\lib\site-packages\mako\lexer.py, line 143:
`raise exceptions.SyntaxException(`
c:\Python38\lib\site-packages\mako\lexer.py, line 427:
`text, end = self.parse_until_text(True, r"\|", r"}")`
c:\Python38\lib\site-packages\mako\lexer.py, line 262:
`if self.match_expression():`
c:\Python38\lib\site-packages\mako\template.py, line 709:
`node = lexer.parse()`
c:\Python38\lib\site-packages\mako\template.py, line 730:
`source, lexer = _compile(`
c:\Python38\lib\site-packages\mako\template.py, line 427:
`code, module = _compile_text(self, data, filename)`
c:\Python38\lib\site-packages\mako\template.py, line 347:
`module = self._compile_from_file(path, filename)`
c:\Python38\lib\site-packages\mako\lookup.py, line 322:
`self._collection[uri] = template = Template(`
c:\Python38\lib\site-packages\mako\lookup.py, line 260:
`return self._load(srcfile, uri)`
c:\Services\Mylar3\mylar\webserve.py, line 101:
`template = _hplookup.get_template(templatename)`

**Comment by evilhero** [comment]
You're a version behind as this has been fixed in v0.5.5, which was released last week.

**Comment by Berserkir-Wolf** [comment]
Updated and confirmed, definitely fixed. Thanks for the prompt response!
