### ISSUE TITLE
Readme change

### ISSUE THREAD

**Issue by Tom-Neverwinter** [mylar3/mylar3#842]
**Describe the request**
Installation instructions too simple.

need a throw file in C:/mylar

open python terminal

run x command to install.

enjoy. 

**How did you come up with the idea?**
python doesn't use cd... using os.chdir throws error.... decide this is a pain in the rear... look for youtube tutorial.... decide mylar is a waste of time... 

python is cool... just most tutorials are padded and general trash. 

Get to the monkey. 

**Environment (please complete the following information):**
 - OS: Windows10
 - Branch / commit: current

**Additional information**
Its no wonder nobody wants to install. Python doesn't use common or shared standard commands. cd or /whateverdirectorythisis also double \\ may be required?

**Comment by evilhero** [comment]
dude - you made an issue to complain about the program that it's a 'waste of time'

No idea where you get the 'cd aspect' from - that's not in the wiki. 
No one ever said to run any cd command in a python window - like really ? 

It's a wonder you're getting any response to this - as you're apparently trying to install it from some guide that's above your pay-grade.

If you have an issue that's not a bug with the actual program - which this would be, take it to the forums or go on reddit so you can bitch about it to everyone else on there.
