### ISSUE TITLE
Mylar can't connect to qbittorrent

### ISSUE THREAD

**Issue by SonOfDiablo** [mylar3/mylar3#855]
**Describe the bug**
Mylar can't connect to qbittorrent.

**[carepackage.zip](https://github.com/mylar3/mylar3/files/6959890/carepackage.zip)**

**Environment (please complete the following information):**
 - OS: Raspbian GNU/Linux 10 (buster) armv7l
 - Branch / commit: Main

**Additional information**

The specific issue I'm experiencing.
```
10-Aug-2021 09:43:54 - ERROR :: mylar.connect.24 : CP Server Thread-5 : Could not create qBittorrent Object No connection adapters were found for 'seedbox:8080/api/v2/app/preferences'
10-Aug-2021 09:43:54 - WARNING :: mylar.testqbit.6527 : CP Server Thread-5 : [qBittorrent] Could not establish connection to seedbox:8080. Error returned: No connection adapters were found for 'seedbox:8080/api/v2/app/preferences'
192.168.1.120 - - [10/Aug/2021:09:43:54] "GET /testqbit?host=seedbox%3A8080&username=&password= HTTP/1.1" 200 44 "http://seedbox:8090/config" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.102 Safari/537.36"
```

Also, I have both Sonarr and Radarr connecting without issues, using the same settings.

**Comment by barbequesauce** [comment]
First up - radarr and sonarr have nothing to do with mylar - one R, different languages, different codebases, different teams etc etc.

Second - looking in the three lines pasted into the issue I see both ports 8080 and 8090 referenced. Which one is being used?

**Comment by SonOfDiablo** [comment]
> First up - radarr and sonarr have nothing to do with mylar - one R, different languages, different codebases, different teams etc etc.

I only mentioned radarr/sonarr as a way to "prove" qbittorrent was working and it was possible to connect to it with the information I had provided mylar, as a means to avoid "Are you sure qbittorrent is setup correctly" or "double check username/password/ip/port etc"

> Second - looking in the three lines pasted into the issue I see both ports 8080 and 8090 referenced. Which one is being used?

qbittorrent uses port 8080, mylar uses 8090

**Comment by barbequesauce** [comment]
Shouldn't answer support issues while dealing with insomnia.... the 8090 was the config test being served back, not a logged line...

you'll need http:// or https:// in front of 'seedbox:8080'. Add that and you should be fine.

**Comment by SonOfDiablo** [comment]
yup adding http:// worked.. I swear I tried that already, but I must have messed it up the first time I tried.

Thank you so much @barbequesauce!
