### ISSUE TITLE
Can't find any comments from nzbgeek

### ISSUE THREAD

**Issue by ImDevinC** [mylar3/mylar3#859]
**Describe the bug**
I've added multiple comics from different series to Mylar, but it doesn't find any results at all. I can find them manually if I search on nzbgeek, but mylar won't find anything.

**CarePackage**
[carepackage.zip](https://github.com/mylar3/mylar3/files/7011272/carepackage.zip)

**Environment (please complete the following information):**
 - OS: Docker
 - Branch / commit: linuxserver/mylar3

**Comment by evilhero** [comment]
From the logs, looks like you need to specify a protocol for your nzbget host within Mylar:
```[NZB-GET] You need to specify the protocol for your NZBGET instance (ie. http:// or https://).```

**Comment by ImDevinC** [comment]
Thanks @evilhero, that seems to have fixed it. Very strange since using the `Test NZBGET` button said there were no issues.

**Comment by evilhero** [comment]
I'm guessing safeguards are in place for the test option, but not for the actual usage of it ( stupid I know ). 

We should be just throwing back an error based on what the user input as the nzbget host on the test button - so that'll be fixed so it returns an error instead of checkmarking it.
