### ISSUE TITLE
Cert for walksoftly.itsaninja.party has expired

### ISSUE THREAD

**Issue by TheOttoman2012** [mylar3/mylar3#865]
I'm not sure if it's a you thing or someone else thing, but when attempting to recreate a pull list  I get this error:

WARNING :: mylar.locg.58 : CP Server Thread-8 : HTTPSConnectionPool(host='walksoftly.itsaninja.party', port=443): Max retries exceeded with url: /newcomics.php?week=33&year=2021 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)'))).

Looking at the site, the cert expired today

**Comment by evilhero** [comment]
Yup - it's my thing lol.

It won't be happening again hopefully, but it's back online now (do a ``Recreate Pullist`` from the Weekly page to get everything back in sync if you don't want to wait for the 4hr window to fire off)
