### ISSUE TITLE
Folder Format issue at restart with Type = Print between brackets

### ISSUE THREAD

**Issue by Jbaal** [mylar3/mylar3#882]
Hi!
I have an issue with the Folder Format, I use this one : 
$Publisher/$Imprint/$Series $VolumeN ($Year) [$Type]
When created, everything's okay, when the serie is a Print, it creates the folder like this:
/mnt/Comics/DC Comics/Green Lantern 2021 Annual (2021)
skipping the [Print] part. It's ok with me, as long as the One-shots, TPB and others have the right informations.

But when I relaunch mylar, here is the Directory given by the comic details page:
/mnt/Comics/DC Comics//Green Lantern 2021 Annual (2021) []
The brackets are back and empty, and the folder seen as non existant.

Thanks again a lot for your work!

 - OS: dietpi
 - Branch / commit: [56a8469e]

**Comment by evilhero** [comment]
Please follow the template - you also haven't described the problem at hand.

**Comment by Jbaal** [comment]
Sorry I missclicked, I just edited the post

**Comment by evilhero** [comment]
To use the ``$Type`` field, you need to find the ``format_booktype`` field in the _[General]_ section of the config.ini and set the value to ``True`` (ie. ``format_booktype = True``).

Note that you have to make sure Mylar is not running when you edit the ini or else your changes won't be honoured.

**Comment by Jbaal** [comment]
`format_booktype` is allready set to `true`, and it works well with the other types, for example:
/mnt/Comics/DC Comics//Harley Quinn The Animated Series The Eat. Bang Kill. Tour (2021) [Digital]
This one as been created like this and didn't change after a restart. The only issue is with the Prints

**Comment by evilhero** [comment]
``Print`` will not display - so it should blank out the value from being written.

Does the directory exist on your filesystem with or without the ``[] ``? A

**Comment by Jbaal** [comment]
When adding the serie, the directory is created without the `[]`.
When restarting mylar, the logs give me this :

> 12-sept.-2021 18:30:07 - DEBUG :: MainThread : helpers.py:updateComicLocation:914 : Updated : /mnt/Comics/DC Comics/Green Lantern 2021 Annual (2021) .: TO :. /mnt/Comics/DC Comics//Green Lantern 2021 Annual (2021) []

The folder on my filesystem still exists without `[]`, but the webpage comicDetails?ComicID=138764 give me those informations:
`Directory:
this directory does not currently exist/mnt/Comics/DC Comics//Green Lantern 2021 Annual (2021) []` with the red cross next to it.

**Comment by evilhero** [comment]
Can you go the configuration page within Mylar and click on the carepackage button? Then attach the carepackage.zip file to this issue and I can look more into it (I have the same folder creation as you and mine works as expected, so there's something different in your setup).

**Comment by Jbaal** [comment]
Oh great! That was it! Thank you very much and sorry for my mistake!
By the way thanks again for your hard work, some times ago I was suggesting to be able to overwrite the Type (https://github.com/evilhero/mylar/issues/2292) and now it is fully functional! I really appreciate !
