### ISSUE TITLE
Prowlarr Searches Not Working

### ISSUE THREAD

**Issue by wraith1385** [mylar3/mylar3#890]
Since switching from NZBHydra2 to Prowlarr, Mylar never finds any issues when searching, however I can see the issues are on my indexer and I can see the issues when I do a search in prowlarr.  Care package is attached.  Please let me know if there's anything else you need.

[carepackage.zip](https://github.com/mylar3/mylar3/files/7199286/carepackage.zip)

**Comment by evilhero** [comment]
You're running v0.5.4 - most recent is v0.5.8.

Basically, you need to update as all the Prowlarr additions were in the last 2 releases.

**Comment by wraith1385** [comment]
Thanks.  For some reason the little popup notification in the bottom right that normally tells me there's a new version, wasn't showing up until I manually made it check for a new version.  After updating the prowlarr integration works.
