### ISSUE TITLE
errno.EExist typo causes infinite loop

### ISSUE THREAD

**Issue by aschi2** [mylar3/mylar3#892]
**Describe the bug**
Caught in an infinite restart loop due to errno typo I think

**CarePackage**
Not sure how to extract this without a running instance but the traceback is pretty clear, and as far as I know errno has no attribute EXIST, only EEXIST.

mylar3  | Traceback (most recent call last):
mylar3  |   File "/app/mylar3/Mylar.py", line 387, in <module>
mylar3  |     main()
mylar3  |   File "/app/mylar3/Mylar.py", line 251, in main
mylar3  |     if exception.errno != errno.EXIST:
mylar3  | AttributeError: module 'errno' has no attribute 'EXIST'

**Environment (please complete the following information):**
 - Windows 10 Docker
 - Branch / commit: latest

**Comment by evilhero** [comment]
Yeah it should be EEXIST, nice catch. 

However I'm not sure that causes an infinite loop as it should either exit to console on error or increment the counter and exit the loop (unless docker restarts on error, then that would just keep on starting / stopping). 

Is this a fresh install or an existing one?

You're using the backup option, are you doing it via the -b switch or using the config.ini option?

For the time being, just temporarily remove/disable the backup option and see if it's able to start up.

**Comment by aschi2** [comment]
Yes it starts up when I comment out the backup code.
