### ISSUE TITLE
comicDetails give error 500 since last update

### ISSUE THREAD

**Issue by Jbaal** [mylar3/mylar3#909]
Since the last update I have an error 500 when trying to access any comic page. All the others pages works without issues, there's just those comicDetails pages that seems to fail.

Sorry but I can only give you this traceback as nothing seems to appear in the logs :

> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/dist-packages/cherrypy/_cprequest.py", line 638, in respond
>     self._do_respond(path_info)
>   File "/usr/local/lib/python3.7/dist-packages/cherrypy/_cprequest.py", line 697, in _do_respond
>     response.body = self.handler()
>   File "/usr/local/lib/python3.7/dist-packages/cherrypy/lib/encoding.py", line 219, in __call__
>     self.body = self.oldhandler(*args, **kwargs)
>   File "/usr/local/lib/python3.7/dist-packages/cherrypy/_cpdispatch.py", line 54, in __call__
>     return self.callable(*self.args, **self.kwargs)
>   File "/root/mylar3/mylar/webserve.py", line 211, in comicDetails
>     if os.path.exists(secondary_folders):
>   File "/usr/lib/python3.7/genericpath.py", line 19, in exists
>     os.stat(path)
> TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

 - OS: dietpi
 - Branch / commit: python3-dev[badc190f]

**Comment by evilhero** [comment]
fixed as of 10 minutes ago.

**Comment by Jbaal** [comment]
Oh great! Thanx!
