### ISSUE TITLE
Series Page Not Displaying Correctly

### ISSUE THREAD

**Issue by kmccormi** [mylar3/mylar3#921]
After updating to the latest commit, a new wrinkle developed: each time I go to the series page of a comic, the issues table is stuck on "processing" with no issues displayed. The exception to this is if the comic has only 1 issue in the table and if so everything displays normally. 

I have: refreshed the series / refreshed ALL series / paused then restarted the series/ tried accessing the series page from different access points such as Wanted or This Week or Manage /checked file and folder permissions /deleted the installation and then reinstalled and added back config.ini, mylar.db and the cache directory, but the problem persists. The only unrelated change I made to my install prior to this was when I set up Prowlarr last week. 
 
**Environment 
Windows 11
python3-dev/630e932a

Any help would be appreciated

**Comment by evilhero** [comment]
If either of you are running Chrome, can you open up the Developer's Console in Chrome (via Developer options I believe) and then try to load a fresh page. It should throw some kind of error in the console

**Comment by evilhero** [comment]
Can you right-click on the link and select ``Open in new tab`` - if mylar is still running it will try to directly execute that and throw the 500 exception error into the new tab where it's an more readable error (thanks for the first part btw).
