### ISSUE TITLE
Verify SSL checkbox for Search Provider not working properly when verify=False

### ISSUE THREAD

**Issue by JaiZed** [mylar3/mylar3#929]
**Describe the bug**
When using a Newznab provider, the Verify SSL checkbox not working properly when verify=False.
Here's the description of the scenario that causes the bug.
I would constantly get errors that look like this:

11-Oct-2021 16:39:37 - WARNING :: mylar.NZB_SEARCH.1188 : SEARCH-QUEUE : [<module 'errno' (built-in)>]Connection error trying to retrieve data from newznab: HTTPSConnectionPool(host='xxx.asuscomm.com', port=8280): Max retries exceeded with url: /api?t=search&q=money%20shot%20015&o=xml&cat=7030&apikey=MYAPIKEY&maxage=1500 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131)')))

In my case, I have exactly 1 newznab search provider. This provider runs a small indexer and he uses a self-signed certificate. So, according to the documentation, I toggled the Verify SSL checkbox to be off in the search provider configuration. After saving the configuration, I looked at the config.ini file and I saw that the fourth item was indeed a zero, meaning off. I then restarted the server and turned debug logging on. To my surprise, I saw several lines with Verify SSL to be true just before I get the SSL CERTIFICATE_VERIFY_FAILED error message.

16-Oct-2021 14:02:47 - DEBUG   :: mylar.NZB_SEARCH.1170 : SEARCH-QUEUE : [SSL: True] Search URL: https://xxx.asuscomm.com:8280/api?t=search&q=batman%20urban%20legends%208&o=xml&cat=7030&apikey=xUDONTNEEDTOKNOWTHISx

16-Oct-2021 14:02:47 - WARNING :: mylar.NZB_SEARCH.1184 : SEARCH-QUEUE : Connection error trying to retrieve data from newznab: HTTPSConnectionPool(host='xxx.asuscomm.com', port=8280): Max retries exceeded with url: /api t=search&q=batman%20urban%20legends%208&o=xml&cat=7030&apikey=xUDONTNEEDTOKNOWTHISx&maxage=1500 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131)')))

I thought about tracing the logic and trying to figure out what the various if then else statements did but I decided to do an old fashioned hack instead. I just hacked the code in **search.py** to set
**_verify = False_**
just before any attempted accesses to the search provider. Lo and behold, everything started to work beautifully!
I suspect that this bug has been around so long because most people use search providers that have proper SSL certificates and that they usually set this checkbox to be on.

**CarePackage**
I don't think it's necessary, the bug is straightforward enough.

**Environment**
 - OS: Windows 10
 - Branch / commit: mylar3/latest

**Additional information**
The weird thing is that every once in a while it would work and I thought that maybe a bug had been fixed, but then it would start failing again consistently.  Ever since I hacked **search,py**, it has been working flawlessly,

**Comment by JaiZed** [comment]
You are correct, I did indeed miscount, it it the third item which is 0,
The config looks like this:
extra_newznabs = provider, https://xxx.asuscomm.com:8280/, 0, xUDONTNEEDTOKNOWTHISx, name, 1, 1

I have performed the Test connection many times. it performs correctly. When I toggle the SSL Verify on, the connection fails, When I toggle it off, it succeeds.

I've reverted my hacks so that the issue appears again in the log files.
I've now attached a new carepackage that shows the errors.

Thanks for looking into this!

[carepackage.zip](https://github.com/mylar3/mylar3/files/7358491/carepackage.zip)

**Comment by evilhero** [comment]
Should be fixed in #931 - apparently the config.ini value was being stored as a string, which I knew, but we were taking the boolean of the string (which will always be True), as opposed to taking the boolean of the integer of the string.

Thanks for pointing out the error !

**Comment by evilhero** [comment]
if you're meaning the place where it's hard-coded as ``verify = True`` around 3769 in the PR, that doesn't affect newznabs. 

That particular verify statement at that location only affects experimental nzb retrievals - it was doing http requests instead of https, so the verify was forced to False previously to accomodate that. I fixed that in the same PR is all.

**Comment by JaiZed** [comment]
No, actually, it's about 30 lines earlier.
See below

        if nzbprov == 'newznab' or nzbprov == 'nzb.su':
            # need to basename the link so it just has the id/hash.
            # rss doesn't store apikey, have to put it back.
            if nzbprov == 'newznab':
                host_newznab = newznab[1].rstrip()
                if host_newznab[len(host_newznab) - 1 : len(host_newznab)] != '/':
                    host_newznab_fix = str(host_newznab) + "/"
                else:
                    host_newznab_fix = host_newznab

                # account for nzbmegasearch & nzbhydra
                if 'searchresultid' in link:
                    logger.fdebug('NZBHydra V1 url detected. Adjusting...')
                    nzbhydra = True
                else:
                    apikey = newznab[3].rstrip()
                    if rss == 'yes':
                        uid = newznab[4].rstrip()
                        payload = {'r': str(apikey)}
                        if uid is not None:
                            payload['i'] = uid
                    verify = bool(newznab[2])

The line above needs the update, I think.
