### ISSUE TITLE
Comic series name with trailing periods causes a loop

### ISSUE THREAD

**Issue by FrankEBailey** [mylar3/mylar3#939]
**Describe the bug**
I add the comic "**Locke & Key: ...In Pale Battalions Go....**" which has trailing periods in the name. On Windows the trailing periods are ignored, resulting in a folder named "**Locke & Key ...In Pale Battalions Go**" being created on my computer's file system. 

Mylar3 is still looking for the original folder name, though, so subsequent folder operations fail, and the writing of the info files and comic thumbnail fail, which appears to prevent the creation of the comic in the Mylar database from completing. The GUI just refreshes infinitely and the comic details on-screen are never populated.

**CarePackage**
[carepackage.zip](https://github.com/mylar3/mylar3/files/7459440/carepackage.zip)

**Environment (please complete the following information):**
 - OS: [e.g. Windows10]
Windows 10

 - Branch / commit: [e.g. Dev/38aksi1]
v0.5.9.5
4a54f5f

**Additional information**
I'm happy to use a workaround (if one exists) to prevent this issue as I haven't found many comics whose name contains trailing periods.

Thanks as always for your hard work and a fantastic piece of software!

**Comment by theRealKLH** [comment]
is this Windows specific? Just so happens I pulled the same the other day with "no issue"...
![image](https://user-images.githubusercontent.com/65736720/139951523-1df29736-e5e5-497c-92e4-77fa0d6d335e.png)

I'm running LSIO docker and library resides on NAS, but shows fine via Windows explorer.![image](https://user-images.githubusercontent.com/65736720/139951671-cdada4a4-eb81-473d-a316-6408f30e1fd7.png)

**Comment by evilhero** [comment]
No, it's based on your folder format string. The OP's folder format string was something like ``$Publisher/$Series/$VolumeY``, which ended up trying to create a sub-directory with the ``....`` which is invalid and registers on Windows explorer as the capitalised folder names with the squiggly (ie. ``LSJ891O~``)

Your format string isn't ending a directory/sub-directory with the $Series tag, so you would never encounter this type of error. You sir, are safe.
