### ISSUE TITLE
'NoneType' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by mlsmithjr** [mylar3/mylar3#947]
**Describe the bug**
This error occurs during manual run, consistently. If I manually fix the problem in the container by avoiding the all() built-in it works.  But it just reverts after the next docker image update.

**Environment (please complete the following information):**
 - OS: Ubuntu Linux via Docker
 - master ([v0.6.0])

**Additional information**
[carepackage.zip](https://github.com/mylar3/mylar3/files/7491228/carepackage.zip)
Add any other information about the problem here.

**Comment by evilhero** [comment]
Which docker container are you using for mylar3 ? 

I ran thru abunch of tests, and I can't get this error to trigger on my side - tried in both LSIO docker and in non-docker. 

I'm wondering if it could possibly the version of python that's being used in your docker that might be causing some discrepencies in how it handles the all(), as normally it's FIFO, so it wouldn't trigger the 2nd check if the first one fails - I saw this previously in python2 usually (and maybe early python3 versions), but I really haven't seen it happen in the newer version of python3 as of late at least.

That being said, pretty sure we can just test for None and break it out - at least then it's a clean slate and there shouldn't be any problems related to the various checks.

PS. Sorry for the delay in responding

**Comment by mlsmithjr** [comment]
I’m using linuxserver/mylar3 and have watchtower updating every M-W-F, so it’s very current.

Maybe there’s something corrupted in my data files or database?  I’m ok pointing to a clear config dir and setting up again.

**Comment by evilhero** [comment]
Due to the CV issues and other problems, this kinda hit a side lull and I almost forgot about it.

I'll update the changes (as they're not breaking from the looks of it) so it'll be in the next master release (it'll be in python3-dev or nightly for docker users by tomorrow).
