### ISSUE TITLE
Comicvine isn't updated anymore

### ISSUE THREAD

**Issue by tchirou** [mylar3/mylar3#957]
Hi
It isn't exactly an issue but as Mylar is built around Comicvine, I thought I put some info here
I just spent an hour trying to figure out why mylar hadn't downloaded anything in the last 10 days. Nothing from the pull-list was added in the wanted tab, even though there were some issues marked as wanted in the pull-list
Turns out nothing is wrong with my setup but actually Comicvine hasn't been updated for mainstream comics for the last 13 days.
A reddit thread here  https://www.reddit.com/r/comicrackusers/comments/qvgfc9/sothe_guy_at_comicvine_that_enters_all_the_new/
@evilhero maybe you have some insider info about this ?
Thanks a lot

**Comment by evilhero** [comment]
Not much to say - CV is being updated, just on community basis now and not by one individual as per before. I'm sure at this point you've read all the other forum posts (reddit, cv forums, etc) - so you know that issue data is being populated by the community right now, so things are slowly returning to a usable state.

I know nothing of what actually transpires within CV aside from reading posts just as you do - I am but an outsider, looking in.

Will close this as it's not really mylar-issue related at this point in time.

Cheers,
