### ISSUE TITLE
mylar website usable from the local machine but not my local network.

### ISSUE THREAD

**Issue by ferfey** [mylar3/mylar3#967]
**The bug**
I'm able to reach the Mylar web interface if I'm physically on my local server at either localhost:8090 or its static IP address of 192.168.4.11:8090 but I can't access it from the other machines on my local network. For context, I'm able to access Radarr, Sonarr, SABnzbd, etc without problems. Is there some unique setting with Mylar that I'm missing?

**Environment:**
 - OS: Ubuntu 20.04
 - Branch / commit: not sure but got from github a few days ago

**Comment by evilhero** [comment]
Localhost and ip designatjom restrict access to those entry points only (meaning only the machine itself).

Use 0.0.0.0 instead and then you can access it from anywhere (machine and external to machine)

**Comment by ferfey** [comment]
That worked! Thanks for the help!
