### ISSUE TITLE
story arc processing issue (IndexError: No item with that key)

### ISSUE THREAD

**Issue by phairplay** [mylar3/mylar3#971]
**Describe the bug**
Post processing Story arc comics hang within NzbGet
following error appears in the log
```

10-Dec-2021 11:17:01 - ERROR   :: mylar.excepthook.315 : Post-Processing : Uncaught exception: Traceback (most recent call last):
  File "C:\Mylar3\mylar\logger.py", line 337, in new_run
    old_run(*args, **kwargs)
  File "C:\Python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Mylar3\mylar\PostProcessor.py", line 1816, in Process
    'seriesyear':    oneinfo['ComicYear'],
IndexError: No item with that key

```

**CarePackage**
CarePackage included, yet I've had to remove the DB file due to size

[carepackage (2).zip](https://github.com/mylar3/mylar3/files/7692336/carepackage.2.zip)

**Environment (please complete the following information):**
 - OS: Windows10
 - Branch / commit: d48b26a61f6e826341373dd55a74dd07e5b34bcb (python3-dev)

**Additional information**
normal comic process without issues

**Comment by evilhero** [comment]
oops - should be ``oneinfo['SeriesYear']``, not ``oneinfo['ComicYear']``

**Comment by phairplay** [comment]
All good.
Thank you for your conituned support
