### ISSUE TITLE
unexpected address sent to SAB queue

### ISSUE THREAD

**Issue by mgaulton** [mylar3/mylar3#973]
Running into an issue where an unexpected issue where the job sent to SAB from Mylar, is using an unexpected address, resulting in failed processing.
Not sure if there's a way to make Mylar send only the local address as part of the queue request or I need to rewrite the IP address of the request during prequeue.
Any and all suggestions appreciated.

Running Mylar git latest
running SAB git latest
Opensuse x64 Tumbleweed
Python 3.8.12

Example:
Green.Arrow.v2.134.nzb - Trying to fetch NZB from http://10.35.0.14:8090/api?apikey=...

SAB running in VPN namespace
Mylar running same VPN namespace
Both running as the same user
Using socat to transition from ROOT namespace to VPN namespace for processes outside the namespace.

An unexpected IP address is sent to the queue in SAB, meaning it doesn't seem to resolve, breaking nzbToMedia processing.
STDIO tcp-connect\:0.0.0.0\:8090, STDIO tcp-connect\:localhost\:8090 and STDIO tcp-connect\:127.0.0.1\:8090 address options were all attempted.

SOCAT config for Mylar, similar to SAB, just different ports.
have tried 
if pgrep -f "tcp\-listen\:8090" > /dev/null
then
    echo "Running"
else
    echo "Stopped"
    socat tcp-listen:8090,fork,reuseaddr exec:'ip netns exec vpn socat STDIO tcp-connect\:0.0.0.0\:8090',nofork &
fi

ROOT namespace
no 10.x addresses assisgned, only 192 and 172

VPN Namespace
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
22: tun0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN group default qlen 500
    link/none
    inet 10.35.0.42 peer 10.35.0.41/32 scope global tun0
       valid_lft forever preferred_lft forever
    inet6 fe80::18c4:404d:284a:eb7f/64 scope link stable-privacy
       valid_lft forever preferred_lft forever

**Comment by mgaulton** [comment]
Nmap scan report for 10.35.0.42
Host is up (0.0000020s latency).
Not shown: 996 closed tcp ports (reset)
PORT     STATE SERVICE
8082/tcp open  blackice-alerts
8085/tcp open  unknown
8090/tcp open  opsmessaging
8181/tcp open  intermapper

**Comment by evilhero** [comment]
With Mylar not running, set the **host_return** field in the config.ini to your local IP instance in the form of how you would declare the SAB host address within Mylar (ie. ``host_return = http://localhost:8090`` - or use your internal local IP if available since localhost may not resolve properly on some systems). This will change the url in the downloadnzb command that is initiated and shown in your SABnzbd client, that is used to retrieve the nzb from the mylar cache via an internal Mylar api call.

**Comment by mgaulton** [comment]
So, I cleared the queue and the jobs being added now have a different IP address. now I'm really puzzled

  | WAIT 7 sec Trying to fetch NZB from http://10.35.0.10:8090/api?apikey=...&cmd=downloadNZB&nzbname=Spider-Man.2099.018.2017.Digital.Zone-Empire.nzb | comics | 0%0 MB / 0 MB | Fetch |

**Comment by mgaulton** [comment]
Ahh let me try that now.

**Comment by mgaulton** [comment]
My value was None, modified and starting it up.
Thanks, i'll update you.

**Comment by apastuszak** [comment]
I have this same problem. Modified my config.ini with `host_return = http://172.20.0.3:8090` and I'm still getting the same problem.

I'm running the linuxserver.io image in docker.

**Comment by evilhero** [comment]
Then that's probably not the IP of the mylar host. When you access it in a browser what's the ip that you use? That's what you should be putting in as a host_return value if you even need to use it (some configurations don't - depends on your system setup). 

What is your mylar host set to within the mylar program currently?

**Comment by apastuszak** [comment]
mylar and sabnzbd are both running inside of docker, so I used the IP address assigned to it in docker.

**Comment by evilhero** [comment]
Yeah haha that's not what I asked. You have to specify specific IPs in host return in order for it to properly hit the mylar api endpoint. 

So we need to know what the address for the mylar host in mylar. Dockers are considered to be independent of each other so localhost on one will not resolve to localhost on the other, so you need to specify IP if you're targeting a specific docker from another docker within the program.

**Comment by apastuszak** [comment]
Would this not be the ip address of the mylar container?

<img width="934" alt="image" src="https://user-images.githubusercontent.com/3401054/150646134-bae89940-5c89-43d2-bdbe-94315f4232e6.png">

**Comment by evilhero** [comment]
No that's not the image ip, that's the container ip.

Try:
``docker -ps`` to get the container id

Then:
``docker inspect <container id> | grep -i ip``

The result of the last one will show you the op of the  mylar image.

**Comment by apastuszak** [comment]
```
                        "HostIp": "",
            "IpcMode": "private",
                "org.opencontainers.image.description": "[Mylar3](https://github.com/mylar3/mylar3) is an automated Comic Book downloader (cbr/cbz) for use with NZB and torrents written in python. It supports SABnzbd, NZBGET, and many torrent clients in addition to DDL.",
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
                        "HostIp": "0.0.0.0",
                        "HostIp": "::",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
                    "IPAMConfig": null,
                    "IPAddress": "172.20.0.3",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
```
Still says 172.20.0.3, or am I reading that wrong?

**Comment by evilhero** [comment]
What is the mylar host set to within the mylar configuration of the program itself?

**Comment by apastuszak** [comment]
0.0.0.0

I assume I need to change that?

**Comment by evilhero** [comment]
If you change it from 0.0.0.0 and specify the IP then you'll only be able to access the mylar instance via that specific ip and not external to it. So I'm assuming that's not what you want since you probably access the web interface somehow?

Portainer / docker isn't really my knowledgebase, but have you looked at something like this at all? 
https://www.youtube.com/watch?v=q6PimerKycI

**Comment by apastuszak** [comment]
I'll keep playing with it. I updated my docker image last night, and before that it was working fine.

**Comment by evilhero** [comment]
If you hop on our discord, there's probably alot of people more knowledgeable than myself with regards to docker (literally everyone), and you might get some additional assistance that way.

**Comment by apastuszak** [comment]
I forgot to pull down the latest image.  DOH!  I just did that.  I will be retesting in 5 minutes.

**Comment by mgaulton** [comment]
I just discovered it happened again and value was reset to None.
Would an upgrade clobber this?

**Comment by evilhero** [comment]
Nope, the only thing that previously hammered the ini by mistake was about a month or so ago, and only on the python3-dev branch. But that was fixed shortly thereafter so unless you were running the python3-dev branch and upgraded around that time, and then haven't looked at it since, that probably didn't affect you.

Odds are if one value is blank the rest of the ini might be all default values. Otherwise it's nothing mylar is doing.

**Comment by barbequesauce** [comment]
@mgaulton is this still an open issue?

**Comment by evilhero** [comment]
Closing as too many fluctuations in both the app and logs since this was opened.

If it's still an outstanding issue, please open a new issue with a fresh carepackage and indicate the problem.
