### ISSUE TITLE
TPB Series With A Single Issue - Searches Failing Due to Including Expected Issue Number (ie. "1")

### ISSUE THREAD

**Issue by jakem742** [mylar3/mylar3#995]
I'm trying to get TPB's from GetComics but the Mylar3 queries all include the issue number ("1") in every search term and subsequently return 0 results (refer my debug logs below). My comic definitely exists on GetComics: [Star Wars Vol. 4 – Shattered Hope (Marvel Edition) (2015)](https://getcomics.info/marvel/star-wars-vol-4-shattered-hope-marvel-edition/).

```
05-Jan-2022 16:13:30 - INFO :: mylar.NZB_SEARCH.824 : SEARCH-QUEUE : Shhh be very quiet...I'm looking for Star Wars A Shattered Hope issue: 1 (2014) using DDL.

05-Jan-2022 16:13:30 - DEBUG :: mylar.NZB_SEARCH.884 : SEARCH-QUEUE : findloop: 0 / findcount: 1

05-Jan-2022 16:13:30 - DEBUG :: mylar.NZB_SEARCH.935 : SEARCH-QUEUE : Sending request to DDL site for : Star Wars A Shattered Hope 1

05-Jan-2022 16:13:31 - DEBUG :: mylar.search.96 : SEARCH-QUEUE : [DDL-QUERY] Query set to: "Star Wars A Shattered Hope #1 (2014)"

05-Jan-2022 16:13:31 - INFO :: mylar.search_results.228 : SEARCH-QUEUE : There are 0 results

05-Jan-2022 16:13:33 - DEBUG :: mylar.search.96 : SEARCH-QUEUE : [DDL-QUERY] Query set to: Star Wars A Shattered Hope #1 (2014)

05-Jan-2022 16:13:34 - INFO :: mylar.search_results.228 : SEARCH-QUEUE : There are 0 results

05-Jan-2022 16:13:36 - DEBUG :: mylar.search.96 : SEARCH-QUEUE : [DDL-QUERY] Query set to: Star Wars A Shattered Hope #1

05-Jan-2022 16:13:36 - INFO :: mylar.search_results.228 : SEARCH-QUEUE : There are 0 results

05-Jan-2022 16:13:38 - DEBUG :: mylar.search.96 : SEARCH-QUEUE : [DDL-QUERY] Query set to: Star Wars A Shattered Hope 1
05-Jan-2022 16:13:39 - INFO :: mylar.search_results.228 : SEARCH-QUEUE : There are 0 results 
```

Would it be difficult to implement a check for TPB's where if there is only a single issue, an additional search is appended to the end which excludes any sort of issue numbering? ie. In my case, an additional search for "Star Wars A Shattered Hope" would find my TPB:

Query set to:

1. "Star Wars A Shattered Hope #⁠1 (2014)"
2. Star Wars A Shattered Hope #⁠1 (2014)
3. Star Wars A Shattered Hope #⁠1
4. Star Wars A Shattered Hope 1
5. Star Wars A Shattered Hope **<--- New Search**

Logically, if there is only a single issue in any comic series I would think it would make sense to exclude issue numbers, however I am quite new to comics in general and realise that these naming schemes aren't always dictated by logic aha.

**Environment (please complete the following information):**
 - OS: Docker [linuxserver/mylar3]
 - Branch / commit: Master [v0.6.2]

**Additional information**
This appears to be the same problem as outlined in [Issue 712](https://github.com/mylar3/mylar3/issues/712)

**Comment by evilhero** [comment]
Thank you for creating a new issue. New issues help us track things easier and we can notice missed responses as opposed to closed comments that we don't see. 

As far as your problem, it actually follows the same answer as the post you commented on after inspection. Unfortunately it's one the inherent problems in dealing with how CV has things named and how GC has it, as well as it being a TPB type of volume. 

Mylar will already loop thru the iterations of the issue number as well as extra one of the item is a TPB/GN/HC/One-shot/Annual. The first 4 of those types (TPB/GN/HC/One-shot) is what the Edition has to say for the given series on the series detail page in order for the loop to work properly.

Now the other part, the naming. The title on GC is completely different from what Mylar is searching for. In mylar there is no mention of a V4, or that it is a marvel edition. Because those items are added to the filename on GC that's what mylar uses to parse the information from and so it'll never match up to what it has due to those discrepancies. The Vol. 4 thing is the big part as typically that denoted a series volume and CV (what Mylar uses) tends to isolate volumes of TPB's as opposed to adding them all under one volume.

The only way around it is to make use of the Alternate Search Name field on the Edit Settings tab of the series detail page. Setting the value to what GC has ``Star Wars Vol. 4 - Shattered Hope (Marvel Edition) `` might make things match but the Vol. 4 might throw off the parser enough to exclude it as a match. In which case setting the Alternate Search Name to ``Star Wars - Shattered Hope (Marvel Edition) `` and then changing the volume to ``v4`` might allow it all to match up, but that's just me guessing atm cause I can't test the theory atm.

**Comment by jakem742** [comment]
Before I reply, I just wanted to say a big thank you; this is a huge project to manage and it works quite well considering the complexity involved!

Are you suggesting that even if a search was done for "Star Wars A Shattered Hope" the results wouldn't be satisfactory because of the extra text in the title of the CV entry? I guess there is the potential for incorrect resultsif you make it too vague, but it would be nice be ably to manually override the search to exclude issue numbers where none are mentioned (I have a number of TPB's all with the same problem - single issue & no search results).

I tried setting the Alternate Search Name in the series but it still appends the issue number. :(

```
05-Jan-2022 19:06:36 - INFO :: mylar.comic_config.6146 : CP Server Thread-9 : Validating Directory (/data/media/comics/Star Wars A Shattered Hope (2014)). Already exists! Continuing...

05-Jan-2022 19:06:36 - DEBUG :: mylar.comic_config.6185 : CP Server Thread-9 : Updated Series options!

05-Jan-2022 19:06:36 - INFO :: mylar.load_image.213 : CP Server Thread-3 : filename: /config/mylar/cache/77559.jpg

05-Jan-2022 19:06:39 - DEBUG :: mylar.queueissue.2002 : CP Server Thread-3 : ComicID: 77559

05-Jan-2022 19:06:39 - DEBUG :: mylar.queueissue.2003 : CP Server Thread-3 : mode: want

05-Jan-2022 19:06:39 - INFO :: mylar.queueissue.2095 : CP Server Thread-3 : Initiating manual search for Star Wars: A Shattered Hope issue: 1

05-Jan-2022 19:06:39 - INFO :: mylar.queueissue.2134 : CP Server Thread-3 : [WANTED-SEARCH][TPB] Now Queueing Star Wars: A Shattered Hope (2014) for search

05-Jan-2022 19:06:39 - INFO :: mylar.search_queue.3255 : SEARCH-QUEUE : [SEARCH-QUEUE] Now loading item from search queue: {'issueid': '468039', 'comicname': 'Star Wars: A Shattered Hope', 'seriesyear': '2014', 'comicid': '77559', 'issuenumber': '1', 'booktype': 'TPB'}

05-Jan-2022 19:06:39 - INFO :: mylar.search_init.86 : SEARCH-QUEUE : [SEARCH] Special Characters exist within Series Title. Enabling search-safe Name : Star Wars A Shattered Hope

05-Jan-2022 19:06:39 - DEBUG :: mylar.search_init.103 : SEARCH-QUEUE : Publisher is : Dark Horse Comics

05-Jan-2022 19:06:39 - DEBUG :: mylar.search_init.111 : SEARCH-QUEUE : Issue Title given as : A Shattered Hope

05-Jan-2022 19:06:39 - DEBUG :: mylar.search_init.151 : SEARCH-QUEUE : Checking for torrent enabled.

05-Jan-2022 19:06:39 - DEBUG :: mylar.search_init.207 : SEARCH-QUEUE : nzbprovider(s): ['experimental']

05-Jan-2022 19:06:39 - DEBUG :: mylar.search_init.210 : SEARCH-QUEUE : There are 0 torrent providers you have selected.

05-Jan-2022 19:06:39 - DEBUG :: mylar.search_init.215 : SEARCH-QUEUE : There are : 1 nzb providers you have selected

05-Jan-2022 19:06:39 - DEBUG :: mylar.search_init.217 : SEARCH-QUEUE : Usenet Retention : 1500 days

05-Jan-2022 19:06:39 - DEBUG :: mylar.search_init.220 : SEARCH-QUEUE : there are 1 Direct Download providers that are currently enabled.

05-Jan-2022 19:06:39 - DEBUG :: mylar.search_init.242 : SEARCH-QUEUE : search provider order is ['DDL', 'Experimental']

05-Jan-2022 19:06:39 - DEBUG :: mylar.search_init.315 : SEARCH-QUEUE : calpha/cnumber: None / None

05-Jan-2022 19:06:39 - DEBUG :: mylar.search_init.358 : SEARCH-QUEUE : Initiating Search via : api

05-Jan-2022 19:06:39 - INFO :: mylar.NZB_SEARCH.824 : SEARCH-QUEUE : Shhh be very quiet...I'm looking for Star Wars: A Shattered Hope issue: 1 (2014) using DDL.

05-Jan-2022 19:06:39 - DEBUG :: mylar.NZB_SEARCH.884 : SEARCH-QUEUE : findloop: 0 / findcount: 1

05-Jan-2022 19:06:39 - DEBUG :: mylar.NZB_SEARCH.935 : SEARCH-QUEUE : Sending request to DDL site for : Star Wars: A Shattered Hope 1

05-Jan-2022 19:06:40 - DEBUG :: mylar.search.96 : SEARCH-QUEUE : [DDL-QUERY] Query set to: "Star Wars: A Shattered Hope #1 (2014)"

05-Jan-2022 19:06:41 - INFO :: mylar.search_results.228 : SEARCH-QUEUE : There are 0 results

05-Jan-2022 19:06:43 - DEBUG :: mylar.search.96 : SEARCH-QUEUE : [DDL-QUERY] Query set to: Star Wars A Shattered Hope #1 (2014)

05-Jan-2022 19:06:43 - INFO :: mylar.search_results.228 : SEARCH-QUEUE : There are 0 results

05-Jan-2022 19:06:45 - DEBUG :: mylar.search.96 : SEARCH-QUEUE : [DDL-QUERY] Query set to: Star Wars A Shattered Hope #1

05-Jan-2022 19:06:46 - INFO :: mylar.search_results.228 : SEARCH-QUEUE : There are 0 results

05-Jan-2022 19:06:48 - DEBUG :: mylar.search.96 : SEARCH-QUEUE : [DDL-QUERY] Query set to: Star Wars A Shattered Hope 1

05-Jan-2022 19:06:48 - INFO :: mylar.search_results.228 : SEARCH-QUEUE : There are 0 results

05-Jan-2022 19:06:50 - DEBUG :: mylar.NZB_SEARCH.2550 : SEARCH-QUEUE : booktype:TPB / chktpb: 1 / findloop: 99

**05-Jan-2022 19:06:50 - INFO :: mylar.search_init.577 : SEARCH-QUEUE : Alternate Search pattern detected...re-adjustingto : Star Wars Vol. 4 - Shattered Hope (Marvel Edition)

05-Jan-2022 19:06:50 - INFO :: mylar.NZB_SEARCH.824 : SEARCH-QUEUE : Shhh be very quiet...I'm looking for Star Wars Vol. 4 - Shattered Hope (Marvel Edition) issue: 1 (2014) using DDL.

05-Jan-2022 19:06:50 - DEBUG :: mylar.NZB_SEARCH.884 : SEARCH-QUEUE : findloop: 0 / findcount: 1

05-Jan-2022 19:06:50 - DEBUG :: mylar.NZB_SEARCH.935 : SEARCH-QUEUE : Sending request to DDL site for : Star Wars Vol. 4 - Shattered Hope (Marvel Edition) 1

05-Jan-2022 19:06:51 - DEBUG :: mylar.search.96 : SEARCH-QUEUE : [DDL-QUERY] Query set to: "Star Wars Vol. 4 - Shattered Hope (Marvel Edition) #1 (2014)"

05-Jan-2022 19:06:52 - INFO :: mylar.search_results.228 : SEARCH-QUEUE : There are 0 results

05-Jan-2022 19:06:54 - DEBUG :: mylar.search.96 : SEARCH-QUEUE : [DDL-QUERY] Query set to: Star Wars Vol. 4 - Shattered Hope (Marvel Edition) #1 (2014)

05-Jan-2022 19:06:54 - INFO :: mylar.search_results.228 : SEARCH-QUEUE : There are 0 results

05-Jan-2022 19:06:56 - DEBUG :: mylar.search.96 : SEARCH-QUEUE : [DDL-QUERY] Query set to: Star Wars Vol. 4 - Shattered Hope (Marvel Edition) #1

05-Jan-2022 19:06:57 - INFO :: mylar.search_results.228 : SEARCH-QUEUE : There are 0 results

05-Jan-2022 19:06:59 - DEBUG :: mylar.search.96 : SEARCH-QUEUE : [DDL-QUERY] Query set to: Star Wars Vol. 4 - Shattered Hope (Marvel Edition) 1

05-Jan-2022 19:06:59 - INFO :: mylar.search_results.228 : SEARCH-QUEUE : There are 0 results**

05-Jan-2022 19:07:01 - DEBUG :: mylar.NZB_SEARCH.2550 : SEARCH-QUEUE : booktype:TPB / chktpb: 1 / findloop: 99

05-Jan-2022 19:07:01 - INFO :: mylar.search_init.577 : SEARCH-QUEUE : Alternate Search pattern detected...re-adjustingto : Star Wars A Shattered Hope

05-Jan-2022 19:07:01 - INFO :: mylar.NZB_SEARCH.824 : SEARCH-QUEUE : Shhh be very quiet...I'm looking for Star Wars A Shattered Hope issue: 1 (2014) using DDL.

05-Jan-2022 19:07:01 - DEBUG :: mylar.NZB_SEARCH.884 : SEARCH-QUEUE : findloop: 0 / findcount: 1

05-Jan-2022 19:07:01 - DEBUG :: mylar.NZB_SEARCH.935 : SEARCH-QUEUE : Sending request to DDL site for : Star Wars A Shattered Hope 1

05-Jan-2022 19:07:02 - DEBUG :: mylar.search.96 : SEARCH-QUEUE : [DDL-QUERY] Query set to: "Star Wars A Shattered Hope #1 (2014)"

05-Jan-2022 19:07:03 - INFO :: mylar.search_results.228 : SEARCH-QUEUE : There are 0 results

05-Jan-2022 19:07:05 - DEBUG :: mylar.search.96 : SEARCH-QUEUE : [DDL-QUERY] Query set to: Star Wars A Shattered Hope #1 (2014)

05-Jan-2022 19:07:05 - INFO :: mylar.search_results.228 : SEARCH-QUEUE : There are 0 results

05-Jan-2022 19:07:07 - DEBUG :: mylar.search.96 : SEARCH-QUEUE : [DDL-QUERY] Query set to: Star Wars A Shattered Hope #1

05-Jan-2022 19:07:08 - INFO :: mylar.search_results.228 : SEARCH-QUEUE : There are 0 results

05-Jan-2022 19:07:10 - DEBUG :: mylar.search.96 : SEARCH-QUEUE : [DDL-QUERY] Query set to: Star Wars A Shattered Hope 1

05-Jan-2022 19:07:10 - INFO :: mylar.search_results.228 : SEARCH-QUEUE : There are 0 results

05-Jan-2022 19:07:12 - DEBUG :: mylar.NZB_SEARCH.2550 : SEARCH-QUEUE : booktype:TPB / chktpb: 1 / findloop: 99

05-Jan-2022 19:07:12 - INFO :: mylar.search_init.647 : SEARCH-QUEUE : Could not find Issue 1 of Star Wars: A Shattered Hope (2014) using DDL [api]
```

**Comment by jakem742** [comment]
Thanks for the clarification. :) I think I understand how much of a pain it must be to manage accurate searching for so many potential variants etc aha. Definitely kudos to you for getting Mylar3 working so well.

I guess the big thing that would be nice to have is a manual override on the search in some way as I'd love to keep everything through mylar rather than having to do some file downloads outside mylar and bring them in manually. 

In this case, do you have any recommendations for getting downloads to work when the search results are slightly off? What is your suggested next step after setting the Alternate Series Name? There is no Marvel edition listed on CV, so I imagine I'm out of options with modifying the search terms any more...?

**Comment by evilhero** [comment]
Search iteration for DDL queries based on booktype are in and have been for a few months. Assuming this is resolved, and if not (at least with the particular series being tried in the issue) it's due to the publisher variation which can be fixed by faking the comicname term using the Alternate Search Name as discussed above.
