### ISSUE TITLE
[BUG?] No "Download" or "Add to Readlist" options

### ISSUE THREAD

**Issue by WedgeSparda** [mylar3/mylar3#996]
**Describe the bug**
Since last version (0.6.1) I'm unable to download any issue from comic details view.
Neither can add any issue to the Readlist manually.
This is mainly because both buttons have disappeared from the options list, as you can see here

![image](https://user-images.githubusercontent.com/48375/143678897-3b204035-077a-4c0e-badc-04d37fd40d1d.png)

**CarePackage**
[carepackage.zip](https://github.com/mylar3/mylar3/files/7815090/carepackage.zip)

**Environment (please complete the following information):**
 - OS: Synology DSM 
 - Branch / commit: master

**Comment by theRealKLH** [comment]
Not a bug. They were removed. From Discord....

`Somewhat relatedly, the "Download" icon/link also appears to be gone in 0.6.0 😕`

`yeah those would have to be added back in - honestly I didn't think anyone was using those functions due to readers like Komga and Codex being available
[6:34 PM]
it's easy enough to do, I just need to create the items in javascript now`

**Comment by WedgeSparda** [comment]
I see. Is there an ETA for these to come back?

**Comment by theRealKLH** [comment]
That doesn't actually say they (download button only. don't know about the add to readlist) "will" be back (grin). But only @evilhero can answer that one..

**Comment by DieselTech** [comment]
Realistically you should look into setting up something like Komga or Kavita for reading. That would let the devs focus on making improvements to the core functions rather than keeping alive a feature not many people use.

**Comment by barbequesauce** [comment]
Sorry @DieselTech, they're functions I do use...

**Comment by cnewham699** [comment]
They’re ones I use quite a lot too. I have missed them but didn’t raise it as I know how much work you guys have going on but if there is any chance in them being restored then you have my vote.

**Comment by evilhero** [comment]
Both ``Download`` and ``Add to Reading List`` will be available in the next PR that goes into python3-dev.

**Comment by WedgeSparda** [comment]
@evilhero Thank you, I appreciate your hard work. I'll close this issue now.
